== Vorwort
Die vorliegende Dorfchronik ist neben drei anderen Arbeiten das große und über viele Jahre erarbeitete
Werk des früheren Hauptlehrers Johann von Böhl aus Süderlügum, der auch mein Lehrer war.
Nach seinem Tode ist die Arbeit in loser Blattform dem Landesarchiv Schleswig-Holstein im Schloß
Gottorf übergeben worden. Mit Erlaubnis von Frau Helene von Böhl und des Landesarchivs habe ich
auf meine Kosten mit Hilfe des Landesarchivs die Originaltexte auf Mikrofilm ablichten lassen. Diese
vorliegende Chronik enthält, soweit es möglich gewesen ist, die an vielen Stellen sehr unlesbaren
Seiten zu entziffern, eine Abschrift der Originaltexte. Nur die Gliederung der verschiedenen Abschnitte
ist etwas geändert worden, bei einer möglichst geringen Abweichung vom Original.

Die Quellen, die Johann von Böhl gebraucht hat, und welche an vielen Stellen (teilweise) angegeben
sind, sind größtenteils im Staatsarchiv in Kiel und beim Katasteramt in Niebüll zu finden oder in den
Grundbüchern des Amtsgerichtes in Leck und in alten Schuld- und Pfandprotokollen der Karrharde.
Sie sind aber auch den Erzählungen und Angaben vieler älterer Einwohner entnommen und last not
least den alten Kirchenbüchern.

Um dem Leser bei der Lektüre zu helfen, ist es angebracht, etwas über die verschiedenen alten Geld-
und Maßeinheiten zu sagen. In den einzelnen Abschnitten werden Geldbeträge erwähnt, und die
unterschiedlichen Bezeichnungen könnten den Leser verwirren.

Es muß daran erinnert werden, daß es in den verschiedenen Zeiten um Silbermünzen oder Papiergeld,
dänisches oder holsteinisches, lübisches, hamburgisches oder um Reichsgeld ging. Der Chronist
gebraucht Abkürzungen wie Rthl = Reichstaler, Rbthl = Reichsbanktaler, M = Mark lübsch, r = Mark
Courant, RM = Reichsmark und DM = Deutsche Mark. Gewöhnlich wird die folgende Stufung
gebraucht:

l Reichstaler = 16 Schillinge, 1 Schilling = 12 Pfennige.

Die Abkürzungen, die am meisten in dieser Chronik gebraucht werden, sind Reichstaler (Rthl),
Schillinge (ß) und Pfennige (d).

Die verschiedenen Landmaße sind in den Abschnitten, wo sie auftreten, erklärt. Im allgemeinen wird
der "Pflug" als Flächenmaß gebraucht. Ein "Pflug" ist zwischen 40 und 100 Demat groß und oft
dasselbe wie ein "Bohl". Häufig wird das Entfernungsmaß die "Meile" gebraucht. Eine Meile ist
ungefähr 7 km lang, also viel länger als die englische Meile.

Durch die ganze Chronik hindurch wird der Name des Kirchspiels und des Dorfes in zweifacher Weise
bezeichnet: "Lügum" und "Süderlügum". Bis vor nicht allzulanger Zeit ist der gebräuchliche Name bei
den Einheimischen "Lügum" gewesen, und erst in den letzten Jahren ist er langsam auf "Süderlügum"
übergegangen. Auch wird der Leser in alten Berichten das Wort "Gemeine" und nicht "Gemeinde"
finden. Das ursprüngliche Wort war "Gemeine" und stammt aus der Zeit der gemeinsamen
Feldbenutzung. Die "Gemeine" kennt man auch unter dem Namen "Allmende".

Nur die vielen Daten über Geburten, Sterbefälle und Eheschließungen sind von mir den Böhlschen
Aufzeichnungen entnommen, neu vom Computerberechnet und in entsprechend neue Diagramme
verwandelt worden.

In dem Nachlaß von Herrn Johann von Böhl sind auch einige kürzere Arbeiten zu finden. Diese sind
mit Ausnahme von einigen kurzen Aufsätzen hier nicht mit einbezogen worden, da sie meistens nicht
direkt mit der Dorfchronik zu tun haben.

Dr. H. W. Rerup +
North Vancouver, Canada +
25. November 1993 +