== 10. Die Entwicklung der Landwirtschaft

=== 10.1. Der Ackerbau

In Jahrhunderten vor der Feldaufteilung war der Ackerbau nur wenig entwickelt. Nur ein Teil des
verfügbaren Landes, etwa 1/3, diente dem eigentlichen Körnerbau. Ackerland, Wald, Wiese und Weide
waren nicht scharf voneinander getrennt. Alle Kulturen trugen Mischcharakter. Der Staat kimmerte
sich wenig darum, war ihm doch die Wildbahn wichtiger als der Kornbau.

Nach dem Erdbuch von 1613 (Abschrift in meinem Besitz) bestellen die beiden 3/4 Bondenstellen in
Lügum nur je 5 Demat mit Roggen und Sommersaat; bei kleineren Besitzern waren es nur, 4, 3,2, 1,
oft noch nur 1/2 oder 1/4 Demat. Im ganzen wurden angebaut:

|===
|             | Roggen     | Sommersaat
| Lügum       | 86 1/2 Dt. | 86 1/2 Dt.
| Wimmersbüll | 10     "   | 34 3/4 "
| Ellhöft     | 11     "   | 11     " (720 Fuder Heu)
| Uhlenberg   |  2     "   |  2     " (+ 60 Fuder Heu)
| Böglum      |  3     "   |  -     "
| Struxbüll   |  -     "   |    1/4 "
|===

Daraus läßt sich errechnen, daß die Erträgnisse nur für die eigene Wirtschaft bzw. Bevölkerung gereicht
haben können.
Nach und nach wurde dann mehr Land urbar und dem Ackerbau dienstbar gemacht. Da aber nur wenig
Dünger zur Verfügung stand, gab das Land nur in den ersten Jahren mäßige Erträge. Oft überließ man
es dann wieder seinem Schicksal und versuchte es anderswo. Immerhin war, wie das Erdbuch von 1697
(Abschrift in meinem Besitz) ausweist, im verflossenen Jahrhundert bedeutend mehr Land unter den
Pflug genommen. So kann denn auch das Erdbuch von 1712 schon ganz ansehnliche Größen nennen,
aufgeteilt in Wiesen- und Marschland und Ackerland, wobei die Rutenzahl in der folgenden
Zusammenstellung fortgelassen wurde:

|===
|  | Wiesen- und Marschland | Ackerland
| Lügum | 863 Dt. | 1192 Dt.
| Wimmersbüll | 38 " | 314 "
| Böglum |  212  " | 27 "
| Ellhöft | 488 " |  231 "
| Struxbüll | 167 " |  - 
|===

Bei Lügum heißt es: _"1 Pflug ist gleich 38 Demat Wiesen- und Marschland, wird aber nicht alles zum
Heuwuchs gebrauchet, sondern einiges geweydet, einiges aber wohl gar mit Hafer und Gersten besäet,
wie der Eigenthümer es für gut befindet"_ . Die Bemerkung verrät, daß der Kornbau immer noch
untergeordnete Bedeutung hatte. Struxbüll: _"Auf Aussaat ist kein Etat zu machen, da das Land bald
Weyde, bald Wiesenwuchs, auch bisweilen gepflügt, also hat es mit diesem Gut eine so gar unebenen
Bewandtnis nicht"_ . Uhlenberg: _"110 Fuder Heu, wenn alles zu Heu gebrauchet würde, viel aber
geärndtet da dann die Saath ümb so viel höher kombt"_ . Auch bei den andern Dörfern wird die
Ackerfläche nur so am Rande erwähnt.

Buchweizen und Roggen bildeten die Hauptfrucht. Sie hat als Brot und Grütze lange die Hauptnahrung
abgegeben. Zu ihnen gesellten sich dann bald die Gerste und der Hafer. Vielleicht sind auf den Fennen
in Lügum, die heute noch den Namen Haferland tragen, die ersten Versuche angestellt. Um 1770 taucht
der Name zum erstenmal in den Akten auf, als Hans Ketelsen, dessen Besitz im Dorf durch Feuer
zerstört worden, einen Platz zum Ausbauen sucht. (Siehe Hauschronik Nr. S 156).

Um diese Zeit haben auch die Kartoffeln hier ihren Einzug gehalten, was zum Teil auf das Konto der
ins Land gekommenen Kolonisten aus Süddeutschland gesetzt werden mag. Aber dieser _"Potatobau"_
fand zunächst wenig Freunde, störte er doch die alten Regeln der Feldgemeinschaft, wie sie in den
Dorfwillküren festgelegt. Nach ihnen wurden Pferde, Vieh, Schweine und Gänse nach der Ernte ohne
einen Hirten auf die Stoppeln gelassen. Nun waren aber die Kartoffelfelder um diese Zeit noch nicht
abgeerntet, so daß die Tiere dort oft großen Schaden verursachten. Erst die Anordnung, das Vieh nie
ohne Hirten zu lassen und die Androhung von 10 Rthl Strafe haben allmählich auch im Kartoffelanbau
Wandel geschaffen (1765).

Es läßt sich nicht verkennen, daß die bäuerliche Bevölkerung einen Willen zur Breite, zum
Vorwärtskommen, zum Aufstieg bekundet hat. Doch ist dieses Streben durch widrige Zeitumstände,
Kriege und Seuchen, und durch die Verständnislosigkeit der Verwaltung für bäuerliche Belange so
gehemmt und belastet worden, daß Stagnation und Rückschritt eintreten mußten. Waren nicht im
"Brandenburger Kriege" viele Bauernstellen abgebrannt und wüste geworden? Keiner wollte sie, trotz
der versprochenen Freijahre. Noch gegen Ende des 17. Jahrhunderts zählte man viele wüste Hufen, also
Hufen ohne Eigentümer. Und die andern bleiben immer wieder mit ihren Steuern im Rückstand und
mußten um Niederschlagung der Restschulden bitten. Wenn dann noch Unglücksfälle, Brandschäden,
Viehseuchen, Dürre, Überschwemmung, häusliches Unglück, Krankheit und Tod dazu kamen, waren
so viele hemmende Faktoren zusammen, daß aller Fleiß sie nicht aufwiegen konnte. Hatte Karen
Petersen in Rohrkarr nicht 1687 ein verlassenes Bohl angenommen? Und 1705 war sie - inzwischen
waren allerdings auch 16 Kinder geboren - gänzlich verarmt.

Auch in den ersten Jahrzehnten des 18. Jahrhunderts war es nicht besser. Der Zeitraum des Nordischen
Krieges (1700 - 1721) trug dieselben Vorzeichen. Es trat ein gewaltiger Rückgang in der Zahl der
Bauernwirtschaften und im Anbau ein. Wolf und Heide kamem wieder vor. Eine ländliche
Unterbevölkerung begann die Lage zu ihrem Vorteil auszunutzen, indem sie sich der
erstrebenswertesten Teile des verlassenen Landes und der Stellen bemächtigte, ohne aber als Träger
öffentlicher Lasten in Erscheinung zu treten. Die Steuereinnahmen wurden dadurch so gesenkt, daß
auch höhere Sätze den Ausfall nicht ausgleichen konnten. Für die alten Bauernfamilien wurde diese
Entwicklung immer verhängnisvoller, da die höheren Steuern auf den wenigen Schultern jede
Entwicklung hemmen mußten. Nun wollte man gerne zu geschlossenen Höfen zurückkehren und die
Kätner aus ihren gewonnenen Stellungen entfernen. Aber die staatlichen Maßnahmen - die Einführung
der Güteklassen - kamen entweder zu spät oder scheiterten daran, daß sie durch den Schlendrian der
Unterbeamten sabotiert wurden. Die Folge war, daß eine gutgemeinte Reform für viele Jahrzehnte
unwirksam bleiben mußte.

Die niedrigen Erträge hatten zudem noch ein anderes im Gefolge: Sie bewirkten oft, so 1740, ein
Ansteigen der Preise. Und die hohen Preise verführten dazu, das Korn schnell zu verkaufen. Die Folge
war, daß es bald an Brot und Saatkorn im Lande fehlte. Ein Ausfuhrverbot für Weizen, Roggen, Hafer
und Gerste kam zu spät und genügte nicht mehr, die Katastrophe aufzuhalten. Es mußte sehr viel Geld
ausgegeben werden, um das Nötigste wieder einzukaufen. Und bei den oft knappen Ernten war dieser
Vorgang fast eine Dauererscheinung. An Hand der Akten läßt sich feststellen, daß dauernd staatliche
Maßnahmen nötig waren, um das Gleichgewicht zwischen Angebot und Nachfrage, zwischen Vorrat
und Bedarf sicherzustellen. Schon 1608 war ein Ausfuhrverbot erlassen worden und angeordnet, daß
alles Korn auf den Tonderner Markt zu bringen sei. Die Verschiffung von Getreide mußte seitdem
streng überwacht werden, da man immer wieder versuchte, verleitet durch die von auswärts gebotenen
hohen Preise - Husum bekam viel Gerste aus der Wiedingharde und von Föhr - geheime
Ausschiffungen vorzunehmen.

Selbstverständlich haben auch die kriegerischen Verwicklungen der Zeit, besonders starke
Einquartierungen, wie 1624, Plünderungen usw. Marktlage, Preis und Vorrat stark beeinflußt. Erst als
1697 die Versorgungslage stabiler wurde, gab man den Handel mit Korn gegen den Protest der Stadt
Tondern wieder frei, doch durfte auch dann noch nicht aus den Herzogtümern heraus verfrachtet
werden.

Um die Mitte des folgenden Jahrhunderts kamen wieder Krisenjahre. Die Preise stiegen wieder. Roggen
kostete 9 Rthl 8 ß, Gerste 4 - 5 Rthl gerechnet nach dem Markt in Tondern, auf dem die Preise für uns
etwas höher lagen als für dänische Ware. Wieder mußten Kornschiffe aus Amsterdam und Danzig die
Vorräte auffüllen. Die Gerste blieb lange so knapp, daß die Graupenmühlen still lagen.
Lügum hatte noch 350 Tonnen Roggen, sonst nichts, und zwar:

|===
|               | Vorrat | Eigener Bedarf | Verkäuflich
| Lügum         | 120 To. | 50 To. | 70 To.
| Wimmersbüll   | 170 " | 30 " | 140 "
| Ellhöft       | 60 " | 20 " | 40 "
|===

Eine 1762 ausgesprochene Beschlagnahme hob man nach kurzer Zeit wieder auf, da die Vorräte zu
unbedeutend waren. Der Verkehr innerhalb des Landes wurde wieder erlaubt, aber der Verkäufer mußte
jederzeit über den Käufer Auskunft geben können.
Die gespannte Versorgungslage hielt auch für die nächsten Jahrzehnte noch an. Der Roggenpreis, von
6 auf 9 Rthl gestiegen, blieb konstant. Große Mengen gingen infolgedessen ins Ausland, viel wurde
auch zu Branntwein gebrannt. Alljährlich wurden die vorhandenen Mengen festgestellt. Während 1782
infolge der außerordentlich ungünstigen Witterung - es regnete 7 - 8 Wochen ununterbrochen - eine
späte Ernte schlechten Ertrag gab, bescherten die folgenden Jahre wieder eine so reiche Ernte, daß ein
Einfuhrverbot für Roggen nötig wurde. Die dauernd gestoppte Ausfuhr wurde allerdings überall,
besonders über Südwesthörn, durch illegalen Handel illusorisch.
Eine Übersicht über die Erträge in unserem Kirchspiel haben wir aus dem Jahre 1796:

|===
|erforderliches Brotkorn 950 To | Roggen  | Gerste |  Hafer | Buchweizen
|vorhandenes Korn  | 790 To |  600 To | 266 To | 216 To. 
|notwendiger Verbrauch  | 700 " |300 "| 116 " | 66 " 
|für Mühlen | 80 " | | | 
|für Brennereien | 90 " | | |
|für Ausfuhr | - | 300 " | 150 " | 150 "
|===

Langjährige Notstände brachten es mit sich, daß damals schon das Problem auftauchte, wie man die
"unvermögenden Volksklassen" mit Brotkorn zu billigen Preisen versorgen könne. Es wurden neben
dem Ausfuhrverbot eine Ausfuhrverteuerung (Zoll), eine Einfuhr-Prämie und die Anlage von
Kornmagazinen in Stadt und Land in Auge gefaßt. (In der "Geschichte des Armenwesens" ist darüber
mehr zu erfahren). Um diese Vorratswirtschaft richtig durchführen zu können, mußten alljährlich
Ernteschätzungen stattfinden und Berichte eingeliefert werden. So meldete Lügum 1806:

_"Roggen: recht gut; Gerste: wenig, aber gut; Hafer: sehr gut;
Buchweizen: gab nicht die Aussaat; Weizen: gar nicht üblich
Heu wenig,aber gut"_ .

Inzwischen war nun in der Entwicklung eine grundsätzliche Änderung eingetreten: die Feldaufteilung,
die bei uns in den letzten Jahrzehnten des 18. Jahrhunderts stattfand. Sie ist als eine der großen
Fortschritte in der Kulturgeschichte des Landes zu bewerten. Die Stagnation hörte auf. Der Fortschritt
konnte marschieren. Jeder hatte jetzt sein eigenes Feld, konnte seine Wirtschaft nach seinem Gutdünken
und Können einrichten und war sicher, das zu ernten, was er säte.
Der Staat hatte durch Kolonisten hier und da auch weiteres Land erschlossen. Um die Steuerkraft des
Landes zu heben, fing er auch an, sich um die Kulturen zu kümmern. Neben dem Kartoffelanbau
empfahl er andere Nutzpflanzen, so den Anbau von Flachs, der auf Fünen in dem Schrollschen Institut
für Flachsbereitung schon eine gute Stätte gefunden hatte. Qualifizierte Lehrlinge erhielten Staatsmittel.
So u. a. Martin Juhl in Abel, der eine ansehnliche Kultur anlegte (1806) oder Andreas Carsten Andresen
in Überg (1810). Das machte Schule, so daß der Flachsanbau auch bei uns bald Eingang fand, was nur
zu begrüßen war, weil die abnehmende Schafzucht die benötigte Wolle nicht mehr zu liefern imstande
war.

Auch der Anbau von Futterkräutern und Handelspflanzen (Rüben, Klee, Senf) wurde gefördert und fand
langsam Eingang. Neu war auch der Anbau von Feldbohnen als Pferdefutter, der natürlich nur auf
schweren Böden glückte. In Wimmersbüll gibt es noch heute eine Bohnenfenne (siehe die Flurnamen).
Alles ging nur langsam voran, schien doch jede Neuerung den ganzen Wirtschaftsbetrieb umzuwerfen.
Die wenigen Getreidesorten waren anfänglich doch nur in einfacher Folge angebaut: 1. Buchweizen
2. Gedüngten Winterroggen, 3. Ungedüngter Winterroggen, 5 Jahre Ackerweide. Und nun immer die
Neuerungen! Und wie viele Hindernisse lagen da nicht auf dem Wege voraus! Die *Ackergeräte* waren
noch so primitiv, daß sie keine intensive Bodenbearbeitung zuließen. Ein Tiefpflügen mit dem
Holzpflug, der zwar ein eisernes Schar hatte, war kaum möglich, man eggte im allgemeinen wenig, und
die hölzernen Zinken lieferten nicht die beste Arbeit. Die Ackerwagen waren schmal und klein, um
1800 noch teilweise ohne Beschlag, wie das Auktionsprotokoll des Ketel Andersen, Wimmersbüll, aus
dem Jahre 1802 ausweist. Man kannte nur wenig Getreidesorten, die in einfacher Fruchtfolge angebaut
wurden: Buchweizen, gedüngter Winterroggen, ungedüngter Winterroggen und 5 Jahre Ackerweide.
Die *Grundwasserregelung* war noch sehr mangelhaft. Dem Zuviel sowohl als dem Zuwenig stand der
Einzelne noch machtlos gegenüber, solange der Genossenschaftsgedanke auf diesem Gebiet nicht
wirksam wurde. Der *Kalkmangel* unserer Geestböden war eines der größten Hindernisse. Die
*Verkehrsverhältnisse* waren für Verkauf und Ankauf äußerst schlecht. Auch Kriege hemmten immer
wieder die Entwicklung und führten das Land in Krisen hinein. Zu den oben angeführten hier noch ein
Beispiel: Die guten Preise um 1820 verführten zu umfangreichen Landkäufen, zu hohen Krediten, die
später bei sinkenden Preisen (1827) oder Mißernten (1829 und 1830) viele Konkurse auslösten. Auch
der Naturalzehnte hemmte die Entwicklung. Diese Abgabe bestand im Bistum Schleswig seit 1186 und
wurde von der katholischen Kirche bis zur Reformation erhoben. Die Abgabe wurde zwischen Bischof,
Prediger und Kirche aufgeteilt, so daß jeder die 30.Garbe erhielt. 1533 wurde der Bischofszehnte
abgeschafft. Als die Kirchen in den Besitz der Gemeinden übergingen, fiel auch das zweite Drittel, aber
der Predigerzehnte (eigentlich = dreißigteil) blieb. Im Anfang des 19. Jahrhunderts fing man an, diese
Last öffentlich zu kritisieren. Sie wurde 1819 als _"ärgste Geisel der Landwirtschaft"_ bezeichnet.
Beschwerden und Streitigkeiten hörten nicht auf. Das man seit 1892 in die Predigerbestallung die
Klausel einfügte, daß jederzeit Veränderungen vorgenommen werden könnten, zeigt, daß man die
ungerechte Belastung endlich als solche empfand.

Im Laufe des 19. Jahrhunderts sind nun die meisten dieser ungünstigen Einflüsse langsam überwunden
worden. Die Mergelkuhlen in unserer Gemarkung können davon erzählen, was die Bauern in
mühseliger Arbeit zur Verbesserung ihres Bodens getan haben. Trotzdem ist das Wort "langsam" wohl
am Platze; denn schon in den Provinzialberichten aus dem Jahre 1818 heißt es: _"Die Bemergelung
gehört zu den wohlthätigsten und wichtigsten Erfindungen neuerer Zeit. Welch großen Umschwung hat
sie nicht in dem Betrieb des Ackerbaus gegeben! Wie prangen jetzt unsere Felder mit kornschwangeren
Ähren, wo ehedem nur spärlicher Kornwuchs sich zeigte!"_ Man schreibt schon von doppeltem Ertrag.
Der Mergel soll manchen auf seinem Besitz gelassen haben, der sonst in den Notzeiten der Verarmung,
als der Kurs des Geldes von Jahr zu Jahr sank, anheimgefallen wäre. Selbstverständlich, das wußte man
schon damals, setzt eine Bemergelung doch eine genaue Kenntnis des Bodens voraus, wenn nicht das
alte Wort zu Recht bestehen soll, daß sie "reiche Väter und arme Söhne" mache. Auch der damals neu
eingeführte Anbau von Klee hatte große Förderung durch die Bemergelung: Es gab mehr Gras, mehr
Heu; man konnte mehr Vieh halten, es gab mehr Dünger, der wieder dem Acker zugute kam; die
Milcherzeugung stieg und eine umfangreiche Aufzucht und Schweinemast wurde ermöglicht.

Ob aber damals schon bei uns eine Bemergelung stattgefunden hat, erscheint zweifelhaft und ist nicht
nachweisbar. Eine intensive Bemergelung erscheint auch erst im Zeitalter der Maschine und des
Verkehrs denkbar. So wurden hier erst 1906 durch den Anschluß an die Renzer Genossenschaft
Struxbüll und Teile von Ellhöft, Böglum und Lügum bemergelt. Und erst 1925 wurde durch den
Mergelverband Ladelund und Umgegend der größte Teil unserer Ländereien mit Mergel versorgt. Der
damalige Gemeindevorsteher Julius Jensen war im Arbeitsausschuß vertreten. Es wurden 15 - 20 cbm
auf den Demat gegeben. Der Preis stellte sich auf 6.- RM je cbm.

Auch die Acker- und Wirtschaftsgeräte wurden allmählich verbessert. Es kam der Motor, es kamen
Licht und Kraft. Der frühere Gemeindevorsteher von Wimmersbüll, Herr Paul Andresen, berichtete mir
aus dieser Übergangszeit: _"Bis 1880 gab es noch keine brauchbaren Maschinen. Nur auf festen Boden
konnte mit Maschine gemäht werden. Harkmaschinen gab es noch nicht. Das Heu wurde mit der
Handharke gesammelt und mit Pferden zusammengefahren. Rüben wurden schon angebaut. Die
Dreschmaschine war noch unbekannt. Wenn um Martini (11. Nov.) das Vieh eingestallt wurde, hörte
die Außenarbeit auf, und der Dreschflegel schlug den ganzen Winter den Takt. Das Füttern war damals
auch etwas anders: Alles Vieh mußte paarweise losgemacht und zum Wassertrog gejagt werden.
Häcksel wurde mit der Hand geschnitten. Die Milch wurde im Hause entrahmt und verbuttert. In jedem
Hause wurde gebacken und Bier gebraut. Abends spannen die Frauen, und stellenweise klapperte der
Webstuhl (W. Nr. 5).
Mit der Zeit änderte sich alles. Zwischen 1895 und 1900 kam die erste Harkmaschine. Die erste
Dreschmaschine, ein Trapper, d.h. eine Maschine, die von einem Pferd, das auf einem Rad ging,
getreten wurde, habe ich 1901 für Matthias Paysen (W. Nr. 13) vom Moor bei Maasbüll leihweise
geholt. Später kamen die Lokomobile, die mit Kohlen geheizt wurden, ins Dorf, um gegen ein Entgelt
das Dreschen zu besorgen. Erst nach 1900 stellten die Besitzer selbst Dreschmaschinen auf, die durch
Göpel mit Pferdekraft getrieben wurden.
1910 erhielten die Besitzer Nr. 17 und 18 in Wimmersbüll Windturbinen für Dreschen, Mahlen und
Pumpen. Die Besitzer von Nr. 1, 13 und 14 stellten einen Motor auf, der auf den ersten beiden Höfen
auch zur Erzeugung von elektrischem Licht benutzt wurde. 1927 fing die Überlandzentrale an, den Ort
mit Licht und Kraft zu beliefern, ausgenommen Nr. 13, 14 und 17. Das war eine große Veränderung.
1931 erhielt auch Nr. 17 elektrisches Licht- und Kraftstrom, die Pachtstelle Nr. 14 etwas später. Nr.
13 erzeugt durch Rohölmotor selbst Licht."_

Auch bessere Verkehrsverhältnisse - Wege, Straßen, Eisenbahnen - und eine großzügige
Wasserregulierung in unseren tiefliegenden Wiesen, besonders seit 1935,(beides wird in besonderen
Abschnitten behandelt) sind der Landwirtschaft weitgehend zugute gekommen. Verbesserte Pflüge und
Eggen, Kultivatoren und alle Arten von Maschinen taten das ihrige. Eine umfangreiche Drainage,
besonders seit 1920, brachte ihren Segen. Zu dem vermehrten Stalldünger trat der Handelsdünger. Der
Hackfruchtanbau, die Grundlage der gesteigerten Viehhaltung, brachte infolge der besseren Ausnutzung
des Bodens eine reichere Fruchtwechselfolge:Gras, Hafer (Roggen), Hackfrucht, Mengkorn(Weizen)
und 5 - 6 Jahre Gras. Wiesen reichlich mit Binsen und sauren Gräsern bestanden, veränderten ihr
Aussehen. Ländereien, die streckenweise jährlich für längere Zeit unter Wasser traten, bringen jetzt eine
gute Ernte. Die Hektarerträge weisen eine Steigerung auf, die man vor 50 Jahren nicht für möglich
gehalten hatte.

Durch die Beseitigung aller früheren Hemmungen, nicht zuletzt durch die bessere Kenntnis sowohl des
Bodens wie auch der Wachstumsbedingungen der Kulturpflanzen, ist auch die Kulturfläche ungeheuer
gewachsen. Es ist kaum ein Stückchen Heide mehr zu finden. Erwähnt werden muß in diesem
Zusammenhang auch das Verdienst der bäuerlichen Organisation und die Schulung des Nachwuchses
auf den Berufsschulen. Durch Arbeit und Fleiß und Sparsamkeit des einzelnen Bauern aber hat nun
unsere Geest ein anderes Gesicht bekommen. Was hier an Kulturarbeit durch die bäuerliche
Bevölkerung geschaffen ist, wird immer ein Ruhmesblatt der Landwirtschaft bleiben. 1774 verzeichnete
Lügum noch 800 Demat Ödland, jetzt ist alles Weide, Acker oder Wald. 1877 hatte es in 1.392
Parzellen 1.656 ha steuerpflichtige Liegenschaften. 1880 hatte Ellhöft 154,7140 ha, Böglum 117,8906
ha und Wimmersbüll 232,3319 ha Ackerland.

1925 wurden die Kulturflächen wie folgt angegeben:

|===
|              | Süderlügum | Ellhöft | Böglum | Wimmersbüll | Zusammen 
| Gesamtfläche | 2183 | 432 | 342 | 403 | 3360
| Acker        | 944 | 118 | 135 | 335 | 1532
| Weide        | 230 | 92 | - | - | 322
| Wiesen       | 350 | 21 | 200 | 41 | 808
| Wald         | 488 | - | - | - | 488
| (1947)       | 659 |  |  |  | 
|===

Hand in Hand mit dieser Entwicklung im Ackerbau und ohne die überhaupt nicht denkbar, geht die
Aufwärtsbewegung in der Viehhaltung. Die hier getrennt behandelten Gebiete müssen in engster
Wechselwirkung gedacht werden.

=== 10.2. Die Viehzucht
Im Satzungsregister und Erdbuch von 1712 findet sich folgender Passus: _"Das Dorf ist durchgehends
von gar guter constitution, und kann sowohl den Kornbau sich zu nutze machen, als es auch aus der
Vieh- und Pferdezucht, nicht minder aus dem Weyden feister Ochsen guten Vortheil ziehet, hat dabey
die Nothdurft von Feuerung, welches ein großer ist."_

So wurde damals schon das Kirchspiel, gewiß infolge der sehr zahlreich vorhandenen Heide Flächen(=
Weiden) und des Anteil an den Wiesen der Süderau und des Karrharder Alten Kooges, ein wichtiges
Aufzuchtgebiet.

Im Erdbuch von 1613 werden schon folgende Zahlen genannt, leider für Wimmersbüll unvollständig:

|===
|             | Beeste | Pferde | Schweine | Schafe
| Lügum       | 529 | 104 | 137 | 260
| Wimmersbüll | - | - | - | 90 
| Ellhöft     | 80 | 36 | 12 | - 
| Uhlenberg   | 26 | 16 | 4 | -
|             | 643 | 260 | 157 | 350 
|===

Für Böglum und Struxbüll sind gar keine Zahlen angeführt. Das wird durch folgende Bemerkung
entschuldigt: _"hier ist zu wißen, daß dieße Leuthe kein Geestland haben, da Sie Ihre Pferde und ander
Viehe auf Greßen, sondern müßen solches auf Ihr bedeichet Landt, so Vorheer nach Dhematzahl einem
Jeden angeschrieben, auferziehen"_ .
Im Jahre 1714 wird der Rindviehbestand an Kühen unter drei Jahren mit 196, an Kühen über drei
Jahren mit 156 angegeben, zusammen somit 352 Stück.
Erst aus dem Jahre 1669 liegt ein vollständiges Rindviehverzeichnis vor, das den Bestand jedes
einzelnen Besitzers nach Kühen, Ochsen, Jungvieh und Kälbern aufteilt:

|===
|              | Kühe | Ochsen | Junvieh | Kälber | insgesamt
| Lügum        | 254 | 142 | 291 | 81 | 768
| Wimmersbüll  | 59 | 105 | 61 | 21 | 246
| Böglum       | 21 | 11 | 41 | 16 | 89
| Stuxbüll     | 15 | 6 | 15 | 5 | 41 
| Ellhöft      | 81 | 25 | 104 | 40 | 250
| Uhlenberg    | 9 | 4 | 16 | 4 | 33
|              | 439 | 293 | 528 | 167 | 1427
|===


|===
| Einzelbeispiele: | Nr. der Hofchronik | Kühe | Ochsen | Jungvieh | Kälber | insgesamt
| *Lügum:*          |  |  |  |  |  |
| Pastor Ambders    | 45 | 6 | - | 13 | 5 | 24
| Johs. Sönnichsen  | 7 | 8 | 36 | 12 | 4 | 60
| Lorenz Todsen     | 57 | 5 | 23 | 4 | 1 | 33
| Peter Karstensen  | 46 | 6 | 6 | 10 | 1 | 23
| *Wimmersbüll:*    |  |  |  |  |  | 
| Lorenz Brodersen  | 14 | 5 | 25 | - | 1 | 31 
| Iwer Brodersen    | 4 | 4 | - | 9 | 2 | 15
| Thordt Nissen     | 18 | 6 | 30 | 8 | 3 | 47
| *Böglum:*         |  |  |  |  |  | 
| Fedder Andersen   | 5 | 7 | 2 | 10 | 7 | 26
| *Uhlenberg:*      |  |  |  |  |  | 
| Andreas Brodersen | 5 | 7 | 2 | 10 | 7 | 26
| *Ellhöft:*        |  |  |  |  |  | 
| Friedrich Thomsen | 9 | 8 | 4 | 14 | 5 | 31
| Wolf Andersen     | 11 | 10 | 8 | 24 | 6 | 48
| Peter Carstensen  | 13 | 9 | 4 | 16 | 6 | 35
| Karsten Christiansen | 18 | 6 | 3 | 12 | 6 | 27
|===

Vergleicht man die Gesamtzahlen von 1714 und 1779 miteinander, so fällt die gewaltige Steigerung
von 695 auf 1.727 Stück, also um mehr als das Doppelte sofort ins Auge. Dies bezieht sich aber nur auf
Ochsen, Jungvieh und Kälber, während der Kuhbestand, von 591 auf 439 Stück, also um 34,6%
gefallen ist. Auch bei Durchsicht der Einzelbeispiele wundert man sich über die geringe Anzahl der
großen Höfe Nr. 7, 57 usw.. Worin war die Abnahme in der Kuhhaltung begründet? Ihre Reihen
scheinen sich besonders durch die in den letzten hundert Jahren wiederholt auftretende Viehseuchen
gelichtet zu haben.

In den achtziger Jahren des 17. Jahrhunderts trat eine bis dahin unbekannte Seuche unter dem Vieh auf,
so daß mehr denn _"1.000 Stück Vieh hinfalle und verrecken"_ . Man bezeichnete sie als Lungensucht. Der
Viehbestand, schmolz zusammen. Der Dünger fehlte dem Acker. Viel Land wurde wieder zu Heide.
Nur sehr langsam konnte die Landwirtschaft sich wieder erholen. Doch war nur ein reichliches
Jahrzehnt des neuen Jahrhunderts dahingegangen, da kam die Seuche wieder. Die verschiedenen
Namen: Rinderpest, Viehpestilenz, Contagien (Anstechung), laufendes Feuer, Lungensucht und
Brustseuche beweisen, daß man sie immer noch nicht kannte und deshalb auch nicht wirksam
bekämpfen konnte. Wegen der Ansteckung war es gefährlich, Viehmärkte zu besuchen. Die Städte
versuchten sich zu schützen, indem sie Pestwachen aufstellten. Unsere Karrharde war stark befallen.
Trotzdem kaufte der Tonderner Kaufmann Peter Mennige eine größere Partie Ochsen in Lügum und
schickte sie nach Holland. Unterwegs sollen ganze Ladungen eingegegangen sein und von dem Rest
wurde _"gantz Holland infizieret"_ .

Da die Seuche in jedem Jahre aufs neue auftrat und das Dorf Lügum 1717 ganz verseucht war, wurden
auch hier Wachen aufgestellt. Ihre Aufgabe war es, zu verhüten, daß krankes Vieh durch das Dorf
getrieben wurde. Frei umherlaufende Hunde wurden abgeschossen. Erkranktes Vieh mußte getötet und
3-4 Ellen tief in ungelöschtem Kalk verscharrt werden. Einzelwohnende mußten die Fuhren zur Mühle
übernehmen. Die Dienstboten durften das Haus _"bei Strafe der Karre"_ nicht verlassen. Innerhalb von
sechs Stunden mußte eine Erkrankung gemeldet werden, andernfalls es keine Vergütung gab. Alle
möglichen und unmöglichen Mittel zur Vorbeugung, zur Verhinderung weiterer Verbreitung und zur
Heilung des erkrankten Viehs wurden empfohlen, probiert, verworfen und wieder empfohlen. Dem
Physikus Fabricius in Tondern verdanken wir die Kenntnis von über 30 Rezepten, die von ihm
durchgeprobt (1745), numeriert und zusammengetragen wurden. Viele nötigen uns heute nur noch ein
Lächeln ab - ich habe sie alle abgeschrieben -, spiegeln aber auch den ganzen verzweifelten Ernst der
Lage der bäuerlichen Bevölkerung wider. Teufelsdreck, saurer Hering, Teer, Hefe, Bier-Käsig, Hafer-
und Gerstenschleim, Aderlaß und Leberpulver, die Brühe von den Köpfen der erkrankten Tiere: kein
Mittel half. Auch die von Holland angepriesenen Mittel, die dort mit großem "success" gebraucht
worden, erwiesen sich als wirkungslos. Das Absperren einzelner Gehöfte, ganzer Dörfer, der ganzen
Karrharde, ganzer Distrikte und Landschaften konnte nicht helfen. Was der Krankheit selbst nicht zum
Opfer fiel, wurde durch Totschlag der gefährdeten Tiere erledigt. So häuften sich die Verluste. Um alle
Gegenmaßnahmen durchführen zu können, wurde 1 Rthl lübsch vom Pflug erhoben. Drei Schauleute
aus Lügum schrieben 1717:0 _"Gott, hilf uns überwinden und wende dieße verderbliche Vieh-Seuche von
uns in Gnaden ab, damit wir nicht alle zum Bertelstab greifen sollen. Die meisten in Lügum Dorf sind
dar fast all an"_ .
Nachdem die Seuche 1718 erloschen war, trat sie im September 1724 in Lügum und den benachbarten
Dörfern wieder auf. Man glaubte die Ursache in nasser Witterung, mangelhaftem Kornwuchs, dumpfen
Ställen und schlecht erhaltenem Futter suchen zu müssen. Wieder zeigte sich auch, wie früher, die
Verständnislosigkeit der Bevölkerung gegenüber den behördlichen Anordnungen, die der Ausbreitung
der Krankheit Vorschub leistete.
Besonders starke Verluste hatten wir von Mai 1746 bis Mai 1747. Von 2.345 Rindern, die die
Karrharde einbüßte, verlor Lügum in wenigen Wochen 817 Stück. 1752 schien die Krankheit wieder
erloschen zu sein. Aber noch einmal kam eine Heimsuchung: 1763 verloren wir 548 Tiere (Braderup
229, Humptrup 82, Ladelund 820, Medelby 444). Die größten Höfe unseres Kirchspiels verloren 10,
12, 15, 16, ja einer sogar 20 Stück in diesem Sommer. Viele Kätner büßten ihre einzige Kuh ein. Die
Ställe wurden leer, dem Acker fehlte der Dünger und die Einnahmen fehlten. Auch eine Steuerfreiheit
von ein oder zwei Jahren konnte das Schicksal vieler Familien nicht mehr wenden. Angesichts dieser
Verluste verstehen wir, daß man sich 1779, im Jahr der Viehzählung, noch nicht wieder erholt hatte.
Die Seuche der Jahre 1774 - 1782, die Schleswig noch 63.160 Stück abforderte, erreichte unser
Kirchspiel glücklicherweise nicht. So war es möglich, daß wir infolge guter Ernten in den achtziger
Jahren und durch Einfuhr nach und nach unsere Ställe wieder füllen konnten.

Seit Jahrhunderten sind wir hier, wie das eingangs erwähnte Erdbuch von 1712 schon feststellte,
Aufzuchtgebiet gewesen. Der Ochsenhandel war deshalb auch stets das Rückgrat unserer
Landwirtschaft. Viele Bauern waren nicht nur Produzenten, sie waren auch Händler, Käufer und
Aufkäufer fremder Tiere, Verkäufer, Marktreisende. Sie brachten große Gewinne nach Hause, wurden
wohlhabend und reich, um ebenso schnell wieder Gewinn und Glück verfließen zu sehen, zu verarmen
und Haus und Hof zu verlieren. Monatelang durchreisten sie Jütland als Aufkäufer und tage- und
wochenlang standen sie im Süden zu Markt. Der lockende Gewinn ließ sie alles vergessen und alles in
Kauf nehmen: die Unbill der Witterung, die Gefahren der Landstraße, die Abwesenheit von und die
Sorge um Familie und Haus und Hof, die Unbequemlichkeiten längeren Aufenthalts auf fremden
entfernten Märkten, die mögliche Verführung zu Trunksucht und leichtem Leben.

Holland scheint um 1600 Hauptabnehmer gewesen zu sein. Vieles ging auch nach Ostfriesland. Eine
besondere Rolle im Ochsenhandel spielte immer der Zoll. Der Zollsatz war damals 4 ß _"vor jedes
Stück"_ . Natürlich versuchte man, die Zollstellen zu umgehen und die Zollabgaben zu sparen. Die
Brücheregister sind voll von Zollhintergehungen. Namentlich scheint sich der Adel in dieser Richtung
versucht zu haben. 1630 erhob die Zollstelle Rendsburg l Rthl für Pferde und Ochsen.
In den Marktstädten vermittelte der Ochsenschreiber den Handel, zuweilen auf Kosten des Händlers.
So wird 1685 von dem Ochsenschreiber Jürgen Bussen aus Hamburg berichtet, daß er sich, _"da er
seynen Beutel genugzahm besticket, betrüglicher wyse nebest dem Gelde und Büchern davon
gemachet"_ . Solch ein Fall hatte dann oft schlimme Folgen, denn häufig waren die Ochsen noch nicht
bezahlt, auch sollte der Zoll vielfach erst nach dem Verkauf, also nach der Rückkehr entrichtet werden.
Dazu kam noch die Unsicherheit der Landstraßen: 1663 hatte Ingwer Thomsen aus Humptrup Ochsen
in Jütland gekauft, nach Hamburg zu Markt getrieben und dort mit anderen verkauft. Als er _"die Gelder
nach Hause fahren wollte, kamen Straßenräuber bey mir und plünderten mir mein Gelt, so bey 600
Rthl, und alles ab, wie männiglich bekannt, gestalt, denn auch zwey von denselben Räubern zu Lübeck
seyn justificieret"_ . Thomsen aber wurde verurteilt, den Personen, von denen er die Tiere gekauft hatte,
zu bezahlen und - verlor darüber seinen Besitz.

Nis Lorentzen in Lügum hatte 1682 Ochsen an Berendt Berntsen in Tondern verkauft. Da letzterer
nicht zahlen konnte, hatte er es verstanden, _"sich einen Aufschub von 2 Jahren zu erschleichen"_ .
Lorentzen aber wurde von seinem Gläubiger Iwer Andersen zu Maasbüll gedrängt, von dem er die
Ochsen erstanden. Die angeordnete Zahlung innerhalb von 14 Tagen bringt auch ihn in einige
Verlegenheit.

So lassen sich durch die Jahrhunderte hindurch viele Beispiele anführen, die zeigen, daß der Handel
sehr oft zu wirtschaftlichem Niedergang und völligem Ruin des Einzelnen führte. Das verschlimmerte
sich noch als infolge geldwirtschaftlicher Verflechtung der Abstieg des einen auch andere in
Mitleidenschaft zog. Das Jahr 1902, in dem vier Höfe in Konkurs gerieten, ist noch heute bei älteren
Einwohnern in schlimmer Erinnerung.

Die Viehseuchen hatten natürlich auch eine Schwächung des Handels und großen Rückschritt im
Gefolge gehabt. Aber die günstige Entwicklung - 1787 und 89 waren außerordentlich fruchtbare Jahre
- ließen sie doch bald überwinden. Der Kirchspielsvogt Johannes Sönnichsen in Lügum (Nr. 7) wird
unter den Handeltreibenden genannt. Aber das Jahr 1813, das Jahr des dänischen Staatsbankrotts, bringt
wieder einen Rückschlag. Die in Holstein auftretende Seuche erreicht glücklicherweise unser Gebiet
nicht, so daß die Chancen bald wieder steigen. In den nächsten Jahrzehnten verlagert sich der Handel
von Holland in die aufblühenden Elbmarschen: Husum, Itzehoe und Hamburg werden Marktstädte für
uns. Wir hatten hier großen Durchgangsverkehr, führt doch der alte *Ochsenweg* durch unsern Ort. Trift
auf Trift, Magervieh für die Marschweiden und Fettvieh für die Märkte, wurde durch Lügum getrieben,
je 30 - 40 Tiere, die gewöhnlich von zwei Treibern gegen guten Lohn und Verpflegung betreut wurden.
An warmen Tagen hatten sie ihre schweren jütischen Holzschuhe zusammengebunden über die Schulter
geworfen oder einem Tier an die Körner gebunden und machten selbst den Weg in Socken oder barfuß.
Der Rückmarsch war leichter, auch mit dem Lohn in der Tasche und einem Paar neuer Stiefel über der
Schulter. Schneller, bequemer und vornehmer reiste der Händler selbst, der den Markt besuchte und
den Handel abschloß: zu Pferde (siehe Nr. 77 der Hofchronik) oder mit der Gig, die schweren
Silbertaler im Mantelsack oder in einem Kasten unter dem Wagensitz. Da verschlug nämlich keine
Geldtasche unserer Tage. Verkaufte einer nur 10 Ochsen zu je 100 Rthl, so wogen diese schon 25 kg.
Und wie oft wurden von einem Mann 20, 30, ja bis zu 100 umgesetzt.
Und die Heiden nördlich und südöstlich des Kirchdorfes waren gesuchte Weide- und Lagerplätze und
das Dorf füllte sich mit Händlern und Treibern . Noch 1844 schreibt Petersen in seiner _"Wanderung
durch Nordfriesland"_ : _"Im Frühling und Herbst machten Passage aus Jütland und dem nördlichen
Westen des Herzogthums nach den Viehmärkten in Leck und Husum und umgekehrt, Viehhändler und
ihre Scharen Süderlügum lebhaft. Man trifft dann an bestimmten Tagen der Woche in den hiesigen
bedeutenden Wirtshäusern eine brüllende Frequenz; oft übernachten in deren einem zugleich dreißig
Viehhändler außer ihren Rottmeistern"_ .

Dieser Durchgangsverkehr aus dem Norden hatte sich bedeutend verstärkt, als die alte Zollgrenze an
der Königsau 1827 aufgehoben war. Nicht nur Ochsen, sondern auch Pferde, Schweine und Schafe
fanden den Weg nach dem Süden. Schon in den Jahren 1818 - 1823 hatte Jütland außer 48.000 Rindern
56.000 Schweine, fast 9.000 Pferde und 231 Schafe geliefert. Als 1845 in England der Freihandel
eingeführt wurde, wurden auch Husum und Tönning als Verschiffungshafen ausgebaut und benutzt.
So gingen z.B. 1861 von Tönning 23.530 Rinder und viele Schafe nach England. Erst als 1864 die
Ausfuhr über Tönning erschwert war, konnte Esbjerg anfangen aufzublühen. Für uns sind natürlich
immer die nahen heimischen Märkte die wichtigsten gewesen. Sie konnten von jedem erreicht werden.
Tondern hat immer den ersten Platz eingenommen. Seit 1548 tritt daneben Leck, wohin der bis dahin
in Strichsand bei Medelby abgehaltene Markt durch den Herzog Johann verlegt wurde. Aber bis 1920
wurde Leck von uns aus weniger besucht. Mit der Entwicklung Tonderns zum verwaltungs- und
geschäftlichen Mittelpunkt wurde auch der Tonderner Markt für uns der wichtigste. Wie dort an den
Vortagen der Märkte in den Ställen schon manches Geschäft getätigt wurde, entwickelte sich auch in
Süderlügum ein umfangreicher Vormarkt, den die Händler aus dem Süden gerne besuchten. Die
Besitzer der Häuser Nr. 46, 47 und 48 hatten vor demselben in einem Meter Abstand ein Geländer
(steinerne Pfähle, durch die oben eine Eisenstange lief) errichtet, nicht zwar, um die Fenster vor
neugierigen und aufdringlichen Tieren zu schützen, sondern besonders, um sie vorteilhaft in einer Reihe
aufstellen und anbinden zu können. Bei Nr. 47 ist diese Einrichtung noch heute (1950) vorhanden.
Neben dem Hornvieh verdienen auch die andern Zweige der Viehzucht eine kurze Darstellung und
Würdigung. Schon früh, aktenmäßig nachweisbar vor 250 Jahren, erkannte man, daß unser Gebiet
besonders gut für die *Aufzucht von Pferden* geeignet sei. Wenn auch die schlechten
Verkehrsverhältnisse einen großen Verschleiß an Pferden bedingen mochten, so wurde dies doch durch
den wenig entwickelten Ackerbau völlig aufgehoben, so daß bei einer planmäßigen Aufzucht bald eine
Ausfuhr möglich wurde. Unsere Bauern lernten bald, das Pferd richtig zu taxieren. Der Pferdehändler
schöpfte den Überschuß für den Export in den Marschharden und auf den Märkten ab und sorgte dafür,
daß für alte und unbrauchbare Tiere Ersatz zur Verfügung stand. Von einer Zucht, d.i. eine planmäßige
Auswahl der Elterntiere, hören wir zum erstenmal 1711: Für das Amt in Tondern sind sechs neu
aufgekaufte Hengste aufgestallt. Die Kosten in Höhe von 1.701 Rthl werden über das ganze Amt
verteilt. Die Stuten, die diesen Hengsten zugeführt werden, wurden gebrannt, die Füllen registriert und
ihre Ausfuhr verboten. Doch blieb der erhoffte Erfolg aus: Die Entfernung war zu groß; man weigerte
sich, die Stuten 5 - 6 Meilen entfernt zum Hengst zu führen. Erst um 1769 scheinen diese Mißstände
einer positiven Lösung näher gekommen zu sein. Es tauchen nämlich Vorschläge auf, jeder Harde
einen Hengst aus der Königl. Stutterey zur Verfügung zu stellen. Hand in Hand damit sollten dann die
untauglichen Tiere abgeschafft werden. Um hier durchgreifen zu können, forderte man den Körzwang
und ließ eine genaue Beschreibung der gewünschten Beschaffenheit von Kopf, Ohren, Augen, Hals,
Brust, Rücken, Kreuz, Beine und Füße ausarbeiten. Aber nur langsam wächst die Überzeugung, daß
das schöne Pferd wertvoller und leichter zu verkaufen sei als das schlechte. Da in den Jahren gerade
viele kleine schlechte Pferde aus Ripen und Hadersleben auf dem Markt erschienen - kurz von Hals,
breit am Kopf, nicht gerade auf den Beinen -, rief man immer wieder zum Halten von Hengsten auf,
ohne Erfolg: _"Es hat sich niemand in Karrharde bereit gefunden, gute Hengste zu halten, ob schon die
Dörfer Lügum, Humptrup, Klixbüll, Braderup und Leck gut dafür qualificieret wären"_ . Wenn auch die
Preise dabei eine nicht unwichtige Rolle spielen - gute Tiere kosten 100 - 150.- Rthl, alte nur 10 - 20.-
Rthl -, so scheinen doch die Pferdehändler die ablehnende Haltung der Bauern maßgeblich beeinflußt
zu haben. Da so auf der Grundlage der Freiwilligkeit nicht weiterzukommen war, wurde die
Angelegenheit auf dem Verordnungswege vorangetrieben. Jedenfalls trat auf dem Klipleffer Markt im
Jahre 1800 diese Verordnung vom 30.2.1797 in Kraft: die Besichtigung der Hengste wurde
durchgeführt.

Seit dem ist nun die Entwicklung langsam, aber stetig weitergegangen. Welcher Fortschritt allein in den
letzten Jahrzehnten! Von 163 Hengsten im Jahre 1910 stieg ihre Zahl bis 1949 auf 462, davon 301 in
Einzelbesitz und 161 in Genossenschaftsbesitz. In Südtondern sind es jetzt 40, davon sechs allein im
Privatbesitz von Heinrich Nissen in Wimmersbüll (Nr. 22). Wenn man den Durchschnittsatz von 80
Stuten je Hengst zugrunde legt, kommt man auf eine ansehnliche Zahl und erkennt, daß auch bei uns
das Schleswigsche Kaltblutpferd eine gute Stätte gefunden hat.
Die *Schweinezucht* hat in unserer Landwirtschaft immer eine untergeordnete Bedeutung gespielt. Zwar
war es einmal anders. Aber mit der Schrumpfung und dem gänzlichen Untergang des mittelalterlichen
Waldes ging auch die Schweinezucht zurück. 1830 kam auf zehn Kühe nur noch ein Schwein. Mit der
Hebung der Milchwirtschaft trat allerdings eine Steigerung ein: 1845 kam auf drei bis vier Kühe schon
ein Schwein. Außer den heimischen Märkten waren Hamburg, Lübeck und Holland, später auch
Sachsen und das Rheinland unsere Aufnahmegebiete. Groß war dagegen der Durchgangsverkehr mit
Schweinen. Ganze Herden von borstigen, mageren Tieren zogen Jahr für Jahr durch das Kirchdorf nach
Leck und Husum, die Treiber voran, mit langen Peitschen bewaffnet, den Brotbeutel schwingend, dem
die Tiere willig folgten. Als die harten Chausseen kamen, war es aus mit diesen Triften.
Auch die *Schafzucht* ist hier einmal bedeutend gewesen, wurden doch 1613 in den Dörfern Lügum und
Wimmersbüll allein 360 Schafe gezählt. Auch die Erwähnung der Schafe in den Dorfwillküren sowie
der Schafdiebe in den Brücheregistern beweist, daß das Schaf ein sehr geschätztes Tier war, lieferte es
doch durch Jahrhunderte hindurch fast den gesamten Bekleidungsstoff. Als aber nach der
Feldaufteilung die Heideflächen immer kleiner wurden und als ausländische billige Stoffe hereinkamen,
ging die Schafhaltung schnell zurück. Auch die gutgemeinte Förderung durch amtliche Stellen, wie z.B.
der Verkauf von Spanischen Widdern aus der Königl. Schäferei zu Esserum auf dem Markt in Tondern
1806, konnte den Rückgang nicht aufhalten. Der Mangel an Wolle und Stoffen während der Weltkriege
zwang noch einmal zu vermehrter Schafhaltung, die aber nach wenigen Jahre wieder abebbte.
Das Mittelalter war auch die Blütezeit der *Bienenzucht*. Fast jeder Garten hatte seinen Bienenstand.
Der Wachsbedarf der katholischen Kirche war groß. Honig war fast der einzige Süßstoff und bei
vielerlei Krankheiten ein geschätztes Heilmittel. Der Med war ein altbeliebtes Getränk. In alten
Abnahmekontrakten finden sich oft Bestimmungen über den Bienenhagen. Wenn auch seit 1838 noch
einmal eine geringe Zunahme der Bienenvölker festzustellen war, die hemmenden Faktoren waren doch
ausschlaggebend: neue Süßmittel, Sirup und Zucker, allmähliches Verschwinden der Heideflächen,
Unkraut- bekämpfung, Kunsthonig und Einfuhr von billigen Auslandshonigen. Wenn die Bienenzucht heute auch
rationeller betrieben wird als früher, indem die Korbimkerei fast ganz dem Mobilbetrieb, dem Gebrauch
der beweglichen Wabe im Kasten, hat weichen müssen, wenn neue Zuchtmethoden und besseres
Wissen um das Leben der Bienen, wenn in der Pflege der Bienen und der Behandlung des Honigs auch
mehr getan wird als früher, die Zahl der Völker ist wie die Zahl der Imker nur verhältnismäßig klein.
1949 wurden nur 42 Bienenvölker gezählt.

|===
| *Viehzählung von 1949:* | *Süderlügum* | Ziegen | 4 
| Pferde | 192 | Federvieh | 1180
| Hornvieh | 1089 | Gänse | 128
| davon Milchkühe | 337 | Enten | 76
| Schafe | 146 | Truthühner | 25
| Schweine | 552 | Bienen | 42
|===

=== 10.3. Das Meiereiwesen

Die Aufwärtsbewegung in Ackerbau und Viehzucht ist, wie aus vorigem erhellt, besonders seit der
Feldaufteilung zu konstatieren. Die Viehseuche war überwunden, die Futtergrundlage wurde verbreitert
und verbessert, der Viehstapel wuchs und, was das Wichtigste war, die Qualität wurde von Jahrzehnt
zu Jahrzehnt verbessert. Noch um 1820 wogen die kleinen Holländer Kühe nur drei- bis vierhundert
Pfund und gaben täglich nur 8 - 10 1 Milch, sie benötigten aber 1 1/4 ha Weidefläche. Bald wurde es
nun möglich, auf derselben Fläche mehr Tiere zu halten. Der Milchertrag stieg: hatte bis 1838 die
Produktion nur ausgereicht, um den Binnenmarkt notdürftig zu versorgen, so stellte die Mehrleistung
die Landwirtschaft bald vor ernste Fragen betreffend Verwertung und Absatz. Sie konnten nicht mehr
von dem Einzelnen gelöst werden, sondern erforderten gemeinsames Handeln, d.i. Arbeit auf
genossenschaftlicher Grundlage: 1865 wurde in Pöhlf auf Alsen die erste Meierei errichtet, damit war
der Weg der zukünftigen Entwicklung beschritten. Ein Kreis folgte dem andern, ein Ort dem andern.
Das Gründungsjahr für Süderlügum ist 1897, in dem eine Anzahl Landwirte beschlossen, eine freie
Genossenschaftsmeierei zu errichten, d.h. eine Meierei, die keinem übergeordneten Verband
angeschlossen war. Sie umfaßte die Gemeinden Süderlügum, Wimmersbüll, Humptrup, Seth und
Überg. Andreas Jens Jensen war ihr erster Vorsitzender.

Durch die Grenzziehung 1920 wurden die Gemeinden Seth und Überg abgeschnitten und verlangten
ihren Anteil ausbezahlt, wodurch die Meierei in eine schwierige Lage geriet. Da auch die Zukunft
infolge der Verluste dieser Distrikte keine Besserung zu bringen versprach, beschloß man - Küster
Jensen, Humptrup, hatte inzwischen den Vorsitz übernommen - , die Meierei zu verkaufen. Sie ging
in den Besitz des Butterhändlers Carstens in Hamburg über. Meierist blieb Christophers, der seit der
Gründung den Betrieb geleitet hatte. Als in Uphusum eine neue Meierei gebaut wurde, ging er nach
dort und Paul Wiese wurde sein Nachfolger hier.

Damit war es eine Privatmeierei geworden, die ihre Milch frei ankaufte und verarbeitete. Da aber der
Ertrag für den Einzelnen nicht den Erwartungen entsprach, auch die Inflation inzwischen immer größer
wurde, so daß die nachträglichen Auszahlungen fast wertlos waren, wurden viele Lieferanten der Sache
leid. Während einige ihre Milch zeitweilig nach Uphusum lieferten, schaffte ein großer Teil Zentrifugen
an, um die Milch selbst verarbeiten zu können. Sie verschafften sich dadurch laufend wertbeständige
Ware und konnten in etwa der Geldentwertung entgegnen. Die Meierei war die Leidtragende dieser
Entwicklung, die sie bald gänzlich unrentabel machen sollte.
In den Jahren 1925 und 1926 erwachte aber doch der Genossenschaftsgedanke unter den Bauern von
neuem, was zur Gründung einer neuen Genossenschaft mit unbeschränkter Haftung führte. Der
Geschäftsanteil war 5.- RM pro Kuh. Als die Meierei in Konkurs geriet, wurden mit dem Besitzer
Carstens Verhandlungen angeknüpft. Diese führten jedoch zu keinem tragbaren Ergebnis, da sich die
Bredstedter Sparkasse als Hauptgläubiger - die Schuld soll 23.000.- RM betragen haben - als Käufer
einschaltete. Vom Standpunkt der Genossenschaft war das nur zu begrüßen. Als die Sparkasse
Besitzerin geworden war, war der Weg frei für Verhandlungen, die schnell in günstigster Weise zum
Abschluß gebracht werden konnten. Sie war nämlich nicht nur bereit, das investierte Geld stehen zu
lassen, sondern auch noch 5.000.- RM als Betriebskapital zu leihen. Damit war ein guter Start für die
Meierei gesichert.

Erster Vorsitzender, der auch die Ankaufsverhandlungen geführt hatte, war Julius Jensen, Betriebsleiter
wurde Hugo Thießen. Während Humptrup, Grellsbüll und Braderup sich an die Uphusumer Meierei
angeschlossen hatten, lieferten jetzt Braderupfeld, Humptrupfeld, Aventoft, Wimmersbüll, Süderlügum
und Ellhöft ihre Milch nach hier. Man beschloß die Auszahlung nach Fettgehalt, geht 1928 zwecks
Feststellung desselben von dem Lactruskopverfahren zu dem Verfahren von Dr.Gerber über. Im
folgenden Jahre wurde der Anschluß an das Netz der Überlandzentrale vollzogen.

Da die Maschinen durch die Benutzung in über 30 Jahren veraltet und verschlissen und damit
unrentabel geworden waren, mußten in den folgenden Jahren dauernd neue Investitionen gemacht
werden. Sie betrafen die Kesselanlage, die Zentrifuge, die Kühlanlage und die Wasserpumpe. Obgleich
das viel Geld verschlang, wurde die Leistungsfähigkeit im ganzen doch kaum gehoben, so daß man
1936 vor der Entscheidung stand, die Art der stückweisen Erneuerung fortzusetzen oder einen
gründlichen Um- und Neubau vorzunehmen. Infolge Meinungsverschiedenheiten legten Vorstand und
Aufsichtsrat ihre Ämter nieder. Sönnich Winter wurde zum neuen Vorsitzenden gewählt. Er sah seine
wichtigste Aufgabe darin, die Meierei leistungsfähiger zu machen, was aber nur durch Umbau und
Einbau neuer, aufeinander abgestimmter Maschinen möglich war. Der wichtige Entschluß wurde 1936
mit 34 gegen 17 Stimmen gefaßt; zugleich wurde die Umwandlung in eine Genossenschaft mit
beschränkter Haftung beschlossen. Die Einzahlungssumme wurde auf 25.- RM erhöht, die Haftsumme
bis zu 100.- RM pro Kuh festgesetzt. Keiner durfte mehr als 30 Anteile erwerben. Die Umbaupläne
wurden von der Maschinen- und Beratungsstelle des Milch- und Fettwirtschaftsverbandes ausgearbeitet
und unter Leitung des Architekten Meyland in Niebüll ausgeführt. Die Maurerarbeiten machte die
Firma Heinsen in Niebüll, während Gebr. Klaus, Flensburg, die Maschinen lieferte. Die Kosten des
Umbaus beliefen sich auf 56.000.- RM. Der Staat gab einen verlorenen Zuschuß von 20.000.- RM. Als
alles überstanden war, verblieb der Genossenschaft eine Gesamtschuld von 44.000.- RM.

So war alles neu und leistungsfähiger geworden. Die neuen Maschinen haben eine Stundenleistung von
3.000 I und können täglich bis zu 12.000 1 Milch verarbeiten. Die täglich entnommenen Milchproben
werden dreimal monatlich in Niebüll durch den Landeskontrollverband auf Fettgehalt untersucht. Die
Meierei ist Mitglied der Butterabsatzgesellschaft in Altona. Sie ist der Landesgenossenschaftsbank in
Husum angeschlossen und tätigt ihre Geldgeschäfte durch die Spar- und Darlehnskasse in Süderlügum.
Sie verarbeitete 1946 die Milch von 850 Kühen. 1952 waren es 1.000. Die Gesamtanlieferung betrug
1947 rund 1,2 Mill. Liter. Die in den folgenden Jahren festzustellende Tendenz der Landwirtschaft zu
vermehrter Kuhhaltung und Steigerung des Milchertrages ergab 1952 eine Anlieferung von 2,1 Mill.
Litern. Die günstige Entwicklung die schon 1946 in der Feststellung eines schuldenfreien Betriebes
ihren Ausdruck gefunden hatte, scheint anzuhalten. Im Jahre 1949 wurde deshalb ein weiterer Ausbau
beschlossen und durchgeführt: mit einem Kostenaufwand von 35.000 DM wurde eine Tilsiter -Käserei
angebaut. In ihr können seitdem täglich 2.000 I Milch zu Käse verarbeitet werden. Der eingerichtete
Lagerraum hat Platz für 2.000 Stück. Der Anbau ermöglichte auch, die Meierei mit einem eigenen
Verkaufsraum zu versehen, in dem täglich die Produkte an die Bevölkerung verkauft werden.
Das Jahr 1952 wurde noch einmal ein Baujahr. Das alte Kesselhaus entsprach nicht mehr den gestellten
Anforderungen. Es wurde mit einem Kostenaufwand von 20.000,- DM vollständig erneuert, wobei die
Heizfläche von 10 qm auf 25 qm erhöht wurde.

So verfügt Süderlügum jetzt (1952) über eine mit den modernsten Maschinen und allen notwendigen
sanitären Anlagen versehene Meierei. Seit 1946 ist der Bauer Christian N. Hansen Vorsitzender.
Beim Umbau 1937 hatte man auch die Wohnung für den Betriebsleiter, die im alten Gebäude viel zu
wünschen übrig gelassen hatte, nicht vergessen. Am 2. April 1939 zog dort ein neuer Betriebsleiter ein,
der Molkereimeister Andreas Clausen. Wenn die Meierei den Erwartungen, die man 1937 auf sie setzte,
voll entsprochen hat, so ist das zu einem großen Teil sein Verdienst. Die Meierei ist sein ganzer Stolz.
Es ist immer eine Freude, die blitzsauberen Räume und Anlagen zu besichtigen.