
== 12. Handel und Verkehr

=== 12.1. Von der Hökerei zum Kaufmannsgeschäft

Bezüglich Handel und Verkehr in alter Zeit dürfen wir nicht heutige Maßstäbe anlegen. Jede
Haushaltung, besonders jedes Bohl, war fast autark, d.h. man begnügte sich mit dem, was die nächste
Natur an Materialien, Pflanzen und Tieren bot und hervorbrachte und was man im Garten und Stall
produzierte. Haus und Inneneinrichtung, Geräte und Werkzeuge, das meiste davon wurde selbst
hergestellt. Das Holz nahm dabei den ersten Platz ein. Eisen war teuer und knapp. Holz und Torf, selbst
geschlagen und gegraben, waren die einzigen Brennmaterialen. Den Tisch deckten Feld und Garten.
Die Buchweizen- und Gerstengrütze fehlte fast zu keiner Mahlzeit. Unsere Kolonisten brachten die
Kenntnis des Kartoffelanbaus mit. Fleisch, Milch und Käse lieferte der Viehbestand, die Gewürze der
Garten. Kolonialwaren gab es noch nicht. 1789 wurden folgende Sämereien feilgeboten: Dill, Kerbel,
Köll.Kresse, Majoran, Porree, Petersilienkraut, krause Petersilie, Spinat, Thymian, Krautsellerie,
Knollensellerie, Mangold, Blumenkohl, Weißkohl, Würsinger, brauner und grüner krauser Kohl,
Karotten, Pastinak, Mohrwurzeln, rote Beete, Petersilienwurzeln, Cichorien, Erbsen, welsche und
türkische Bohnen, Krupschwerdbohnen, Perlbohnen, gelbe Prinzessbohnen, Kopfsalat, Radieschen,
schwarzer Rettich, Bitterrüben, Agurken, rote holländische Zwiebeln, Nelken, Turnips, Klee. Nur ein
Gewürz mußte man durch Tausch oder Kauf erwerben, das Salz. Es stammte aus Lüneburg oder
Oldesloe oder aus der Marsch, besonders von Galmsbüll, wo die beiden letzten Salzsieder 1782 ihre
Arbeit einstellten, weil die Feuerung zu teuer wurde.

Salz und viele andere notwendige, aber auf dem Lande rare Sachen erstand man in Tondern oder
Flensburg. Vieles war auch beim Hausierer zu haben. Da kamen die Wollhändler, kauften die Wolle
auf und boten Mützen und Strümpfe und andere Bekleidungsstücke an. Auch Zwirn und Nadeln,
Knöpfe und Spangen wurden so erstanden. Der Wagen mit den Topfwaren, besonders den Jydepotten
aus der Varder Gegend nahm altes Eisen, Knochen und Lumpen in Zahlung. Seit 1711 war
Lumpensammeln ein "freier Beruf".

So ist es erklärlich, daß es noch keine Kaufmannsgeschäfte in unserem Sinne geben konnte. Erst als
die Kolonialwaren Eingang fanden, kamen die Hökereien etwas voran. Immer aber waren sie keine
selbständigen Berufe. Ein Handwerker, Kätner oder kleiner Bohlsmann, meistens aber der Gastwirt,
der Krüger, betrieb ein kleines Ladengeschäft nebenbei. Die Hökereien im Kirchspiel waren alle an
Krugswirtschaften gebunden. 1791 wurden genannt Cäcilie Carstensen, Johannes Volquardsen und
Jens Christensen. Es handelt sich um die Hausnummern S 46, 40 und 71 der Hauschronik. Die
Eröffnung und Führung einer Hökerei war von einer Erlaubniserteilung durch das Amt abhängig. Dafür
waren durch Königl. Resolution von 1742 bestimmte Richtlinien aufgestellt worden: Ohne Erlaubnis
darf keine neue Hökerei errichtet werden: erteilte Genehmigungen sollen mit dem Tode des Inhabers
erlöschen, worauf dann eine neue Verpachtung stattfindet. Der Pachtpreis, die jährliche Rekognition,
fließt in die Amtskasse. Die drei Lügumer zahlten 1791 5.- Rthl 16 ß, 5.- Rthl und 16 ß und 4.- Rthl.
Daß es nicht so leicht war, sich neu zu etablieren, mußte schon um 1750 der Spitzenhändler Jens
Clausen Reimer in Lügum erfahren. Er bat um eine solche Genehmigung und bot gleichzeitig eine
Pachtsumme. Es wurden deshalb zwischen Kopenhagen und Tondern bezw. Lügum viele Fragen und
Antworten ausgetauscht und ihm schließlich der Bescheid erteilt, daß, da die Krüge die
Hökereigerechtigkeit inne hätten, es ihm frei stände, sich bei der nächsten Krugsverpachtung als
Höchstbietender zu produzieren.

Auch die Waren, die der Laden feilbieten durfte, waren genau bestimmt. Übertretungen waren unter
Strafe gestellt. Noch 1854 mußte der Kaufmann Christian Jessen Krog (Nr. 16) sich einem Verhör
unterziehen lassen, weil er mit Kaffee gehandelt hatte.

Mit zunehmendem Handel wurde die Ehe mit dem Krug gelöst. Als um 1800 Nr. 40 als Höker
ausschied, hat Nr. 16 die Hökereigerechtigkeit erworben. Der genannte Kaufmann Krog, der 1850 das
alte Bauern- und Kruggewese erwarb, führte die Krugwirtschaft nicht weiter, sondern baute das
Kaufmannsgeschäft tatkräftig aus. Wöchentlich fuhr ein Wagen von ihm nach Flensburg, um den Laden
zu füllen und dem steigenden Bedarf begegnen zu können.

Ein Bruder von Frau Dohle, Andreas Lorenzen - Laust Hansen Dohle hatte 1873 die Bohlsstelle Nr.
85 erworben - errichtete in diesem Hause eine Hökerei, die sich im Laufe der Zeit zum ersten
Kaufmannsgeschäft im Ort entwickelt hat. Die Räumlichkeiten wurden erweitert und immer mehr
Dinge zum Verkauf gestellt: Eimer und Töpfe, Besen und Bürsten, Lampen und Laternen, kosmetische
Artikel und Drogen, Geschenkartikel, Spielzeug, Wäsche und Kleidung, alle Dinge, die man bisher nur
in der Stadt kaufen konnte und auch gekauft hatte. In Tondern mußte man ja doch zu Markt, dort
wohnte der Arzt, war die Apotheke, die Amts- und später die Kreisverwaltung, dort wohnten der
Tierarzt, der Schuhwarenhändler, der Klempner, der Manufakturist. Alle legten in reicher Auswahl ihre
Waren aus und erfreuten sich besonders an den Markttagen regen Zuspruchs vom Lande. Mit dem
Ausbau unserer Kaufläden verebbte der Strom nach Tondern allmählich und hörte natürlich mit der
Grenzziehung im Jahre 1920 ganz auf.

Nr. 71 hatte sich immer mehr auf reinen Bauernbetrieb eingestellt. Johannes Iwersen war der letzte
Höker. Als unter seinem Sohn Jacob Peter die Gebäude im Jahre 1866 abbrannten und an anderer Stelle
neu aufgeführt wurden, war die letzte Erinnerung an die alte Hökerei dahin.

Jüngeren Datums ist das Geschäft von Nicolai Heinrich Rieber, das er im Jahre 1909 gegenüber der
Gastwirtschaft von Lorenz Nissen in Wimmersbüll anfing. Es hat sich in den 40 Jahren seines
Bestehens, namentlich seit 1920, nachdem neben dem Altdorf eine umfangreiche Zoll- und
Eisenbahnsiedlung enstand, glänzend entwickelt. Weiteres siehe in der Hauschronik unter Nr. W 44.

=== 12.2. Vom Sandweg zur Kunststraße
Die Beförderung der Waren geschah auf den wenigen Wegen von Dorf zu Dorf und von und nach den
nächsten Städten Tondern und Flensburg. Das jütische Lov bestimmte ja, daß jedes Dorf höchstens vier
Ausgänge haben durfte, was auch für unsere Dörfer zutraf. Daß sie nachts durch Schranken
verschlossen werden sollten, zeigt, daß der Verkehr nur klein war und daß man keinen großen Wert auf
"Fremden Verkehr" legte, besonders nicht in der Nacht. Auf den Hauptstraßen, auf denen sich der
Durchgangsverkehr abspielte, wurde diese Bestimmung aus dem Jahre 1240 allerdings bald hinfällig.
Lügum lag an dem alten Ochsenweg. Dieser führte von Norden kommend über Tondern und Seth beim
Übergang über die Süderau, die frühere Struxbrücke (früher auch: Struxen), in unser Kirchspiel. Nach
den alten Wegeverzeichnissen von 1811, 1815 und 1835 hatte er auf unserem Gebiet drei
Teilabschnitte:

1. Von der Struxbrücke machte er einen nach Osten offenen flachen Bogen und führte so, noch heute
erkennbar, westlich um das heutige Zollhaus herum, kreuzte dann die jetzige Landstraße zu einem eben
solchen Bogen nach Osten und folgte der Landstraße (in Wirklichkeit ist's umgekehrt) bis zur Kleinen
Brücke über den Kleinen Strom, früher Böglumbrücke und Böglumstrom genannt. Länge ca 925 m.
2. Von der Böglumbrücke nach Süden bis zum früheren Chausseehaus(Nr.S 158). Länge ca .1.000 m.
3. Am Chausseehaus bog er nach Südosten ab auf die Heide am Rande von Küßham. Dort nahm er nach
600 m wieder südliche Richtung an, führte ins Dorf, westlich an Kirche und Pastorat vorbei, machte
dort eine scharfe Biegung nach Osten, ging zwischen den Häusern Nr. 47 und 48 hindurch in einem
großen nach Westen offenen Bogen durchs Dorf, bis er vor dem Haus Nr. 57 wieder nach Südosten
abbog und, noch heute gut erkennbar, an der Haidburg vorbei an der Braderuper Grenzscheide unser
Kirchspiel verließ. Länge ca. 5.000 m.

Von diesen ca. 7 km langen Durchgangswegen auf Kirchspielsgrund zweigte am Ostausgang des
Dorfes bei dem noch heute dort stehenden Obelisken (Inschrift:Bredstedt-Husum-Bökingharde) der
Heerweg nach dem Süden ab. Er geht über die Braderuper Grenzscheide, Braderupheide, Braderupdorf,
Braderupmühle und südlich in Richtung Klixbüllhof. Auf Klixbülldeich erreicht er die von Dagebüll
und damit von den Inseln nach Flensburg führende Verbindung. In unserem Kirchspiel liegen ca.
1.50m.

Der Weg Grellsbülldeich-Wimmersbüll-Lügum-Westre war ein Teil des Verbindungsweges von den
nördlichen Marschharden und der Wiedingharde nach Flensburg. Die Strecke von Wimmersbüll nach
Lügum führt noch heute die Bezeichnung Alter Wimmersbüller Weg. Er stößt beim Pastorat auf den
Ochsenweg und führt dann durch den Ortsteil Horsberg nach dem Osten. Länge ca. 7.000 m.
Südlich von diesem Weg, zunächst parallel zu ihm, führt der Weg von Lügum nach dem Westen nach
Grellsbüll. Bei der Wimmersbüller Mühle biegt er nach Süden ab. Länge ca. 1.750 m.

Ellhöft fand über Gulum und Böglum seinen Anschluß an den Ochsenweg und damit nach Tondern.
In südöstlicher Richtung lief ein vielbenutzter Weg über Westre Heide (jetzt Forst), Westre, Ladelund
nach Leck, so die Verbindung mit Flensburg herstellend. Auch nach Norden, in die Tondern- und
Schluxharde konnte man kommen. Der Weg führte bei Windtwedt über die Süderau. Überhaupt gab
es neben diesen Hauptwegen viele dorfeigene Wege, Richtwege, Kirchen- und Schulsteige. So hatte
z.B. Ellhöft früher zwei solcher Richtwege nach dem Kirchdorf. Der eine führt durch den Nordzipfel
des heutigen Forstes, nördlich um das Naturschutzgebiet herum und dann in westlicher Richtung an den
Häusern Nr. 96 und 94 vorbei ins Dorf. In seinem mittleren Teil war er nicht ausgelegt; man fuhr über
die Heide, wo es einem beliebte, was die Heidespuren im Naturschutzgebiet noch heute beweisen. Der
Weg und der Wall sind erst durch die Forstverwaltung angelegt. Der zweite Weg ging von Gulum aus
und erreichte südlich von Wohlgetan (Nr. 148)den Ochsenweg.

Ein besonderes Kapitel war stets die *Unterhaltung der Wege*. Damit hat es immer gehapert. Darum
waren sie oft, besonders im Winter, unpassabel, so daß Pferde und Wagen stecken blieben. Klagen und
Beschwerden, Verordnungen und Strafandrohungen, Streit und Prozeßberichte füllen die Akten. Woran
lag das? - Einmal an dem fehlenden Wegematerial. Ganze Strecken wurden nur mit Sand und
Heidesoden ausgebessert, andere dann mit etwas Kies und Lehm vom Ravens- und Gooskildeberge. Und
dazu kam die komplizierte Unterhaltungspflicht, die teils der Harde oder den Harden, teils dem
Kirchspiel oder auch mehreren Kirchspielen und teils den einzelnen Dörfern oblag. An vielen Strecken
waren alle drei beteiligt.

Was hatte Lügum zu unterhalten? (1735).

(Die Vermessung der Wegstücke geschah nach Ruten (Rt), Ellen (E), Viertel Ellen (g) und Linien oder
Daumen (d). Im folgenden werden nur Ruten und Ellen aufgeführt):

1. beim Tonderner Mühlendamm 10 Rt 1 E,
2. vom Tonderndamm / von Rohrkarrbrücke bis Taulumbrücke 3 Rt 6 E,
3. von Taulumbrücke bis Norden Seth 30 Rt 1 E,
4. von Sether Straße bis Brücke Süden Seth:
** die Lügumer Kätner 4 Rt,
** das Kirchspiel I5 Rt 1 E,
5. von Brücke Südens Seth bis Struxbrücke 1 Rt 3 E,
6. von Struxbrücke bis Böglumbrücke:
** Böglum 4 E,
** das Kirchspiel 19 R 1 E,
** das Kirchspiel 7 E,
** Lügum Dorf 13 Rt,
7. am Soholmer Damm 20 Rt 6 E,
8. am Grünhofer Weg, von Westre Heide bis Norden Lüdersholm, hatte Lügum nach dem Register von 1693 ein Stück von der Heide bis Beiers 46 Rt 6 E und von Beiersbrücke bis Lüdersholm noch 13. Rt 5 E.

Außer diesen Stücken an den Hauptwegen-! Rute 8 Ellen = ca. 4,5 m hatten wir noch die Unterhaltung
folgender Strecken:

[start=9]
. bei Rabensberg "ein Stück Weges, so von den Bohlsleuten und Kätnern des Kirchspiels unterhalten wird".
. "Zwischen Ellhöft und Böglum hat Lügum Kirchspiel auch ein Stück Weges zu unterhalten, so von Ellhöft, Windtwedt, Uhlenberg und Böglum gemacht wird”,
. neben der Lügumer Pforte ist ein kleines Stück Weg, vor einigen Jahren “angelegt, so vom ganzen Kirchspiel gemacht wird”.
. "Der Weg von Lügum nach Braderup, sowohl als nach Wimmersbüll, wird von der Braderuper Mühle ab und hingegen wiederumb, zu der Lügumer Wind-Mühle verleget worden, so haben die Eingesessenen beregten Dorfes solches Stück Weges nachhero auch nicht gemacht. Besonders wird es die natürliche Billigkeit erfordern, daß die übrigen Mühlengäste den Weg unterhalten".

Es geht aus dieser Zusammenstellung hervor, daß jede Wegstrecke in viele kleine und kleinste Teile
abgeteilt war. Die 180 Ruten von der Kleinen Böglumbrücke bis zum Ende des Tonderndammes gegen
die Lügumer Heide zählten z.B. 95 Teile. Die Grenzen wurden durch Pfähle oder Steine
gekennzeichnet. Die einem Kirchspiel zustehenden Stücke lagen nicht zusammen, sondern wurden von
Strecken anderer Kirchspiele unterbrochen. Und jedes Stück mußte inerhalb des Kirchpiels wieder
unterverteilt werden. Dies geschah bei uns seit 1774 nach Pflügen. Für die unter 6. aufgeführten 19 Rt
1 E stellten so Struxbüll vier Leute für 1 Rt2E, Wimmersbüll 14 Leute für 6 Rt 1 E und Lügum Dorf
27 Leute für 11Rt7E.

Die Maße wurden mit der _"eisernen Kette"_ der auf dem Amtshause sich befindlichen Elle
vorgenommen. Durch Beschädigungen durch Wasser oder mutwillige Veränderungen wurden
Nachmessungen nötig, so 1724, als das Winterwasser im Tonderndamm ein großes Loch gerissen hatte.
Der Landmesser Broder Hansen gibt dafür folgende Rechnung ein:

"Für diese Abmaße, so nebst meinem Sohn
verrichte, will einsetzen 2 Rthl 4 ß
Vor seine beiden Pferde, so dahin geritten. 1 ß
Verzehrung in Lügum für mich und die Pferde. 6 ß
3 Rthl 10 ß 

Es ist verständlich, daß diese verwickelte Ordnung zu Reibereien und Streitigkeiten führen mußte. Die
Wege selbst sind dadurch leider in einem Zustand verblieben, der für ein ganzes Jahrhundert als
beschämend bezeichnet werden muß. Hier können nur einige Beispiele von Wegestreitigkeiten
mitgeteilt werden:

[.underline]#1. Der Weg Ellhöft - Ladelund#

Zwischen Ladelund und den Ellhöftern enstand 1717 ein Streit wegen Benutzung des Weges über
Ackerwang, weil _"der rechte Landweg gegenwärtig nicht reparieret und in passablen Stande bevor
eintretendem Frühjahrs oder Sommers gebracht werden kann". Es kam ein Vergleich zustande: "Die
Ladelunder sollen biß dahin fürs erste den Weg Ackerwang frey und ohne einige Hinderung passieren,
alsdann im Sommer die Ellhöfter gehalten sey, ged. Weg auf verantwortlicher Weiße zu verhöhen und
zu machen. Gestalt denn die Sämbl. Eingesessenen in Ellhöft hierdurch ernstlich angedeutet werden,
den alten Fahrweg durch Ackerwang und womit derselbe entweder durch Soden oder Pfähle versperret
und zugemachet sey, gleich auf Empfang dießes wieder, und zwar Osten daß Schütt, woselbst der Weg
gleichfalß auch aufgefüllt und gebessert werden muß, zu öffnen, und eine freye Fahrt machen sollen
bey Vermeydung 3 Rthl herrschaftl. Brüche"_ .

[.underline]#2. Der Tonderndamm#

_"Der Weg von der Karr- und Bökingharde nach Tondern ging in alten Zeiten über einen sogenannten
Boyers-Weg, der wegen des Gutes Grünhof geschehen, und noch heute existiert. Als aber gegen Ende
16. Jahrhunderts dieser Hof abgebrannt, war der jetzige Lügum Damm, welcher nach der Stadt
Tondern, durch die Lügumer beteichten Ländereyen geht ausgeleget und der Karrharde zur
Unterhaltung angewiesen, und hat ein jedes Kirchspiel deren erhalten daher denn auch dem Kirchspiel
Lügum ein bestimmtes Stück zugetheilet worden"_ . - Die Schwierigkeit lag eben darin, daß die ganze
Harde unterhaltungspflichtig war. An einer Stelle hatten alle Kirchspiele Anteil an ganzen 26 Ruten.
Immer wieder gingen Pfähle verloren, so daß heftige Zänkereien neue Vermessungen notwendig
machten. Erst 1783 begann man den Fehler einzusehen und schlug vor, die kleinen getrennt liegenden
Stücke der einzelnen Kirchspiele und Ortschaften in ein oder zwei Stücken zusammenliegend
auszulegen. Denn gerade dieses Stück des Hauptweges erforderte besondere Unterhaltung, da es über
niedriges, leicht Überschwemmungen ausgesetztes Land führte. Es mußte besonders erhöht und mit
besserem Material versehen werden, ja, die Böschung mußte teilweise mit Pfahlwerk festgemacht
werden. Trotzdem ward es z.B. 1741 von dem hohen Winterwasser ganz durchbrochen und unpassabel
gemacht. In öffentlicher Licitation (Ausschreibung) übernahm es Andreas Carstensen auf Struxbüll als
Mindestfordernder, den Schaden innerhalb von 14 Tagen für 7 Rthl 44 ß auszubessern.

[.underline]#3. Der Weg Ellhöft - Böglum#

Dieser Weg hatte 1773 drei Teilabschnitte: a) der östliche Teil ein Schottdamm, war unter die
Unterhaltungspflichtigen verteilt. Er wurde jährlich _"handfest"_ gemacht. b) ein unverteiltes Stück lag
auf Böglumfeld = 227 Rt, davon 187 Rt teils hohen und harten, teils niedrigen Boden hatten. c) der Rest
von ca. 40 Rt bildete das sogenannte Watt; es ist das westlichste Stück, das die Verbindung mit dem
Lügumer Damm herstellte. Von jeher niedrig, war es immer Überschwemmungen ausgesetzt. Die
damals schon in Aussicht genommene "bedeutende Erhöhung" ließ noch über ein Jahrhundert auf sich
warten. Aber auch das Mittelstück von Gulum bis Böglum hatte immer seine schwachen Stellen, die
erhöhte Kosten erforderten, die Böglum nicht allein tragen konnte. Lügum, das nach § 3 des 56.
Kapitals des Lov - Buches helfen sollte, weigerte sich. Die Rechtslage wurde nämlich dadurch
verwickelt, daß im Zuge dieses Weges Siel und Brücke lagen. Die wiederholten Beschwerden der Jahre
1777 - 1782 weisen immer auf dieselbe Wegestelle hin. Auch der Krugpächter Peter Carstensen in
Ellhöft trat beschwerdeführend auf, da er seine Pachtzahlung an die Bedingung geknüpft hatte, daß der
Weg endlich ausgebessert werde. Um etwas ganzes tun, tauchte ein neuer Plan auf, der durch die
nachstehende Skizze erläutert wird: Da das Siel ganz verfallen ist - der Hauptgrund für die
Wasserstauung an dieser Wegstrecke - die Brücke auch sehr schadhaft, will man den Strom 200 Schritt
Norden am Weg entlangführen und dann an der Stelle des alten Siels den Weg kreuzen lassen. Aber
gleich melden sich Gegner dieses Planes (Uhlenberg), so daß wieder eine Verzögerung eintritt und die
Ellhöfter gezwungen sind, ihren Weg nach Tondern über Lügum zunehmen.

Nach einer Anordnung von 1783 soll die Brücke endlich mit _"gesamter Hand"_, d.h. vom ganzen
Kirchspiel gemacht werden. Aber Lügum kann sich wieder weigern mit dem Hinweis, daß, wer den
Weg zu machen hätte, auch die Brücke machen müsse, wegepflichtig waren hier aber Medelby,
Ladelund und Überg. Diese aber weigern sich wiederum, neue Lasten zu übernehmen, da die Brücken
ja längst verteilt seien. So bleibt der Brückenbau, ganz zu schweigen von einer Verlegung derselben,
weiterhin offen. Nach langen Verhandlungen läßt sich Lügum 1783 bewegen, den Böglumern zu
helfen. Aus der einmaligen Hilfeleistung soll aber keine dauernde Unterhaltungspflicht abgeleitet
werden. Darum verweigert es diese Hilfe 1795 und in den folgenden Jahren wieder. Diesmal kamen
ihm die Wegeordnung von 1784 und die Verordnung von 1786 zustatten. Darin werden die von den
Hauptstraßen abzweigenden Heerwege namentlich aufgeführt, und der Böglumer Weg ist nicht dabei.
Nur diese hat das Kirchspiel zu unterhalten, soweit sie über Kirchspielsgrund führen. Ein weiterer
Grund ist, daß der Weg nicht als Poststraße benutzt wird, sondern nur von den Übergern zum Torfholen
und von Leuten, die über Schäferhaus nach Schleswig fahren. Außerdem ist Böglum die Unterhaltung
wohl allein zuzumuten, hat doch die ganze Arbeit 1783 nur 52.- Rthl 8 ß gekostet. Die vier Bohlstellen
in Böglum werden in 13 Jahren doch wohl diese Summe aufbringen können, ist es doch für jeden nur
1 Rthl jährlich. Mit solchen Gründen versuchen sie, den letzten Verpflichtungsbescheid von 1797 zu
entkräften.

[.underline]#4. Der Weg auf Lügumfeld#

Der Weg nördlich des Dorfes, der dasselbe mit dem Lügumdamm verband und zwischen Acker und
Pfluggründen in einer Breite von 12 Ellen, über die Heide in 16 Ellen Breite ausgelegt war, mußte von
dem Dorf unterhalten werden. Obgleich er 1783 gut ausgebessert war, wird er 1798 als _"ganz wüste"_
bezeichnet. Lügum mußte wünschen, daß er in Zukunft vom ganzen Kirchspiel unterhalten werde.
Während Wimmersbüll nur 120 Rt, Ellhöft nur 160 Rt Wegepflicht hatte, konnte Lügum über 2.000
Rt nachweisen. Da vom Amt Zwangsmaßnahmen gegen die beiden Dörfer angedroht werden,
bequemen sie sich zu einer Übereinkunft: 1) Wimmersbüll und Ellhöft helfen, wenn Lügum ihnen je
Pflug einen Mann auf einen Tag stellt; 2) Der Weg nach Leck und Braderup wird mit Heidesoden
belegt; Lügum vergütet die Arbeit mit 2 ß je Fuder; 3) _"Die jeweilige Belegung der Wege süden nach
Leck und Braderup samt norden dem Dorfe geschieht vom Kichspiel, jedoch mit dem Bedin g, daß man
die auswärtigen Dörfer des Kirchpiels Braderup, als Uphusum und Holm von dem Wege auf
Braderupfeld in Zukunft frei läßt, indem nämlich die auswärtigen von Lügum Kirchspiel (Wimmersbüll
und Ellhöft) auch von dem Wege nach Braderup wegen Belegung desselben dergestalt frei sind, daß
Lügum Dorf Ihnen die Heide-Belegung des Weges nach Braderup nach Billigkeit vergütet."_ 

[.underline]#5. Der Wimmersbüller Weg#

Er wurde von Wimmersbüll und Lügum gemeinsam unterhalten und befand sich immer in
verhältnismäßig gutem Zustand. Besonders nachdem er 1785 begradigt worden war. Bis dahin führte
er nördlich um das Waldstück von Westerhof (1949 abgeholzt) herum und wies einige schlechte
Wegestellen auf. Da wurde er _"auf höheren Grund gelegt, in der Feldscheide bedeuten erhöht und mit
einem Siel versehen"_ . Im Jahre 1817 trat vorübergehend eine Schwierigkeit auf, als das Siel
verschwunden war. Wimmersbüll beschwerte sich, daß das Wasser in der Griff aufgestaut wurde, so
daß sie ihre Ländereien durch Dämme schützen mußten und ihren Kirchen- und Mühlenweg nicht
benutzen konnten. Eine Lokalbesichtigung schaffte aber schnell Abhilfe, indem er zu folgenden
Vergleich führte:

1. Die Dörfer legen halbschiedlich ein neues Siel.
2. Jede Dorfschaft unterhält ihren Teil des Norderweges, nur das Schneeschaufeln macht Wimmersbüll allein.
3. Lügum legt an einer niedrigen Stelle - die dem Paul Andresen Lerche gehörigen Hause - ein Siel in den Weg, hält den Weg 12 Ellen breit und unterhält ihn.
4. Bei der ersten Instandsetzung hilft Wimmersbüll.

21 Lügumer und 12 Wimmersbüller haben den Vergleich am 29.12.1817 unterschrieben.

[.underline]#6. Der Soholmer Damm# (zwischen Klixbüll und Niebüll)
Da hatten wir, wie wir festgestellt haben, 20 Rt 6 E zu unterhalten. Es war einmal anders: _"Da ist
Lügum Kirchspiel nach dem alten Register ohne Besetzung der Maaße bis an das Sand gemessen
worde, weilen es sich aber jährlich verlängert, so haben die Eingesessenen besagtes Kirchspiels die
Reparation bis an das Sand nicht bewerkstelligen wollen, sondern selber eine Maaße von 20 Rt6 E zu
repariren genommen, da dann das übrige, wann etwas dabey gemachet ist, von der ganzen Harde auf
ein Recht bezahltet worden"_ (1735).

Lügum hatte sich aber schon seit 1785 eine Erleichterung dadurch verschafft, daß es mit drei Mann aus
Enge getauscht hatte, die auf Ligumdamm Wegepflichten hatten. Da allerdings 1835 der Soholmer
Weg nicht gemacht worden war, auch Lügum eine Aufforderung dazu nicht beachtete, weil es den

Tausch als zulässig und rechtsgültig ansah, wurde die Arbeit verdungen und Lügum mußte 9 Rthl 8 ß
zahlen.

[.underline]#7. Der Weg Lügumdamm-Struxbüll#

Um diesen von Lügumdamm nach Struxbüll führenden 165 Ruten langen Weg entstand um 1789 ein
Streit. Wer soll ihn unterhalten? Der Deichvogt Lorenz Todsen hatte angeordnet, daß er von den
Landanliegern zu erhöhen und als Schottdamm herzurichten sei. Er ging davon aus, daß der Weg in den
300 Demat großen Struxbüllkoog ein Koogsweg sei, daß ihm deshalb die Oberaufsicht zustehe und die
Verantwortung für den Zustand des Weges obliege. Es kam ihm dabei eine Akte aus dem Jahre 1709
zugute, nach der die Landeigner wegepflichtig waren. Da der Weg einzig und allein von den drei
Feldinteressenten benutzt wurde, haben sie nach anfänglicher Weigerung mit der Begründung, daß es
sich um einen Geestweg handle, doch die Arbeit angefaßt. Bei der Lokalbesichtigung 1790 konnte
festgestellt werden: _"Es fehlt nur der Antheil des nach der Ladelunder Mühle verzogenen Andreas
Andersen (Nr. B 2), der seinen Staven hiesigen Orts verheuert hat"_.

[.underline]#8. Die Feldwege in Lügum#

Nach den vorliegenden Akten scheinen die Feldwege sich dauernd in sehr schlechtem Zustand
befunden zu haben. (Der 17 Koogswege wird in einer anderen Arbeit gedacht). Gemeinschaftlich
wurden nur zwei Wege unterhalten, der Heuweg nach der Hirten- und neuen Wiese und der Weg im
Osten von Grausand nach den Flachenschiften. Und die andern? - Wenn die Ackerenden gegen den
Weg lagen, mußten die Anlieger unterhalten, sonst wurde die Arbeit gemeinschaftlich ausgeführt.
Im Jahre 1822, nachdem die Kolonistenhäuser schon bald 60 Jahre gestanden hatten, wurde von dem
Kirchspielsvogten Gottfried Wilde und dem Dorfaufseher Johannes Chr. Jannsen in Lügum der Weg
nach den Kolonistenplätzen abgesteckt. Bis dahin hatte man den Weg nach dem Ochenweg beliebig
über die Heide genommen. Streitigkeiten mit den Gräsungsberechtigten und die weitere Besiedlung der
Heide hatten endlich die Auskennung eines Weges veranlaßt.

Bevor nun die Entwicklung der Wege weiter verfolgt wird, ist es notwendig, einiges über Siele und
Brücken nachzutragen. - In ältester Zeit führte der Weg nicht über den Wasserlauf, sondern durch ihn
hindurch. Natürlich wählte man dafür seichte Stellen. Wir wissen von der Furt zwischen Flützholm und
Bremsbüll, die ja zeitweilig denselben Besitzer hatten, von der Furt durch den Kleinen Strom und die
Süderau, die im Zuge des Feldweges lag, den Todsen (Westerhof) und die Ausflütter _"auch nach
Tondern fahren konnten wenn sie nicht den richtigen Weg benutzen wollten"_ (1786), und von der Furt
bei Windtwedt. Bei manchem Übergang wird es sich dann als praktisch erwiesen haben, Weg und
Wasser unabhängig von einander zu machen. Das geschah durch Siele und Brücken, die beide im Laufe
der Jahrhunderte von einfachster Konstruktion zur heutigen soliden Bauweise fortgeschritten sind. Die
Schwierigkeiten, die wir bei der Unterhaltung der Wege kennengelernt haben, wurden durch die
Brücken noch wesentlich erhöht. Sowohl an der Erbauung als auch an der Unterhaltung waren auch hier
Harden und Kirchspiele und Dörfer beteiligt. Oft, ja meistens, hatte eine Brücke drei Interessenten: der
eine hatte die eine Hälfte, der zweite die andere Hälfte und der dritte das Brückenhaupt zu unterhalten.
Die Skizze zeigt die vorhandenen Brücken, von denen uns hier nur zwei interessieren.

[.underline]#1. Die Brücke zu Windtwedt#

Nach einer alten Dingswinde aus dem Jahre 1563 ist die Brücke über _"de Aue midden dörch dat landt
tho Windtwith gehörig, geleget worden, dat de Inwahners tho wintewitt daraver tho der karken und
Stad fahren konten"_. Sie war von den drei Harden Karr-, Schlux- und Tondernharde erbaut. 1634 wurde
sie ein Opfer der Großen Oktoberflut, auch ein Beweis dafür, daß die Sturmflut weite Strecken des
Festlandes in Mitleidenschaft gezogen hat: sie war _"von den Solten water afgedrofen, ock nicht wedder
verfertigest worden"_ . Erst 1656 hatte Arend Henningsen eine neue, 24 Ellen lange Brücke gebaut, damit
die Leute wieder_ "mit Pferden und Wagen tho stadt Karc und sonsten fahren konnten"_ . Henningsen
hatte das Geld vorgeschossen, das ihm nun wieder von den drei Harden zurückzuzahlen war. Auch
Überg, das sich anfänglich weigerte, seinen Anteil in Höhe von 114 Rthl zu zahlen, wurde durch das
Amt zur Zahlung gezwungen. Der Prozeß zog sich über zehn Jahre hin. Der Versuch der Karrharde,
die den größten Nutzen von der Brücke hatte, war damit gescheitert. 1719 war die Brücke wieder ganz
baufällig, _"also das Niemand auch nur darüber gehen, viel weniger aber mit Pferd und Wagen fahren
könnte"_ . Sie wurde mit einem Kostenaufwand von 313 Rthl 3 ß von Grund aus erneuert. Wieder legten
die drei Harden die Summe nach Pflugzahl um.

Als 1792 das Brückenhaupt neu bekleidet werden mußte, kamen die drei Hardesbevollmächtigten auf
den Gedanken, ob nicht vielleicht Asmus Lorenzen auf Windtwedt, der den Weg bei der Brücke zu
unterhalten hatte, verpflichtet wäre, auch den Brückenkopf zu machen. Es war damit die schwer zu
entscheidende Frage aufgetaucht, ob das Brückenhaupt als Zubehörteil des Weges oder der Brücke
anzusehen sei. Der Streit dauerte wieder viele Jahre. Lorenzen will wohl Erde aufschütten, wenn die
Harden die Bretter legen. 1797 mußte eine Notreparatur vorgenommen werden. Erst später wurde
entschieden, daß derjenige, der die Brücke setzt, auch den Belag erneuern muß. Da erwuchs den Harden
eine neue Schwierigkeit, indem Lügum jetzt eigentlich statt gegen Windtwedt gegen Lügum, also gegen
ihr eigenes Mitglied klagen müßte.

Über zwei gründliche Erneuerungen wird noch berichtet. Die erste, die 1821 stattfand, erforderte 822
Rthl 13 ß. Der Anteil der Karrharde war inzwischen auf Lügum übergegangen, aber ohne
Brückenhaupt. Der letzte Umbau wurde 1853 von unserem Schleusenmeister Carsten Matthiesen (S
Nr. 6) vorgenommen.

[.underline]#2. Die Struxbrücke#

Die Struxbrücke über den Struxstrom (Süderau) im Zuge des alten Ochsenweges, mitten im
Tonderndamm, war 19 Ellen lang und 6 Ellen Breit. Sie mußte von den Kirchspielen Karlum, Medelby
und Überg unterhalten werden, und zwar so, daß Karlum ein Drittel der nördlichen Hälfte, Medelby
die zwei Drittel derselben und Überg die südliche Hälfte hatte, Die Brückenhäupter gehörten hier, wie
auch an der Kleinen Böglumbrücke südlich, zu Karlum. Im Jahre 1773 fand eine Neuverteilung statt.
Als damals die Hardesanteile am Tonderndamm an die Kirchspiele übergingen, wurden die Böglum-
und Windtwedtbrücke dem Kirchspiel Lügum zugewiesen.

Seit 1707 hatte Böglum südlich der Brücke 4 Rt Weg zu machen, die ursprünglich nördlich derselben
gelegen hatten, aus der Begründung erfahren wir, daß die Brücke _"vor vielen Jahren nach dem Norden
in den Südharder Weg verleget"_ .

Als 1837 ein Neubau der Brücke notwendig wurde, fand durch den Kirchspielsvogten Gottfried Wilde
die Verdingung der Fuhren statt, und Schleusenmeister Matthiesen legte die hier wiedergegebene
Handzeichnung vor, nach der er dann die Brücke gebaut hat.

Wenn wir uns nun wieder der Entwicklung der Wege zuwenden, ist festzustellen, daß die versuchte
Neuverteilung der Wege aus den Jahren 1784, 1811, 1816 und 1824 für unser Kirchspiel weder
Entlastung noch Fortschritt gebracht hat. Immer noch mußten die Kirchspiele _"mehere Meilen machen,
um zu dem Ort zu kommen, wo sie Wegestrecken verfertigen sollen"_ . Für uns war und blieb besonders
der Tonderndamm das Sorgenkind. _"Die Strecke von Tondern bis Lügum Heide ist immer noch theils
mehr, theils minder den Überschwemmungen des Winter-Wassers ausgesetzt und daher 3 bis 4 Fuß
über Maifeld zu erheben und so wie ein Deich mit einer Dossierung geformt, welches für die
Unterhaltung sehr schwierig ist"_ . Die Wegelast wurde nach 1855 auf breitere Schultern gelegt, indem
auch Kätner, Insten und Kolonisten mit herangezogen wurden. Aufsicht und Kontrolle wurden strenger,
man bemühte sich um eine gerechtere Verteilung. Auf jeden Pflug sollen 155 Ellen kommen (1839),
und da Lügum mit seinen 1016 Rt5 E schon 248 Rt zuviel hat, müsssen Braderup und Klixbüll dies
übernehmen.

Die Wegeordnung von 1842 wurde grundlegend für die folgenden Jahrzehnte. Sie führte neue
Bezeichnungen ein: die Nebenpoststraße nach Leck (Ochsenweg) wurde jetzt als Hauptlandstraße, die
Strecken von Klixbülldeich und Grellsbülldeich bis Lügum als Nebenwege erster Klasse bezeichnet.
Wesentlich aber war, daß eine Chaussierung der Hauptlandstraßen angeordnet wurde. Unter ihnen
befand sich auch die Strecke Husum-Tondern-Ripen-Gredsted-Broe (13 1/4 Meilen). Da _"alljährlich
mindestens 2, und womöglich 3 - 4 Meilen Kunststraße gebaut werden"_ sollten, die genannte Strecke
aber an neunter Stelle im Bauplan stand, wurde sie erst 1863 vollendet. Damit verlor der Ochsenweg
einen Teil seiner Bedeutung. Die neue Kunststraße verkürzte die Nordsüdverbindung wesentlich, da
sie viele Kurven abschnitt und namentlich den großen Umweg über Leck überflüssig machte. Die nicht
unbedeutenden Baukosten gingen zu Lasten des Staates, ebenso die Unterhaltung. Für die Benutzung
erhob man dafür ein bestimmtes Wegegeld. Zu dem Zweck erbaute man in Abstände von ca. einer
Meile Chausseehäuser, bei uns Nr. 158, in denen Wegegeldeinnehmer das Wegegeld für Viehtriften
und Fuhrwerke erhoben. Die Straße war hier durch einen Schlagbaum - noch heute heißt das Haus
Bommhaus - gesperrt, d.h. nur des Nachts. _"Es muß dann aber beständig eine Laterne mit brennendem
Licht am Fenster der Expeditionsstube stehen"_ . Da das Haus an der Straßenseite mit einem Vorbau
versehen war, konnte der aufmerksame Einnehmer am Tage die Annäherung von Fuhren usw.
rechtzeitig bemerken, weshalb der Schlagbaum am Tage regelmäßig geöffnet war. Das Chausseegeld
wurde nach einem bestimmten Tarif in Schillingen erhoben. Für eine Meile zahlten einspännige Wagen
3 ß, zweispännige 10 ß, Lastfuhrwerke für jedes Zugtier 3 ß, ein Reiter 3 ß, ein Pferd 3 ß, Rindvieh 2
ß, Füllen, Kälber, Schweine, Ziegen und Lämmer von 3 - 5 Stück 1 ß, für jedes dritte Stück mehr: 1 ß
je Meile. Das Wegegeld für 1 1/2 und 2 Meilen war entsprechend höher. Für jede Zahlung mußte
Quittung geleistet werden, die beim nächsten Chausseehaus als Legitimation galt. Natürlich gab es eine
ganze Reihe von Befreiungen: die Königlichen und deren Gefolge, Verwaltungs- und Hebungsbeamte,
Branddirektor und Zollinspektor, Militär und Feldpoststafetten, Wegeinspektor und Polizeireiter,
Prediger und Küster, für die Herrschaft requierierte Fuhren und Pferde, Fuhren für Straßen-, Deich- und
Schleusenbau, Wirtschafts- und Baufuhren, Kriminal- und Polizeifuhren, Fuhren zur Mühle, Kirchen-,
Schul- und Armenfuhren, Deputatholzfuhren, Hebammenfuhren. Jede Befreiung mußte durch eine
Bescheinigung glaubhaft gemacht werden und galt nur für einen bestimmten Bezirk.

Nach der Eingliederung unseres Landes in den preußischen Staatsverband wurde diese Art der
Nutzungssteuer aufgehoben. Das Haus ging 1885 in Privathand über, verrät aber durch seine Lage und
Bauart noch heute seine frühere Bestimmung.

Südlich des Dorfes erwarb die Chausseeverwaltung eine Parzelle Landes in Größe von 0,2802 ha (Flur
23, Flurstück 4, Türenacker), die als Baumschule eingerichtet wurde, um Pflänzlinge für die Einfassung
der neuen Kunststraße durch eine Baumallee heranzuziehen. Rund 30 Jahre hindurch hat sie Pflanzgut
geliefert. Erst nach 1892, nach dem Verschwinden des Wegemeisters Reimers (Nr. 14) verfiel sie.
Heute sind nur einige hohe Bäume des Schutzgürtels als Zeugen jener Jahre erhalten.

Mit der Fertigstellung der neuen Straße entfiel die Unterhaltspflicht der Gemeinde. Eine wesentliche
Besserung im ganzen trat aber erst ein, als auch für die anderen Wege die Chaussierung durchgeführt
wurde. Das geschah für den Weg nach Westre im Jahre 1908. Das Material kam größtenteils mit der
Eisenbahn und wurde mit Fuhrwerken und Loren angefahren. Um diese Arbeiten auf eine breitere
Grundlage zu stellen, wurde der Gesamtwegeverband, der alle Dörfer des Kirchspiel zusammenfaßte,
gegründet. Nachdem in demselben Jahre Ellhöft die Strecke Ellhöft bis zum Tonderndamm ausgebaut
hatte - es mußte zu dem Zweck beim Armenverband eine Anleihe von 25000 RM aufnehmen - ,
übernahm der Gesamtverband die Unterhaltung. Der Weg nach der Bahn und weiter nach Wimmersbüll
wurde 1911 ausgebaut und vom Verband übernommen. So hatte der Gesamtwegeverband jetzt drei
Teilstrecken zu unterhalten:

l) den Weg nach Westre bis zum Waldkrug Westre,
2) den Weg nach Wimmersbüll bis zu Thorlichens Ausfahrt (Nr. W 13) und
3) die Abzweigung von diesem westlich des Bahnüberganges bis zur Grenzscheide Grellsbüll.

In jedem Jahre wurden nun diese Wege mit Grus und gesiebtem Steinschlag versehen, aufgerundet und
ausgebessert. Die Arbeiten wurden verdungen. Das Material lieferte größtenteils der Ravensberg. Die
Zeit der Sandwege war vorbei. Die Heerstraße nach dem Süden, der alte Wimmersbüller Weg und das
Stück Ochsenweg nördlich des Dorfes sanken nun zu Feldwegen herab.

Als die chaussierten Wege als Wege zweiter Ordnung vom Kreis Südtondern übernommen wurden,
löste sich der Gesamtwegeverband auf.

Kurz vor Ausbruch des zweiten Weltkrieges (1939 - 1945) wurde eine neue Grenzstraße, im
Volksmunde auch Zementstraße genannt, fertiggestellt. Sie führt von Grellsbülldeich in östlicher
Richtung nach Flensburg und verkürzt den Weg dorthin um ca.8 km. Eben südlich des Chausseehauses
kreuzt sie die Reichsstraße Nr.5 nach Tondern. Durch sie erhielt Ellhöft eine bessere Verbindung zum
Kirchdorf, während der alte Ellhöfter Weg über Böglum seine Bedeutung dadurch verloren hat.
Vom Sandweg zur Kunststraße: eine jahrhundertelange Entwicklung, Teil der Gesamtentwicklung des
Verkehrs überhaupt, bedingt durch die Ausweitung der ländlichen Besiedlung und die Bedürfnisse des
Landes, ein Anschlußsuchen der dörflichen Wirtschaft an die Volkswirtschaft und so ein Stück Dorf-
und Heimatgeschichte, aufzeigend wie auch die Entwicklung der Wege das Gesicht der dörflichen
Landschaft fortlaufend und wesentlich verändert hat.

=== 12.3. Die Eisenbahn

Verhältnismäßig spät haben wir eine Eisenbahnverbindung erhalten. Altona und Kiel wurden 1844
verbunden, Flensburg erhielt 1843 Anschluß nach Süden, Tondern bekam seine Ostverbindung 1862,
und die Marschbahn Husum-Tondern wurde erst 1887 in Betrieb genommen.Erbauer war die
holsteinische Marschbahngesellschaft in Glückstadt. 1895 übernahm sie der preußische Staat und 1921
das Reich. Der späte Ausbau unserer Strecke mag immerhin den Vorteil gehabt haben, daß die
Eisenbahn inzwischen einige ihrer Kinderkrankheiten überwunden hatte. In den ersten Jahrzehnten -
die erste Eisenbahn wurde 1835 von Nürnberg nach Fürth gebaut - war es doch ein recht zweifelhaftes
Vergnügen, namentlich im kalten Winter, sich diesem neuen Verkehrsmittel anzuvertrauen.
Unpünktlichkeit, lange Wartezeiten, Stockungen und Verspätungen waren an der Tagesordnung. Das
war doch in den vergangenen fünfzig Jahren wesentlich anders geworden.

Heute kann es auch nur ein Kopfschütteln erregen, wenn man hört, daß die Linienführung der Bahn an
das Kirchdorf heran durch dörflichen Einspruch verhindert wurde. Infolgedessen blieben der
Bahnkörper und das Bahnhofsgebäude auf Wimmersbüller Dorfgrund, während Süderlügum die Ehre
hatte, der Station den Namen zu geben. In der Hauschronik ist einiges über die Entwicklung des
Bahnhofs zu lesen. Während bis 1920 die Züge nach Tondern durchfuhren, wurde Süderlügum nach
der neuen Grenzziehung Grenzbahnhof. Nur die Bäderzüge wurden bis 1927, nachdem sie hier
plombiert waren, über Tondern nach Hoyerschleuse durchgeführt, bis dann nach Fertigstellung des
Hindenburgdammes die Strecke Hamburg-Westerland die Hauptstrecke wurde. Wir erhielten dafür
direkte Verbindung nach Flensburg. Auf der Teilstrecke Niebüll-Süderlügum wurde das zweite Geleis
dieser anfänglichen Hauptstrecke während des zweiten Weltkrieges wieder abgebaut.

Von Süderlügum nach Tondern wurde ein Pendelverkehr über die Grenze errichtet. Von 1945 bis 1951
hat der Verkehr auf dieser Strecke vollständig geruht.

=== 12.4. Das Postwesen

==== I

Das Postwesen hat sich in unserem durch königliche und herzogliche Gewalt vielfach geteilten Land
nur langsam und höchst buntscheckig entwickeln können.

Herzoglich und königliche Höfe, Städte, alle arbeiteten sie in ihrem Land oder Gebiet gesondert. Dazu
hatten wir von 1612 - 1869 noch die schwedische Post durch unser Land nach Hamburg.

Über Jahrhunderte lagen wir abseits der ältesten Postroute, Hamburg - Kopenhagen, die 1624 auf
Befehl von König Christian IV mit regelmäßigem Verkehr eingerichtet wurde. Die älteste
Postverordnung für das Königreich Dänemark und die Herzogtümer von 1624 machte die
Briefbeförderung zu einer Angelegenheit des Staates und setzte Strafen fest, wenn Versendungen auf
anderem Wege als durch das königliche Postwesen vorgenommen wurden.

Erst im ersten Jahrzehnt des 18. Jahrhunderts, um 1710, wurden nun fahrende Posten auch von
Schleswig und Husum nach Tondern eingerichtet und berührten unseren Ort. Damals hatten sich aber
aus den Botenposten schon fahrende und reitende Posten entwickelt.

Postverordnungen sorgten für Bequemlichkeit, Sicherheit und beschränkte Pünktlichkeit. Die
Verordnung vom 7. November 1791 regelte alle Einzelheiten der Brief-, Paket- und
Personenbeförderung. Die ersten offenen Wagen, darin Sitze mit Lehnen und mit Post gefüllte Kisten,
wurden vom Postillion gefahren. Sie sollten die Meile in 1 1/4 Stunde (im Wald 1 % Stunde)
zurücklegen: Der Reiseplan mußte bei der Abfahrt von den Reisenden unterschrieben werden. Die
Posthäuser, in denen im Winter den Reisenden ein warmes Zimmer zur Verfügung stand, mußten
nachts auch an brennenden Laternen kenntlich sein.

Der Fahrpreis für Personen betrug bei gewöhnlichen Posten 10 Schilling die Meile = 75 Pf. Um nicht
Grobheiten zu hören, wie der Dichter Johann Heinrich Voß berichtet, kam dazu noch ein
_"gesetzmäßiges"_ Trinkgeld (1801).

Bei üblem Betragen konnten Reisende von der Fahrt ausgeschlossen werden. Auch der Postillion hatte
seine strengen Vorschriften: Unvorsichtiges Fahren, das mit Umwerfen endigte, kostete I Rthl. Strafe.
Auf der Fahrt war Einkehr in Wirtshäuser bei Strafe verboten. Trunkenheitsdelikte wurden sogar mit
Freiheitsstrafen geahndet.

Im Sommer mag es ein Vergnügen gewesen sein, im offenen Wagen durch die Landschaft zu fahren.
In Winterkälte bei Schnee und Vereisung oder in nassen Zeiten, die die Wege grundlos machten, war
es wahrhaftig kein Spaß. Da war Umwerfen, Radbruch und stundenlanges Warten an der
Tagesordnung. Und dabei war man auf die Posten angewiesen. Mietspferde durfte man nur bis zur
ersten Poststation benutzen und zur Heimfahrt. Kein Privatfuhrmann durfte länger als 24 Stunden von
zu Hause fortbleiben.

Neben der Personenbeförderung wurde natürlich die Briefpost mitgenommen. Aus der Briefposttaxe
vom 18. Juli 1818 waren alle Beträge entsprechend der Entfernung der Orte zu ersehen. Briefe in
Dörfer, die nicht aufgeführt waren, kosteten zum nächstgelegenen Ort 1 Schilling. Auch Frachten,
Pakete beförderte man nach genauen Vorschriften je nach Art und Menge. So war noch 1819 die
Versendung von “Kaffeebohnen mit Frachtfuhren in Quantitäten (Mengen) unter vierzig Pfund”
verboten.

Daß in Kriegs- oder Friedenszeiten die Reisen nicht gefahrlos waren, haben zahlreiche Berichte über
Überfälle und Ausplünderungen bezeugt.

Um die Mitte des 19. Jahrhunderts traten bedeutende Verbesserungen im Postwesen ein. Am 15.
November 1850 erschienen die ersten Briefmarken. Es gab zwei Werte: 1 Schilling = blau, 2 Schillinge = 
rosa, beide Marken wurden “Postschillinge” genannt. Das Frankieren der Briefe ermöglichte die
Aufstellung von Briefkästen. Auch Geldsendungen durch die Post waren jetzt möglich.

ln.

In Lügum wurde 1871 eine eigene Postagentur eingerichtet. Die Post fuhr jetzt statt von Leck von
Niebüll nach Tondern. Die Haltestelle war bei Haus Nr. 46, dort war gleich hinter der Eingangstür der
Postschalter des Kontors.

Beim Gastwirt und Postexpediteur (oder Expedient) hatte der Postwagen auch vorher immer gehalten.
Der erste Postagent war Andreas Lorenzen (Andreas Post). Er war Junggeselle und ein Schwager von
Dehle in Haus Nr. 85. 1894 wurde die Agentur nach Haus Nr. 92 (Thimsen) ‚verlegt. Postagent war
Jens A. Jensen, der spätere Gemeindevorsteher. Als er 1909 das Haus Nr. 88 kaufte und abbrechen ließ,
wurde auch die Agentur von Nr. 92 1910 in den aufgeführten Neubau verlegt. Dort ist sie bis 1917
gewesen. Seitdem befindet sie sich in der Süderstraße im Haus Nr. 9. Nicolaus Hansen, der Besitzer
dieses Hauses, wurde Postagent.

Nach 1887 wurden die Postgüter mit der Eisenbahn befördert. 1934 wurde die Postbeförderung
“verkraftet”, d.h. Postautos beförderten die Post täglich von Niebüll aus in die Postorte.

Bis 1934 oblag auch die Zeitungsübermittelung in die Häuser der Post, seitdem wird sie teilweise durch
Privataustragen in die Häuser gebracht. Da das Briefschreiben in den ersten Jahrzehnten seit Bestehen
unserer Agentur noch wenig entwickelt war und es auch nur wenig Zeitungen und Zeitungsleser gab,
waren die Zustellbezirke - vorher hatte man die Postsachen abholen müssen - sehr groß. Nur ihre Größe
und daß die weiten Wege dazu täglich zu Fuß zurückgelegt werden mußten, erklärte es, daß wir doch
zeitweilig fünf Briefträger hier hatten.
Jens volquard Wollesen, der 1874 Haus Nr. 157 baute, war der erste Briefträger in Süderlügum. Der
Postbezirk umfaßte zeitweilig: Süderlügum, Ellhöft, Böglum, Struxbüll, Wimmersbüll, Grellsbüll,
Humptrup, Krakebüll, Kahlebüll und Braderupfeld. Als der Postverkehr intensiver wurde, mußten die
Bezirke verkleinert werden. Nachdem Humptrup 1946 ganz ausgegliedert war, konnten drei Briefträger
(Wilhelm Biller, Jacob Jacobsen und Bernhard Godbersen) die Arbeit machen. Dies ist allerdings nur
möglich geworden durch die “Indienststellung” des Fahrrades.
1907 wurde ein Fernsprechamt in Süderlügum eingerichtet, und zwar zunächst einmal mit unter zehn
Teilnehmern. 1917 bediente man im Amt bereits 20 Teilnehmer. Die Verbindungen wurden durch
Zusammenstecken der Leitungen am Klappenschrank handvermittelt (es konnte beim Amt mitgehört
werden). Die Entwicklung des Telefonierens war durch den Krieg und der späteren zeitweise
auftretenden Materialknappheit behindert worden. Die Entwicklung setzte erst in den Jahren ab 1925
richtig ein. Anfang der dreißiger Jahre waren rund 100 Teilnehmer dem Amt angeschlossen und 1952
waren es bereits rund 200. Das Amt war bereits seit Jahren als Selbstwählamt umgerüstet worden und
die Leitungen im Dorf waren verkabelt worden.
Nach der Verabschiedung des Postamtsleiters Nicolaus Hansen wurde Carsten Bossen, Haus Nr. 53,
am 1. Nov. 1952 Leiter des Postamtes. Das Postamt wurde im Juni 1953 nach Umbau im Haus Nr. 187
in Räume verlegt, “die den heutigen Anforderungen in jeder Beziehung gerecht werden und das Wort
modern für sich in Anspruch nehmen können”.