== 13. Verwaltung und Recht

=== 13.1. Allgemeines

Durch die Personalunion mit Dänemark war es gegeben, daß sich die höchste Verwaltungsstelle für das
Herzogtum in Kopenhagen befand. Es war die Deutsche Kanzlei, die dem dänischen Staatsrat, dem
Geheimen Staatsconseil, unmittelbar unterstellt war. Selbstverständlich waren da alle
Verwaltungszweige, besonders höhere Verwaltungsorgane vorhanden, für Heer und Flotte, Post und
Zoll usw. Die bäuerlichen Belange wurden durch die Schleswig-Holsteinische Landkommission
wahrgenommen.

Verglichen mit anderen Kirchspielen, war die Verwaltung bei uns, die wir keine adeligen, klösterlichen,
kirchlichen oder gutsherrlichen Untertanen hatten, verhältnismäßig einfach. Nur die Rivalität zwischen
König und Herzog konnte zu Zeiten eine gewisse Unruhe und Unsicherheit hervorrufen.

An der Spitze des Amtes Tondern, das mehrere Harden umfaßte, stand der Amtmann mit königlicher
Bestallung. Jede Harde hatte ihren Hardesvogt. Für die Karrharde war Leck der Amtssitz. Dem
Hardesvogt zur Seite standen Sandmänner, die auf seinen Vorschlag ernannt wurden.

Das Dorf, ursprünglich oft nur aus einer Sippe bestehend, ordnete seine Kommunalangelegenheiten sehr
selbständig. Alle notwendigen Vorschriften wurden in der Dorfwillkür niedergelegt, die bis zum Jahr
1520 zurückgehen (siehe den betr. Abschnitt).

Alle Dörfer des Kirchspiels bildeten eine Verwaltungseinheit, an deren Spitze der Kirchspielsvogt
stand. Er hatte nicht nur die innerdörflichen Angelegenheiten verantwortlich zu leiten, sondern war
gleichzeitig der Untergebene des Hardesvogten und hatte als solcher die Belange der Herrschaft,
Steuern, Abgaben, Dienstleistung, Fuhren usw. zu vertreten. Die Entlohnung war zunächst nur minimal
gewesen, wird doch 1610 von Peter Ebsen, _"Carspel Vogt zu Lügum"_ , berichtet, daß er _"1 Fuder Torf = 
4ß als Freyheit genießet"_ . Die ihnen im Laufe des Jahrhunderts zugebilligte Abgabenfreiheit wurde
1698 aufgekündigt, ihr Land wurde taxiert wie die anderen Ländereien und ein halber Pflug abgabenfrei
gelassen. 1705 wurden aber für jeden Kirchpielsvogten besondere Besoldungspflüge angesetzt. Für
Ingwer Jonas (Nr. 68), den damaligen Kirchspielsvogten, wurde 3/5 Pflug festgesetzt. Sein Einspruch,
von sieben _"beeydigten Schatzlegern"_ unterstützt, daß er nur 9/16 Pflug im Besitz und Gebrauch habe,
hat scheinbar nichts genützt; denn in der Folgezeit wird für Lügum immer 3/5 Besoldungspflug
gerechnet. Um ihn selbst freizustellen und ihn für seine Arbeit zu entlohnen, mußten die
Kirchspielseingesessenen die darauf entfallenden Abgaben aufbringen. Die Herrschaftliche Kasse durfte
Ja keine Einbuße erleiden. Bald trat dazu noch eine Veränderung ein: der Amtsschreiber mußte einen
Teil der bis dahin dem Kirchspielsvogte obliegenden Verpflichtungen übernehmen, nämlich die
Hebung der Kontributionsgelder. Für den Ausfall wurde ihnen dafür nach Reglement von 1705 eine
Jährliche Entschädigung von 15, 20 oder 25.- Rthl zugestanden. Als das Reglement von 1709 nur 15.-
Rthl zugestand, rief das die heftigsten Proteste sämtlicher Kirchspielsvögte der Karrharde hervor. Aus
ihnen erfahren wir denn auch, was sie alles für diese geringe Entlohnung leisten mußten, - und sie
müssen es ja wissen:

[quote]
____
1. Wir müssen die andern Gefälle, als Hardes Zinsen und berechneten Geldern so wohl als
was sonst extraordinair ausgeschrieben wird, einheben, wie denn auch die
Bestellung der Fuhren und was sonsten erfordert wird, nach wie vor bey unsern Diensten
verbleiben,

2. ist hauptsächlich zu consideriren, daß wir vor dem Harde uns vorschrieben, unsern credit
interponiren, und dahin streben müssen, daß die zinsen richtig abgeführet, und
Hardes credit conserviert werde, wodurch wir denn uns und unsere Güter in nicht geringe
Gefahr setzen,

3. müssen wir die Aufsicht auf alle Wege und Stege so wol alhier bey Tundern als wo
dieselben sonsten in dem Harde belegen, habe, welche denn manche, zumahlen da in denen
meisten Kirchspielen, viele frembde als Königl. Gräfliche, Adelige und andere Unterthanen
sich befinden, keinen geringen Verdruß und Ungelegenheit causiret,

4. bringet unsere function es mit sich, daß ein jeder in seinem Kirchspiel vigiliren müsse,
damit der hohen Herrschaft Interesse nicht gekränket werden, worauf dann

5. zugleich gefolget, daß wir alle verfallenden Brüch-Sachen mit Fleiß observieren, selbige
registriren und überliefern, auch bey der Brüch-Dingung auf dem Abthause
mit erscheinen, um zu der Registrirung sowohl als der unterthanen Zustand Rat und Antwort
geben müssen, wozu noch

6. die vielfältigen Reisen kommen, welche wir so wohl nach Tundern, als wohin wir sonsten
gefordert werden, zu thun verbunden und ist leichtlich zu ermessen, daß diese
15 Rthl bey weitem nicht zureichen können, unsere Reisen Zehrungskosten zu stopfen,
besondern großen Schaden dabey haben, zugeschweigen daß wir vor unsere großen Mühe
und vielfältige Versäumnis nicht das geringste uns zu erfreuen haben, und ist es

7. auch keine geringe Abzehrung vor uns, daß wir Jährlich und das ganze Jahr durch bald
an einem bald an den andern Ort die bey hiesigen Ambtshause bestellte Schützen mit
denen Hunde, wenn sie auf die Jagt ausziehen, nicht nur im hause nehmen, sondern auch
zuweilen einige Tage mit Essen und Trinken versorgen auch ihren Pferden Fütterung ohne
einige Entgelt reichen müssen; und ist es leichtlich zu ermessen, daß sie das geringe
Salarium so wir genießen nicht nur vollankömlich verzehren, besondern wir können
auch mit Grund der Wahrheit sagen, daß kein eintziger von uns damit auskommen könne.
Andere functionen und Beschwerden so täglich bey unsern Diensten so wohl in dem Kirchspiel, als
auch außerhalb desselben vielfältig vorfallen, an jetze zu geschweigen."
____

Auch die Sand- und Taxierungsmänner erhielten eine Vergütung. Sie betrug 1827 jährlich 4 Rthl; auch
waren sie von Fuhren und Dienstleistungen freigestellt, ausgenommen die Königs- und Militärfuhren.
Im Jahre 1814 wurden in den Kirchspielen, die aus mehreren Dörfern bestanden, Dorfaufseher bestellt.
Sie sollten den Kirchspielsvogt in jeder Weise unterstützen, die Aufbewahrung und Zusammenstellung
der Dorfschaftspapiere, Karten, Bücher und .dergleichen, übernehmen, die Ordnung bei den
Reparaturen der Wege und die Reinigung der Ströme und Wasserlösungen überwachen, das Fuhr- und
Einquartierungswesen regeln, für beschleunigte Beförderung der Ordres sorgen und bei Bränden die
Aufsicht übernehmen, bis der Vogt selbst zur Stelle gekommen war. Auch waren sie für die
Freimachung der Dorf- und Feldwege im Winter zuständig, während das Schneeschaufeln auf den
Landstraßen, die von Postwagen benutzt wurden, Sache der Kirchspielsvogte blieb. - Mit der
Einsetzung von Dorfaufsehern war der erste Schritt zur Verselbständigung der Dörfer in
verwaltungsmäßiger Hinsicht getan.

Die Dorf- und Kirchspielsversammlungen, früher unter freiem Himmel auf dem Dorfplatz abgehalten,
waren im Laufe der Zeit in die Häuser, später in den Krug verlegt worden.

Die Ereignisse von 1848 - 1866 haben auf die Verwaltung unseres Kirchspiels wenig Einfluß gehabt.
Veränderungen, Amtsenthebungen und Neuverteilung von Aufgaben betreffen neben den Pastoren und
Lehrern mehr die Amtmänner und Hardesvögte. Das Jahr 1867 aber war auch für die Verwaltung von
einschneidender Bedeutung, wurden wir doch durch Patent von 12.1.1867 als Provinz in den
preußischen Staat aufgenommen, und Tondern bildete einen der zwanzig Kreise dieser Provinz. Mit
der Ernennung des Landrats Kleicken am 20.1.1868 stellten die alten Hardesvogteien ihre Tätigkeit ein.
Der Kreis wurde in sieben Distrikte eingeteilt, jeder unter einem _"Königlichen Hardesvogt"_ . Sein
Aufgabengebiet war Ortspolizei, Verwaltungsgeschäfte, Brandpolizei, Aufstellung der Stammrolle
usw.. Das Wichtigste aber war, daß nun das Dorf, die Gemeinde, als unterste politische Einheit auf den
Plan trat und das Kirchspiel diese Rolle abgab. Aus der Karrharde wurde 1868 der Hardesvogteibezirk
Leck gebildet, aus den zehn Kirchspielen entstanden in der Übergangszeit bis 1871 42 politische
Gemeinden. Sie waren jetzt Körperschaften der Selbstverwaltung, die durch die Stimmberechtigten in
den Gemeindeversammlungen oder -vertretungen ausgeübt wurde. Im Jahre 1888 verschwinden die
Hardesvogteibezirke auch. Der Kreis bestand nun aus einer Stadt, 3 Flecken und 52 Amtsbezirken mit
192 Gemeinden. Unser Kirchspiel bildet seitdem mit Braderup, Uphusum, Holm und Humptrup den
Amtsbezirk Süderlügum. Der Amtsvorsteher hatte Polizeigewalt und einige Verwaltungsbefugnisse.
Er wurde auf Vorschlag des Kreisauschusses vom Oberpräsidenten ernannt. Amtssitz war bis 1935
Süderlügum, wo auch die beiden Gendarmen stationiert waren (S 176).

Rückblickend kann man feststellen, daß im Laufe von Jahrhunderten große Veränderungen auf dem
Gebiete der Verwaltung vor sich gegangen sind. Träger der Selbstverwaltung war aber immer eine
Kommunalrepräsentation, die aus mittelalterlichen Kirchspiels- und Dorfversammlungen
hervorgegangen war. Zu ihnen wurden alle Grundbesitzer geladen, denn für jeden Pflug (oder 100
Demat) wurde ein Pflugmann bestellt und geladen. Sein Erscheinen war Pflicht. Es ist
selbstverständlich, daß mit der Feldteilung die Bedeutung dieser Einrichtung stark abgeschwächt wurde.
Aber die Entwicklung, sorgte dafür, daß mit der zunehmenden Wichtigkeit von Wegen, Brücken und
Wasserlösungen ein immer noch reiches Feld selbstverwaltlicher Bestätigung vorhanden war. (Über
diese Dinge wird in einem besonderen Abschnitt berichtet).
Jedes Kirchspiel hatte seine Vertretung: Kirchspielvogt und die beteiligten Dorfschaften, daneben das
Kirchenkollegium, das auch Armenkollegium war und das Schulkollegium, bestehend aus dem Pastor
und zwei Schulvorstehern.

Und aus Vertretern der Kirchspielskommunen setzte sich die Hardesrepräsentation zusammen. In ihr
lebte die alte Hardesgemeinschaft fort, die gewiß schon in der Wanderzeit als Hundertschaft oder
Geschlechtsverband Seßhaftigkeit erworben hatte und Siedlungsgenossenschaft geworden war. Als
solche hatte sie eigene Verfassung, Gericht und Siegelführung. Die Autonomie dieser Verbände wurde
allerdings auch durch die zunehmende herrschaftliche Gewalt mehr und mehr geschwächt. Jedes
Kirchspiel mußte einen Bevollmächtigten für die Harde stellen Sie und die zehn Kirchspielsvögte
bildeten die Gesamthardesvertretung. So war die Selbstverwaltung bis unten hin durchgebildet, denn
auch das Kirchspiel mußte, dem Selbstverwaltungsgedanken Rechnung tragend, Bevollmächtigte in
eigenen Sachen ernennen. Eine Anordnung des Amtsmannes aus dem Jahre 1705 verrät nicht nur, daß
Lügum mit der Einführung dieser Einrichtung etwas gezögert hat, sondern gibt auch Aufschluß über
den Aufgabenbereich der Bevollmächtigten. Sie lautet:

[quote]
____
"Die meisten Eingesessenen Beschweren sich bei mir, daß in ihrem Kirchspiel keine
Kirchspiels-Bevollmächtigen gehalten werden, welche bey deren Rechnung und sonsten das
gemeine beste observieren könnten, und also zu dem Ende zwey aus ihrer Mitte, Ebbe Jagsen
in Lügum und Niß Christensen in Elhovet, hiermit in Lügum Kirchspiel constituiret und
verordnet, also und dergestalt, daß sie denen Gemeine Kirchspielsrechnung alle Mahle mit
beywohnern, dieselbe mit fleiß durchsehen und achten auf Ihre Durchl.Interesse, auch des
Kirchspiels Notturft fleißig in acht nehmen und fördern helfen, allen unnöthigen Schaden und
Nachtheil verhüten."
____

Auch hier zeigt sich die Tendenz staatlichen Eingreifens, wie sie im Laufe der Zeit immer spürbarer
wurde. Der Selbstverwaltungsgedanke wurde in den Gemeinden durch die Wahl der Gemeidevertreter,
gewählt durch die Bevölkerung, dokumentiert. Später erfolgte diese Wahl auf dem Umwege über
politische Parteien. Die Vertreter wählten dann den Gemeindevorsteher bzw. Bürgermeister. Obwohl
so die Selbstverwaltung eigentlich bei dem Bürgermeister der Gemeinde lag, war doch feststellbar, das
dieser laufend mehr zu einer weisungsgebundenen Person wurde. Er war selbst und in seinen
Geschäften übergeordneten staatlichen Organen verantwortlich und erhielt von dorther Anordnungen
und Befehle, die er ausführen mußte. Dieses hatte mit Selbstverwaltung nichts mehr zu tun.

=== 13.2. Die Gerichte
Die Harde war nicht nur Siedlungsverband, der die volksgemäße Einheit der Verwaltung darstellte,
sondern bildete auch einen eigenen Gerichtsverband, Verwaltung und Gericht waren eben nicht
getrennt. Der höchste Verwaltungsbeamte war zugleich der höchste Richter.
Zivile Streitigkeiten waren früher auf Kirchspielsgerichten erledigt worden, während das Strafrecht
immer ein Privilegium der Harde gewesen war. Die dörfliche Gerichtsbarkeit hat gar keine Tradition
auszuweisen. Dem 15. und 16. Jahrhundert fehlen die Kirchspielsdingswinden (Gerichtsprotokolle).Mit
dem Erstarken der landesherrlichen Gewalt hatte sich das Strafrecht ohnehin an die Hardesgerichte
verlagert. Die Herrschaft erkannte die gute Einnahmequelle der Gerichte bald und nutzte diese aus. Sie
war mit Erfolg bestrebt gewesen, das ganze Gerichtswesen durch seine Beamten und zu seiner Taxe
ausüben zu lassen.

Der Hardesvogt Carl Friedrich Lorentzen (1751 - 1786) hat bei der Beantwortung einer Anfrage des
Amtshauses im Jahre 1771 über das Karrharder Dinggericht erschöpfende Angaben gemacht, die hier
in Frage und Antwort verwertet worden sollen:

*Welche Person?*...Das Criminalgericht: Hardesvogt, Gerichtsschreiber, die Sandmänner und
Landsnäfninge als Richter.
Das ordentliche Dinggericht: Aus dem präsidierenden Amtmann, dem das Urteil allein
abgebonden und Justifizirenden Hardesvogt, 1 Gerichtsschreiber, 2 Sandmännern und
Dinghörern aus jedem Kirchspiel. Die Ansage der letzteren ist zu der Observanz.
*Wer hat sie bestellt?* - Die Landsnäfninge werden alljährlich einmal vom Hardesvogt ernannt.
Die Dinghörer wechseln ab unter den Eingesessenen. Die Sandmänner werden auf Vorschlag
des Hardesvogten vom Amtshause bestellt. Die übrigen haben Königliche Bestallung.
*Wie oft?* - Kein bestimmter Termin, sondern wenn Sachen vorliegen.
*Wo?* - Kein Dinghaus vorhanden, beliebige Stelle in Leck, öffentlich.
*Wo befindet sich das Archiv?* - In der Privatwohnung des Hardesvogten und des
Gerichtsschreibers.
*Welche Sachen werden behandelt?* - Alle illiquiden im Schätzungsfalle den Wert von 10.-
Rthl überschreitenden Civilsachen, welche weder das herrschaftliche Interesse unmittelbar noch
durch spezielle Gesetze aus summarischen Verfahren verwiesen sind.
Wie geschieht die Verhandlung? - Mündlich, mit Beziehung auf eingereichte Schriftstücke.
*Weiche Fristen?* - 4 Wochen für Klagen, Exception 3 Tage.
*Wohin wird appelliert?* - Unmittelbar an das Königliche Obergericht.
*Wie vollzogen?* - Durch Pounal und Executions Mandat; evt. Wardierung usw. beim
Amtshause erwirken.
*Entfernung der Eingesessenen vom Gerichtsort?* - Ost-West 4 1/2, Süd-Nord 3 Meilen, also
nirgends mehr als 2 Meilen vom Gerichtsort entfernt.

Demnach wirkten bei diesen Volksgerichten immer freie Bonden als Beisitzer mit. Der
Hardesvogt war der Vorsitzende und leitete den Prozeß. Im 17. Jahrhundert hatte er die alleinige
Urteilsgewalt erhalten. Auch der Amtmann konnte teilnehmen und den Vorsitz führen, hatte
aber keine Stimme. Er hatte in seinem Amt wohl die Oberaufsicht über die Rechtspflege, aber
nur eine beschränkte eigene Gerichtsbarkeit. Durch Gewohnheit und Gesetz (1768) wurde er
erste Instanz in allen geringfügigen und summarischen Sachen, wie Gesindeangelegenheiten,
Beleidigungen, Spolien usw.. Keine Sache durfte vor die ordentlichen Gerichte gebracht
werden, wenn vorher nicht ein Vergleichsversuch vor dem Amtmann stattgefunden hatte.
Über alles, was vor den Gerichten und der Harde verhandelt wurde, geben Urkunden und Akten
Auskunft. So sind die alten Schuld- und Pfandprotokolle, die seit 1698 geführt wurden, mit
ihren Nebenbüchern, eine unersetzliche Quelle für jeden Heimatforscher geworden. Ohne sie
wäre die Aufstellung einer Haus- und Hofchronik kaum möglich.

Jeder Vertrag sollte vor dem Hardesvogten und seinem Gerichtsschreiber geschlossen werden.
Natürlich mußte jede Handlung bezahlt werden, wie auch jede Gerichtshandlung nach der
Sporteltaxe vergütet wurde. 1772 waren z.B. folgende Sätze gültig: Diäten für die
Gerichtsperson je Tag 1 Rthl, Vorladung einer Dingperson 8 ß, Protokoll 6 ß je Bogen, ein
Zeugenverhör 24 ß, für einen Eid ebenfalls 24 ß, für einen einfachen Bescheid 3 ß, für ein
Definitivurteil 24 ß. Um dem Hardessvogten und dem Gerichtsschreiber die ihren
beikommenden rechtmäßigen accidenten zu stehen, wurde durch Verordnungen (1721, 1723,
1728, 1732) immer wieder eingeschärft, daß nur solche Abmachungen gültig wären, die vor
dem Gerichtsschreiber bestätigt waren. Die Wiederholung der Anordnung zeigt aber, daß man
immer wieder versuchte, andere Wege zu gehen. So ergeht z.B. 1761 wieder _"der öffentliche
Befehl"_ , der mittels _"Öffentlicher Publication von denen Cantzeln zu jeder Manns Wissenschaft
zu bringen ist, daß Niemand sich unterstehen soll, Theilungen, Contracte, Transactie und
dergleichen Instrumente, solche dem Hardesvogten und Gerichtsschreiber beykommen, durch
andere verrichten und verfertigen zu lassen...."_

Bevor man einen Vertrag dem Protokoll anvertraute, mußte in drei aufeinanderfolgenden
Dingtagen die Bekanntmachung der Absicht des Verkaufs oder Überlassung geschehen sein.
Das nannte man "Lachbieten". Erst wenn gegen die beabsichtigte Handlung keine
Einwendungen erhoben waren, wurde eine Dingswinde ausgefertigt und dem Käufer der
Kaufbrief zugestellt.

[quote]
____
"Dingswinden Protokoll 1731.
Ich, Herrmann Berntz, Königl. Hardesvogt in Karrharde, Johann Richartsen und Andres
Johannsen, Sandmänner daselbst, Thun kund und bekennen Kraft dieses, daß am heutigen dato
nach der heilsahmen gebuhrt unser Erlösers Jesu Christi 1731 als am Donnerstage nach dem
Isten Sontage S. Trinitati, was der 31ste May, für unß und denen Hardeßleuten so viel der Zeit
bey öffentl.gehegtem Ding und Recht zugegen gewesen, ist zur stelle erschienen, Jap Jensen aus
Bögwadt, und hat zum letzten und dritten mahl, maßen solches auch vorher zu zwo mahlen als
den 26. April und 10. May a.c. geschehen, öffentlich lachbieten lassen, einen von Peter Jansen
in Lügum am 11. Febr.a.c. erhaltenen Kaufbrief, vermöge dessen er von demselben sein in
Lügum stehendes wester Hauß von 6 fach, nebst dabey gefindl. 75 rth. Kohlhof, wie es daselbst
belegen und vorhanden, mit was in dem Hauße, Erd- Nied- und Nagelfest, wie auch ein
Kuhgraß auf der gemeinen Kuhweide daselbst, frey und ohne einige Beschwerde, umb und für
270 Rthl bedungene Kauf-Summe gekauft. Ob jemand vorhanden, der darauf wegen Erb-
Pfandt- und anderer Gerechtigkeit zusprechen berechtiget seyn möchte, davoneben gebührende
ansuchung gethan, ihm darüber die gericht. Bestätigung und eine Dingswinde mitzutheilen.
Nachdem nun drey mahl öffentl. lachboht, lov und Landesrecht nach geschehen, und Niemand
weder in- noch außerhalb Gericht dagegen gesprochen, oder Last und Klage gegeben,
So selbsten wird des Käufers Jap Jensen gethanes suchen hiermit deferiret, und mehr erwohnte
hierbey in original angehefteter Kaufbrief wörtl. inhalts Confirmieret und zu Recht bestätiget,
als daß sich derselbe und dessen Erben gäntzlich danach zu richten haben, und von Niemanden
dawider beeintrechtiget oder gefärdet werden sollen. Inmaßen dan die gesetzte Dingswinden
von nach beschriebenen Hardesleuten hiermit ertheilet wird, benamtl.: Süncke Hainßen,
Matthieß Jensen, Jürgen Matthießen, Andreas Nielßen, Andreas Christenßen, Hinrich
Buhrmeister und Hans Sönnichßen, welche einhellig bezeugen, daß es sich vorbeschriebener
maßen habe zugetragen. Urkundt. mit des Hardesvoigten und der Sandleyten Insegeln
besiegelt."
____

Als der Leutnant Welder 1754 seine vor sechs Jahren von dem Kirchspielsvogten Hans Johannsen
gekaufte Kate an die Frau Pröbstin Wendelin aus Dahler weiterverkaufen will, muß der Kaufbrief von
1748 nachgeholt und gerichtlich bestätigt werden:

[quote]
____
"Ich zu endes benandte Hans Johannsen, Kirchspielsvoigt in Lügum in gegebener Vollmacht
meiner Schwieger-Mutter sahl. Marina Nissen hierselbst in ihrem Leben:/Thue kund und
bekenne hiermit für allen und Jeden so daran gelegen, wie daß mit rechten Raht und gutem
vorbedacht verkauft und überlassen habe/an H. Leutenant Jacobus Arnoldus Welter und seinen
Erben alhie in Lügum/Ihres gewesenen Feste Kathe, so bestehet in Hauß und Staven/ welches
vorheer ein freyer Staven gewesen, Sie aber alles erst in der Feste, aus besonderer uhrsache
solches gelassen:/so wie es daselbst zwichen Janne Laußens und Hans Anderßens Hauß und
Staven stehet und belegen ist, alles was da in Erd-, Nied- und Nagelfest, umb und für 350 Mark
sage drey Hundert und funftzig Mark Cuhrt, welche Kauf Summa der Käufer auch richtig und
völlig bey ausfertigung und unterschreibung dieses danckbahrlicht entrichtet, dahero ihm
wegen oben gedachte gantze Kauf Summa völlig hier mit in der bündigsten Form Rechtens
quitire, verkaufe, Codire und überlasse dannach hier mit und Kraft dieses, vorbemeldtes Hauß
und Staven an mehr besagten H. Käufer und seinen Erben solcher gestalt und also/daß Er nicht
allein die Feste behörig darauf suchen, sondern auch solches von dato ab/mit aller ins künftig
darauf kommende onera und beschwerden/ möge annehmen/ dasselbe bewohnen, bebauen,
bepflanzen, nutzen und genießen und in Summa damit wie mit andern Feste Kahten zu thun und
zu lassen guten Fug und Recht haben mag.

Da wieder unß und unßere Erben keine Exception noch Recht behelfe schützen möge, will auch
dem H(errn) Käufer solches frey gegen manniglich an- und zuspruch, heim- und öffentliche
Schulden gewahre,/ Zu mehrer Urhkund daß dieses fest gehalten werden soll, bescheinige ein
solches mit Eichenhändiger Unterschrift.

So geschehen Lügum den 4. Dec. 1748."
____
(Hans Johannsen bewohnte Haus Nr. 7)

Die älteste mir bekannt gewordenen Dingswinde stammt aus dem Jahre 1590. Unter dem
Vorsitz des Hardesvogten Rickert Christernßen wird darin die Gültigkeit eines Uphusumer
"_Wollkörlsbreffes"_ beraten.
Momme Japsen tho Lugem wird unter den elf _"Beradttfragenden"_ genannt.

Die Hardesvogtei erledigte auch die Konkurssachen. Von den Kanzeln wurde zunächst die
Bekanntmachung, die Proclama, verlesen:
Nachdem die früher mit Martin Petersen zu Westrefeld verheiratet gewesene Witwe des weil.
Grobschmieds Gadsen Petersen zu Lügum (Nr. 44 der Hofchronik) mit Tode abgegangen,
werden alle, die Ansprache auf die auf dem Westrefelde und im Dorfe Lügum belegene
bewohnt gewesene Stelle oder zu ihrer damaligen Verlassenschaft Interesse habe, aufgefordert,
sich zu melden. (20.5.1813).

Im Konkursverfahren bestimmten dann zwei Wardierungs- und Sandmänner den Wert des
Besitzes, der danach auf öffentlicher Auktion in andere Hände überging. Dem Meistbietenden
wurde sein Recht durch eine Adjudikationsakte bestätigt.
Dem Hardesgericht lag auch die Fürsorge für unmündige Erben ob. Sobald einer eine zweite
Heirat eingehen wollte, mußte er sich zur Vogtei begeben und eine _"Aussage"_ protokollieren
lassen:
Aussage des Johann Boysen Hansen in Lügum, welcher nach dem Ableben seiner zweiten Frau,
Tochter des weil. Niels Jessen zu Lügum, und einer Schwester seiner verstorbenen ersten Frau
dem mit letzterer erzeugten einzigen Kinde Nicolay Hansen, geb. Febr. 1816 Aussage zu leisten
verbunden ist,
und Sibbert Martensen und Detlef Dinsen zu Ellhöft als nächste Angehörige der Mutter des
Kindes schließen folgende Vereinbarung:

1. Johann B. Hansen versieht den Sohn mit allen Erfordernissen bis zur Mündigkeit und gibt ihm dann 500.- Rthl.
2. Bei Mündigwerden kann der Sohn das Festeland der Mutter und die taxierten Gebäude zur Theilung bringen, wie in dem Falle die 500.- Rthl wegfallen.
3. Wenn er dann die 2.000.- Rthl Schulden nicht übernehmen will, behält es der Vater. (25.10.1818).

Sowohl bei Wiederverheiratungen als auch in Todesfällen galt es, das Recht der unmündigen Kinder
sicherzustellen. Deshalb werden die Herren Prediger 1761 _"nachdrückl.anerinnert, nach Masgabe der
desfals erlassenen Königl.allerhöchsten Verordnung, alle Todesfälle, wo unmündige nachgelassen
werden, dem H.Hardesvoigte ungesäumet zu melden, damit die zu bestellenden Vormiünder bey mir in
Vorschlag gebracht, und darauf von mir gehörig verordnet werden können"_ .

Daß auch Auktionen und kleine Verkäufe der Genehmigung bedurften, hatte man von jeher als
drückend empfunden, war doch immer die Erlegung von Gebühren damit verbunden. Um Kosten und
Reisen zu sparen, häuften sich die Fälle, in denen man versuchte, diese Bindungen zu lösen. So bittet
Ketel Andersen in Wimmersbüll 1805 um die Erlaubnis, sein eigenes Land selbst zu verpachten und
Auktion abhalten zu dürfen. Er hatte schon im März 1802 durch den Kirchspielsvogten Fedder
Johannsen in Lügum (Nr. 110) _"über einige seiner Effechten und Immobilien eine öffentliche Licitation"_
abhalten lassen. Erst das 1804 eingeforderte Auktionsprotokoll offenbarte dem Hardesbeamten die
Größe seiner Verfehlung: der gesamte Viehbestand und das landwirtschaftliche Inventar im Werte von
1.255 Rthl waren verkauft. Ebenso hatte er seine Ländereien auf 6 Jahre verpachtet (Gesamtpacht 1.371
Rthl) alles ohne Genehmigung und Mitwirkung der Hardesvogtei. Das bedeutete für den Hardesvogten
und den Gerichtsschreiber eine nicht geringe Schmälerung ihres Einkommens, weshalb sie ihn scharf
verurteilten und strenge Bestrafung vorschlugen. Da aber aus anderen Kirchspielen, z.B. aus Braderup,
ähnliche Fälle vorlagen und Beschwerden und Gesuche sich beim Obergericht in Gottorf häuften,
erlaubte man schließlich allgemein, daß kleine Dinge wie Landverheuerung und dergleichen von jedem
selbst vorgenommen werden durften.

=== 13.3. Kleinere Fälle und Geldstrafen
Bevor der schwersten Fälle von Gesetzübertretungen und Bestrafungen gedacht wird, wollen wir zuvor
noch einen Blick in das jährliche Brücheregister der Amtsstube werfen. Kleine Versehen wurden dem
Kirchspielsvogten geklagt und nach Möglichkeit von ihm erledigt, andernfalls sie an den Amtmann
verwiesen wurden. Die Brücheregister in den Amtsrechnungen geben deshalb Auskunft über das
Zusammenleben der Bewohner, über ihre Stellung zu obrigkeitlichen Verordnungen und Gesetzen und
über die Moral derselben. Oft handelt es sich nur um geringfügige Dinge. Schon eine vermeintlich
unberechtigt verabfolgte Ohrfeige an einen Jungen ruft die Eltern mit einer Klage auf den Plan.
Beleidigungen nehmen einen großen Raum ein. Die Aufzählung beginnt meistens mit den
Verfehlungen gegen das sechste Gebot, so 1731 : _"Den Herrn Pastori Peträi abgegebenen Attest zufolge
sind in einstehendem Jahre in derselben Gemeinde (Lügum) keine, so wieder das sechste Gebot
gesündiget"_ . Oft ist diese Einleitung allerdings auch positiv: 1718 werden sechs Personen aufgezählt,
die contra sextum gesündigt haben. Zwei Frauen werden mit je 1 Rthl bestraft, weil sie _"eines Kindleins
zu früh genesen"_ , zwei weitere Personen erhalten 8 Rthl und 10 Rthl Strafe, weil wirklicher Ehebruch
vorlag. Die letzten beiden erhalten, weil sie _"so bettelarm"_ waren, sechs Tage Gefängnis, wo sie mit
_"Wasser und Brod gespeißet"_ . Niß Tordsen in Lügum muß 1733 das gleiche Vergehen sogar _"in
Ansehung seines Zustandes(=Standes)"_ - mit 40 Rthl büßen. Jeder Fall wird nach der Schwere
besonders behandelt und bestraft. Gewöhnlich handelt es sich um Geldstrafen. Das Interesse der
Amtskasse steht sehr im Vordergrund. Gefängnisstrafen werden nur bei Zahlungsunfähigkeit verhängt.
Im 16. Jahrhundert wird auch noch die Kirchenbuße als Strafe benutzt. Peter Iwersen aus Wimmersbüll
wird 1555 in den Turm geworfen als Strafe, weil er mit der Kusine der Frau, die bei ihm in Brot steht,
ein Kind hat. Ein Geständnis kann nur durch Drohung mit dem Scharfrichter erzwungen werden. Das
Hardesthing billigt ihm _"milderne Umstände"_ zu und legt ihm auf, _"öffentlich in der Kirche Buße zu thun"_ .
 
=== 13.4. Schwere Strafen - Galgenberg
Das Dingsgericht hatte nicht nur die zivilen Rechtssachen, sondern auch die Strafsachen, also die
peinliche Gerichtsbarkeit, und damit über Leben und Tod zu entscheiden. Die Lügumer werden oft
Zeugen des Strafvollzuges gewesen sein, war doch hier auf dem Galgenberg die Richtstätte der
Karrharde. Noch heute heißen die Fennen nördlich des großen Heidehügels die Galgenfennen. Der
Heidehügel bildet den westlichen Teil der Süderlügumer Süderberge, gegenüber der Haidburg hart an
der Süderlügumer-Braderuper Grenzscheide gelegen. Carstensen, der Chronist von Leck, schreibt, daß
alte Leute den Galgen noch vor 60 Jahren gekannt hätten. Das läßt sich heute nicht mehr nachprüfen.
Jedenfalls stand er noch, wie aktenmäßig feststeht, im Jahre 1792.

Amitsdiener, z.Zt. Fußknechte genannt, fuhren den Deliquenten hinaus. Die Dinggenossen schlugen den
Kreis, d.h. sie grenzten den eigentlichen Richtplatz nach außen hin ab, und der Scharfrichter aus
Tondern verrichtete sein trauriges Handwerk. Darauf wurde die Leiche in der Nähe des Galgens
verscharrt. So war es nicht verwunderlich, daß man bei dem Auswerfen des Panzergrabens (1944), der
hart am Hügel vorbeiführte, Reste eines menschlichem Skeletts fand.

Die "Tax-Ordnung für Scharfrichter" aus dem Jahre 1698 gibt nicht nur Auskunft über die Gebühren,
sondern vermittelt auch eine Vorstellung von den verchiedenen Strafmaßnahmen, die eine
mittelalterliche Gerichtsbarkeit verhängte:

```
Einen Kopf mit dem Schwerdte abzuhauen            10 Rthl
mit dem Beile                                      8 "
Eine Hand oder Finger abzuhauen                    4 "
Einen Kopf und eine Hand an den Pfahl zu schlagen,
für jedes 2 Rthl sind                              4 "
Einen zu hängen                                   10 "
Einen wieder vom Galgen herunter zu nehmen         4 "
Einen ganzen Körper auf das Rad zu legen, und den
Pfahl einzugraben und zu setzen                    7 "
Einen Arme und Beine in Stücken zu schlagen, und
ihn auf das Rad zu flechten                       14 "
Einen todten Körper aus der Stadt zu fahren        2 "
Einen Körper in die Erde zu graben                 3 "
Einen zu viertheilen und auf das Rad zu legen     12 "
Für einen jeden Griff mit glühenden Zangen         2 "
Einen zu brandmarken                               4 "
Einen aus der Stadt zu stäupen                     5 "
Einen zu religieren
oder Stadt und Landes zu verweisen                 4 "
Einen Körper zu verbrennen                        10 ".

Grapen oder Kessel, Zange, Brenn-Eisen, Blöcke, Axte, Phähle, Räder, Nagel, Schleiffen, mit
zubehörigen Pferden, Beile, Seile, Stricke und andere dergleichen Instrumente verschaffen die
Scharfrichter sich selbst.
```
Oft kamen solche _"Executionen und Verrichtungen"_ recht häufig vor. So wurden 1820 in Flensburg
sechs Missetäter auf einmal hingerichtet. _"Schnell und glücklich verrichtete der Scharfrichter sein Amt.
In einer Stunde war fast alles vollent"_ , und er hatte 96.- Rthl verdient.
Die letzten Hinrichtungen in Lügum haben nach den Amtsrechnungen im Jahre 1721 und 22
stattgefunden. Mette Tielles zu Braderup hatte 1720 ihr unehelich geborenes Kind getötet und wurde
am 9. Januar 1721 durch den Scharfrichter Eberhard Asthusen mit dem Schwerte hingerichtet. Drei
Fußknechte hatten sie vom Porthause in Tondern nach hier gefahren. Der Kopf wurde an den Pfahl
genagelt und der Körper unter dem Galgen begraben. Die anwesenden landesherrlichen Beamten
erhielten für das Schlagen des Kreises ihre Gebühren aus der Amtskasse.
Am 22. Juni 1722 wurde Hans Iwersen aus Braderup wegen _"begangener Entleibung"_ - er hatte einen
Bauern aus Emmerschede erstochen - hingerichtet. Die Amtsrechnung des Jahres enthält an Unkosten

u.a.
an den Gerichtsschreiber Kirchhoff in Karrharde an Reise- und Zehrungskosten =
18.- Rthl1 28 ß,
die Sandleute in Karrharde als verordnete Richter in der Inquisitions Sache wegen baar verlegter
Gelder und Wegezehrung = 51.- Rthl 40 ß,
der Kirchspielsvogt Iver Hansen in Braderup = 23.- Rthl 20 ß.

Außerdem werden genannt die nachgelassene Witwe des Eberhard Asthusen - er ist inzwischen
verstorben - , der Pförtner Jens Christensen wegen der Delinquenten Verzehrung und die drei
Fußknechte, deren einer auf seinem Pferd den Delinquenten eingebracht. Im ganzen werden es 244.-
Rthl 19 ß. Die Kosten einer solchen nicht ganz billigen Prozedur werden auf die Amtsuntertanen
umgelest.

=== 13.5. Die Rechtsgrundlage
Die Rechtsgrundlage für die Urteilsfindung bildete das Jydske Lov, eine Gesetzessammlung Waldemars
II. aus dem Jahre 1241. Wenn sich im Laufe der Jahrhunderte daneben auch andere Einflüsse geltend
machten und die Rechtsprechung buntscheckig und uneinheitlich erscheinen ließen, so hat es doch
dadurch, daß es bis ins 19.Jahrhundert hinein seine vorherrschende Stellung bewahren konnte, seinen
inneren Wert bewiesen.

Wir haben gesehen, daß die Strafen von außerordentlicher Strenge sein konnten: Folterungen,
Verstümmelungen und schreckliche Todestrafen. In der Urteilsfindung war man trotzdem peinlich
gerecht und individuell. Die Härte war durch die Zeitanschauungen und Zeit-umstände bedingt. In den
unsicheren Zeiten des Mittelsalters, wo der persönliche Schutz durch die staatliche Ordnung sehr
mangelhaft war, wo also jeder auf seine eigene Sicherheit bedacht sein mußte, sowohl zu Hause als auf
der Landstraße, und wo deshalb das Messer griffbereit in der Tasche und das Schwert lose in der
Scheide steckte, wo oft Kriegshorden das Land durchzogen und die Unsicherheit vermehrten, da mußte
das Moment des Abschreckens bei der Zuteilung des Strafmaßes schon eine wichtige Rolle spielen.
Diebstähle wurden schwer bestraft, zuweilen mit dem Tode. Vieles wurde mit Geld gesühnt. Gefängnis
wurde nur während des Strafverfahrens angeordnet. Oft läßt sich allerdings auch eine gewisse
Gefühlsduselei feststellen, die in unverdienten Begnadigungen in Erscheinung trat. Die Gnade ist zu
gewissen Zeiten käuflich gewesen. Der Hardesvogt verurteilte und der Herzog begnadigte. Durchweg
spielte das Geld eine große Rolle. Das 16. Jahrhundert war die Zeit des Frühkapitalismus. Es war
verhältnismäßig viel Geld da, und das Geld verführte zum Setzen von Schranken, zum Geltendmachen
vom Recht, zum Führen von Prozessen. Dazu gehörten wieder viele Eideshelfer, womit die Gefahr des
Meineides und der Urkundenfälschung erhöht wurde. Dazu kam noch der Hexenglaube des Mittelalters.
Gerüchte und Verdächtigungen genügten oft, um eine mißliebige Person durch das Gericht erledigen
zu lassen.

Die Urkunden spiegeln Kultur und Unkultur, Sitte und Unsitte, Recht und Unrecht wieder. Und nicht
nur inhaltlich sind sie bedeutungsvoll, sondern auch in ihrer äußeren Form. Im 14. und 15. Jahrhundert
war das Plattdeutsche die Amtssprache. Die erste plattdeutsche Hardeswinde soll aus dem Jahre 1492
stammen. Bis ungefähr 1600 hatte Plattdeutsch die Führung. Doch war das Hochdeutsche damals schon
seit einem halben Jahrhundert im Vormarsch. Luthers Bibelübersetzung und sein Katechismus hatten
ihren großen Anteil daran und die Beamten. Es war die Zeit der Perücke und des Stöckelschuhes. Man
fing an, die Sprache mit französischen Floskeln zu "schmücken" und wollte bewußten Abstand vom
Volke. Da man im Volke selbst bald Epigenen (Nachahmer) hatte, wurde die plattdeutsche Volks- und
Schriftsprache bald in eine Aschenbrödelstellung gedrängt. Selbstverständlich konnte man jetzt auch
nicht mehr unter offenem Himmel im Beisein des Volkes tagen, sondern zog sich in das Thinghaus
zurück.

=== 13.6. Die Rechtsentwicklung

Nachdem wir 1867 preußische Provinz geworden waren, erlebten wir nicht nur grundlegende
Veränderungen auf dem Verwaltungssektor - hier liegen die Anfänge der heutigen Gemeinde - und
Kreisverwaltung -, sondern auch auf dem Gebiete des Rechtswesens. Während in der höchsten Instanz
die altüberlieferte Einheit von Verwaltung und Rechtspflege, ausgeübt durch das Schleswigsche
Obergericht in Gottorf, schon 1834 aufgehört hatte, indem die Verwaltung ganz auf die Schleswig-
Holsteinische Provinzialregierung überging, geschah die Trennung auf der Hardes- bzw. Kreisebene
am 1.9.1867. Es wurden drei Instanzen eingerichtet: 1. das Amtsgericht in Leck, 2. das Kreisgericht in
Flensburg, seit 1879 Landgericht, und 3. das Appellationsgericht in Kiel, seit 1879 Oberlandesgericht.
Das bestehende Recht blieb in Kraft, wurde aber durch Grundbuchgesetze (1875 und 1879), das
preußische (1851) und das Reichsstrafgesetzbuch (1871 und 1876) moduliert. Seit 1900 bildet das
Bürgerliche Gesetzbuch die Rechtsgrundlage in Zivilsachen. Unser Kirchspiel wurde dem Amtsbezirk
Leck zugewiesen.

13.7. Personelle Angaben

Zum Schluß einige personelle Angaben, die nicht den Anspruch auf Vollständigkeit machen.

7) Leider sind die weiteren Angaben nicht in den Akten H.W.Rerup
