== 14. Steuern und Abgaben

===  14.1. Allgemeines
So buntscheckig die Besitzverhältnisse in alter Zeit waren, so vielseitig und für den Mann des Volkes
fast undurchsichtig war auch die Reihe der Abgaben und Steuern. Bis in das 16. Jahrhundert hinein war
der Haushalt in Kirchspiel, Harde und Amt noch echt mittelalterlich auf Naturalwirtschaft gegründet.
Alle Abgaben standen ursprünglich irgendwie mit Burg und Schloß in Tondern in Beziehung, "ro behoff
unses slates Lutken-Tunderen". In dem Abschnitt "Lügum und Tondern" ist die Abhängigkeit schon
näher beleuchtet worden. Das Studium verschiedener Festebriefe hat gezeigt, daß der Herzog Festegüter
verlieh mit der Pflicht zur Ablieferung von Butter, Honig und anderen Erzeugnissen, alles für den
Unterhalt der Burgbesatzung und zur Besoldung der Bedienung. So führt die Hebung des Amtes aus
dem Jahre 1567 an:

1. Geld 11030 Taler
2. Roggen und Mehl 29 Last (1 L. = 12 Tonnen)
3. Weizen 7 T. 5 Sch.
4. Malz und Gerste 36 L, 1 Ort., 4 Sch,
5. Bohnen 6L.
6. Salz 3L.
7. Butter 5L. 9T.
8. Mauersteine 46553
9. Schweine 942
10. Honig 1L. 6T.
11. Hühner 220
12. Eier 940
13. Hafergrütze 11 Sch.
14. Schafe und Lämmer 251
15. Kühe 3
16. Futterrinder 41 1/2
17. Gänse 6
18. Roggengarben 234 Drag.
19. Hafer 14. 16 Ort 9 1/2 Sch
20. Gerstengarben 49 Drag.
21. Holz 2785 Fuder
22. Torf 2785 Fuder
23. Kohlen (Holskohlen) 2L.
24. Heu 2578 Fuder. 

TIP: (1 Ortug = 10 Schip Roggen = 12 Sch. Gerste = 20 Sch. Hafer).

Da im Jahre 1580 für diese Dinge die entsprechenden Werte in Mark (=1 Mark lübsch = 16 ß
(Schilling) = 12 Groschen = 192 Pfennige) angegeben werden, ist anzunehmen, daß der Übergang zur
Geldwirtschaft sich anbahnte und die reine Naturalwirtschaft nach und nach abgelöst hat. Das im
Abschnitt "Streifzüge durch die Siedlungsgeschichte " erwähnte Erdbuch von 1613 nennt noch
Schweine, Schafe, Hühner, Torf und Futterroggen. Aber daneben sind auch die Geldwerte eingesetzt.
Trotzdem sind die alten Namen und Bezeichnungen noch lange geblieben.

In die vielseitige Pflichtlieferung zum Schloß, die gerade im 16. Jahrhundert einen großen Umfang
angenommen hatte, griff nun der Staat mit außerordentlichen Steuern ein, zunächst in Kriegs- und
Notzeiten. So trat neben die _"Rechte Pflicht"_ , später _"Stehende Gefälle"_ genannt, die regelmäßig nach
den Erdbüchern gehoben wurde, als außerordentliche Steuer die *Bede*. Sie ist wohl zuerst als
"*Kontribution*" zur Landesverteidigung _"erbeten"_ , daher der Name, dann aber als ständige Realsteuer
beibehalten und als Pflugsteuer zu einer wichtigen ordentlichen Einnahme der Herrschaft geworden.
Der Pflug wurde überhaupt die Steuereinheit. Der Grund und Boden und seine Betriebsmittel bildeten
ja den Reichtum des Bauern, und die einfache Wirtschaftsnorm zur Zeit der Feldgemeinschaft
rechtfertigte ein einheitliches Steuermaß. Jede Harde verteilt das Aufkommensoll auf die Kirchpiele,
die nach ihrer Pflugzahl gleichzeitig ihre kommunalen Steuern hoben. Festebauern zahlten die
*Bondenbede* nicht.

Eine weitere Steuer war der Königsstuhl. Da Stuhl = Kapital ist, ist anzunehmen, daß es sich um eine
Abgabe der Bonden zur Verzinsung eines Kapitals handelt, vielleicht um die Bußsumme, die König
Christian I. der Harde auferlegt hatte, weil sie an dem Aufstand gegen ihn beteiligt gewesen waren. 230
freie Bonden des Kirchspiels zahlen 1613 rd. 100 Taler Königsstuhl.

Als König und Herzog miteinander in Fehde lagen, wurde eine *Magazin- und Fouragesteuer*
ausgeschrieben. Auch sie wurde nach Pflugzahl gehoben und blieb auch in Friedenzeiten als ordentliche
Last bestehen.

Da die alte Pflugzahl nicht alles Land umfaßte, wurde 1800 eine außerordentliche Pflugzahl eingeführt,
wodurch das zur ordentlichen Kontribution nicht erfaßte Land auch mit herangezogen wurde. Sie wirkte
sich zur Zeit der napoleonischen Kriege sowie 1848 - 1851 und 1864 - 1866 besonders drückend aus.
Zu dieser an und für sich sehr ungleich wirkenden Abgabe kam dann 1802 die Einführung einer neuen
Steuer, der Landsteuer. Sie war eine Grund- und Benutzungssteuer, die nach einer durchgeführten
Kategorisierung, welche die Einheit der Steuertonne (=260 Quadratruten = 0,5417 ha) einführte und
in elf Klassen nach der Güte des Bodens gehoben wurde. In der Stadt trat an ihre Stelle die Haussteuer.
Die Gewerbetreibenden mußten die Erlaubnis zur Ausübung ihres Gewerbes durch eine jährliche
Rekognition bezahlen. Näheres darüber in dem Abschnitt "Handwerk und Gewerbe". In Hinblick auf
die Ergebnisse dieser Steuer muß hier aber festgestellt werden, daß die durch die Stadt Tondern
ausgeübte Gewerbebefugnis immer mehr abbröckelte, indem auch innerhalb der Bannmeile mehr und
mehr Konzessionen erteilt wurden und dem Amt einen ansehnlichen Steuerbetrag einbrachten. Ein
Blick in die Amtsrechnungen belehrt uns über das Verhältnis der Aufkommen zueinander:

=== 14.3. Kriegssteuern und die weitere Entwicklung der Steuern
Wenn es schon ın normalen Jahren schwer war, neben den auf dem Besitz lastenden verschiedenen
Abgaben die regulären Steuern aufzubringen, so war es in Kriegzeiten doppelt schwer, mußten dann
doch besondere Kriegssteuern, Kontributionen genannt, ausgeschrieben werden. Und wann hatten wir
hier im Mittelalter keine Kriege? Diese Steuern mußten zusätzlich aufgebracht werden. Gewöhnlich
handelte es sich um große Summen. Obgleich die auferlegte Kontribution von 15.000.- Rthl 1695 auf
10.000.- Rthl ermäßigt wurde, ging das Geld schlecht ein. Und als die Wellen des 30jährigen Krieges
in unser Land schlugen, fremde Regimenter das Land durchzogen, als Abbrennen des Korns und der
Häuser und Plünderungen einsetzten, wurde das Geld so knapp, daß es unmöglich wurde, den
steuerlichen Verpflichtungen nachzukommen (1627). Erst nachdem _"die schwedische Kriegszeit
überstanden und die Unterdrückung der armen Leute aufgehört"_ hatte, war man gewillt, dem Herzog
wieder etwas unter die Arme zu greifen, doch nur mit kleinen Beträgen von 2 oder 3.- Rthl.

Als 1653 wieder 50.000 Rthl umgelegt wurden - es handelte sich um Gelder, die den Schweden
vorgeschossen waren -, protestierten einige Harden, darunter auch die Karrharde gegen die ungerechte

Verteilung:

1. Sie haben schon 4.- Rthl je Pflug für Ausstattung gewisser Auslagen bezahlt.
2. Von den vom Landtage bewilligten 24.- Rthl sind schon 12 abgeführt.
3. Die "Königl. Dennemarkische Einquartierung hat über 1.000 . Rthl gekostet".
4. Auch von den je Pflug geforderten 30.- Rthl sind schon 12 bezahlt;
5. "Haben, so wol die Königl. Dennemarkischen als auch her- nacher die Königl.
Schwedischen hin und wieder Marschierte Völker bey uns Geestleuten, und sonderlich so
nicht weit von der Heerstraße gesessen, allemahl das Quartier genommen, welche wir das
nicht alleine alles was sie begehret vergeben müssen, besonders wann sie wieder weg
gezogen haben sie mit genommen was ihnen gedienet und vorhanden gewesen, also daß wir
uns in einem meserablen zustande befinden”.
6. Zur Unterhaltung der Königl. Hochf. Durchl. Völker von jedem Pflug 2.- Rthl, 6 monatelang.
7. Haben sie noch 600.- Rthl Monatssold für 200 Mann abziehende Truppen vorgeschossen."

Die Steuern gehen immer schlecht ein und müssen oft durch Dragoner (1657) oder"6 Soldaten" (1659)
eingetrieben werden.

1665 ist schon wieder von 24.000.- Rthl Obligationen die Rede. Doch ist das Land verarmt, die Güter
sind verwüstet, das Land muß erst besät werden, ehe es wieder Steuern aufbringen kann. Die
Restantenliste wird immer größer. Man soll Korn verkaufen, heißt es wohl. Aber das Jahr 1666 brachte
Mißwuchs in Gerste und Buchweizen. Und der Roggen, der gut war, ist schlecht im Preis und meistens
schon an _"die Geldjuden"_ verkauft. Man hat ihn abstoßen müssen, um die mit militärischer Exekution
angedrohte Ausschreibung von 5.000.- Rthl durch den Obristen Walter aufzubringen. Dadurch ist der
Landmann _"gantz erschöpfet"_. Nun kommt noch die ordinäre jährliche Pflicht, dazu die 167.- Rthl
Dienstgeld, die doppelten Schweinepflichtgelder und 5.- Rthl je Pflug als Rentenkammergeld. Da muß
man schon _"zinsbares Geld"_ aufnehmen. Daß die Kornpflicht und die Kontribution in eine Summa von
40.- Rthl zusammengezogen werden, machen ihre Aufbringung um nichts leichter.

Bei diesen Zuständen bleibt kein Geld übrig, um kleine private Gläubiger zu befriedigen. Kein Wunder,
daß die _"Gebohtsbriefe"_ (Zahlungsbefehle) beginnen, in die Häuser zu flattern. 1697 werden im
Kirchspiel 22 Zahlungsbefehle durch den Amtsschreiber ausgefertigt über eine Schuld von 19.- Rthl
32.ß.

Da 1704 wieder 17.- Rthl je Pflug ausgeschrieben werden, muß das Kirchspiel ein Darlehen aufnehmen,
ebenso für 1705. Da werden 12.- Rthl je Pflug verlangt. Das macht für das Kirchspiel 416.- Rthl 14 ß
6. d. _"Solche Summa haben die Kirchspiels Eingesessenen sich verschafft und bahr erleget"_ . (Die
vollständige namentliche Steuerliste ist in meinem Besitz).

Nicht nur die Bohlsleute, auch die Kätner leiden unter der Ungunst der Zeiten und den Verpflichtungen,
die man ihnen auferlegt. In ihrer trostlosen Lage versuchen sie zunächst, das Ventil gegen die
Bohlsleute zu öffnen, um etwas Dampf abzulassen. Schon bei der Schatzung von 1659 fühlen sie sich
benachteiligt: Waren die Legesmänner nicht Bohlsleute gewesen? Natürlich hatten die verhindert, daß
_"die armen und verschuldeten Bohlsleute wegen unbilliger Ansetzung der Kontribution, wodurch sie
in gäntzlichen ruin gestürtzet und endlich Hauß und Hof zu verlassen genöthiget"_ , wogegen sie, die
Kätner, hätten herhalten müssen. Es war den Bohlsleuten daraufhin auferlegt worden, die Kätner _"inden
Jetzigen beschwerlichen Kriegsläuften nach Billigkeit einzuschätzen."_ Darauf berufen sich _"sämbliche
Kätner zu Lügum in Karrharde, Tunderschen Ampts"_ in ihrer Beschwerden im Jahre 1669: _"Sie haben
die Billigkeit nach eigenen gut dünken formiret, und dahin verstanden, daß wir armen Kätener gar
untergehen und verderben sollen"_ . Diese sind _"in zweyerley Bewantnuß zu consideriren, nämlich daß
etliche Kötener, die ihre Kathe mit eigenen Geldeankaufet, oder gebauet, von theilß Boelßleuten etwas
landt an sich gepfändet, und wegen der Zinßen, die Jährlichen früchte des landes genießen. Dieße
Kätener müsssen billich den boelen, wovon daß landt gekommen, in allen contributionibus.... zu Hülfe
legen, soweit die proportie der Ländereyen solches aussaget. Hiermit aber sint die boelßleute nicht
Jriedlich sondern wen der Kätener über den nocht etwaß zu Viehe pferden und dergleichen in Vermögen
hat, soll er zugleich auch davon den Kirchspiell Hülfe legen, da doch Niemandt der boelßleute von
ihren Vieh und pferden etwas in specie contribuiret, sondern in ihren boelen und pflügen, solches mit
beschlossen wirt,

Fürß ander seint viele Kätener, die nicht mehr alß die bloße Katen besitzen, mit der sweren
handtarbeit, von den boelßleuten und sonsten, ein taglohn verdienen, und nicht ein schaaf oder ganß
auf die weyde schlagen dürfen, sie haben dann zuforderst den boelßleuten die Häuser davon entrichtet.
Diese armen Kätener, bey welchen oftmahlß nocht leute mehr in den kathen sich aufhalten und Insten
genannet werden, haben wenige zeitliche mittel, können auch sich und ihre Kinder nicht anderß alß mit
der sweren handtarbeit ernehren. Indem seindt sie ihren nachbahrn den boelßleuten nicht schädlich,
hingewegen viellmehr nützlich"_ , da sie sonst _"viel mehr Gesinde mit großen kosten halten müssen und
sie daran ihre conservation, und nicht ihren ruin suchen sollten"_. Die Bohlsleute sammeln die Früchte
ein und viel Heu, welches die Kätener teuer von ihnen kaufen müßten. _"Daher die große Ungleichheit,
was uns von den boelßleuten aufgebürdet wirt"_ . Nicht der Kirchspielsvogt und die Legemänner sollten
sie schützen, sondern der Amtsschreiber und der Hardesvogt. Die Höhe der Lasten soll nicht örtlich und
willkürlich festgesetzt werden.

Auch die Eingesessenen und Kätner von Wimmersbüll haben in den _"vorwichenen Kriegszeiten"_ viele
Schulden gemacht und verlangen 1661 Schutz gegen die _"sie hart bedrändenden Creditoren"_.
Nur wer unter 1/4 Pflug besaß und unter 12 ß gab, war bisher von Verbittelsgeld frei gewesen. Es waren
bei uns nur sechs Personen.

Im Jahre 1707 ruft eine neue Verordnung, nach der die Insten ihr Verbittelsgeld in Höhe von 1 Species
Reichstaler jährlich zu Ostern zahlen sollen, die Humptrupper und Lügumer Insten noch einmal auf den
Plan. Ihre Eingabe zeigt, daß sich ihre trostlose Lage in den letzten 50 Jahren um nichts gebessert hat:

[quote]
____
"Nach dem Ew. Hochw. und Hochwohlgeb. Excell.gnädiges mandatum neuerlicher Zeit dahin
publiciret worden, daß wir zukünftig unsere Verbittelsgelder auf Ostern an den H.
Amtsschreiber abfahren und bezahlen sollen, auch daß die Hauß Eigener allenfalß dazu
respondiren sollen, und dann von unß Blut armen Leute, nicht wie biß dahin etwa 14 Schilling
(so wir vergang. Herfst unterthänigst richtig abgeführet haben) sonders zu species Rthl als
Verbittelsgeld gefordert werden will; so können wir nicht umbhin, Ew.Hoch. und
Hochwohlgeb.Excell. deßfalß mit dieser unserer Unterthänigen deh- und wehmüthigen Schrift
beschwerlich zu fallen, denn unsen zu stadt betreffend, so haben wir außer unser armes Leben
gahr nichts und müssen unser Brodt für uns und unsere Kinder mit saurer Arbeit kümmerlich
suchen, wenn wir aber mit und krank sind, von der Bohlsleute Gnade und Almoßen unser
dürftiges leben unterhalten, außer der blosen Wohnung haben wir in den Dörfern auf der Heyde
und Weyde nicht das allergeringste zu genießen. Nun ist ja bekant, was ein armer Arbeit-Mann
von seiner Arbeit übrig haben kan, und noch viel mehr, da unsere Arbeit, worauf wir unß das
gantze jahr vertrösten müssen, nur den Sommer und Herbst währet, im Winter und Frühling
aber für unß nichts zu verdienen ist. Ist es alßo uns eine wahre Unmüglichkeit, den geforderten
Species Reichsthaler und noch viel mehr denselben umb Oster Zeit, da wir bald ein halb Jahr
ohne Arbeit und verdienst leben und die Hunger Pfoten saugen müssen, aufzubringen. Sollten
denn nun unßere Hauswirthe gedrungen werden, die geforderten Species Reichsthaler
unßertwegen zu bezahlen, so würden dieselben, alß welche aus Barmherzigkeit und Mitleyden
und damit sie unsere Hülle in der Erndte Zeit genießen mögen, biß dahin uns bey ihnen zu
wohnen vergönnen, uns hinkünftig aus ihren Wohnungen stoßen, und wir armen Leute nirgends
bleibende Stelle mehr bekommen, sondern unter dem bloßen Himmel jämmerlich umkommen
und verderben müssen.
Weilen aber dießes nicht alleine wieder die Christ.Liebe, sondern gar wieder die Humanität
were: unßer Wesen und Gewerbe aber, wie angeführet, in Ewigkeit nicht vermag den Species
Reichsthaler aufzubringen, wir aber doch unßeren aüßersten Vermögen nach wegen des unter
Hochobrigkeitl.Aufsicht zu genießenden Schutzes, was wir bißhero erleget, auch künftig, und
zwar auf Martini, wenn wir etwas verdiehnen Gelegenheit gehabt haben, abzuführen unß wollen
lassen angelegen seyn. Dahero aber ein oder ander so gar schlecht solte seyn, daß er aufstehen,
davon geben, und alßo die Schutzgelder nicht bezahlen konte, es ja elend genug für solche Leute
selbst, daß sie nichts mehr haben, als womit die jede Stunde fort marschiren können. Und wenn
endlich wir wegen das über unßer Vermögen geforderten Species Reichsthalers vertrieben und
unß anderwerts hin zu begeben genöthigtet worden, oder in Mangel Obdachs gar solten
crepiren müsssen, die Bohlsleute an deren Wohlstandt der Herrschaft am meisten gelegen
darunter leyden müssen, indem sie von anderwerts her, ihre Arbeits-Leute mit großen Kosten
herzuholen genötiget seyn würden.

Solchen allem auch, gelanget an Ew. hochw. und Hochwohlgeb. Excell. unßere unterthänige
und flehentliche Bitte, Sie geruhen gnädig, und umb Gotteswillen, die Verfügung dahin zu
machen, daß es bey dem Alten in dießem Fall gelassen, und wir darüber nicht beschweret
werden mögen.

Die Insten deer in dem Kirchspielen
Lügum und Humtrup."
____

Besonders schwer war es immer, die hohen Kontribuitionsummen aufzubringen. Unser Kirchspielsvogt
Ingwer Jonas, dem die Hebung in Oktober 1689 anvertraut war, gibt darüber 1695 einen ausführlichen
Bericht. Von den 4.387.- Rthl, die in den fünf Jahren gefordert wurden, stehen noch über 300.- Rthl aus.
Die Restanten werden in einer besonderen Liste namentlich aufgeführt, _"wobey angegeben, wer zahlen
kan oder nicht, so Viel all mir bey mein Eydt und Pflicht bewußt ist"_

Einige charakteristische Beispiele:

```
“Lügum:
    Andreas May restirt 10.- Rthl 3 ß 7
        Der Mann ist gantz Unvermögsahm und arm wegen daß seine Frau verlehmbt ist;
    Ebbe Janßen 9.- Rthl OB 6
        Kan wohl bezahlt werden, weil sein Schwager daß Gut bekommen und angenommen
        hat;
    Momme Nissen 7.- Rthl 43 ß 4
        Der Mann sitz schlecht bey Nahrung hat ein gantz Theil unerzogene Kinder ;
    Peter Paysen 22.- Rthl 39 ß 8
        Der Mann ist gantz arm und unvermögsahm;
    Niß Bock 17.- Rthl 30.ß
        Der Mann hat ein Theil Schuldt seyn Creditoren gehn mit daß Guth weg und keinen
        will er wenig geben;
    Edlef Siwertz Witbe 21.- Rthl 7. ß
        Die Frau ist arm und unvermögsahm stickt in großen Schulden die Creditoren gehn
        damit weg;
    Lewe Jensen 20.- Rthl 38.ß
        Der Mann ist gestorben. Lorentz Johannsen hat das Guth gefestet kan woll bezahlen;
    Hans Jensen 4.- Rthl 9 ß
        Der Mann kan woll bezahlen;
    Peter Christiansen 22.- Rthl 0 ß 9
        Der ist unvermögsahm, der Mann hat guth Landt. Er will sich selbst nicht helfen;

Wimmersbüll:
    Janze Hanßens Erben 27.- Rthl 6.
        Die Leute sind unvermögsahm, ist auch von etzlichen Jahren abgebrannt;

Struxbüll:
    Karsten Nissen I4.- Rthl 16.ß
        Der Mann hat ein Theil unerzogene Kinder;

Ellhöft:
    Niß Andersen 13.- Rthl 31 .ß
        De Mann ist unvermögsahm wegen Viesturtz und dergleichen Unglück mehr.
    
Für 1693 abgeführt 302.- Rthl 36 ß. Und von dem Rest eine richtige Specification bey dem
Herrn Ambtschreiber Eingeliefert, welche in alle Ewigkeit nicht Bezahlt werden kan, Zumahlen
etzliche gehn mit dem Bettelstab und die andern sindt mit all weg gelofen den die meisten sindt
aus Jütlandt.

Für 1694 bezahlt 534.- Rıhl 18 ß in guten denschen Kronen so daß es Vermittels groß
Lammentiren Zu Sahmen gebracht ist. Der eine hat sein Acker versetzt der ander sein Wisch,
damit sie es zu Sahmen gekriegt haben.

    Lügum d. 22. October Ao 1695
    Ingwer Jonas".

```

Die Jahrhundertwende bringt keine Erleichterung, wie die Insteneingabe schon zeigte. Der Nordische
Krieg, der dem Kirchspiel zu dem noch öfter Einquartierung bringt, läßt die Steuerquellen immer mehr
versiegen. 1706 müssen 16, 1707 schon 25 Lügumer und 8 Ellhöfter Insten wegen Zahlungsunfähigkeit
gestrichen werden. Die _“Contribu- tions-Bilance"_ von 1704 weist für die Zeit von 1695-1703 wieder
einen Rest von über 240 Rthl auf. Auch die neue Landvermessung von 1712 ändert wenig daran. Als
Begründung für das Nichtzahlenkönnen wird immer wieder dasselbe angeführt: Kriegspressuren,
Mißwuchs und teure Zeit.

Und zu den Abgaben, den Pflichtgeldern, Pflug- und Kriegssteuern kommt dann noch die Korn- und
Magazinsteuer. Sie wird alljährlich neu festgesetzt: je Pflug 2 Tonnen Roggen und I Tonne Hafer,
einmal etwas höher und einmal etwas niedriger, und soundso viele Pfund Heu und Stroh. Bei
Nichterfüllung wird Exekution angedroht und auch durchgeführt, meistens militärische Exekution.
Diese bestand gewöhnlich aus I Offizier, 1 Unteroffizier und 4 Musquetieren. Wer zahlen kann und
es nicht sofort tut, wird mit einer Exekutionsgebühr belegt. Die beträgt täglich (und zwar für die ersten
8 Tage) 1 Lübschilling, dann 2 Lübschilling usw. Der Offizier erhielt 20, der Unteroffizier 12 und jeder
Gemeine 6 ß. Der Überschuß muß abgeliefert werden.

So heißt es z.B.: Von Restanten-Debitoren erhoben von Hinrich Xator von des H. Maj. Kalckreuters
Comp. von 15. - 23. Dez. 1722:

```
Peter Tordsen       1 mal l = 1 ß
Andreas Feddersen 1/2 mal l = 6 d
Peter Tordsen son   1 mal 2 = 2 ß
Lorenz Johannsen    2 mal 2 = 4 ß
Andreas Boysen      1 mal 6 = 6 ß usw.
```

Seit 1739 kann die Kornsteuer in natura oder in Geld bezahlt werden. Die Quartiergelder, die seit 1731
mit 6 Rthl für nicht stattgefundenene Einquartierung erhoben war und die Schreibgebühren kommen
in Fortfall.

Oft wird eine außerordentliche Steuer zusätzlich auferlegt, so 1704 für das Magazin der Festung
Tönning und neue Regimenter. Sie beträgt 1757 den 12. Teil der Jahreskontribution = 2.- Rthl, _"Alles
für die schwere Ausgabe zur Unterhaltung der geschehenen beträchtlicen Ausrüstungen zu Lande und
zu Wasser"_ .

Als 1802 die neue Landsteuer eingeführt wird, mußte eine neue Vermessung und Bonitierung des
Landes stattfinden. Die Ergebnisse sind in folgender Übersicht zusammengestellt:


|===
| | Pflugzähliges Land in Tonnen |  Taxe je Tonne | Taxationswert in Reichsbanktalern
| Böglum      | 198 | 80 | 15840
| Ellhöft     | 4459 | 100 | 45900
| Gulum       | 11 | 40 | 440 
| Lügum       | 1714 | 60 | 102840 
| Struxbüll   | 170 | 80 | 13600 
| Uhlenberg   | 54 | 80 | 4320 
| Wimmersbüll | 613 | 80 | 49040 
| Windtwedt   | 120 | 100 | 12000 
|             | 3339 |    | 245980 
|===

Lügum hatte außerdem 75 Tonnen nicht pflugfähiges Land, das mit 60 Rbthl die Tonne bewertet
wurde. Zum erstenmal tritt hier die Tonne (= Demat) als Landmaß auf, und es wird für jedes Dorf ein
Einheitswert bestimmt.

Es muß auffallen, daß Ellhöft und Windtwedt höher besteuert werden als die übrigen Dörfer. Das liegt
daran, daß sie nicht zum Kooge gehörten und deshalb von altersher keine Deichlasten aufzubringen
hatten. Nach dem alten Spade-Landrecht von 1619 waren nur die Ländereien deichspflichtig, die in den
großen Sturmfluten von Seewasser überspült gewesen waren.

Nach obigen Bonitierungswerten wird nun die Landsteuer errechnet. Sie beträgt für je 100 Rbthl Wert
409 bß (Bankschilling). Über die Berechnung dieser Grund- und Benutzungssteuer besitze ich eine nach
der Verordnung vom 9.Juli 1813 aufgestellte vollständige Steuerliste des Kirchspiels. Sie führt jeden
Besitzer mit seiner Landgröße, dem Taxationswert, dem Einheitswert im einzelnen und im ganzen und
dem errechneten Steuersoll auf. So lauten die Angaben für Andreas Feddersen in Wimmersbüll: 25 T.
Land, Taxe 80 Rbthl, Gesamtwert 2.000 Rbthl, Steuer 8 Rbthl 32 bß

Wenn in diesen Abschnitten eine besondere Steuer ins Blickfeld gerückt ist, dürfen wir nicht vergessen,
daß es sich hier nur um eine neue Form der Pflugsteuer handelte. Die andern Abgaben laufen immer
noch nebenher.

So zahlt Carsten Redlef Sönnichsen, Lügum, im Jahre 1829 an

```
Kontribution        71 Rbthl 84 bB
Pflicht             89 "     80 " 
Landsteuer          20 "     -  "
Kopfsteuer          15"      40 "
       Insgesamt   197 Rbthl 12 bß
```

Der Schleusenmeister Carsten Matthiesen (Haus Nr. 6) gibt als Handwerker und Kätner:

```
Kontribution           2 Rbthl 40 bß
Pflicht                3 "      - "
Handwerkerrekognition  2 "      - "
Landsteuer             - "     54 "
Verbittelsgeld         - "     32 "
           Insgesamt   8 Rbthl 60 bß.
```

Dazu kam dann noch für viele die Magazinsteuer, die erst, wie so viele Steuerarten, mit der großen
Steuerreform, die die Angliederung an Preußen in Gefolge hatte, in Wegfall kam.
Als 1867 die Kontribution auf 1/4 ermäßigt, die Gewerberekognition u.a. Steuerarten entfielen, hatte
Lügum folgende Kosten aufzubringen:

|===
| | Mark | Sibergroschen | Pfennig 
| Kontribution | 817 | 17 | 3 
| Landsteuer | 582 | 2 | 10 
| Pflicht  | 1476 |  | 2 
| Dienstgelder  | 86 |  |  
| Kolonisten-abgabe | 7 | 6 |  
| Erbpachtgeld | 123 | 7 | 6 
|===

1874 wurde das Land neu vermessen und geschätzt. Es wurden acht Güteklassen festgelegt. Als
Steuermaß diente von da an der Reinertrag. Derselbe war errechnet nach den Durchschnittspreisen der
Jahre 1837 - 1860 unter Fortlassung der zwei teuersten und der zwei billigsten Jahre. Die Steuer war
nur mäßig, betrug sie doch kaum 10 v.H. des Reinertrages.
Auch wurde jetzt eine Klassensteuer, die Einkommensteuer, erhoben. Nach der Freigrenze von 900 Mk
war sie bis zu 4% gestaffelt. Auch dafür waren umfangreiche Vorarbeiten nötig. Der Vermögenswert
jedes einzelnen Besitzes mußte festgestellt werden. Aus der Schätzungsliste, die für das Dorf Lügum
abschriftlich erhalten ist, sollen einige wenige Beispiele angeführt werden:

|===
| | Markus Hansen | Math. N. Petersen | Volqu. Jannsen | Bachmann 
| Landgröße | 52 1/2 ha | 5 ha | 41 1/2 ha | 22 ha 
| Landwert | 11 025 Mk | 1050 Mk | 8715 Mk | 4620 Mk 
| Vieh u. Mobilien | 5052 " | 1090 " | 640 " | 1800 " 
| Gebäude | 4670 " | 1840 " | 2578 " | 6440 " 
| Vermögen | - | 4800 " | - | - 
| Schulden | 6000 " | - | 3200 " | - 
| Besondere Einnahmen | 315 " | - | - | 30 " 
| Besondere Abzüge | - | - | - | 260 " 
|  | 15 062 Mk | 87000 Mk | 8925 Mk | 1263 Mk 
|===


Der Landwert ist hier mit 210.- Mk je Hektar eingesetzt. Außer den Schulden konnten Beträge für
schlechtes Land, für schwierige Familienverhältnisse, für Abnahmeverpflichtungen usw. abgesetzt
werden.
Mit der Einführung der neuen Gebäudesteuer kam die Zahlung der Verbittelsgelder in Fortfall (1875).
Nach und nach wurden auch die Festegelder abgelöst.
Das Gartendienstgeld, ein Ablösungsgeld für die frühere Verpflichtung der Kätner, den Schloßgarten
in Ordnung zu halten, hat sich noch am längsten gehalten. In meinem Besitz ist die alte Hebeliste von
1811 - 1840 und von 1851 - 1853. Die erstere enthält die Namen von 39 Kätnern aus Lügum und zwei
aus Ellhöft, die letztere nur 16 Namen. Ein Verzeichnis aus dem Jahre 1839 über die Freikätner - es
enthält elf Namen - läßt darauf schließen, daß auch diese Verpflichtung nach und nach abgelöst worden
ist, bis sie 1876 ganz aufhörte.
Als 1894 die staatliche Vermögenssteuer eingeführt wurde, durften die Grund- und
Gebäudesteuererträge in die Gemeindekasse fließen. Seit dem Jahre 1924 wurde eine Hauszinssteuer
erhoben, doch nur für nicht landwirtschaftliche Gebäude. Sie war bestimmt, den so notwendigen
Wohnungsbau zu fördern.