== 15. Süderlügum und Tondern

=== 15.1. Schloßdienste
In den Kämpfen zwischen Herzog und König im Anfang des 15. Jahrhunderts spielte auch die Stadt
Tondern eine wichtige Rolle. Der Friede zu Vordingborg 1435 sprach das Herzogtum Schleswig
einschließlich Nordfrieslands und den Inseln dem Herzog Adolf VIII. zu. Unter den Schauenburgern
haben sich die Städte besonderer Gunst erfreut. Sie waren, weil meist mit Burgen versehen, nicht nur
militärische Stützpunkte, sondern entwickelten sich im Laufe der Zeit auch zu führenden Wirtschafts-
und Verwaltungsmittelpunkten in ihren Gebieten, d. h. in den umliegenden Harden. Der Burgvogt und
Schloßhauptmann war Lehnsmann des Herzogs, führte den Oberbefehl und vertrat den Landesherrn
als Richter. Die landesherrliche Verwaltung und Erhebung der Einkünfte lag in seiner Hand und
Verantwortung. Nicht nur die Stadt, sondern auch die Harden und viele einzelne Bauern hatten Steuern
an die Burg zu zahlen. Diese bestanden zunächst aus Naturalien: Speck, Malz, Korn, Tiere (Hühner,
Schweine) usw.. Allmählich vollzog sich der Übergang zur Geldwirtschaft, so daß beide Formen zuerst
nebeneinander bestanden. (Siehe die Abgaben im Erdbuch von 1613).
Die umfangreichen Um- und Erweiterungsbauten am Schlosse bis 1585 erforderten ungeheure Mengen
an Materialien und bedangen auch ein ganzes System von Arbeitsleistungen. Jeder Bauer der Karrharde
wurde zu Spann- und Hofdiensten herangezogen, jeder Kätner zu Hand- und Laufdiensten.
Die Schloßküche forderte besonderen Tribut. Die Burgbesatzung war nicht unbeträchtlich. Dazu hatten
die Herzöge, besonders in der vorgottorfschen Zeit, noch keine feste Residenz. So kam es, daß die
_"reisende Hofhaltung"_ auch ab und zu die Burg in Tondern heimsuchte. Und auch später, als Gottorf
fester Hof- und Verwaltungsmittelpunkt geworden war, war immer mit einem kurzen Besuch des
Herzogs und seines Hofes zu rechnen, sei es zu Gerichtstagen, Jagden, Besichtigungen der Deiche, der
Marschen usw.

In dem Dachgeschoß des Schlosses wohnte der Kornschreiber, der die Pflichtabgaben an Korn, Butter
usw. überwachen mußte und in dessen Hand die ganze Wirtschaftsführung lag. Er hatte dafür zu sorgen,
daß alles da war. Für besondere Anlässe wurden erhöhte Anforderungen an die Untertanen gestellt. Und
aus der gelegentlichen Anlieferung von Naturalien wurde im Laufe der Zeit eine feste Gewohnheit, aus
der Freiwilligkeit wurde Pflicht und Zwang. Was nicht für die Bedürfnisse der Burg und ihrer
Besatzung ging, floß der herzoglichen Hofhaltung zu.

Wie so die Abgaben immer drückender wurden, so wurden auch die zu leistenden Dienste nicht
weniger. Die Unterhaltung der Burg erforderte schon dauernd Arbeits- und Spanndienste. Der
Torfverbrauch war um 1.600 auf 3.000 Fuder gestiegen. Diese mußten gegraben und angeliefert
werden. Die Kätner von Süderlügum und Klixbüll hatten ihn in der Scheune aufzusetzen. Und welche
Unmengen verschlangen nicht die beiden Ziegelöfen, die in neun Öfen jährlich 180.000 Steine
brannten.

Kätner aus Süderlügum hatten mit anderen zusammen auch Gartendienst im Schlosse zu verrichten.
Die Wasserzufuhr zur Schloßmühle zeigte sich 1598 als durchaus ungenügend, so daß man beschloß,
nicht nur die alte Mühle durch einen Neubau zu ersetzen, sondern auch die Wiedau zu regulieren und
ihr teilweise ein neues Strombett zu geben. Wieder mußten die Hardenbewohner antreten. Auch die
spätere Unterhaltung, besonders die der Soemmerdeiche, der ausgebaggerten Au wurde auf die Dienst-
pflichtigen umgelegt. Das Kirchspiel Süderlügum übernahm allein den Steindamm von der Freischleuse
bis zur großen Mühlenbrücke.
Als im Jahre 1533 der Burgraum nicht mehr genügte, um die Verpflegung aus eigener Wirtschaft
sicherzustellen, wurde in dem südlich der Stadt gelegenen Hestholm ein Vorwerk eingerichtet, das im
ganzen 365 Demat Land umfaßte. Damit wurden die bisher zur Burg pflichtig gewesenen Süderlügumer
zum Dienst auf Hestholm verwiesen, aus der ganzen Karrharde 180 Bauern und 90 Kätner.
Doch auch das dauerte nur seine Zeit. Zwei Generationen haben in dieser Dienstbarkeit gestanden.
Gottorf gestaltete die Verwaltung immer straffer und zentraler, die örtlichen Verwaltungsstellen
verlieren mehr und mehr an Bedeutung. Die Domänenwirtschaft hatte sich schon längst als
unwirtschaftlich erwiesen. Hestholm wurde 1608 verpachtet. Die Folge war, daß die Bauern ihrer
Dienstpflicht ledig wurden, seitdem aber eine jährliche Abgabe für ihre Freiheit zahlen mußten, das
sogenannte Hestholmer Dienstgeld. (Siehe Erdbuch 1613).
Dem Amt aber mußten weiterhin Dienste geleistet werden. Waren Reparaturen am Schloß, an den
Vorwerken oder den herrschaftlichen Mühlen, mußten die Bauern und Kätner wieder antreten, auch
das Torfgraben und Anliefern nach Tondern blieb bestehen. Erst durch das Reallasten-Ablösungsgesetz
von 1873 sind die Dienstpflichten endgültig verschwunden.

=== 15.2. Torflieferungen
Unter den Pflichtleistungen, die wir Tondern gegenüber zu erfüllen hatten, nahmen, wie aus dem
vorigen Abschnitt zu ersehen, die Torflieferungen den ersten Platz ein. Nachdem die Wälder vieler
Harden zusammengeschrumpft, ja teilweise gänzlich vernichtet waren, war der Torf fast das einzige
Brennmaterial. Das älteste Torfregister der Karrharde, _"Vertekennisse weswegen des Tegel-Holtes oder
Torfes"_ - es ist in plattdeutscher Sprache geschrieben - stammt aus dem Jahre 1590. Danach hatte das
Kirchspiel 94 Fuder zu liefern, und zwar:
Lügum 42, Wimmersbüll 29, Strucksbüll 3, Böglum 5, Ulenbarge 3, Ellhöwett 11 und Windtwedt 2
Fuder. Die 54 pflichtigen Bohlsleute sind namentlich aufgeführt. Restanten mußten _"vor Iden Voeder
Ver Schillinge zahlen"_ . Im Laufe des 17. Jahrhundert sanken die Zahlen etwas. 1711 waren es aber
immerhin noch 1741 Fuder, allein 1.200 für das Schloß, von denen die Dörfer Abel, Überg, Ladelund,
Karlum, Leck, Enge-Stedesand, Klixbüll, Braderup und Lügum zusammen 413 Fuder zu liefern hatten.
Lügum mußte hiervon 79 1/2 Fuder aufbringen, für jeden Pflug Landes zwei Fuder. Das Fuder wird
im Ablösungsfall jetzt aber schon mit 16 Schillingen berechnet. Außer an das Schloß wird an folgende
Personen geliefert (1733):

```
Süderlügum:
an den Hausvogten und Kammerrath Behm       9 Fuder (85)
an Kammerrath Werffel...................... 2 "     (70)
an dem Scharfrichter....................... 2 "     (10)
an den Pförtner............................ 2 "     (50)
an die 3 Fußknechte........................ 4 "     (10)
an den Sekretär Fabricius.................. 7 "     (60)

Wimmersbüll:
an den Hausvogten.......................... 2 "
an den Teutschen Schulmeister.............. 2 "     ( 6)
an den Kammerrath Morffel.................. 2 "

Ellhöft:
am der selben.............................. 3 "

Uhlenberg:
an den Amtmann von Holstein................ 1 "
```

Die eingeklammerten Zahlen geben an, was der Empfänger im ganzen zu erhalten hatte.
Der Torf wurde zur Hauptsache auf den herrschaftlichen Mooren gegraben. Die Lügummer waren auf
das große Moor bei Beiers, südlich von Lüdersholm, verwiesen. Man war verpflichtet, den Torf zu
graben, zu trocknen und nach Tondern zu liefern. Das Graben auf den herrschaftlichen Mooren geschah
an *einem* Tage. Ein Soden sollte 8 Zoll lang und 2 1/2 Zoll breit und dick sein.
Durch den jährlichen Eingriff in den Moorbestand, dazu oft genug durch ganz unsachgemäßes Graben,
sah man die Moore immer mehr dahinschwinden. Seit 1729 beschäftigte man sich immer wieder mit
der Frage, wie man _"die Möhre konservieren"_ könne. Es wurden zu dem Zweck genaue Anweisungen
herausgegeben: es ist nur die obere Schicht abzugraben, die Löcher müssen wieder aufgefüllt werden.
Das Wasser ist tunlichst abzuleiten, damit der abgegrabene Moorboden für Wiesenwuchs und Kornbau
geeignet wird. Es wird empfohlen, probeweise Hanf anzubauen. Daneben war man bemüht, die
Deputatlieferungen nach Tondern herabzusetzen. Wenn 1784 auch noch 12 Fuder für einen Hegereiter
hinzukamen, weil keine genügenden Holzlieferungen mehr zur Verfügung standen, so sank die
Fuderzahl doch von Zeit zu Zeit. Während es 1772 noch 927 Fuder waren, wurden 1789 nur 727 Fuder
geliefert. Die Lieferung fiel aber nicht einfach fort, sondern mußte von dem Freigestellten in Geld, das
Fuder mit 32 Schill. bezahlt werden. So entfielen 1780 die 20 Fuder, die Lügum als Hoftorf an der
Amtspförtner zu liefern hatte, mußten aber mit 20 x 16 Schill. an die Amtskasse bezahlt werden. 1755
wurde allerdings die Naturallieferung wieder eingeführt.
1810 gruben auf dem Moor bei Beiers

*aus Lügum:* Andreas Johannsen
2 F., Maren Carsten 2 F., Peter Paulsen 2 F., Jesper Lorenzen 2 F., Siebert Färber 1 F., Andreas
Jacobsen 1 F., Ebbe Jansen 1 F., Detlef Andersen 1 F., Karsten Tordsen 1 F., Hans Jensen I F.,

*aus Wimmersbüll:* Karl Andersen 2 F., Hans Thiesen I F.,

*aus Böglum:* Peter Karlsen 1 F., Andreas Friedrichsen 1 F.,

*aus Ellhöft:* Thomas Friedrichsen 2 F., Peter Folger 2 F. und

*aus Windtwedt:* Asmussen 2 F.

Im ganzen wurden dort 194 Fuder gegraben.

Neben den herrschaftlichen Mooren gab es eine ganze Anzahl von Privatmooren. Da das Moor bei
Beiers nur noch schätzungsweise für 20 Jahre Torf liefern konnte, erwog man den Gedanken, ob die Privatbesitze nicht heranzuziehen
wären. Da dem aber schwerwiegende rechtliche Bedenken entgegenstanden, die Bohlsbesitzer hatten
dort Eigentumsrechte und die Festebauern Nutzungsrecht, nahm man Abstand davon.

Der Hausvogt Fonteney machte 1812 den Vorschlag, auf Beiers Moor Preßtorf zu fabrizieren. Da die
Heizkraft das Eineinhalbfache des gegrabenen Torfes betrug, würde man mit dem damals noch
reichlich 55 Demat großen Moor immerhin etwas länger aushalten. Doch war der Preßtorf damals noch
unbekannt und die Verhandlungen zogen sich über 20 Jahre hin, da die Fragen der Entwässerung, der
Arbeitskräfte, der Neuverteilung der Deputatsmengen und vieles andere sehr gründliche Überlegungen,
Vorarbeiten, Besichtigungen, Messungen, Beratungen usw. erforderten. Inzwischen hatte schon die
enfernte Lage des Herrschaftlichen Moores bewirkt, daß viele ihren Torf auf Privatmooren graben
ließen. So wurden 1816 von den 627 Fudern nur 147 in Beiers Moor gegraben, die restlichen 480 in
eigenen Mooren. Viele hatten auch Ablösung erwirkt. Lügum lieferte in dem Jahre nur 67 1/2 Fuder
in natura und bezahlte 12 Fuder bar.

Um 1830 wurde es Brauch, sich das Moor selbst zu beschaffen und das Anfahren zu verdingen.
Sönnichsen, Ladelund, lieferte 1831 fast allen Torf nach Tondern. Auch Lügum schloß einen
Lieferungsvertrag mit ihm ab. 1834 unterschrieb der Kirchspielsvogt Gottfried Wilde für die Gemeinde
einen solchen auf sechs Jahre. Der 1846 von 16 Gemeinden, darunter auch Lügum, abgeschlossene
Vertrag ist von Marcus Hansen und dem Kirchspielsvogten P. C.Petersen unterzeichnet. 1848 werden
aber 28 1/2 Fuder mit 2.- Mk für das Fuder abgelöst, während die anderen 39 Fuder weiter in natura
zu liefern sind. Die Ablösungsverhandlungen werden in diesen Jahren immer häufiger. Man fordert die
Gemeinden direkt zu Vorschlägen auf. Gemeinden, die zu wenig bieten, müssen weiterliefern, wodurch
man allerdings in die sonderbare Lage kommt, mehr Torf zu erhalten als man braucht; so hatte man
1848 fast 200 Fuder zuviel.

Diese kurze Darstellung zeigt, daß die Torflieferungen auch für unser Kirchspiel durch Jahrhunderte
hindurch eine unbequeme Untertanenpflicht gewesen war. Allmählich lockern sich auch diese Bande.
Ihre Zeit ist vorbei und damit wird ein Stück fesselnder Unfreiheit beseitigt.

=== 15.3. "Zuzugsgenehmigung"
Schon im frühen Mittelalter kann man feststellen, daß sich zwischen Stadt und Land große
Unterschiede entwickeln. Sie betreffen die Arbeit, Wohnung, Kleidung, Gesellschaftsform,
Lebensweise und Lebensauffassung. Hier der landgebundene Bauer, der Kätner, wenige Handwerker,
dort der Handwerker, das Gewerbe jeder Art, der Handel. Hier der Mensch, der auf dem Seinigen seine
Nahrung, sein Genüge findet, dort ein Mensch, der mehr auf den anderen angewiesen ist, nicht nur für
den eigenen Bedarf schafft, sondern verkauft, kauft, ein Zusammenleben, das schon früh eine gewisse
Ordnung erforderlich macht, Grenzen abstecken läßt, eine Verwaltung bedingt. Schon die Anhäufung
von Menschen auf einen verhältnismäßig kleinen Raum bedingt Aufgliederung, Ordnung, Gesetz,
Verteilung von Recht und Pflicht. Es bildet sich ein besonderes Bürgerrecht heraus. Bürgerrecht ist
durch Geburt gegeben und kann auch erworben werden. Der Bürger darf Handel und Gewerbe treiben,
hat Rechte und Vorrechte, bekleidet Ehrenämter, kommt auch seiner Steuerpflicht nach, kein Erbe, kein
Staven darf an Fremde verkauft werden, er werde denn erst Bürger oder wenigstens Bewohner. Bürger
wird, wer den Bürgereid ablegt und seinen Bürgerbrief erhalten hat. Voraussetzung ist eheliche Geburt,
Ehrbarkeit und tadellose Lebensführung, Mündigkeit und christliche Religion. Städtische
Gehaltsempfänger, Geistliche, Lehrer, Organisten Stadtvögte, Ratsdiener, Marktvögte, Rackerknechte,
Totengräber u.a. sind ganz ausgeschlossen; ist es doch schon schwer, die zu Grabe gebracht zu kriegen.
Keiner will tragen, man muß sich oft eines Schlittens bedienen. Als der 1680 in Tondern verstorbene
Träger Steffen Knutzen in seinem Heimatdorf Lügum beerdigt werden soll, verweigern Pastor Claudius
und der Küster ihm Leichengefolge und Gesang. Nach der Beerdigung muß von solchen Personen ja
auch das Leichenlaken und die benutzte Bahre verbrannt werden, weil sie durch den Gebrauch entehrt
sind.

Abgesehen von diesen besonderen Umständen zeigt dieser Fall, daß die Stadt Tondern Zuzug vom
Lande hatte. Das oft ärmliche Leben auf dem Lande, der Glaube an leichteres Leben und
Vorwärtskommen in der Stadt, ließen viele den Versuch wagen. Auch die Stadt wünschte diesen Zuzug,
erhielten solche Neubürger doch ein Jahr Steuerfreiheit, allerdings mußten sie dafür reihum den
Klingelbeutel in der Kirche umtragen, wenn sie sich nicht mit 3 -4.- Rthl von dieser Verpflichtung
loskauften.

In den Einwohner- und Bürgerlisten der Stadt Tondern finden sich nun auch viele Lügumer Namen.
1616 wird ein Peter Jensen genannt, 1698 ein Niels Petersen Winter aus Gammelby, ein Vorfahre
unserer Lügumer Familie gleichen Namens. 1709 bis 1868 haben 32 Personen aus Lügum das
Bürgerrecht in Tondern erworben, gewiß nur eine kleine Zahl, in jedem fünften Jahre einer; doch muß
man bedenken, daß man nicht ganz mittellos sein durfte, daß die Innungen sehr strenge Maßstäbe
anlegten und daß man damals über Seßhaftigkeit und Freizügigkeit anders dachte als heute.

Anzahl der Abgewanderten und Verteilung auf die Dörfer des Kirchspiels:

|===
| Beruf | Lügum | Wimmersbüll | Ellhöft | Struxbüll | Im ganzen
| Ohne Angabe | 3 | 1 |  |  | 4 
| Schuhmacher  | 6 |  |  |  | 6 
| Höker u.Kaufmann  | 4 | 1 |  |  | 5 
| Schneider | 1 |  |  |  | 1 
| Bäcker | 1 |  |  |  | 1 
| Tagelöhner | 4 |  |  |  | 4 
| Gewürzhändler | 1 |  |  |  | 1 
| Rotgießer | 1 |  |  |  | 1 
| Maler | 2 |  |  |  | 2 
| Gastwirt | 3 |  | 1 | 1 | 5 
| Maurer |  |  | 1 |  | 1 
| Fuhrmann | 1 |  |  |  | 1 
|  | 27 | 2 | 2 | 1 | 32 
|===

Im einzelnen handelte es sich um folgende Personen:
l. Andres Christianßen, ohne Beruf, 1709, Lügum,
2. Johannes Andresen, Lügum, Schusteramtsmeister, 1731,
3. Andres Peterßen, Lügum, ohne Beruf, 1733,
4. Martinus Johanßen, Lügum, ohne Beruf, 1735,
3. Peter Eriehßen, Lügum, Sehuhflieker, 1737,
6. Sönke Todsen, Wimmersbüll, Höker, 1753,
7. Jacob Wollesen, Lügum, Schuhflicker, 1753
8. Peter Mathies, Lügum, Tagelöhner, 1754,
9. Peter Marcußen, Wimmersbüll, ohne Beruf, 1755,
10. Johann Brodersen, Lügum, Schneider, 1755,
11. Ebbe Petersen, Lügum, Schusteramtsmeister, 1760,
12. Andreas Bossen, Lügum, Grobbäcker, 1762,
13. Momme Jensen, Lügum, Tagelöhner, 1762,
14. Lorenz Andersen, Lügum, Gewürzhändler, 1773,
15. Franz Peter Hansen, Ellhöft, Maurermeister, 1779;,45 Jahre alt, legte Entlassungsschein über abgeleistete Militärdienstpflicht vor.
16. Andreas Hansen, Lügum, Höker, 1783, 42 Jahre alt,
17. Iwer Jensen, Lügum, Rotgießer, 1783,
18. Christian Jensen, Lügum, Schustermeister, 1785,
19. Lorenz Lorentzen, Lügum, Höker, 1783, 42 Jahre alt,
20. Lass Petersen, Süderlügum, Höker, 1788,
21. Lorenz Bertram Carstensen, Ellhöft, Gastwirt, 1842, durch Freilass militärfrei,
22. Andreas Christian Hansen, Süderlügum, Krugwirt, 1843,
23. Jes Hansen Jessen, Süderlügum, Schuhmacher, 1854,
24. Frederik Christian Hansen, Süderlügum, Maler, 1856,
25. Peter Johan Lund, Süderlügum, Tagelöhner, 1863, Entlassungsschein nach erfüllter Militärdienstpflicht,
26. Paul Peter Johannsen, Süderlügum, Kaufmann, 1863,
27. Hans Peter Petersen, Struxbüll, Gastwirt, 1864,
28. Hans Peter Petersen, Lügum, Gastwirt 1815, Befreiungsschein vom Landausschuß,
29. Claus Johannsen, Lügum, Fuhrmann, 1856,
30. Jacob Jessen, Süderlügum, Wirtsmann, 1849,
31. Andreas Iwersen, Lügum, Kaufmann, 1851,
32. Friedrich Hinrichsen, Lügum, Tagelöhner, 1868.

Beim Bürgereid konnte man sich der deutschen oder dänischen Sprache bedienen. Von den oben
aufgeführten Personen leisteten Nr. 25 und 26 den Eid in dänischer Sprache.
Von den eingewanderten "Einwohnern", also von solchen Personen, die das Bürgerrecht nicht erwerben
konnten, kann hier nur einer genannt werden. Es ist der Advokat und Notar Christoph Hermann
Ambders, der Sohn des Pastors Andreas Ambders zu Lügum (1735 - 1787).

=== 15.4. Amts- und Königsfuhren
Sehr drückend war es von jeher für die bäuerliche Bevölkerung, umfangreiche Fuhrdienste für das
Amtshaus zu übernehmen, d. h. entweder zweispännige Wagen oder Vorspannpferde zu stellen. Mußte
ein herrschaftlicher Wagen von Tondern nach Leck, so stellte Lügum entweder den bespannten Wagen
oder derselbe wurde in Tondern bespannt und wechselte bei uns die Pferde. Mußten die Beamten zum
Thing, zur Deichschau, zu einer Wegebesichtigung: immer mußten die an der Strecke liegenden
Kirchspiele die Beförderung übernehmen. Oft genug ging es auch über die Hardesgrenze hinaus nach
Bredstedt, Husum, Schleswig, Flensburg, Apenrade, Hadersleben. So fährt Lügum:

am 21.2.1732 nach Leck; 1 Wagen und 1 Paar Vorspannpferde, Amtsgeschäfte;
am 27.3.1732 nach Leck: 3 Paar Pferde
am 24.5.1732 nach Leck: 2 Wagen und 7 Paar Pferde, Musterung des Kgl. Leibregiments in Schleswig;
am 19.5.1732 nach Leck: | Wagen, ein Kornett soll in Bredstedt aufgestallte Pferde auf die Weide bringen;
am 21.5.1732 nach Leck: nach Klixbüll: 1 Wagen, welcher Hafer nach Husum bringen soll;
am 27.5.1732 nach Leck: 3 Paar Pferde, der Amtmann fährt nach Schleswig;
am 7.6.1732 nach Tondern: 3 Paar Pferde, der Amtmann kommt von Schleswig zurück;
am 21.6.1732 nach Leck: 3 Paar Pferde der Amtmann fährt nach Husum;
am 22.8.1732 nach Klixbüll: 2 Wagen, der Zimmermeister Hausfried, Hoyer, besichtigt die Mühlen;
am 26.8.1732 nach Tondern: 2 Wagen und 3 Paar Pferde, ein Justizbeamter fährt von Leck nach Apenrade;
am 27.8.1732 nach Tondern: 3 Paar Pferde, der Amtmann muß nach Tondern zurück;
am 19.12.1732 nach Klixbüll: 2 Paar Pferde, für eine Fahrt in den Christian-Albrechtskoog.

Zu diesen Amtsfuhren kam dann noch eine starke Beanspruchung durch Königsfuhren. Unternahm Sr.
Maj. eine Heeresfahrt nach Holstein, so war ein ganzer Fuhrpark erforderlich. So stellte Lügum 1735
von 266 Wagen und 165 Paar Pferden 14 Wagen und 21 Paar Pferde, 1734: 6 Wagen und 14 Pferde,
1771: 44 Wagen und 54 Paar Pferde.

Lügum leistete in:

1777: 8 Königs- und 60 Amtsfuhren,
1782: 20 Königs- und 13 Amtsfuhren,
1787: 1 Königs- und 14 Amtsfuhren,
1797: 32 Königs- und 14 Amtsfuhren,
1807: 26 Königs- und 8 Amtsfuhren
1810: 65 Wagen und 77 Paar Pferde in Königsfuhren und 5 Amtsfuhren usw..

Während Lügum Sandfuhren nach Tondern nicht ausgeführt hat - Tondern brauchte z.B. 1780 fast 60
Fuder Sand - , so mußte es doch Arrestanten von hier nach dem Porthaus (Gefängnis) befördern oder
von dort abholen, so 1835 die Arrestanten Anna Catharine Floy, Christian Christiansen Floy, Lügum
und Nicolay Reichsen, Lexgaard. 1839 mußte die sich auf dem Porthaus befindliche Maria Todsen
geholt werden.

Auch für militärische Zwecke wurden Spanndienste ausgeschrieben. Für den Truppentransport von
Apenrade nach Hadersleben mußte Lügum 17 Wagen und 13 Paar Pferde stellen; von Jündewatt nach
Agerschau benötigte das Kg. Leibregiment 75 Pferde und 115 Wagen, von denen Lügum 29 Paar
Pferde und 31 Wagen zu liefern hatte. Der Rücktransport der Truppen aus dem Lager Hellewatt
erforderte am 4.7.1792 14 Paar Pferde und 31 Wagen und am 5.7.1792 5 Paar Pferde und 27 Wagen.
Im ganzen hat Lügum in dem Jahre 1876 Königs- und 10 Amtsfuhren ausführen müssen.

In Jahren kriegerischer Verwicklungen steigerten sich die Bedürfnisse. Dies galt besonders für die Zeit
der napoleonischen Kriege.

=== 15.5. Dienstleistungen z.7t. der Napoleonischen Kriege
Schon 1801 mußten Fuhren für das Hauptquartier vor Hamburg geleistet werden. Das Jahr 1808
verzeichnet für die Tondernharde, Schluxharde und Karrharde 2.300 Fuhren, besonders Reserve- und
einige wenige Fouragefuhren. Diese erstreckten sich über 3, vereinzelt 4 1/2 Meilen. Dabei war genau
bestimmt, daß ein Bauernwagen in den Herzogtümern 50 Liespfund = 700 Pfund Heu oder Stroh laden
mußte, ein Gespann von zwei Pferden mußte 7 Tonnen Hafer oder 7 Tonnen Gerste laden. Da
Löhnung, Brot und Fourage an jedem fünften Tag ausgegeben wurden, war in diesem Jahr wie auch
im folgenden fast kein Tag ohne Fuhrdienst. Tondern fuhr 1808 reichlich 35.647 Meilen.
Während Prediger, Küster und Kirchspielsvogt von den Amtsfuhren befreit waren, wurden sie zu den
Militärfuhren herangezogen. Oft führte die Pflicht weit über die Hardesgrenzen hinaus. So mußte
Tondern 1814 für das Belagerungskorps vor Hamburg 15 vierspännige, weitspurige Wagen mit
Fuhrleuten stellen, die sich, mit Fourage versehen, in Pinneberg melden mußten. Die Vergütung betrug
l.- Rthl je 24 Stunden für 2 Pferde.

Die an der Landstraße liegenden Dörfer hatten die größte Last zu tragen. Zu den Estafetten (Stafetten = 
reitende Eilboten), die sie zu stellen hatten, kamen Fuhren, Wegweiserdienste, Halten von
Reservepferden für Vorspann, Einquartierung feindlicher Truppen und Requisitionen. Die
Einquartierungskosten waren auf 64 bß (Reichsbankschilling) für den Mann und Tag festgesetzt. Alles,
auch das Beschlagen der Pferde, die Lieferung von Lanzen und die Zehrkosten in den Krügen an der
Landstraße, sollten natürlich bezahlt werden, wenn eine Quittung vorlag. Nur zu oft aber kamen
Übergriffe der Truppen vor, die nie gesühnt wurden. So hatten die Schweden in Felstedt nach
Friedenschluß noch vier Pferde mitgehen heißen, die nie bezahlt worden sind.
Der Kirchspielsvogt Gottfried Wilde in Lügum stellt 1814 folgende Rechnung auf:

```
81 Rthl 6 ß  für Estafetten (reitende Boten)
22 "         für Vorspannpferde, Fuhren und Wegeweisung
18 "         für Requisitionen (Beschlagnahmen)
 8 "   51 ß  für Einquartierung.
```

Zu den umfangreichen Fuhrdiensten kamen dann noch große Requisitionen an Korn und Fourage. So
mußte das Amt Tondern im November 1812 an das Magazin in Schleswig 358 Tonnen Hafer liefern,
und zwar acht Tage nach Ansage. Von den 200 Tonnen Hafer, 15.000 Pfd. Heu und 15.000 Pfd. Stroh,
die im Mai 1813 nach Rendsburg verlangt wurden, mußte die erste Rate (23 Tonnen 6 Schip Hafer und
je 2.300 Pfd. Heu und Stroh) schon nach drei Tagen am Ort sein. Auch Lügum hatte daran seinen
Anteil. Jede solcher Auflage brachte die Bohlsleute in Schwierigkeiten. Waren schon die Fristen bei
den langen Wegen von 18 - 20 Meilen kaum innezuhalten, so war besonders das Aufbringen dieser
Mengen an sich recht schwer. Und es war kein Trost, daß man auch in Geld zahlen konnte, waren doch
die Ablösungssätze so hoch gesetzt, daß diese Art der Abgebung einen großen Verlust für die Bauern
bedeutete. Dazu war auch die verlangte Silbermünze in jener Zeit, wo das Land vor dem Konkurs stand,
sehr knapp und teuer. Da auch die Ernte gut gewesen, war es immer vorteilhafter, in natura zu liefern.
Da aber nicht jeder die verlangte Menge vorrätig hatte, schalteten sich dabei die Kornhändler ein. Um
sich nicht der Gefahr der Strafe bei Nichtlieferung oder verspäteter Anfuhr auszusetzen, mußten sie nun
zu den niedrigen Preisen, die die Händler in Ausnutzung ihrer Lage boten, verkaufen. So konnten sie
mit Recht klagen, daß sie _"durch eine unverschämte Abhandlung der ersten und besten Korn- und
Fouragejuden ein Opfer der willkürlichen Behandlung worden"_ . Sie hatten immer Verluste, welche Art
der Ablieferung sie auch wählen mochten. Die Folge mußte eine zunehmende Verarmung sein. _"Der
Krieg hat inzwischen alle gleich gemacht. Bis dahin hat der Wohlhabende die armen Mitbrüder bis aufs
bloße unterstützt, nun hört Hilfe und Beystand bei der größten Klasse der Unterthanen auf. Auf einen
Bauern kommen zehn Arme."_
Schon sehr früh ist nachweisbar, daß die Bauern nicht nur in Kriegszeiten, sondern überhaupt in
Pflichtfuhren, d. h. in Dienstleistungen, für die es keine Sondervergütung gab, weidlich ausgenutzt
worden sind. Jeder kleine Beamte nahm für sich das Recht in Anspruch, Fuhrdienste verlangen zu
können. Eine Verordnung des Herzoges Friedrich aus dem Jahre 1699 stellt fest, daß die Bauern
dermaßen in Anspruch genommen werden, daß die Feldarbeit darunter leidet und sie unfähig werden,
ihre jährlichen Abgaben zu entrichten. Er droht, die Übeltäter ins Gefängnis zu werfen, _"wo sie acht
Tage lang mit Wasser und Brodt gespeiset werden"_ sollen.
In jener Zeit wurden die Dienstleistungen noch nicht nach der Größe des Besitzes verteilt. Sie trafen
deshalb den kleinen Landmann besonders hart, wie folgende Eingabe aus dem Jahre 1610 zeigt:

[quote]
____
"Durchlauchtigster, Hochgeb. Fürst., Gnädiger Herr,
schuldige und Pflichtwillige Dienste können wir armen Leute und getreue Unterthanen, die
kleine Boelßsmänner Inn dem Carspiell zu Lügum und Huntorf, des Ambtes Tundern, In
Unterthänigkeit unberichtet nicht lassen, obwoll viele unter unß nicht mehr alß ein halb, ja auch
mehrentheilß kaum ein Drittel, Viertel und Fünftel Part Boell Landes und woll darunter, an
Wisch und Acker Ländereien, Zu unßerer gebrauchung haben, und die andern Nachbarn, ein
Jeglicher ein gantz Boell dagegen gebrauchen, daß demnach wir Armen Leute die Wagenfuhren
und Hofdienste zu E.f.g.Hauß Tundern, ohne einige Unterschiede in communi consortie,
nebenst den vollenboelß leuten zugleich verrichten müsssen,
Wann nuhn E. F. und Herr, wir Armen Unterhanen, Inn den abgeregten beiden Carspeln
Zunegest beim Hauße Tundern wohne, und derretwegen, zur notturft bißweilen mehr, alß
andere so weiter davon sein abgelegen, mitt den Wagenfuhren und Hofdiensten werden
beschweret, Auch mitt solcher Ungleichmeßigkeit, wo hirin keine Verenderung geschieht, Zum
unabwindlichen Schaden dadurch kommen werden,

AIß bitten E. F. G. wir armen Unterthanen hierauf unterthäniglich, ex officie und
Landesfürstlicher Obrigkeit, lauter umb Gotteswillen dieselbe ander hohe betrencknuß, auß
angeborener Fürst! Rechstmäßigkeit Inn gnaden geruhen, und die gnädige Versehnung darein
zu thun, damit wir armen Leute der kleinen Boellßmenner Inn vorgemelten Carspeln, nach
diesen Tagen mit diesen Schweren plagen gelindert, und ein Jeder nach Land-Zahll der Bohle
an Wisch und Acker-Ländereien zu dem Fl.Hauße Tundern leisten, und Alß der eine nicht mehr
alß der andere nach anzahl seines habendem Landes, hinferner beschweret werden möge, Deß
sind wir armen getreuen Unterthanen umb
E. F. G. mitt Hantt und Blut zu uerdienen bereit und willig.

Dat. den 29. ochtobris 1610
E. F.G.
Unterthänige und gehorsamste
Kleine Boelßleute der Carspell
Lügum und Huntorf,
samb und sonders."
____

Da sich derartige Beschwerden häuften, wurde schließlich jede Ausschreibung nach der Größe des
Landbesitzes angeordnet und damit eine gerechtere Verteilung der Lasten in die Wege geleitet.

=== 15.6.Die Kätnerdienste
Kätnerdienste hatten aber auch ihre Last. Im ersten Abschnitt dieser Arbeit ist schon dies und
jenes aufgeführt. Hier nur einige Ergänzungen. Es waren namentlich die Garten-, Torf- und
Hofarbeiten sowie die Botengänge, die sie unbequem empfanden. 1695 reichen sie folgende
Beschwerde- und Bittschrift ein:

[quote]
____
"Ew. Hovhfürst.Gnaden werden wir armen Käthener des Kirchspiels Lügum, alß
Ew.Hochfürstl.Durchl.gehornsahmste Unterthanen, in aller weh- und demuht klagende Hochlig
veranlaßet, was gestalt wir mit Hofarbeiten, alß da sein 22 Tage Gartenarbeit, in der Schloß
Torf Scheune 3 Tage, so wohl alß mit laufenden Botten, überauß beschweret werden seindt, also
daß es unß fast eines unmüchliches sey, solche Schwehre laßt hinführe auß zu halten, und da
neben Vor unß, unßeres aller gnedigsten Landes-Fürst und Herrn in allen Gerecht zu werden,
zu mahlen, wir das geringste und nicht zu erfreuen haben, alß einen kleine Kohlhof, wo wir unß,
durch den Segen des Aller Höchsten und unserer Hochfürst.Begnadigung ernehren sollen,
unangesehen wir solche große Hofarbeit da von thun müssen, alßo daß es zu befürchten sey,
das wir dadurch zuletzt gar ruinirt und an den Bettelstab gerahten werden.

Solches von Ew. Hochfürstl. Gnaden, In dehmütsten Fuß Fall, lauter und Gottes
Barmherzigkeit, gnedigst abzuwenden thun wir Dehreselben aller unterthänigst- und Bittl.
ersuchen auß Landt Veterl. Milde, und auß gnade und barmherzigkeit, unß von solcher un-
müglicher Beschwerde, ein mahl vor alle Mahle, gnedtigst absolviren wollen, alßo daß wir doch
mit unßern kleinen Kindern von solchen Elendt Mögen befreyet werden, welches wir unß von
Ew.Hochfürst. zu versichtlich getrösten werden, die wir ersterben

Euer Hochfürst. Durchl.
Unterthänigste Dieners des Kirchspiels Lügum.”
____

Darunter amtlich die Bemerkung:
Die 26 Kätner des Kirchspiels Lügum, die Dienste thun an Garten, Hof und Torfscheune, ohne die
Laufreisen: 25 Tage a 3 ß, oder wenn sie accordiren 4.- Rthl 2 ß jährlich.
Seit 1696 sind dann tatsächlich viele Hofdienste abgeschafft worden: Backen, Brauen,
Häckselschneiden, Wasserpumpen, das Reinigen des Schloßplatzes, das Mähen der Wiesen, das
Heubergen, das Holen von Heide zum Streuen der Pferde, Dienste, die hauptsächlich von Kätnern der
Tondernharde verrichtet wären. Unsere Kätner aber mußten weiter die Torfscheune reparieren und
zusammen mit den Klixbüllern und denen von Buhrkall den Torf aufsetzen, wovon die Klixbüller sich
allerdings bald durch ein Ablösungsgeld von 3.- Rthl befreit haben. Für Lügum blieb auch das
Botenlaufen. Da es damals noch keine Post in unserem Sinne gab, mußten die amtlichen Schreiben von
Tondern aus in die Harden durch Boten überbracht werden. Vom Amtshause aus wurde ein Bote mit
einer Anzahl Briefe an die Kirchspielsvögte in bestimmten Gemeinden auf den Weg geschickt. Er ging

nach Seth, wo der Kirchspielsvogt den für ihn bestimmten Brief entnahm und einen Boten mit dem Rest
nach Lügum schickte. Von hier aus wurden dann Humptrup, Braderup, Klixbüll oder Leck versorgt.
Es scheint, daß die Pflicht des Botengehens ursprünglich auch den Bohlsleuten oblegen hatte, sie es
aber im Laufe der Zeit verstanden hatten, sie auf die Kätner abzuwälzen. Das dürfen wir aus einer
Notiz, das Kirchspiel Leck betreffend, schließen. Dort waren die Almer-Kätner, d. h. die Kätner, die
nur ihre Kate und keine eigene Gräsung für ihre Kuh hatten, bis zur Feldaufteilung frei gewesen.
Nachdem sie dann etwas Land erhalten hatten, auch nach dem Hebungsregister zum Reichstaler
kontribuierten (beisteuerten), wenn auch nur 1 ß, war der Grund ihrer bisherigen Befreiung entfallen
und auch sie mußten das Botenlaufen mit übernehmen. Danach hatten also gerade die Landbesitzer
diese Pflicht.
Aber auch dort, wo die Kätner an ihre Stelle getreten waren, wie bei uns, bestand unter ihnen selbst
wieder eine große Ungleichheit, indem nicht alle dienstpflichtig waren. Erst 1737 erhielten sie auf
wiederholte Beschwerden folgende Antwort:

[quote]
____
"Nachdem bey uns die sogenannten Königl. Köthener zu Lügum in Karrharde, Amts Tundern,
mittels des angeschlossenen Memorials angezeiget, was maßen in der Lügum Gemeine mehr
denn 100 Köthener wohnhaft weren, daran ein großer Theil, welche auf der Bohls-Leute
Grunde wohnen, vom Laufen und Fortbringen der Obrigkeitlichen Ordres und Briefe, sich frey
zu machen gesuchet, dergestalt daß von 100 Köthener nur 26 die Last allein trügen, da sie doch
alle gleiche Benificie genossen, folglich auch in denen prästationen gleich gehalten seyn
müßten, mit beigefügter Bitte. daß wegen des Botenlaufens unter ihnen eine egalite getroffen
werden mögte, daß alle Köthener in Lügum, welche außer Kahte kein Land besitzen, wovon ins
Register contribuirt und Pflicht erleget wird, die Last des Bothen-Laufens egalement tragen
müssen;
weil der Ort so nahe dem Amtshause belegen und die passage das durch nach vielen Orten, als
nach den insuln, nach dem Cooge, nach gantz Karr- und Bökingharde geht....."
____

Danach blieb das Botenlaufen zwar bestehen, wurde aber auf breitere Schultern gelegt.

=== 15.7. Die Zeit der Erhebungskriege
Die Zeit der Erhebungskriege bringt wieder eine Hochflut von zu leistenden Fuhren für die bäuerliche
Bevölkerung. Im allgemeinen gab die Provinzial-Regierung in Kiel die Anordnungen heraus, doch kam
es oft genug vor, daß auch Freischaren Wagen usw. beschlagnahmten und auch ihnen gegenüber wagte
man sich nicht zu sträuben. Um immer Beförderungsmittel zur Verfügung zu haben, wurden drei
Fuhrparks eingerichtet. Wir gehörten mit dem ganzen Amt Tondern zum Fuhrpark,
zwei in Flensburg. Es wurden sofort 400 Wagen bereitgestellt, von denen Tondern 100 zweispännige
Wagen für Personen und Effekten und 20 für Fourage bei der Schiffsbrücke zu stellen hatte. Zwei Tage
später, am 17. Mai 1848, wurden weitere 180 plus 20 Wagen und sechs Ordonanzpferde mit Reitern
angefordert. Die Wagen mußten drei Tage dableiben und wurden dann durch andere abgelöst. Lügum
lieferte am 27. Mai 1848 20 Wagen mit drei Stühlen und am 20. Mai 1848 20 weitere Wagen. Die
Verpflegung war für diese Zeit mitzubringen. Für die Zeit des Krieges mußten auch die adelichen Güter
Fuhrdienste leisten.

An vielen Stellen kam dazu noch die Last der Einquartierung. So mußten die 300 Mann des Prinzen
von Noer am 1. Juni in Rapstedt 1 1/2 Tage verpflegt werden. In solchen Fällen konnten oft die Wagen
nach Flensburg nicht gestellt werden, besonders auch, weil zu befürchten stand, daß die Dänen
nachrückten. Da mußten dann die anderen Gemeinden einspringen. Auch Lügum hatte seine
Schwierigkeiten. Ein Schreiben von Volquard Jannsen, im Auftrag der Gemeinde unter-
zeichnet, lautete:

[quote]
____
"Lügum, d. 1. Juni 1848
Laut Ordre von der Hausvogtei zu Tondern haben wir diesen Abend und morgefrüh um 4 Uhr
29 Wagens in Flensburg zu stellen. Da nun bereits 20 Wagen in Flensburg liegen, und die
übrigen Wagen auch gestern mit Magazin aus dem Kirchspiel weg sind, wovon wenige
zurückgekommen sind, so thun wir hierdurch die ergebenste Vorfrage, ob es angehen kann, daß
die Wagen, welche bereiis in Flensburg liegen, aber erst zwei Stunden später ausgedient haben,
für diese Tur beordert werden können oder nicht. Hierüber erbitten wir ihre gefällige Antwort
zurück.

Ergebenst
Vollg. Jannsen
im Auftrag der Gemeine."
____

Am 8. Juni 1848 mußten schon wieder 35 Wagen in Flensburg sein, und zwar für die Zeit vom 9. - 13.
Juni 1848. Erst am 29.Juni 1848 kehrten alle Wagen zurück. Doch dauerte die Ruhe nicht lange.
Anfang August ist das Amt Hadersleben ganz von Truppen entblößt, wie sich überhaupt in den
Monaten August und September die ganze Heeresmacht nach dem Süden bewegte, wozu besonders
viele Fuhrwerke nötig wurden. Lügum hat so in der Zeit vom 24.3.1848 - 31.10.1848 im ganzen 1.340
Tagesfuhren gestellt, wozu noch 598 Reisetage kamen (1 Tag =
4 Meilen). Zu dieser Leistung der Fuhrparks kamen dann noch 148 Tagesfuhren und fünf Reisetage.
Das Jahr 1849 brachte auch keine Erleichterung. Von den 150 Wagen, die am 3.5.1849 in Hadersleben
sein mußten, waren drei aus Lügum, von den 100 Wagen für die Exerzierkoppel in Flensburg ebenfalls
drei (20.4.), von den 50 Wagen für den Fuhrpark Hadersleben wieder zwei (7.5. - 27.5.1849). Als am
12.7.1849 - die Wagen wurden also dauernd durch andere abgelöst - der Haderslebener Fuhrpark auf
125 Wagen reduziert wurde, hatte Lügum dort immer noch drei Wagen. Erst nach und nach konnte von
diesen ein Wagen nach dem anderen entlassen werden.

```
Die Spezialfuhrrolle vom 3.5. - 31.8.1849 enthält an Namen aus unserem Kirchspiel:
Fröde Petersen      2.5. - 25.5      21 Tage
Math. N. Petersen   2.5. - 12.5.      8 "
Johann Jensen       7.5. - 20.5.     13 "
Leve Lorenzen       8.5. - 4.8.      89 "
Jacob Iwersen       9.5. - 17.5.      8 "
Joh. P. Floy        12.5. - 20.5.     8 "
Broder Hansen       15.5. - 5.8.     82 "
Volq. Jannsen       15.5. - 4.8.     81 1/2 Tage
Nic.Paulsen         15.5. - 23.5.     8 Tage
Nic. Paulsen        20.5. - 4.8.     76 "
Joh. Chr. Johannsen 20.5. - 27.5.     7 "
Mathias W. Petersen 20.5. - 5.6.     l6 "
Jac. Willesen       20.5. - 27.5.     7 "
Hans P. Floy        20.5. - 5.6.     16 "
Jacob Iwersen       20.5. - 27.5.     7 "
Fröde Hansen        25.5. - 4.8.     71 1/2 Tage
Jac. Iwersen        21.6. - 6.8.     46 1/2 Tage
Math. W. Petersen   28.7. - 30.7      2 Tage    
Jens Lassen         28.7. - 30.7      2 Tage
                                    569 1/2 Tage
```

Außerdem weist die Kriegsfuhrrolle des Jahres allein für die Monate April und Mai noch 32 Bohlsleute
aus unserem Kirchspiel auf, die zusammen 227 1/2 Tage ein Gespann gestellt haben.
Daneben wurden oft Wagen von Militärpersonen für besondere Transporte gechartert, so in Lügum am
19.3.1849 vom Oberquartiermeisteramt, um Oberjäger Fischer mit Montierungssachen und zwei Jäger
von Tondern nach Leck zu bringen: 21 Meilen = 7 Tage (7 Wagen und 14 Pferde), und am 28.7.1849
Premierleutnant v.Jenninger, 2. Schleswig-Holsteinisches Dragonerregiment, Sattelequipage, kranke
Pferde, Lügum - Leck: 1 1/2 Meilen, 1 Tag, 1 Wagen, zwei Pferde.
Auch für fremdherrliche verbündete Militärpersonen mußte in dem ganzen Bereich oft gefahren
werden. Und fremde Truppen waren hier ja übergenug: das Sächsische 2. Inf. Rgt., das 18. Badensche
Rgt., das 12. Preußische Inf.Rgt., das 19. Preußische Landwehrrgt., das 11. Preußische Husarrgt., das
Hannoversche 3. Inf. Rgt., das Hanoversche Dragonerrgt., 3. Schwadron des Kurhessischen 2. Rgts.,
das Bayrische 13. Rgt., das 5. Bayrische Rgt. und Hanseaten.
Lügum mußte für das 4. Bayrische Inf. Rgt., Major Wigard, von Lügum nach Wallsbüll 7 Wagen und
14 Pferde stellen (1.8.1849), am nächsten Tag für die Rückfahrt mit Montierungsstücken und Munition
4 Wagen und 8 Pferde. Am 19.11.1849 wurde ein Gespann für eine Reise nach Husum benötigt: Lügum
fuhr acht Meilen mit Mitgliedern einer Lazarettkommission eines preußischen Füsilierbataillons. Nach
den gesamten Fuhrrollen dieses Jahres hat Lügum 319 1/2 Fuhren ausführen müssen.
In der ersten Hälfte des Jahres 1850 sind nur wenig Pflichtfuhren gemacht worden. Zwei- oder dreimal
sind die Ordres dänisch geschrieben. Am 2. August 1850 wurden in Flensburg wieder 200 Wagen
gestellt, am 2.8. weitere 200, von denen Lügum 12 liefern mußte. In der Mitte des Monats hatten wir
dort noch immer 6 Wagen stationiert. Sie blieben jeweils fünf Tage. Es wurde den Kirchspielen
empfohlen, Mietsfuhrwerke zu stellen, da dann die lästige Ablösung fortfallen konnte. Diese Wagen
waren _"für die Bedürfnisse der dänischen Armee"_ . Im September 1850 sank ihre Zahl auf 120, am
24.9.1850 auf 73, wovon zwei aus Lügum kamen.
Für Torffahren von Flensburg nach Schleswig am 2. und 3.Oktober stellte Lügum von 200 Wagen
sechs. Im November wurde wieder ein Fuhrpark in Schleswig zusammengestellt, Lüägum mußte drei
Wagen dorthin schicken, die bei einer neuen Verteilung bald auf 14 erhöht wurden. Um die Wagen in
Schleswig zu beaufsichtigen, es handelte sich um 437 Wagen, auch, um sie zu einem planmäßigen
Dienst heranzuziehen, wurde ein Wagenmeister, Markus Lützen aus Leck, _" der auch dänisch sprechen
konnte"_ , angenommen. Die Kosten - er erhielt 7.- Rthl 8 ß täglich - mußten die Kirchspiele tragen. Im
Dezember mußten wir weitere zwei Wagen nach Schleswig liefern. Die Anlieferung wurde aber im
ganzen jetzt etwas lässiger. Von 92 Wagen erschienen zunächst nur 47, von denen auch noch 32
kassiert wurden. Von Lügum fehlte auch einer, der aber wegen Radbruch später eintraf.
Widerspenstigen und Säumigen wurde eine hohe Strafe von 30.- Rthl angedroht.

Auch 1851 mußte Lügum wieder an den Holz- und Torffuhren von Flensburg nach Schleswig mit 12
Wagen teilnehmen. Außerdem waren noch ständig 24 Gespanne im Fuhrpark, die am 1.2.1851 auf 12
ermäßigt wurden. 7 Wagen mußten noch einmal für 14 Tage nach Flensburg, bis um die Mitte des
Februar 1851 die beiden Fuhrparks zu Flensburg und Schleswig aufgelöst wurden und alle Wagen nach
Hause zurückkehrten. Lügum mußte noch 23.- Rthl 5 ß an den Wagenmeister zahlen, womit denn auch
dieses für unsere Bevölkerung so unerfreuliche Kapitel als abgeschlossen gelten konnte.

Auch in ruhigen Zeiten waren die Hof- und Herrendienste usw. durch die Jahrhunderte hindurch als
drückende Last empfunden worden, besonders, da sie nicht genau festgelegt und deshalb oft als
willkürlich und ungerecht angesehen wurden. Mußte man 1705 nicht ständig vier Beiwagen nach Leck
stellen, um 60 Mann _"einquartierter Völker"_ nach Tönning zu befördern? Mußten 1707 nicht plötzlich
39 Bohlsleute 60 Fuder Soden nach Tondern liefern, die _"zur conservierung des Kleinen Fischteiches"_
benötigt wurden? Solche plötzlichen Beorderungen, deren Berechtigung man nicht einsah, brachten die
Sache in Mißkredit. Erst 1867 aber war die Zeit endgültig vorbei. Die heutigen Haus- und
Spanndienste, die sich meistens nur auf Arbeiten innerhalb der Gemeinde beziehen, sind nur ein
schwacher Nachklang jener Tage, die nun bald hundert Jahre hinter uns liegen.
