== 18. Die Freiwillige Feuerwehr

Notzeiten führten die Menschen von jeher zusammen. Unvorhergesehene Ereignisse, Katastrophen,
Seuchen unter Menschen und Tieren forderten immer eine Mehrheit oder die Gesamtheit zur Hilfe auf,
dem Einzelnen, als solchen Gefahren machtlos gegenüberstehend, einen gewissen Schutz zu gewähren.
Das Feuer, eines der größten Wohltäter der Menschheit, wird, unbewacht losgelassen, ihr grimmigster
Feind, der unbarmherzig Mensch und Vieh, Hab und Gut, Wald und Heide vernichtet.

Die früher noch mehr geschlossenen Siedlungen unserer Dörfer und die Verwendung von
Baumaterialien, die dem Feuer leicht zum Opfer fielen (Holz, Stroh, Heide, Reth), stellten immer eine
große Gefahrenquelle dar. Das bezeugen die zahlreichen Brände, von denen unser Kirchspiel in den
letzten Jahrhunderten heimgesucht worden ist (man vergleiche die Angaben in der Haus- und
Hofchronik!). Es mag in früheren Zeiten schon eine Selbstverständlichkeit gewesen sein, daß die ganze
Nachbarschaft, d. h. die ganze Dorfschaft Hilfe leistete. Als aber der Wassereimer nicht mehr genügte,
sondern besondere Geräte und Einrichtungen zur Bekämpfung des Feuers als notwendig erachtet
wurden und zur Verfügung standen, als die Erfahrung lehrte, daß nur besonders qualifizierte Leute eine
wirksame Bekämpfung garantieren konnten, daß Umsicht und Ruhe, Mut und Entschlossenheit,
unterbaut durch Belehrung und Training, Veraussetzungen sein mußten, und als endlich behördliche
Empfehlung und Forderung, später auch Anordnung und Gesetz einem gewissen Personenkreis die
Pflicht der Brandbekämpfung auferlegte, entstanden überall die Brandwehren.

Unbeschadet dieser Verpflichtung entwickelten sich überall aus diesen Wehren, und neben ihnen, die
Freiwilligen Feuerwehren. Wünsche und Bestrebungen in dieser Richtung nahmen hier erstmalig im
Jahre 1886 festere Formen an. Nachdem eine neue Handdruckspritze angeschafft worden war, beschloß
eine Anzahl Feuerwehrmänner nach einer Brandübung am 12. Dezember 1886, eine Freiwillige Wehr
zu gründen. Das Gründungsprotokoll verzeichnet 17 Unterschriften: J. P. Winter,

+++C+++. Hansen, Paul Fr. Wilde, M. N. Burgwald, Jacob Nissen, A. Fr. Johannsen, Nath. Jürgensen, Nicolai
Peter Jessen, August Jessen, Hans P. Hartwigsen, Andreas Angel, Jens W. Hansen jun., Ole Heinrich
Boysen, Andreas Chr. Wollesen, Jacob Anton Nielsen, H. J. Jensen und E. J. Koch. Jacob Winter
übernahm den vorläufigen Vorsitz. Schon am 2. Januar 1887 wurde ein Reglement aufgestellt und
angenommen. Es enthielt Bestimmungen über Zweck, Vorstand, Stellung zu Behörden, Aufnahme und
Austritt, Pflichten, Passive Mitglieder, Chargierte, Wahl des Vorstandes, Uniform, Übungen, Dienst
bei Feuer, Verhalten während des Brandes, Verhalten nach dem Brande, Spritzenmeister, Strafen,
Ehrengericht, Prüfung der Geräte, Kasse, Auflösung und Statutenänderung. Jacob Winter wurde zum
Hauptmann, Christian Wollesen zum Spritzenmeister und A. Fr. Johannsen zum Rechnungsführer
gewählt.

Für die nächsten vier Jahre sind leider keine Aufzeichnungen über die Wehr vorhanden. Ob die
Beteiligung nicht genügend gewesen, ob die erste Gründung nur ein Scheinmanöver oder ob besondere
Gründe für ihre Untätigkeit und ihr "Nicht-in-Erscheinung" treten maßgebend waren, wir wissen es
nicht. Merkwürdig bleibt die Tatsache, daß man 1891 einen neuen Gründungsbeschluß faßte. Der Start
war diesmal glücklicher: 27 aktive und 23 passive Mitglieder sind verzeichnet. Die Zahl der Aktiven
hat seitdem zwischen 23 (1926) und 41 (1938) geschwankt, da Austritte und Abgänge immer durch
Einmeldungen wieder ausgeglichen werden konnten. Auch fanden sich stets genügend Einwohner, die
ohne aktiv sein zu wollen oder zu können, die Wehr durch einen jährlichen Geldbetrag, zuerst 3.- Mk,
später 5.- Mk unterstützten.

Als Brandmeister fungierten Andreas Unglaube von 1892 - 1903, Hans Matzen von 1903 - 1905,
Thomas Volquardsen von 1905 - 1912, Sönnich Winter von 1912 - 1924, Andreas Peter Petersen von
1924 - 1928, Sönnich Winter von 1928 - 1934 und Peter Holt von 1934 - 1945.

Die Wehr wurde 1924 mit den anderen Wehren des Amtsbezirks zusammengeschlossen. Peter Jacobsen
übernahm den Halblöschzug. Er wurde 1937 von Andreas Matzen abgelöst.

In den Jahren von 1893 - 1938 ist die Freiwillige Feuerwehr 51 mal für Ernstfälle alarmiert worden,
davon 31 mal nach außerhalb des Dorfes. Mehrmals hat sie durch ihr schnelles und mutiges Eingreifen
Hab und Gut retten können, welches ihr dann durch Anerkennungs-schreiben und Prämien der
Landesbrandkasse quittiert worden ist. Oftmals war auch eine Rettung der Gebäude wegen zu spät
gegebenen Alarms oder wegen schlechter Wege, Wetter- und Windverhältnisse nicht möglich, so daß
man sich damit begnügen mußte, ein Überspringen des Feuers auf Nachbarbesitze zu verhindern.
Am meisten gefürchtet war stets der Wassermangel, der in niederschlagsarmen Jahren und trockenen
Sommers eine wirksame Bekämpfung eines Feuers unmöglich machen konnte. Zwar hatte jedes Dorf
seine Brandkuhlen, und Süderlügum hatte deren sogar sechs:

1. den Dorfteich westlich von Peter Holt,
2. eine Kuhle nördlich von Johann Tüchsen,
3. eine Kuhle westlich des Denkmals in Julius Jensens Toft,
4. eine an der Süderstraße,
5. eine südöstlich von Julius Jensens Haus und
6. eine in der Westerstraße in Broder Jensens Toft.

Davon ist Nr. 2 nicht mehr vorhanden und 1942 durch einen gebohrten Brunnen ersetzt worden. Nr.
3 ist ebenfalls zugeschüttet und durch einen gemauerten Brunnen von 3 m Weite ersetzt. Dasselbe gilt
für Nr. 5, die alte Färberkuhle. Außerdem ist bei der Spar- und Darlehnskasse und bei Helene Bossens
Haus (Nr. 35) 1942 je ein Brunnen gebohrt worden. Auch steht die Wasserkuhle in Christian M.
Petersens (Nr. 71, 69) Garten zur Verfügung. So läßt sich feststellen, daß die Wasserversorgung in den
letzten Jahrzehnten bedeutend verbessert worden ist.
Das 1899 erbaute Spritzenhaus enthält in einem besonderen Raum ein Arrestlokal, wofür das Amt
alljährlich eine kleine Pacht an die Gemeinde Süderlügum zahlen muß. Dem Kirchspiel lag und liegt
auch die Ausrüstung der Wehr mit Spritze, Geräten, Uniformen usw. ob. Für die Uniform haben die
Männer auch selbst ihren Teil beitragen müssen. 1940 wurde eine kleine Motorspritze in Niebüll
gekauft, die 1943 durch eine 800 1-Spritze ersetzt wurde.
Der Ausbruch des Krieges 1939 wirkte sich sehr ungünstig auf die Wehr aus. Da die Mannschaft
größtenteils eingezogen wurde, mußte man auf ältere Männer (50- - 65jährige) und jüngste Jahrgänge
(1926/1927) zurückgreifen. Andreas Matzen wurde durch Andreas Edlefsen, der zum komm.
Brandmeister ernannt wurde, ersetzt. Als auch er 1940 eingezogen wurde, übernahm Sönnich Winter
wieder die Führung. Für die meisten Wehren kamen nun schwere Jahre, wurden sie doch in den
Bombennächten in Kiel und Hamburg eingesetzt. Unsere Wehr hat daran nicht teilgenommen.
Nach 1938 sind keine Ernsteinsätze zu verzeichnen gewesen. Aber der Krieg hat drei Opfer gefordert.
Es sind:

```
Georg Petersen, Wimmersbüll,
Christian Winter, Süderlügum und
Christian Andresen, Wimmersbüll.
```

Nachdem die meisten Mitglieder nach und nach aus dem Felde zurückkehrten, wurden die Arbeiten der
Wehr Anfang 1947 unter Leitung von Andreas Edlefsen traditionsgemäß wieder aufgenommen.
Seitdem feiert man auch alljährlich wieder das Winterfest, das in seiner Ausgestaltung und der
Beteiligung der Bevölkerung immer ein schönes Zeichen der Verbundenheit des Kirchspiels mit seiner
Freiwilligen Feuerwehr gewesen und noch ist. Auf dem Winterfest 1948 wurde vom Chronisten
folgende "Tafelrede" gehalten, die auszugsweise hier wiedergegeben werden soll, weil sie etwas von
der Wertschätzung spüren läßt, die die Feuerwehr genießt, und zugleich als Zeitspiegel der Kriegs- und
Nachkriegsjahre gewertet werden kann.

```
Als wir 1947 dieses Fest gestartet,
Haben von dem neuen Jahr wir allerlei erwartet.
Nun, nicht alle Wünsche sind erfüllt,
Nicht jede Sehnsucht ist gestillt,
Manches blieb, wie immer,
Manches wurde gar noch schlimmer;
Nur selten ist am Himmelsbogen
Ein Silberstreifen aufgezogen.
Doch gehörn hier nur Dinge her,
Die Beziehung haben zur Feuerwehr.

Da ist zunächst wieder das Zündholzproblem.
Es ist so ungelöst, wie ehedem,
Sie sind immer noch knapp
Und brechen oft ab
Und wollen nicht brennen;
Man sollt’ sie nicht Zünd-, sondern nur noch
Streichhölzer nennen,
Denn streichen muß man in jedem Falle,
Aber Zünden tun längst nicht alle.
Auch kann man nicht reden von all zu Vielen,
Es sind immer noch keine übrig für die Kinder zum Spielen,
Na, dem sei nun, wie immer ihm sei!
Vielleicht ist sogar ein Vorteil dabei:
Keine Hölzer in Kinderhand,
Durch Kinderhand kein Brand,
Das ist auch schon allerhand.

Viel schlimmer steht es mit den Kalorien,
Die sind ja überall verschrien.
(Ich rede hier nur von den weißen!)
Sie meinen, die dürfte man hier nicht herbemühn?
Doch! Kalorie soll doch Wärmeeinheit heißen,
Kalorien, Wärme und Feuer gehören zusammen,
Da sie aus einer Familie stammen, .
Vielleicht heißt es aber Kalorie,
So wie der Kaffeersatz, die Zichorie.
Ach, es sind soviele Fremde im deutschen Haus,
man kennt sich bald selber nicht mehr darin aus.
Vor Jahren wollte man uns mit Vitaminen,
Vorne und hinten und seitlich bedienen.
Jetzt spricht man nur selten von ihnen.
So wird es auch mit den Kalorien ergehen:
Haben wir erst wieder gehörig zu essen,
Haben wir den Schwindel auch bald vergessen,
Dann ist es um sie geschehn.
Bis dahin haben wir allerdings keine Wahl,
Sie bilden ja eine besondere Rasse
Sind nicht gefährlich durch ihre Masse,
Sondern durch eine zu kleine Zahl,
Wer nämlich zu wenig von ihnen verzehrt,
Bezeichnet man bald als unterernährt.
Doch - man soll nicht zulange an den Dingen kleben,
Ich will ja nur ein paar Streiflichter geben.

Streiflichter, ja- da denk ich mit einem Male
An unsere gute Überlandzentrale.
Da ist, das wird ein jeder eingestehn,
Nun wirklich ein großer Fortschritt geschehn.
Im vorigen Winter rief alles:" Mehr Licht!"
Wie Goethe auf seinem Sterbebette,
Aber Erwin hörte und erhörte uns nicht.
"Ach, wenn man doch reichlich Kerzen hätte!"
Ich sehe nächst bei der Post Jürgen Kruse und Henry Hansen
Hoch im Gebälk und an der Decke tanzen,
Um ihre Notbeleuchtung einzuschalten.
Ja, das waren höhere Gewalten.
Das hat sich nun alles gewaltig gebessert.
Doch wird uns die Freude etwas verwässert,
Das ganze hat doch noch ein Leck;
Gibt es doch keine Birne noch!
Nun bitt' ich - es kann doch nicht alles auf einmal kommen,
Was kann uns das ewige Jammern frommen?
Es nimmt alles eben seine Zeit,
Noch ein paar Jahre, dann ist auch das soweit,
Vielleicht schon früher: Weihnachten wurden
1 1/2 Pfund Äpfel ausgegeben,
Und man wettet wohl kaum daneben:
Dieses Jahr können wir sicher Birnen erwarten,
(Natürlich auf den Obst- und Gemüsekarten).

Aber ein anderes ist noch sehr wichtig!
Die Leitung ist in Ordnung und richtig.
-Ich werde hier doch nicht mißverstanden?
Ich spreche nicht von jeder Ableitung in deutschen Landen.
Ich meine hier die Lichtleitung,
Und es hat seine große Bedeutung,
Auch für die Feuerwehr;
Es gibt nun keinen Kurzschluß mehr
Und die Kurzschlußbrände
haben für immer ein Ende.
Das ist nicht nur so bei uns allein,
Es muß im ganzen schon so sein,
Prüfen Sie nur ihr Tageblatt,
Was da so drin gestanden hat,
Sehn Sie nach unter bu oder be oder ba,
Sie finden nicht einen einzigen Kurzschluß da.

Ja, ziemlich spärlich ist's mit dem Brennen.
Man kann da noch andere Gründe für nennen,
Sagt' mir doch einer: "Warum es nicht brennt?"
Es gibt doch keinen Stein, kein Holz, keinen Zement!"
Es war im Sommer, als ich dem begegnet,
Es hatte damals noch nicht geregnet,
Er hatte die Hitze nicht gut vertragen,
Sie war ihm aufs Gehirn geschlagen.
Nach ihm ja jeder Brand vorsätzlich sei,
Eine große Brandstifterschurkerei.
Nein, was solle dann noch werden auf Erden,
Wenn alle Ausnahmen Regeln werden?

Aber die Tatsache ist nicht zu leugnen:
Es will sich im Punkte Feuer nicht recht was ereignen.
Und was sagt unsere Feuerwehr dazu?
Macht sie für ein paar Jahre die Bude zu?
Schreibt "Große Ferien!" ans Spritzenhaus,
(Nur das Winterfest fällt nicht aus!)
Nein, das tut die Feuerwehr nicht,
Sie tut weiter ihre Pflicht,
Sie übt und übt und exerziert;
Was schadhaft ist, wird repariert,
Sie probt an Schläuchen, an der Spritze,
Tritt an ın Kälte und in Hitze,
Klettert an Sprossen und Leiter
und so weiter und so weiter.
Denn bei ihr heißt es allezeit:
Immer für den Ernstfall bereit!
Sie betrachtet es, das Feuer,

Als ein schlafendes Ungeheuer;
Doch ist die Ruhe nur von kurzer Dauer,
Es liegt beständig auf der Lauer
Und wartet und späht und späht,
Bis sich ihm eine Gelegenheit bietet,
Wehe, wer die heilige Flamme nicht hütet!
Daß es zum Angriff übergeht.
Einst kommt der Tag, vielleicht ist es auch Recht,
Wenn es plötzlich erwacht.
Schon hört man der Sirenen schrillen Ton,
Da ist auch das Feuerhorn schon,
Die Männer fallen aus den Betten,
In die Kleider in wenigen Minuten,
Aus dem Haus,
In die Nacht hinaus,
Man muß sich sputen,
Gilt es doch, Leben und Habe zu retten.

Ich brauche das nicht weiter zu schildern,
Wir sind alle vertraut mit den Bildern.

Damit beschließ ich meine Reimerei,
Das übrige muß ich bis zum nächsten Fest vertagen.
Wohl war dabei ein wenig Schelmerei,
Doch ganz im Ernste kann ich sagen:
Alles ist erdacht und gesprochen zur Ehr'
Unserer Freiwilligen Feuerwehr.
```