== 21. Für Struxbüll seien an dieser Stelle noch zwei Bemerkungen hinzugefügt.
=== 1. Die Besiedlung im Mittelalter 
Nach dem Erdbuch von 1613 war Struxbüll dichter besiedelt als heute. Es wohnten dort:

1. Nis Schmidt. Er hatte ein halbes Bundengut, säte 1/4 Demat Sommersaat, hatte 41 1/2 Demat Land im Alten Koog;
2. Richert Richertsen. Er hatte ein ganzes Bundengut, 10 Demat Geestland und 80 Demat Marschland im Alten Koog;
3. Johann Andersen. Er hatter 35 Demat Marschland im Alten Koog;
4. Hans Rotberch. Er hatte 21 1/2 Demat Marschland im Alten Koog.
5. Janke Tortzen. Er hatte 17 1/2 Demat Marschland im Alten Koog.

Die Klixbüller Nis Christens und Konsorten hatten 20 Demat Marschland im Alten Koog, aber kein
Haus oder Staven. Außerdem war bei einer Stelle noch eine Bundenkate. Der Kätner Carsten Saße
hatte vier Demat Land im Alten Koog./ _" Hierbei ist zu wissen, daß diese Dorfes Leute keine Gräsung an Geestland zu ihren Beesten haben. Besonders müssen dieselbigen auf Ihr Marschlandt so vorhere einem jeden Dhemathzhall zugeschrieben, aufverziehen und weiden."_

Da man wegen der Überschwemmungsgefahr nur auf Hügeln und Warften bauen konnte, ist
anzunehmen, daß auch der südliche Hügel, der früher höher gewesen ist, eine Wohnung getragen hat,
da Derselbe nicht durchweg aus Sand besteht, sondern mit Kleierde vermischt ist, hat hier
wahrscheinlich eine künstliche Erhöhung stattgefunden. Tatsächlich sind bei Pflügen und Abgrabungen
Steine und Eisenteile als Reste der alten Siedlung gefunden wurden. Anzunehmen ist, daß Nis Schmidt
hier wohnte, trägt doch noch heute die Gemarkung den Namen Schmidts Mark.

Nach dem Erdbuch von 1696 sind nur die Nr. B I und Nr. B 2 und Karsten Nissen, Nis Schmidts Sohn,
hier urkundlich nachzuweisen.

Bei dem Bau des Hauses Nr. B 9 stieß man auf Grundmauern, sowohl da, wo das neue Haus steht, als
auch im Garten. Nach der Mächtig- keit und dem Umfang ist zu urteilen, daß hier einmal ein größerer
Besitz gelegen hat. Leider ist nur eine Nachricht darüber auf uns gekommen:

Auf ihrem _"Guth Struxbüll"_ starb 1666 die alte Dorothea Blome-Reinecken. Bei ihr wohnte ihr
Schwiegersohn Peter de Lange. Ihr Sohn, der Obristenleutenant Dietrich Reinecken, lebte zu Waake
im Lande Braunschweig ._"Sie hat einige geringfügige Möbelgüter und sonstlich auch einige Landtgüter allhie hinterlassen. Da aber dieselben wegen der darauf haftenden großen Teichslasten, sambt Schatzung und Kriegsbeschwerden und sonstig ziehmlich verschuldet und gravieret sint"_, hat
der Schwager den Sohn zur Beerdigung und zur Nachlaßregelung eingeladen. Aber er ist nicht
gekommen, hat auch kein Geld geschickt, so daß von Lange _"zinsbare Gelder"_ hat aufnemen müssen.
Erst 1668 lüftete Dietrich Reinecken den Schleier: der Grund seines Ausbleibens ist nicht nur sein
hohes Alter gewesen, sondern ihn haben die Schulden des Hofes abgeschreckt. Er war schon etwas
orientiert darüber, hatte er doch vor fünf Jahren den Schwager und seine Mutter auf sechs Wochen
besucht. _"Bei meiner Abreise fragte ich den Schwager, wie es mit dem Gut Struxbüll stehe? Er sagte, er habe viel davon zu fordern. Woher denn das käme” Darauf holte er Briefe durcheinander aus einem Kasten und zeigte mir eine Calculation, daß er vor das Guht Struxbüll Sechs Tausend Mk Lübsch ausgeleget und vorgeschossen hätte. Darauf habe ich ihm 2.000.- Mk versprochen und Kontrakt gemacht."_ In den vergangenen fünf Jahren seitdem scheint es nicht besser geworden zu sein. Zudem
hat er seiner Meinung nach dem verschuldeten Gut gegenüber keinerlei Verpflichtung. Hat er doch
schon mit acht Jahren das Elterhaus verlassen und ist mit seinem Bruder zusammen zu dem Großvater,
dem Propsten in Preetz, gekommen, und 1620 oder 1621 ist er mit zwei Pferden und einem Knecht
nach Böhmen in den Krieg gezogen, ohne daß die Mutter einen Schilling beigesteuert hatte. Der
Schwager dagegen hat sich ins warme Nest gesetzt und mit Frau und Kindern bei der Mutter und von
den Gütern gelebt. Er ist jedenfalls nicht bereit, in die Schulden hineinzusteigen. Da schon im nächsten
Jahr in dem Schriftwechsel, in dem auch der Herzog eingeschaltet wurde, das Wort _"proclama"_
auftaucht und daß _"die Creditoren bestimme müßten"_, ist als sicher anzunehmen, daß das Gut bald
unter den Hammer gekommen ist.

Da bei den Erdarbeiten an dieser Stelle auch sechs oder sieben kleine Tonvasen gefunden wurden, die
teilweise Brandspuren tragen, kann man vermuten, daß ein Feuer die Niederlegung des Bestizes
beschleunigt hat.

Schon 1608 tauchten die ersten Anzeichen für den wirtschaftlichen Verfall des Hofes auf: Daniell
Reinecken wird unter den Steuer-Restanten genannt und ihm gnädigst noch ein Jahr zur Zahlung
eingeräumt. 1694 ist alles gewesen: Die adelige Frau von Maintz _"welche von Sehl. Lieutnant Langes Landt gebraucht, 19 Demat, zahlt jährlich 12.- Rthl in Register"_.

=== *2. "Der Verhängnisvolle Schuß"*

So betitelt Pastor Clausen, Süderlügum, (1882 - 1916) ein kleines Heft, in welchem er erzählt, daß der
hiesige Pastor Andreas Christian Claudius, der hier von 178 7- 1798 amtierte, durch einen
verhängnisvollen Schuß die junge Frau Andersen in Struxbüll tötete. Pastor Claudius war ein gern und
oft gesehener Gast bei Momme Andersen und seiner Frau Cäcilie. (Nr. B 2). Auch für den 18. Juli
1796 hatte er sich anmelden lassen. Da er mit seinen 67 Jahren noch immer ein eifriger Jäger war und
das wasserreiche Struxbüll als Entenparadies immer reiche Beute versprach, nahm er auch an disem
Tage die Flinte mit. Da es etwas später geworden war, ging die Frau Andersen hinaus um zu sehen,
ob er nicht bald käme. Inzwischen hatte Claudius sich dem Hause genähert. Da sah er über dem
Düngerhaufen hinweg die flatternden Haubenbänder der Frau, vermeinte, es sei der Feind aller Jäger,
der Fuchs, legt an und schoß: Frau Andersen war tödlich getroffen. Der Pastor nahm sich die Tat so
zu Herzen, daß er irrsinnig wurde und sein Amt nach 1 1/2 Jahren niederlegen mußte. Er starb am
23.12.1799, vier Tage nach dem Tode seiner Frau, und am 30.12.1799 wurden beide in der Kirche
beigesetzt.

Auch Jonas Brodersen, Uhlenberg, erzäht diese Geschichte in seinen Heften _"Fra gamle Dage"_ (Aus
alten Tagen), wenn auch in verkürzter Form (1912). Und in dieser Form erzählen ältere Leute des
Kirchenspiels sie noch heute und werden sie weiter so erzählen, zumal die Veröffentlichung von Pastor
Claudius sich noch in vielen Häusern befindet.

Die Untersuchungsakten ergeben nun ein wesentlich anderes Bild der Geschehnisse. Tatsache ist, daß
Frau Andersen am 18.7.1796 erschossen wurde, aber nicht durch Pastor Claudius, sondern der Gunder
Jansen, der Großmagd des Hofes. Momme Andersen war währenddessen in Lügum in Geschäften. Die
Täterin wurde noch am Abend ins Porthaus nach Tondern geholt. Am nächsten Morgen erschienen
zwei Ärzte auf dem Hof, um die Leiche zu untersuchen. Demnach wurden durch eine Kommission mit
dem Ehemann und den bei dem unglücklichen Zufall zugegen gewesenen Dienstboten eingehende
Einzelverhöre angestellt.

Momme Andersen sagte aus, "es sei bekannt, daß seine unglücklicher Weise erschossenen Frau Sisse
Andersen schon seit mehreren Jahren nicht mehr den völligen Gebrauch ihres Verstandes gehabt.
Wenn diese daher sich nicht durch Worte habe zurecht sprechen lassen wollen, sey es gewöhnlich
geworden, daß der eine oder andere ihr mit einem nicht geladenen Gewehr gedroht und deshalb
vorgehalten. So habe sich auch gestern Nachmittag das Un-glück zugetragen, indem das schon
eingezogene Mädgen Gunder Jansen in seiner Abwesenheit von den in der Stube befindlich gewesenen
beiden Gewehren das eine geholt.

Übrigens habe Deponent nicht die geringste Ursache zu vermuthen, daß solches in einer andern als
der angegebenen Absicht geschehen, auch glaube er nicht, daß das Mädgen im geringsten argwöhnen
konnte, daß das Gewehr geladen gewesen, indem er selbst nicht einmal solches gewußt und auch
gegenwärtig nicht angeben könne, wo, wann, bei welcher Gelegenheit und wie es geladen gewesen."
"Die erste Veranlassung dazu sei gewesen, daß die Frau nicht hier aus einem Kruß trinken wollen,
sondern in die Cammera reingekommen, wo die Dienstboten beim Essen gesessen und sie daran
hindern wollen..."(Aussage des Dienstknechten Peter Hansen). Das Dienstmädchen ergänzt: "Die
verstorbene sey in die Cammer wo die Dienstleute Butterbrod gegessen gekommen, habe daselbst
einen Topf mit Bier genommen und sich beschwert, daß nicht Bier genug darin sey. Gunder habe
darauf versetzt, daß sie nach dem Gruße hingehen könne, und da sie solches nicht gewollt, sey Gunder
mit der Äußerung weggegangen, daß sie sie es lehren wolle. Sie sey hierauf aus der Küche mit dem
Gewehr gekommen, und habe ihr solches vorgehalten. Die Erschossenen habe den Arm vorhalten
wollen und sie selbst, Deponentin, sich wie sie Rauch gesehen, hinter dem Tisch verborgen. Sobald der
Schuß geschehen, sey die Verstorbenen vom Stuhl gefallen und habe stark geblutet...."

Alle Aussagen stimmen darin überein, daß die Tat nicht beabsichtigt gewesen, sondern nur durch
Verkettungen unglücklicher Umstände geschehen konnte. Gunder Jansen war hinausgelaufen und
konnte eben noch von der Dienstmagd davon zurückgehalten werden, sich ın den Brunnen zu stürtzen.
Momme Andersen bittet unter Verpfändung seiner Güter um die Freilassung der Täterin. Und da es
sich hier um übereinstimmende Zeugenaussagen handelt, bestätigt durch die Unterschrift der
Untersuchungskommission, ist nicht davon zu zweifeln, daß der Tatbestand wahrheitsgemäß wiederge-
geben ist.

Zum Schluß erhebt sich deshalb die Frage, wie die eingangs erwähnten Geschichtenschreiber den
Pastor Claudius als Täter hinstellen konnten. Tatsache ist allerdings, daß nach diesen Ereignissen, "eine
Abnahme seiner Geistes- und Leibeskraft" festzusstellen war. Diese "hinderte ihn so sehr in seiner
Amtspflicht, daß nicht nur seit einiger Zeit die Kranken- und Schulbesuche unterbleiben mußten,
sondern auch zn mehreren Sonntagen keine Predigt gehalten werden". Die Folge war, daß er
frühzeitig, am 31.1.1798, seinen Abschied nehmen mußte. Der Sterbetag ist in den Erzählungen richtig
angegeben. Das Unglück mag sicher einen tiefen Eindruck auf ihn gemacht haben, die Erschütterungen
bei dem großen Brand 1795, der 45 Feuerstellen des Dorfes in Asche legte, mögen noch nachgewirkt
haben, möge es ferner stimmen, daß er ein eifriger Jäger gewesen, alles kann aber nicht rechtfertigen,
ihm den tragischen Unglücksfall auf Struxbüll in die Schuhe, oder richtiger, in die Flinte zu schieben.
Gerüchte, böswillige oder harmlose, haben sich scheinbar durch Ausmalen glaubwürdiger und
möglicher Begleitumstände durch Jahrzehnte, ja, durch ein Jahrhundert, mündlich überliefert, erhalten
und so glaubwürdig verdichtet, daß beide Erzähler darauf hereingefallen sind. Ein Quellenstudium
hätte ihnen das Konzept verdorben.