== 23. Kleinere Beiträge
=== 23.1. Unser Gut Struxbüll
Wer auf einer Reise nach Dänemark die Bundesstraße 5 benutzt, durchfährt im Kreise
Sütondern zuletzt das Kirchspiel Süderlügum. Es umfaßt außer dem Kirchdorf die
Gemeinden Wimmersbüll und Ellhöft.Die Gemeinde Ellhöft zieht sich in reichlich 5
km Länge als schmaler Streifen längs der Grenze hin. Der Westliche Teil zwischen
Bundesstraße und der Bahnlinie nach Tondern führt den Gemarkungsnamen Struxbüll.
Wer sich dem Zollhaus Böglum nähert, gewahrt, nach Westen blickend, einige
besiedelte Warften, die sich deutlich aus der flachen Landschaft des Karrharder Alten
Kooges herausheben.

Die Peterswarf auf Struxbüll, die heute den Hof der Frau Ingeburg Johannsen trägt, Krönte im
Mittelalter ein größerer Hof. Als man 1936 die Fundamente zum Neubau legte, stieß man auf
umfangreiche Reste von Grundmauern, die auf einen größeren Gebäudekomplex schließen ließen. Es
handelte sich um das einstige Gut *Struxbüll*. Dabei darf man dem Wort Gut nicht die Bedeutung des
heutigen Sprachgebrauchs unterlegen, da jeder größere Hof früher als Gut bezeichnet wurde.
Immerhin, in unserm Falle hat es sich tatsächlich um ein über das durchschnittliche Maß hinaus
gehendes Besitztum gehandelt. Im Erdbuch von 1613 hat Richert Richertsen, der Besitzer dieses
_"ganzen Bondengutes"_, 10 Demat Geestland und 80 Demat Marschland im Alten Koog.
Dazu kommt die interessante Tatsache, daß man das Gut Struxbüll für eine Zeitlang als halbadlig
bezeichen kann. Zum Verständnis dieser Bezeichnung müssen wir kurz in die Familiengeschichte des
adligen Geschlechtes von *Blome* hineinleuchten.
Von 1595 bis 1608 war Dietrich Blome Amtmann (Landrat) des Amtes Tondern. Seine Wohnung war
das Haus Nr. 25 in der Westerstraße. Darauf hatte er 1601 das Privileg völliger Freiheit von allen
städtischen Abgaben erhalten. Dieses Vorrecht galt nicht nur für ihn, sondern auch für seine Tochter
Dorothea.

Dietrich Blome war im Jahre 1542 geboren. Als er sieben Jahre alt war, starb sein Vater. Über seine
Kindheit und Studienzeit ist nur wenig bekannt. Um 1570 heiratete er Elisabeth Rantzau. Im
Erbvergleich mit seinen drei Brüdern fiel ihm 1572 das Gut Hornstorf zu. Als Geldgeber verstand er
es, sich den Gottorfer Herzögen (Adolf, gest. 1586 ; Friedrich, gest. 1587; Philipp, gest. 1590),
besonders Johann Adolf, unentbehrlich zu machen, so daß wir ihn 30 Jahre lang als Ratgeber und
Amtmann in herzoglichen Diensten finden. Aus seiner 1. Ehe gingen drei Töchter hervor, aus der 2.
mit der bürgerlichen Margarethe Claren zwei Söhne und drei Töchter, die aber nicht gleichberechtigt
waren. Wir haben hier einen der seltenen Fälle einer Verbindung von Adel und Bürgertum.
Die genannte Dorothea gehörte scheinbar einer 3.Garnitur an. Sie stand damit, obgleich sie den Namen
Blome trug, ziemlich außerhalb der Familie. In dem sonst ausgezeichneten Buch von Otto Hintze
_"Geschichte des adeligen Geschlecht der Herren und Grafen Blome"_ wird sie deshalb gar nicht als
Tochter des Amtmannes erwähnt. Die für die folgenden Ausführungen benutzten Akten beweisen aber,
daß Hintze die Geschichte _"unserer"_ Dorothea, die er zwar erwähnt, aber unrichtig wiedergibt.

Wie Dietrich Blome für die Kinder aus zweiter Ehe durch Hauserwerb in Kiel sorgte, so für Dorothea
in Tondern. Sie heiratete Daniel Reinecke, der von 1592 - 1606 Kornschreiber im Amte war. Nach
seinem Tode ging sie eine 2. Ehe mit dem erwähnten Richert Richertsen auf Struxbüll ein und behielt
seinen Hof auch nach ihrer Scheidung von ihm.

Sie vermehrte durch diesen Besitz ihr großes Erbe nicht unwesentlich. Der Herzog Johann Adolf hatte
ihrem Vater schon 1598 _"in Ansehung der langwierigen getreuen Dienste, welche der liebe Dietrich Blome nun etzliche Jahre here getreulich geleistet hat, auch noch hinführe wohl thun mag und wird, und derenwegen seine Tochter Jungfer Dorothea Blome und ihrem künftigen Ehemann, dem sie sich verheiraten wird, die Festeländereyen, die bis dahin Niels Holdensen und danach seine Witwe Catharina Paulsen gehabt"_ zugesprochen. Es handelte sich um reichlich 36 Demat, auf dem
Tonderschen Felde und in Tondernharde gelegen.

Außerdem besaß sie im Gotteskoog Schlickland, 2 1/2 Störten. Die Störte (Stürrkarre) war damals das
Maß für die geleistete Arbeit und bestimmte auch den Lohn derselben, d.h. die Ländereien wurden den
Leuten ihrer Beteiligung entsprechend als Feste zugeteilt. Da aber Schlickländereien gewöhnlich
größere Ausgaben für Schleusen und Wasserlösungen erforderten ehe sie rentabel wurden, _"fiel ihr die große Ausgabe beschwerlich"_ . Als die rückständigen Steuern 1623 auf 82 Mk. angewachsen waren,
beantragte sie bei dem Herzog einen Tausch. Dazu war es nötig, das Land aufzumessen. Dabei zeigte
sich, daß sie an die 100 Demat besessen, während sie nur 30 verschatzet (versteuert) hatte. Der Herzog
wäre in diesem Falle berechtigt gewesen, die verschwiegene Feste einzuziehen. _"Aber aus besonderer Gnade in Ansehung der langjährigen getreuen Dienste, so Dorothea Reineckens Sehl. Vater dem vorigen herzog geleistet"_, willigte er doch in den Tausch ein.

So erhielt der Herzog (König) die rund 100 Demat Schlickländer-eien im Gotteskoog. Sie tragen noch
heute den Namen Kongsland (Königsland) und sind erst in jüngster Zeit grundbuchmäßig in
persönliches Eigentum übergegangen. Dorothea erhielt dafür 36 1/2 Demat, die sog. Norderwisch bei
Tondern, _"frey un eigenthümlich"_. Gleichzeitig wurden ihr die geschuldeten 82 Mk.Deichgelder
erlassen.

Dorothea Reinecke hatte drei Kinder, zwei Söhne und eine Tochter. Die beiden Söhne waren schon
mit acht Jahren zu ihrem Onkel, dem Propsten in Preetz gekommen. Die Tochter Margarethe heiratete
den Leutnant Peter de Lange. In den Akten wird er an einer Stelle Peter Holländer genannt, was auf
seine Heimat hinweisen mag. Margarethe erhielt 1644 die aufgeführten Ländereien als Brautschatz.
Da sie noch vor ihrer Mutter starb, oblag dem Manne, Peter de Lange, die Verwaltung und Bewirt-
schaftung der Güter. Die Festequalität wurde auch für die Kindeskinder der Dorothea bewilligt, so daß
der Familienbesitz als Gut gesichert gelten konnte.

Da brachte das Jahr 1666 eine schlimme Überraschung: Die alte Mutter Dorothea Blome-Reinecken
starb. Der Schwiegerso!-ı Peter schrieb sofort an seinen Schwager Dietrich Reinecke, den ältesten
Sohn der Verstorbenen. Er lebte als Obristenlieutnant in Waake im Lande Braunschweig. Er lud ihn
zur Beerdigung und zur Nachlaßregelung ein. _"Sie hat einige geringfügige Möbelgüter und sonstlich auch einige Landtgüter allhie hinterlassen. Da aber dieselbe wegen der darauf haftenden großen Teichslasten, Sambt Schatzung und Kriegsbeschwerden und sonstig ziehmlich verschuldet und gravieret sind"_, ist die Anwesenheit des Schwagers dringend notwendig. Dietrich aber zog es vor, nıcht
zu kommen. Er wies dabei auf sein hohes Alter und die beschwerliche weite Reise hin, und er schickte,
was das Schlimmste war, auch kein Geld. Da der Briefwechsel einige Zeit nahm, verzögerte sich die
Beerdigung um sechs Wochen. Da mußte dann Peter, als alles nichts half, _"zinnsbare Gelder"_
aufnehmen, um seine Schwiegermutter zur Erde zu bringen.
In einem Briefe des Dietrich Reinecke aus dem Jahre 1668 wird dann der Schleier etwas gelüftet:
Der Grund seines Ausbleibens ist nicht sein hohes Alter gewesen, sondern ihn haben die Schulden des
Hofes abgeschreckt. Er war darüber schon orientiert, hatte er doch den Schwager und seine Mutter vor
fünf Jahren auf sechs Wochen besucht. _"Bei meiner Abreise"_, so schreibt er,_" fragte ich ihn, wie es mit dem Gut Struxbüll stehe? Er sagte, er habe viel davon zu fordern. Ich: woher denn das käme? Darauf holte er Briefe durcheinander aus einem Kasten und zeigte mir eine Calculation, daß er vor das Guht Struxbüll Sechs Tausend Mk Lübsch ausgeleget und vorgeschossen hätte. Darauf habe ich ihm 2.000.- Mk versprochen und Kontrakt gemacht"_. In den vergangenen fünf Jahren scheint es nicht besser
geworden zu sein. Zu dem habe er seiner Meinung nach dem verschuldeten Gut gegenüber keinerlei
Verpflichtung, habe er doch mit acht Jahren das Elterhaus verlassen. 1620 oder 1621 ist er mit zwei
Pferden und einem Knecht nach Böhmen in den Krieg gezogen, ohne daß die Mutter einen Schilling
beigesteuert hat. Der Schwager dagegen hat sich ins warme Nest gesetzt und mit Frau und Kindern bei
der Mutter von den Güter gelebt. Er ist jedenfalls jetzt nicht bereit, erneut in die Schulden
hineinzusteigen. Er rät dem Schwager, alles nach besten Kräften zu ordnen, _"aber das Gut Struxbüll nicht anzutasten, damit es ihm und den Seinen möge erhalten werden"_. Auch die Drohung mit der
proclama (Zwangsversteigerung), der Hinweis, daß _"die Creditoren alles bestimmen müßten"_, und die
Einschaltung des Herzogs in die Auseinandersetzung ändern nichts an seinem Beschluß.
So mußte Peter de Lange einen anderen Weg gehen:
er begann, ein Stück nach dem anderen zu veräußern. Schon 1666, dem Todesjahr seiner
Schwiegermutter, verkaufte er über acht Demat an Stephan Kenckel, den Propsten in Tondern. 1669:
1 1/2 Demat, mit _"vorgedachtem weisen Rath und guth befinden meiner hertzigen Jungfer Töchter"_
(Dorothea Elisabeth und Christina Helena Lange, die den Kaufvertrag beide mit unterschrieben haben)
an den Landschreiber Peter Preuß. 1672: acht Demat Wischland, die nördlich der Stadt gelegene
Norderwische, an Hinrich Wessel (oder Weßling). 1673: 4 3/4 Demat an demselben. 1675: 15 Demat
Freiland und eine kleine Fenne von fünf Demat. Letztere war, wie aus einem Donationsbrief
hervorgeht, ein Geschenk des vorigen Herzogs an Dorothea Blume. Die 15 Demat stammten aus dem
Tauschland von 1623. Der Kaufpreis betrug 2.175.- Mk oder 725.- Rthl. Interessant ist, daß dies Land
verkauft wurde, obgleich es dem Schwager verpfändet war. Im Kaufbrief wird nämlich ausdrücklich
Verpflichtung betont, den Käufer _"und seine Erben so wol gegen meine Herrn Schwager H.Obrist Lieut. Dietrich Blume, wegen der ihnen darunter pfändlich versetzten und mit obigen Kaufgeld mit eingelösten Fünfzehn Demath, auch gegen alle andern Beschwerden zu schützen"_. 1700: 20 Demat 8 Fuß Festeland, _"zwischen Röhrkarr und der Brücken an einem waßrigen niedrigen Ort belegen"_, an
die Frau Majorin Böttchern. Da sie 1696 _"in ihre Heimat nachher Mainz wieder zu kehre resolviret"_,
verkauft sie an den Tonderner Bürger Albert Albertsen, der 1700 einen Festebrief darüber erbittet.
Da der Verkauf der letzten großen Landparzelle vor 1692 zu liegen scheint, ist Peter Lange wenigstens
den Rat seines Schwagers ge- folgt, _"unser Gut Struxbüll nicht anzutasten"_ - solange es mög-

lich war. Noch 1691 erscheint er als Besitzer, 1692 Maria Elisabeth Seckendorff, 1692 geht es auf
Broder Petersen und damit wieder ganz in bürgerliche Hände über.

Das folgende Jahrhundert, das für die Landwirtschaft so bedeutungsvoll war (Feldaufteilung), ist an
Struxbüll fast spurlos vorübergegangen; denn hier hatte schon vor 1770 jeder _"das Seinige"_. Schon
1613 heißt es: _"Hierbey ist zu wissen, daß dieses Dorfes Leute keine Gräsung an Geestland zu Ihren Beesten haben, Besondern müssen dieselben auf Ihr Marschlandt so vorherre einem jeden nach Dhematzhall zugeschrieben, auferziehen und weiden"_.

Vor und um 1800 sitzt auf dem Gut Struxbüll Momme Andersen von der Gath. Von ihm wäre vieles
zu berichten, was aber nicht in den Rahmen dieser Arbeit fällt. Momme Andersen war der letzte
Besitzer des Gutes Struxbüll. Er ist bis 1810 dort nachweisbar. Dann kaufte er einen größeren Besitz
in Süderlügum. Das Gut Struxbüll wird seit diesem Jahre nicht mehr erwähnt. Es ist anzunehmen, daß
es einer Feuersbrunst zum Opfer gefallen ist. 1936 wurden nämlich bei der Fundamentierung des
eingangs erwähnten Neubaus deutliche Brandspuren gefunden, u. a. an einer Reihe kleiner Tonwaren,
die noch heute von der neuen Bäuerin auf der alten Warft sorgsam aufbewahrt werden. Außer dem in
diesem Aufsatz verarbeiteten Aktenmaterial sind sie die einzig “Überlebenden”. Beide sprechen zu uns
in ihrer Sprache, die einen von der wechselvollen Geschichte eines stolzen Hofes, die anderen von
seinem unrühmlichen Ende.

=== 23.2. Chresten Schomaker

Er wohnte in dem langen Strohdachhaus in der Norderstraße, Chresten Schomaker. Wer etwas an
seinem Fußzeug oder Pferdegeschirr - es gab damals noch keinen Riemenschneider (Sattler) im Dorf -
nicht in Ordnung fand, trug es zu ihm. Er reparierte jeden Schaden. Von morgens bis abends saß er auf
dem Schusterbock, schnitt passende Lederstücke zurecht und hantierte mit Ahle und Pechdraht, mit
Holzpflock und Hammer. Er mußte wohl fleißig sein, um seine zahlreiche Familie durchzubringen. Um
die Kuh, den kleinen Acker hinter dem Hause, den Garten und das Hauswesen mußten seine Frau und
die heranwachsenden Kinder sich kümmern. Sein Reich war die Werkstatt. Während des Tages kamen
allerhand Kinder. Sie brachten Schadhaftes und holten Repariertes ab. Er kannte sie alle und hatte für
jedes ein freundliches Wort. Abends, nach Feierabend, kamen auch junge Leute, Nachbarn und
Freunde. Dann wurden alle Ereignisse im Kirchspiel durchgesprochen und unter die Kritik der
Versammelten gestellt, und es wurde etwas Karten gespielt. Er liebte das Kartenspiel und etwas mehr
noch den Teepunsch. Das ging alles ruhig und ordentlich ab. Nur an Sonntagen, besonders aber in der
Fastenzeit, wurde es etwas lebhafter, dann war die Werkstatt nicht mehr ausreichend, auch wohl nicht
fein genug. Dann konnte die kleine Stube nebenan voller Leute, Tabaksqualm, Lachen und
Punschgeruch sein.

So ging manches Jahr in ruhigem Gleichmaß dahin. Es reichte so eben, ohne je reichlich zu sein.
Zweimal aber hat Fortuna die Tür in die Zukunft, in eine leichtere Zukunft, ein wenig geöffnet und ihm
eine Chance gegeben. Das erste Mal war es eine kleine, für seine Verhältnisse nicht unbedeutende
Erbschaft, die sein ganzes Leben von Grund auf ändern sollte. Da konnte man ihm doch nicht zumuten,
weiter Tag für Tag auf dem Schusterbock zu sitzen und sich für andere Leute um weniges Geld
abzumühen. Es kamen auch bald Leute, die Werkstatt oder wenigsten die Einrichtung übernehmen
wollten. Aber nein, da war nichts zu machen. Verkaufen? Das hatte er doch nicht mehr nötig. Die
Pietät gegen seinen alten Beruf, der sein ganzes Leben bestimmt hatte, verböte ihm einen Verkauf -
sagte er. Er packte vielmehr alles in Kisten und schlang dem Schusterbock einen Strick um die Beine
und zog ihn in der Ecke der Werkstatt über einen Haken zur Decke.

Jetzt war er frei. Jetzt hatte er Zeit, und da Kartenspiel und Teepunsch nun erst richtig in ihre Rechte
traten, dauerte es nur ein kurzes Jahr, bis das Erbe zusammengeschmolzen war. Und eines Tages
geschah es: Chresten brach die vernagelten Kisten auf, holte den Bock von der Decke herunter und
begann wieder zu flicken und hämmern.

Und wieder ein Jahr später trat das Glück abermals über seine Schwelle. Der Briefträger Volquard war
sein Bote. Er brachte einen Brief, der als Absender ein Lotterieunternehmen angab. Wie viele Leute
hatte auch Chresten jeden Monat eine Mark abgezweigt für diesen Zweck. Wer weiß? - Und jetzt war
es so weit. Es war schon ein Ereignis, daß der Postbote nicht an seiner Tür vorbeiging, und nun dieser
Brief:

Kein Wunder, daß Volquard sich Zeit nahm, einen kleinen Schnack anzufangen und dabei neugierig
das Gebahren des Schusters beobachtete. Dieser klemmte das Hämmerlein unter den linken Arm,
schob die Brille zurecht, langte nach dem Messer, öffnete den Umschlag, entfaltete das Papier und las -
las mehrmals -, wortlos, und starrte eine Stelle lange an, bis er begriffen hatte. Dann - nein -, er machte
keinen Freudensprung, keinen Aufschrei in die Küche; Mutter, Mutter, hör mal....! Nein, seine Mienen
verdüsterten sich, er griff nach dem Hammer, schleuderte ihn wütend zwischen Fußzeug und Leisten:
"Nu fangt de verdammte Superi wedder an!"

Als er sich umwandte, zog Volquard gerade die Tür hinter sich zu.