== 3. Die ländlichen Besitzverhältnisse in alter Zeit

Wie schon in einem andern Abschnitt dargelegt, muß man in alter Zeit zwischen Bonden, Kätnern und
Insten unterscheiden. Die Bonden, auch Bunden oder Bohlsleute genannt, waren auf dem Lande die
eigentliche besitzende Klasse. Zwar hatten sie als Eigentum ursprünglich auch nur Haus, Garten, Toft,
und, etwas später, die Wiesen. Das andere Land, Acker und Weide, war allgemeiner Besitz, gehörte
also der ganzen Dorfschaft, der sogenannten Nachbarschaft. Es war die Allmende. Doch läßt sich schon
um 1600 feststellen, daß Ackerland in Privatbesitz übergegangen war, d.h., daß jeder seine Anteile als
Eigentum betrachten konnte. Aber die Bewirtschaftung dieser Stücke war weiterhin durch Dorfgesetze,
die sogenannten Dorfwillküren oder -beliebungen, geregelt. Dabei wurde dann die Saatfolge, der
Beginn der Arbeiten, die Ernte usw. für alle festgelegt. Erst durch die Feldaufteilung nach 1770 hat man
in unsern Gemeinden das uneingeschränkte Eigentums- und Nutzungsrecht hergestellt.
Eine Übersicht über die landständische Gliederung der Bevölkerung in der Karrharde aus dem Jahre
1581 zeigt schon die Aufspaltung der Bauern in verschiedene Gruppen:

----
        Karrharde
        Erstlich sind da Bunden
    Summa............ 114 1/2 Volles boll
    Noch ............     twee verdt boll
        Veste gudt
    Summa............             36 boll
    Noch.............     twee verdt boll
        Karckenboll
    Noch.............         7 Kark boll
    Noch.............    drüddeverdt boll
        Summa Volles       158 Vulle boll
    Darup wanen
        310 Bunden lüdde
    Noch 213 Ketenars.
    
    In Gotz Koch (Gotteskoog) hebben de
    Karrharder..611 Demat Deichlich Schlick, geuen
    (geben) von Ein Ider Demat jarliche 4 ß. Nota:
    Darunder ettliche Demat Undeichtich Schlick.
    De Fribunden in Karrharde
        hebben......             53 boll
    Noch... 88 1/2 Demat 46 1/2 Rth 4 Fuß
    Mantall dersülvigen Lüden von den Frey Bohlen
    Sindt............ 142
    Keteners......... 38.
----

Danach gab es Eigentums-, Frei- und Festebonden.

=== 3.1. Die Eigentumsbonden
Sie waren uneingeschränkte Besitzer ihres Bohls, mit dem sie schalten und walten konnten, wie sie
wollten. Sie konnten verkaufen und kaufen, vererben und verschenken. Doch waren schon Erbrecht,
Abfindung der Geschwister, Abnahmegewährung u.a. durch regelnde Verordnungen in bestimmte
Formen gebracht. Schon um 1660 wird berichtet, da es alter Brauch in der Karrharde sei, daß der
jüngste Sohn (oder die älteste Tochter) den Hof erbe, im Gegensatz zu den Marschharden, wo
Ältestenrecht herrschte. Versuche, dasselbe auch bei uns einzuführen, scheiterten. Auch Ausnahmen
ließ man nicht zu: Als Lorenz Thodsen in Wimmersbüll 1769 als primo genito (Erstgeborener) das
väterliche Gut zu gewöhnlicher Taxe erben will, wird sein Ansuchen unter Hinweis auf das herrschende
Jüngstenrecht abgewiesen. In allen Fällen der Übergabe war eine Schätzung der Vermögensteile durch
vereidigte Taxatoren vorgeschrieben. In jeder Harde waren dazu acht Sandmänner bestellt, so daß
immer die Möglichkeit des Austausches bestand,
falls eine Partei Einwendungen machte. Falls eine Taxation überhaupt angefochten wurde, wurden
beide Parteien vor den Amtmann geladen und erhielten Gelegenheit, ihre Notdurft und Gegennotdurft
vorzutragen, wobei der Gerichtsschreiber die Feder führte.
Die Schätzungen des Landes scheinen nach sehr verschiedener Grundtaxe vorgenommen zu sein,
schwankten sie doch zwischen 2 und 30 Rthl je Tonne. Der Hardesvogt lehnte 1739 den Vorschlag,
einheitliche Sätze einzuführen, ab, da doch der Wert des Landes zu unterschiedlich sei und jeweils die
besonderen Umstände, beispielsweise die vorhandenen Schulden, stark berücksichtigt werden müßten.
Im Laufe der Zeit empfand man es als recht, wie es sich eingebürgert hatte: Der Erbnehmer erhielt den
Besitz für die Hälfte des Wertes, weil sonst _"die andern unter Umständen nichts oder nur wenig
erhalten würden"_. Eine Witwe hatte das Bohl gewöhnlich in Erbgemeinschaft mit den unmündigen
Kindern. Bei Wiederverheiratung mußte natürlich eine Taxation und Überlassung an sie und den
zweiten Ehemann stattfinden, um die Rechte der Kinder zu wahren. Den Kindern mußte Unterhalt und
Erziehung gewährt werden. Auch wird das Recht der Zuflucht für nichterbende Kinder des öfteren
erwähnt.
Der Überlassungskontrakt enthält gewöhnlich auch Abnahmebe- stimmungen. Auch in der Haus- und
Hofchronik begegnet uns immer wieder der Zusatz: "Gibt seinen Eltern Abnahme". Diese selbst-
verständliche Pflicht reicht viele Jahrhunderte zurück. Um Streitigkeiten auszuschließen, mußten solche
Kontrakte seit 1778 vom Hardesvogt und dem Gerichtsschreiber unterschrieben werden, wenn sie gültig
sein sollten. In Lügum ereignete sich 10 Jahre später ein Fall, daß ein Vertrag nicht anerkannt wurde,
weil er dieser Bestimmung nicht entsprach. Ein gültiger Kontrakt mußte innegehalten werden, auch
wenn die Abnahmeleute nicht auf dem Hof verblieben, sondern anderswohin verzogen. Eine Abnahme
konnte nicht vergeben oder belastet werden, weil die Gefahr bestand, daß die Leute dann in Not geraten
und der Armenkasse zur Last fallen könnten.
Überlassungs- und Abnahmekontrakte sind immer Spiegelbilder ihrer Zeit. Sie geben nicht nur
Aufschluß über die persönlichen Ver- hältnisse der betreffenden Personen, sondern haben kulturge-
schichtlichen Wert. Außerdem - ich habe hunderte von Kontrakten gelesen - sind sie nicht alle über
einen Leisten geschlagen, sondern immer verschieden, immer den Verhältnissen angepaßt. Aus diesem

Grunde folgen hier noch zwei Beispiele:

*1. Kauf-, Überlassungs- und Abnahme Contract zwischen Andreas Diederichsen in Lügum und seinem Sohn Niels Jensen daselbst.*

[quote]
____
Kund und zu wissen sey hiermit männiglich, insonderheit denen es daran gelegen, daß
zwischen Andreas Diederichsen in Lügum für sich und seine Frau Überlassen einerseits und
ihrem Sohne Niels Jensen daselbst Annehmer am andern Theile, nachstehender Überlassungs-
und Abnahme-Contract wohlbedächtlich errichtet und unwiderruflich vollzogen worden.
Es verkauft nämlich und überläßt Eingangsgedachter Andreas Diederichsen an den gleichfalls
erwähnten Sohn Niels Jensen mit Einwilligung des zweyten Sohnes Diederich Andresen sein
ganzes Aktiv und Passiv Vermögen, namentlich also auch die von ihnen bewohnte Kathe nebst
Zubehörungen für die vereinbarte und wohlbedungene Kaufsumme von 425 hamb.Cour. ist 226
Rthl 64 ß und die nachstehend beschriebenen Leistungen:

Es verpflichtet sich nämlich Annehmer, seine beyden Eltern bey sich zu behalten, sie in
gesunden und kranken Tagen mit Hege und Pflege kindlich zu versorgen, ihnen auch, wenn sie
dessen bedürfen, jährlich 25 Hamb.Mark von der stipulierten Kaufsumme auszuzahlen, nach
ihrem Ableben aber aus dem Rest der benannten Kaufsumme ein anständiges und christliches
Begräbnis ihnen auszurichten.

Auf den Fall der Trennung verpflichtet sich Annehmer, seinen Eltern eine im Hause befindliche
Abnahme-Wohnung einzuräumen gegen jährliche Vergütung von 6 Hamb.Mark, den
Jedesmaligen Rest der Kaufsumme mit jährlich 4 p C zu verzinsen und an sie ihr bestes Bett
nebst Zubehörungen, ihr Leinenzeug, eine Lade, eine Spiegel, die Jetzt im Hause befindliche
Haus-Uhr, 1 Tisch, 2 Stühle, einen Theekessel und einen anderen Kessel, einen Eimer, zwei
Graapen, eine Kaffeemühle, eine eiserne Pfanne, eine Feuerzange, einen eisernen Kesselhaken,
das nothwendige Topfzeug, einen Flaggen- und einen andern Spaden, eine Mistgabel, eine
Heugabel und eine Harke verabfolgen zu lassen.
Nach dem Ableben beyder Eltern wird von Annehmer Niels Jensen dasjenige, was von der
Kaufsumme alsdann übrig ist, zur Theilung mit dem gedachten Bruder Diederich Andresen
gebracht, der hierdurch wegen väterlichen und mütterlichen Erbes in allen Wegen abgefunden
ist.

Solchem nach setzen Überlasser und dessen Sohn Diederich Andresen den Niels Jensen und
dessen Erben in das wahre Eigenthum und deren geruhigen Besitz ihres Vermögens dergestalt
und also, daß er es cum oneribus sofort annehmen, nutzen, gebrauchen und damit
eigenthümlich schalten und walten mag.

Vorstehendes alles fest und unverbrüchlich zu leisten und zu erfüllen, verbinden sich beyderseits
Johann von Böhl Chronik des Kirchspiels Süderlügum Seite 44
Conthrenten unter Verzichtleistung und alle Ausflüchte, samt der Rechtsregel, wonach ohne
vorgängigen besonderen Verzicht der gemein nicht

bindet, Annehmer zugleich bei Verpfändung seines ganzen Vermögens und Bewilligung zur
Protocolation, und haben zur Urkund und Verbindlichkeit diesen Contract unterschrieben.
So geschehen in der Karrh. Vogtei den 2. may 1816.
____

*2. Betr. Abnahme der Witwe Maren Fedders in Böglum*
Nach dem Tod von Fedder Andersen in Böglum haben die Sand-
und Taxierungs-Männer ihr folgendes zugelegt:

[quote]
____
In dem vorhandenen Hause wird ihr der österte Raum samt Ofen, und dabey seyende Küche
wie auch der kleine Kohl-Garten westen dem Hause zum Gebrauch eingethan. Ferner wird ihr
aus der vorhandenen Masse die mittelste Kuh nach der Taxation, lebend und nimmer tod
gegeben, welche sowohl Sommers mit gutem Gras, als Winters mit behörigem Futter gut zu
versehen ist: wie nicht weniger zwey Schafe auf gedachte Weise.

Dann erhält sie auch jährlich zwey Tonnen Rogken, zwey Tonnen Gersten und eine Tonne
Buchweizen, und sei ihr überdies jährlich fünf Fuder Torf und fünf Fuder Flaggen geliefert
werden, und zu einem jährlichen Handschilling Sieben Reichsthaler zu reichen seyn. Daß dieses
sich so verhält, bescheinigen wir mit unserer Namens Unterschrift. So geschehen Braderup und
Grelsbyl d. 21. Ap. 1785
Jes Nissen
Jappe Thomsen.
____

Da der Erbe, ihr Sohn, erst neun Jahre alt war, bewirtschaftet sie den Hof selbst weiter. Die für ihren
Erbteil festgesetzte Abnahme kann deshalb nicht in natura bezahlt werden und wird mit 30
Reichsthalern jährlich abgelöst. Ihre Beschwerde gegen diese ihr zu niedrig scheinende Festsetzung
wird abgewiesen, ein Beweis dafür, daß die Belange des Hofes immer in erster Linie gewahrt wurden.
Es heißt dort (auszugsweise): _"nach denen verwaltenden Umständen aber haben die Vormünder sich auch dahin entschlossen, eben so gerne die vorhin in Vorschlag gebrachten dreißig Reichsthaler nebst Haus-Raum und Kohl-Garten zu liefern und zu bezahlen. - Und wenn man die Einnahmen mit den Ausgaben Jahr um Jahr in eine Vergleichung stellet, kann ohne zu befürchtende zu große Belästigung des Guthes nicht mehr offerieret werden."_

Da die Regierung, vertreten durch den Amtmann in Tondern, das größte Interesse daran hatte, eine
zahlreiche und steuerkräftige Bevölkerung zu haben, wurden Verkäufe, Überlassungen, Erbteilungen
und Abnahme sehr kritisch überwacht. Verkäufe von Bondengütern durften nicht ohne Einwilligung
vorgenommen werden (1774). Gültige Kontrakte wurden seitdem nur noch auf amtlichen Stempelbogen
niedergeschrieben. Schon 1740 hatte man den stückweisen Verkauf von Ländereien verboten, da durch
die Verminderung einer Stelle nicht nur die geldlichen Verpflichtungen gegenüber der Herrschaft,
sondern auch die Einquartierungs-, Fuhr- und Dienstleistungen in Gefahr kommen könnten. Deshalb
wurde das diesbezügliche Ansuchen des Jesper Andersen abgelehnt (1741), während Carsten Andresen
1787 sein Bondengut teilen darf, da es fast einen ganzen Pflug groß ist. Bedingung ist allerdings, daß
auf dem abzutrennenden Lande eine Familienstelle errichtet wird. Ebenso wird es N icolay Lorenzen
und seiner Schwester Catharin, verheiratet mit Jesper Lorenzen, erlaubt, einen Teil des väterlichen
Gutes (Nr. 92) zur Erbpachtmühle zu schlagen, da noch 2/3 Pflug nachbleiben und die Kgl. Kasse
keinen Schaden leidet.

Die Frage, ob bei Konkursen ein Bohl zusammenbleiben oder stückweise veräußert werden soll, ist nie
einheitlich entschieden worden. Da die Bauverbindlichkeit für abgeteiltes Land seit 1784 gesetzlich
festgelegt war, konnte man wohl mit einer Teilung einverstanden sein, wenn die herrschaftlichen
Interessen gesichert waren.

=== 3.2. Die Freibonden
Immer wieder begegnet uns in alten Akten der Ausdruck Freibonden. Was sind Freibauern? Sie
genossen, wie der Name besagt, gegenüber den andern irgendwelche Freiheiten. Es scheint, daß schon
im 15.Jahrhundert adeliges Gut in bürgerlichen Besitz gekommen ist. Die neuen Besitzer bestanden
darauf, daß sie mit Erwerbung des Gutes auch seine Steuerfreiheit erworben hatten. Der Herzog bestritt
das zwar, aber 1458 hat Herzog Adolf VIII. doch das Privileg erteilt, solche durch Erbschaft, Kauf oder
pfandweise erworbenen Freigüter gegen eine jährliche Abgabe von 80 ß, womit alle Abgaben und
Leistungen als abgegolten angesehen werden sollten, zu besitzen.
Diese Freiheiten wurden ihnen in einem Freibrief zugesichert und bestätigt. Beispiel:

[quote]
____
Lüdde Thomsen, aus sonderbahrer uns hier zu bewegenden Ursachen, daß sein guht im Dorfe
Lügum, darauf er itze wohnet und den das halbe guht, danegst belegen, welches er von seiner
Hausfrauen Vater bekommen, die negst folgenden Sechs Jahr über von allen Fron- und
Hofdiensten, Herrenfuhren und dergleichen Auflagen befreyet sei. Dagegen aber er, Lüdde
Thomsen oder der Besitzer solcher gühter schuldig sein soll, Jährlich an Unser Tundersch Ambt
Register 12 Taler lüb., alß bescheidentlich von dem Gute darauf Lüdde Thomsen itze wohnet
ö Taler und dann von dem andern daneben belegenen Gute 4 Taler zu erlegen und zu bezahlen.
Urkundlich darüber
zu Gottorff d. 15. LMartz 1596.
____

In einem andern Freibrief heißt es:
_"......da vör schal und wil der Ehrbar Jiß Regelsen und sine Erwen uns unsern Erwen und unsern Amptmann dersülwest alle Jahr tho rechter tidt egen 2 Tonne Honning...."_

Nach diesen und anderen Urkunden konnten die Bonden sich somit durch eine Jährliche feste Abgabe,
sei es Honig, Butter, ein Draw Futterroggen, einiges, oft 20 Fuder Torf oder durch _"erliches Geld"_ von
Hofdiensten und Pflichtfuhren freikaufen. Viele dieser Freiheiten sind besonders in der Zeit der
Dienstbarkeit zum Schloß und zu Hestholm entstanden, später aber nach der Pflugsetzung und dem
Aufhören der Naturalienlieferungen, als alle Lasten mehr egalisiert wurden, wieder verschwunden. In
den meisten Fällen waren sie nicht auf Zeit gegeben, sondern erblich mit der Stelle verbunden.

Nach dem Erdbuch von 1613 hatten wir in Lügum drei Freybunden:

*1. Jung Niß Petersen:* 1/3 Freigut; 16 Demat Land im Alten Koog; gräst 11 Beeste, 2 Pferde, 3 Schweine, 5 Schafe; sät 2 Demat Roggen und 2 Demat Sommersaat: gibt zu Abgaben 7ß Freischatz, 2 Taler 9ß 4d Hestholmer Dienstgeld und 2 Fuder Torf= 9ß 4d.

*2. Botel Iwers:* 1/4 Freigut: 9 Demat im Alten Koog; gräst 8 Beeste, 2 Pferde, 2 Schweine, 4 Schafe; sät 1/4 Demat Roggen und 1/4 Demat Sommersaat; Abgaben 3ß 6d Freischatz, | Taler 4ß 8d Hestholmer Dienstgeld und 1 Fuder Torf=4ß 8d.

*3. Andreß Petersen:* wie Nr. 2.

Wie damals den 37 Bondestellen nur 3 Freibonden gegenüberstanden, war auch der Anteil der letzteren
an Grund und Boden nur gering. Auch 1669 hatte sich daran kaum etwas geändert, waren doch in der
ganzen Karrharde nur 47 1/2 Pflug Freibauernland, wovon auf Lügum nur 1/2 und 2/3 Pflug entfielen.
Im Laufe der Zeit hat aber die Zahl der Stellen bedeutend zugenommen. Schon bei einer Erbteilung
verdoppelte sich gewöhnlich die Zahl. Bei größeren Landverkäufen legten die Annehmer Wert darauf,
die auf dem Lande ruhenden Freiheiten mitzuerwerben. Oft wurde auch Personen, die sich
entschlossen, aus den dichtbesiedelten Dörfern auszubauen, d.h. draußen vor auf der Heide eine neue
Familienstelle zu gründen, besondere Freiheiten zugestanden.
Bei jedem Regierungswechsel wurden die Freiheiten generell bestätigt. Jede _"Confirmation"_ brachte
Geld in die Amtskasse. Der Kirchspielsvogt legte die Gesamtsumme auf die Freibauern um.
Bestätigungen liegen vor aus den Jahren 1523, 1555, 1540, 1617, 1638, 1641 1670 und 1684. Dabei
tauchte aber immer wieder die Frage auf, welche Freiheiten diese Bauern denn nun eigentlich rechtlich
hatten: von Fuhren, Dienstleistungen, Teilnahme an Jagden oder Geldabgaben ? Schon 1462 hatten sie
die Freiheit erhalten. daß sie Güter, die sie pfandweise an sich gebracht, gegen eine jährliche Abgift von
80 Talern genießen sollten. Das war ihnen 1492 und 1543 bestätigt. Da die aus Bondengütern
verkauften Güter allgemein 11 Taler 4 ß bezahlten, wurde die Abgabe der Freibonden sogar um diese
Summe ermäßigt. Als 1666 ein Teil alter Dienste abgelöst wurden, wurde den Freibauern ein Viertel
der laufenden Kontribution erlassen, d.h. während die andern Bauern 40 Rthl zahlten, gaben sie nur 30.
Doch wurde ihnen diese Vergünstigung 1707 wieder entzogen. Auch ihre Befreiung von Fuhren, Jagd
und Diensten wurde 1734 aufgehoben, 1748 aber wieder bestätigt, allerdings mit der Einschränkung,
daß Königsfuhren gemacht werden müßten. Nach langem Streit, in dem man immer wieder von ihnen
verlangte, Beweise für ihre Rechte zu bringen - was natürlich unmöglich war -, gelang es doch, 1784
eine königliche Bestätigung zu erhalten - allerdings nur gegen die doppelte Taxe von 25 Rthl. Die
Teilnahme an Jagden wurde aber weiter verlangt, weil man Urkunden gefunden, die besagten, _"daß die Freibonden schon 1699 zur Wolfsjagd bei Egbeck und in der Gegend zwischen Schluxharde und Karrharde, wo in alter Zeit immer der Aufenthaltsort der Wölfe und nur war, mit zugezogen worden sind"._

Die Bestätigung ihrer Freiheiten, die nie im einzelnen scharf umrissen waren, verleitete die Freibonden
sofort dazu, nun _"sich von allen Fuhren frey zu machen und z.B. keine Kriegsfuhren, so zum Transport einiger Pulverkarren 1765 vorfielen, leisten wollen, auch kein Material zu der Jündewatter Mühlen fahren, noch Fuhren mit Brücken-Holtz leisten"_. Auch wollen sie die Torflieferungen einstellen und 1785 zum letzten Male fahren.

Die Kirchspielsvögte wurden 1785 veranlaßt, neue Verzeichnisse über ihre Pflugbesitzer einzureichen.
Der Kirchspielsvogt Lorenz Thodsen meldete an Freybonden:

|===
| Freybonden | Zahlt zum Amt Rthl. ß | Bemerkung
| 1. Boh Mathiesen, Lügum
| 4 8 
| Für einen Teil seiner 3 Besitztümer

| 2. Johs. Sönnichsen, " 
| 2 0
| " " " " 3 " 

| 3. Sibbert Ketelsen, "
| 3 0
| " " " " 3 " 

| 4. Peter Jensen, " 
| 1 1 
| " " " " 3 " 

| 5. Ebbe Jensen, " 
| 0 4 
| ein Inste

| 6. Janne Jacobsen, " 
| 24 4
| für 1 Teil von 3 Besitztümer

| 7.Hans Jensen, "
| 15 6½
| 

| 8. Jens Christensen, " 
| l 9 
| für 1 Teil von 2 Besitztümer

| 9. Hans Nissen Hoeck," 
| 0 6½ 
| 2 Freybonden-Kätner, für 1 Teil von 2 Besitztümer

| 10. Mathias Petersen, "
| 0 6½ 
| Kätner, für 1 Teil von 3 Besitztümer

| 11. Christ. Mathiesen, " 
| 2 4½
| Kätner

| 12. Andreas Petersen, " 
| 2 4½
| Freybonden-Kätner

| 13. Peter Hartwigsen, " 
| 2 
| " "
|===

Die anderen Dörfer des Kirchspiels hatten keine Freibauern, und in Lügum waren auch nur die Nr. 6
und Nr. 7 eigentliche Freibonden- stellen, während es sich bei den übrigen um Kätner und Insten oder
um Bohlsleute handelte, die Katen, auf denen gewisse Freiheiten ruhten, erworben hatten. Nr. 6 ist der
jetzige Besitz Nr. 56, der früher bedeutend größer war, und Nr.7 ist die Stelle von Nr. 69.
Der Besitzstand der Freibauern ist auch weiterhin fast unverändert geblieben. 1845 waren es noch 1
131/384 Pflug, die mit I Rthl 10 ß 4 1/2 zum Reichstalersatz veranlagt waren. Erst 1867, als wir unter preußische Verwaltung
kamen, ist die Ungleichheit in der Besteuerung der Bauern gefallen.

=== 3.3 Die Festebonden
Außer den Eigentums- und Freibonden gab es noch eine große Anzahl von Festebonden. Festen
bedeutet mieten. Sie erhielten das Bohl nur gegen eine an den Besitzer zu zahlende Abgabe als Lehn,
also nicht als Eigentum, sondern nur zur Nutznießung. Bei uns hatten wir nur herrschaftliche
Festestellen. Die Festebonden durften nur mit Erlaubnis vererben und verkaufen. Bei jedem
Besitzwechsel mußte das Festegeld aufs neue bezahlt werden, worauf dann der Festebrief ausgeliefert
wurde.

Die nachweislich ersten Festestellen wurden im Jahre 1497 von Herzog Friedrich an Peter Bossen, Jap
May und Nis Bossen in Lügum und Andreas Tordsen in Wimmersbüll verliehen. Als Peter Bossen
gestorben, ist die Feste durch folgenden Festebrief an seine Erben erneuert worden (1503):

_"Von godes gnaden wy Friedrich Erffgenahm tho norwegen Hertoch tho sleszwick und tho
Holsten Stormarn und der Dithmarschen Erwe tho oldenborch unde dolmenhorst den wiilik
apenbar bekennende In unde mith dissen unsen Brev vor alleswennen so also des unse
undersitten Tordt unde Andres Feddersengbröder In unsen Güdern tho Lügum In Karrharde
welke wy und van den düchtigen zeligen Eggerde Gertzen gefordert und erlanget hundert und
achtintich marck lübisk hebben Inholdt zegels und brev up die sülwen güdern gedan das ein
gudt jarliches acht mark und so de upgenante Tordt Veddersen In de opgenannten hunderten
und achtentisch marck hundert und twintig mark vör sich und sin Broder Andres Feddersen vör
sick Sestig mark hebben kontet, dat wy durch zunderer Gunst und gnade opgenant Tordt und
Andres Feddersen eere Erwen desülwe Veste gudt tho lügum In Karrharde gegünnet. Welk
Jarliches acht marck schuldet Tordt Veddersen dar von vir marck Lübiske und Andres
Feddersen davon twe marck lübiske alle Jar unsen Ambtman tho lütkentunder.........."_

Bei diesem nur in den Hauptstücken mitgeteilten Festebrief handelt es sich um ein Bohl, das Eggert
Gjördsen, der 1500 auf Sollwig starb, einmal besessen hatte. Er hatte, dem Beispiel vieler Adliger
folgend, im 15.Jahrhundert ein Gut nach dem andern an sich gebracht, so daß ganz Böglum und halb
Lügum ihm Festegeld zahlen mußten. Er hatte alle Festestellen dann an die Herrschaft verkauft, wie
in dem Brief besonders hervorgehoben wird. (Siehe auch den vollständig abgedruckten Festebrief in
dem Abschnitt über die Kolonisten).

Nach dem Erdbuch von 1613 hatte Lügum 18, Ellhöft 10, Böglum 4 und Uhlenberg 2 Festestellen. Das
Festegeld betrug 8, 10, 12, 18 und 30 Taler je Bohl, Je nach der Größe. Das ergab zusammen immerhin
Jährlich 384 Rthl in die herrschaftliche Kasse.
In Notzeiten wurde es manchen Festebauern schwer, die jährliche Feste aufzubringen. Als Nis
Andersen in Ellhöft 1694 durch ansteckende Seuche 16 Stück Vieh verloren hatte - er hatte auf dem
1/4 Bohl nur 4 Tonnen Ackerland, so daß das Vieh die Steuern aufbringen mußte -, erbittet und erhält
er zwei Jahre Freiheit.

Festen, die erledigt sind, d.h. deren Besitzer verstorben, müssen innerhalb eines Jahres neu gefestet
werden, wenn man sie nicht verlieren wollte. Da man aber die Ausgabe des Festegeldes scheute,
kümmerte man sich wenig um diese Bestimmung und wartete, bis eine behördliche Aufforderung kam.
Das möchte jahrelang durchgehen. Edlef Siewertsen, Lügum, war schon 1785 gestorben. Die Witwe,
verschuldet, mit vielen restierenden Abgaben, kann die Feste nicht erneuern und wartet - zehn Jahre!
Als es 1695 nicht länger geht, weil die proclama, der Konkurs, droht, schickt sie folgendes Bittgesuch
ab:

[quote]
____
"Durchlauchtiger Hochgebohrner Fürst
Gnädiger Herr
Ew. Hoch Fürstl. Gnaden muß ich arme Hoch betrübe Wittwe, in aller weh- und demuht
Johann von Böhl Chronik des Kirchspiels Süderlügum Seite 50
Klagende unterthänigst vortragen, welcher gestalt, durch unglücklicher Zufalle meinen
Sehl.manne, Leyder Gottes, seines Junges Lebens Plützlicher weise habe zusetzen müssen, ich
aber solcher halben, als eine Ein fältiger Hausfraue, mit meine ungezogene Wayselein in
Höchster armuht gerahten: Zu mahlen Ich, wie nachbar Kündig ist, in Höchsten schulden
erwachsen: unangesehen, Er, meine Sehl.mannes Zu Königl. Zeiten auch seines Fäst Briefe
vollkommenth. erhalten, jedoch es mir, als eines Ein fältiges Frauen Persohn unbekandter
weiße abhendig worden sey; wi wohl ich Schmerzlich vernehmen muß, daß ich aufs neue
Wiederumb, in dieser meiner bedrengten Noht, verfästen muß.

Als falle deshalb, umb abwendung meiner, und meiner Kleinen ungezogenen Kindern zu
ruinirung, Ew.Hoch.Fürstl.Durchl. ich mit wasserfließenden Augen dehmütigst zu F uße, Sie
aus lauter barmherzigkeit und Landtväterlicher Milde, gnädigst geruhen wollen, mir als einer
(Bekandte) arme Wittwe, mit meinen Kleinen Kindern, in gnaden anzusehen, und gen.Fäste
auf meine, gebe Gott, verbesserung, aus Ew.Hoch.Fürstl. Gnaden, beliebung aufzuschieben,
und vor dehnen Restirenden Schatzungen, lauter umb Gottes willen aller gnädigst zu schützen,
also daß Ich, Hinführe gleich wie Vorhin, Ew.Hoch.Fürstl.D..in allen gerecht thuen müge, und
bey haus und Hof verbleiben kann. Dessen ich mich zu Ew.Hoch. Fürstl. Durchl. gnädigst
getrösten werde. +
Der ich ersterbe +
Ew. Hoch Fürstl.Gnaden +
aller dehmühtigst und unterthänigste +
Dorthea, Sehl.Edlef Sigwartsen +
nachgelassene Wittwe zu Lügum."
____

Aber nicht nur verschiedene einzelne, sondern die Gesamtheit der Festebauern fühlten sich in der Zeit
gegenüber den Eigentumsbauern stark benachteiligt, hatten sie doch zu allen anderen Lasten immer
Festegeld und Schreibgebühr extra aufzubringen. Durch viele Beschwerden und Eingaben zwecks
gerechter Verteilung der Lasten hatten sie 1692 endlich erreicht, daß eine Kommission von 18
Männern neue Landmaße festsetzen sollte. Wenn die Arbeit auch langsam voranging und die
Festebohlsbesitzer der Schlux- und Karrharde drei Jahre später noch klagten, daß bis dahin nichts
geschehen sei und daß man "Mohr, Sandberge, Moratze, so nicht des Vermessens noch der Taxation
würdig sind" mit einbezogen habe, so wurde doch 1695 ein gewisser Abschluß erreicht. Doch schien
das Versprechen, daß alles nach Pflugzahl belastet und "keiner mehr als der andere graviret" werden
solle, nicht eingelöst. Die Festebauern fühlten sich gegenüber der Marsch und gegenüber ihren andern
Berufsgenossen benachteiligt. Die Marsch war zu gut weggekommen. Während man dort in 20, 30
oder 40 Jahren kaum einen Taler je Demat ausgab, hatte man hier, wenn einer starb, immer die
Festegebühr zu zahlen. Und diesen Nachteil hatte man auch den andern Bauern gegenüber, besonders
bei öfterem Besitzwechsel wurde die Last unerträglich, weshalb auch die Restantenlisten, der
Festebauern so umfangreich waren.

Bei der Landvermessung hatte zudem Wimmersbüll sich noch eine Extrawurst gebraten: Tordt
Andresen hatte es verstanden, sich in die Kommission hineinzudrängen, obgleich er nicht vom ganzen
Kirchspiel gewählt war. Die Folge war, daß Wimmersbüll sehr gut abschnitt, was folgende
Gegenüberstellung zeigt:

|===
| Alte Pflugzahl | Neue Pflugzahl

| Lügum..................16 1/12 Pfl. 
| Lügumdorf.............20 26/48 Pfl. +
sehr erhöht

| Wimmersbüll.............7 1/2 Pfl. + 
Diese NB schalten, was sie haben, und wollen gerne mit dem Vermögen in ruhe stehen.
| Wimmersbüll............7 28/48 "

| Struxbüll...............2 /2 Pfl. +
haben einige Hülfe von nöthen gewiß zuviel
| Struxbüll.............1 6/48"

| Böglum............2
| Böglum.................2 1/48"

| Uhlenberg...........1/2. Pfl
| Uhlenberg................ 19/48 "

| Elhovet............3  Pfl. 
| Elhovet................0 16/48 "

| Windtweth............ 1/2 Pfl." 
| Windtweth.............. 1 " +
zur Hälfte gravieret

| 31 11/12 Pfl 
| 39 Pfl.
|===

Wenn man bedenkt, daß erhöhte Zahlen erhöhte Abgaben bedeuten, versteht man die Kritik an
Wimmersbüll: _"Hieraus erhollet, wie daß Lügumdorf gar zu hoch, Windtwedt zur Hälfte und Elhovet
über die Hälfte wieder alle raison gravieret, hingegen Wimmersbüll bey ihrer alten Pflugzahl
verblieben"_ .
So ist es erklärlich, daß Klagen und Beschwerden nie ein Ende
nahmen, zumal auch die Forderung, ein besonderes Register für Festebauern anzulegen, getrennt von
den Eigentumsbesitzern, nicht berücksichtigt wurde.
Um die Erneuerung der Festebriefe besser überwachen zu können, mußten die Kirchspielsvögte
Jährlich ein Verzeichnis derjenigen Besitzer einreichen, _"so Vest fellig sind"_, d.h. wo der Festebauer
verstorben war. Die Liste, unterschrieben von Ingwer Jonas, enthält 1703 für Lügum 2 Namen, für
Ellhöft 7, außer 10 Kätnerstellen. Die Regelung war hier besonders einfach, weil alle Festegüter
landesherrschaftlicher Art waren. Alle Festen waren Erbfesten und gingen gewöhnlich auf den ältesten
Sohn über, _"wenn er sich meldet"_. Eine Veräußerung von Festeländereien war nur mit Genehmigung
gestattet. Jeder Festebauer hatte gleich den andern Bonden eine Seite im Schuld- und Pfandprotokoll
(seit 1698). Bei Konkursen kann eine Feste unter Umständen geteilt werden, möglichst ist sie aber an
"dem Meistbietenden zu verheuren". Wenn freie Bauern Konkurs machten, wurde das vorhandene
Festeland zur Masse geschlagen. Das mußte Thord Mathiesen auf Struxbüll 1748 erfahren. Er wollte
aus seinem Konkurs die 5 Demat Festeland, die der Mohrkirchener Obrigkeit gehörten, für sich retten 
und eine Katenstelle darauf errichten, wurde aber abgewiesen.

Der Festenehmer mußte seine Geschwister durch eine Abfindungs-summe zufriedenstellen. Wenn die
Kinder noch unmündig waren, konnte auch die Witwe festen, eventl. ihr zweiter.Ehemann. Als die
Mutter der einjährigen Helena Carstensen auf Osterhof in Ellhöft gestorben war, wurde dem Vater,
der sich wiederverheiraten will, die Feste, auf die die Tochter Anspruch hatte, mit Einwilligung des
Vormundes der Kleinen, Bertram Andersen Fries in Seth, unter der Bedingung übertragen, daß er der
Tochter 1000 Rthl aussetzt und ihr Verpflegung und anständige Erziehung zusichert.
Als Peter Mombsen, Ellhöft, 1711 vererben und die Witwe Margaretha sich mit Paul Peter Nissen
wiederverheiraten wollte, erhielt er die Feste. Auch er mußte den drei unmündigen Kindern Kost,
Kleidung, Wohnung und Erziehung gewähren und ihnen bei ihrer Mündigkeit 1600 Rthl ausbezahlen,
außerdem versprechen, die Feste an den ältesten Sohn Carsten Petersen abzutreten, falls er sie bei
seiner Volljährigkeit zu haben wünschte.

Nach dem Erdbuch von 1613 hatten wir in Lügum auch drei Kirchenfestegüter, die wahrscheinlich aus
katholischer Zeit stammen, wo es Sitte war, die Kirche mit größeren Schenkungen zu bedenken.

*1. Hans ‚Jensen:* 1/2 Kirchenfestegut und 20 1/2 Dt. Land im Alten Koog; gräst 16 Beeste, 3
Pferde, 4 Schweine, 8 Schafe; sät 3 Dt. Roggen und 3 Dt. Sommersaat; gibt 12 Taler Festegeld
und zahlt jährlich 4 Rthl an die Kirche.

*2. Chresten Lauesen:* wie 1.

*3. Mom Petersen:* 1/2 Kirchenfestegut und 18 1/2 Demat im Alten Koog; gräst und sät
dasselbe wie 1., zahlt aber 18 Taler Festegeld und jährlich Kirche 4 Rthl 4 ß an die Kirche.

Die beiden ersten Stellen waren 1594 durch Teilung eines ganzen Bohls an die Erben Hans und Lewe
Jensen entstanden. Bei Nr. 1 handelt es sich um Nr. 96 der Hofchronik.
Im Grunde bestand wenig Unterschied zwischen Festegütern und Eigentumsstellen. Die einen erlegten
bei jeder Veränderung, d.h. beim Übergang in andere Hände, die Festegelder und erhalten den
Festebrief, während die Bonden "die Schöte nehmen", d.h. Schoß, Schatz, Abgaben, Steuern bezahlten
(Schoß, Schoot, weil den Käufern früher bei der Übernahme als Zeichen ihres Besitzrechtes eine
Erdscholle in den Schoß gelegt wurde). Da ein freies Bonden- gut aber eine bessere Bewirtschaftung
gewährleistete, erwog man seit der Mitte des 18.Jahrhunderts die Umwandlung der Festestellen in freie
Bondenbesitze. Da aber die Ablösungssumme im allgemeinen recht hoch war, konnten viele es sich
nicht leisten. So wird 1768 aus Leck berichtet, daß man bat, _"von der Ankaufung verschonet zu werden
im Anbetracht der Vieh-Seuche, die nahe grassieret, daß wir nicht wissen können, wie lange wir davon
verschonet und gar zu armen Leuten gemacht werden"_ .
Trotz solcher vorübergehenden Notzeiten ist es den meisten Festebauern in den nächsten 50 Jahren
gelungen, sich loszukaufen und freie Bauern zu werden.

=== 3.4. Kätner und Insten

Die Kätner besaßen nur ihre Kate und den Kohlhof (Garten). Sie, die sich mit Handwerk und
Handarbeit ernährten, hatten in Gemeindeangelegenheiten nicht mitzureden. Manchen war es gelungen,
sich bei sparsamster Wirtschaft eine oder gar zwei Kühe anzu- schaffen, die dann gegen ein billiges
Grasgeld auf der gemein-samen Weide mit gräsen durften. Wie bei den Bohlsleuten gab es auch bei
ihnen volle, halbe und viertel Kätner. Die Kate konnte Eigentums-, Bonden- oder Festekate sein. Viele
Katen waren auf dem Stavensgrund eines Bohls erbaut, sodaß der Kätner dem Bohlsmann die Feste
schuldig war. Diese bestand in Geld oder bestimmter Arbeitsleistung, meistens in beiden.

Nach dem Erdbuch von 1613 bestanden in Lügum 23 1/2 Bundenkaten, 29 Festekaten und 2 Freikaten,
in Wimmersbüll 3 Bunden- und 3 Festekaten und in Struxbüll 1 Bundenkate. Um 1700 hatte sich ihre
Zahl auf über 100 erhöht. Das Festegeld betrug 2 Rthl. Jeder Kätner zahlte an

Abgaben, außer dem Verbittelsgeld und Hestholmer Dienstgeld, je 9 ß 4 d. Verbitten bedeutet schützen.
Es war eine Abgabe für den herrschaftlichen Schutz, den jeder genoß. Das Hestholmer Dienstgeld war
ein Ablösungsbetrag für die Dienste, die man früher auf dem Meierhof Hestholm zu leisten pflichtig
gewesen war. Freikätner zahlten für ihre Befreiung vom Botenlaufen usw. (siehe den
betreffenden. Abschnitt) mit einem ähnlichen Betrag.

Als die Bohlsleute den Kätnern im Ausgang des 17. Jahrhunderts einen 1/2 Pflug Land pfandweise
überlassen hatten, mußten sie auch Landsteuer nach dem Pflugregister entrichten. Da aber alle, die unter
1/4 Pflug Land (später 1/8) hatten, als Kätner Verbittels- geld zahlen mußten, klagten sie über doppelte
Belastung. Dabei war das Land nicht das allein Bestimmende: wer auf eigenem Land in seiner Kate
wohnte, war frei, wer aber trotz eigenen Landes sich eine Wohnung heuerte, mußte zahlen. Auch diese
Ungleichheit führte zu wiederholten Klagen und Beschwerden.

Der Kirchspielsvogt und die Bevollmächtigten mußten dem Amtshause jährlich ein
Instenverbittelsgeldregister und ein Kätnergeld- register einreichen. Da die Endsumme 1730 - 1780
um den vierten Teil zurückgegangen war, wurde dem Kirchspiel Privatinteressen und Mangel an
Verantwortung und Gewissenhaftigkeit vorgeworfen und die Listen zur Ergänzung zurückgeschickt.
Und es muß schon als ein Zeichen dörflichen Zusammengehörigkeitsgefühls und Verständnisses für
soziale Belange gewertet werden, daß die Kirchspielsverwaltung fest blieb, die Vorwürfe zurückwies
und für den Rückgang der Einahmen zwei ganz andere Ursachen anführte: 1). das Fortfallen des
Bohlsverbittelsgeldes von 1 Rthl und 2.) die große Armut vieler Kätner durch die Viehseuche, die
manchem die einzige Kuh genommen hatte. Jedenfalls war man nicht zur weiteren Unter- drückung
der Armen bereit: _".dann muß die Amsstube, die doch alles, wenn möglich, an sich ziehen will, dies
undankbare Geschäft alleine machen"_ .

Insten hatten kein eigenes Besitztum, weder Haus noch Land. Sie wohnten zur Miete und waren
Handwerker und Arbeiter. Und Arbeit gab es damals, als noch die einfachste Maschine fehlte, genug:
Es war eine Unmasse an Torf zu graben, die Wege erforderten viele Unterhaltungsarbeiten, in der
Marsch mußten viele Meter Graben gekleit (ausgeworfen) werden, in der Erntezeit mußten sich viele
Hände rühren, und in den kurzen Wintertagen wurde der Dreschpflegel geschwungen.

=== 3.5.Dienstboten und Tagelöhner

Obwohl das Kirchspiel infolge der großen Zahl der Kätner und Insten mit Arbeitskräften wohl versorgt war,
 dürfen wir uns die Bauernstellen doch nicht ohne
Dienstboten denken. Sie rekrutierten sich aus unverheirateten Leuten. Seit 1740 gibt es eine Gesinde-
ordnung. Man kann um diese Zeit feststellen, daß die Löhne in den letzten hundert Jahren um ein Drittel
gestiegen sind, sich also der erfolgten Preiserhöhung für landwirtschaftliche Produkte angepaßt hatten.
Für die Geest betrugen die jährlichen Lohnsätze 1749 für einen Bauknecht (1. Knecht) 16 Taler, für
einen Mittelknecht 8 Taler, für einen großen Jungen 4 Taler, für einen kleinen Jungen 2 Taler, für die
1. Magd 5 Taler und für die 2. Magd 3 Taler. Der Tagelohn betrug für schwere Arbeit 6 ß, für andere
Arbeit 5 ß, für Frauenspersonen 4 ß. Das Dreschen im Winter wurde mit 12 ß wöchentlich plus Kost,
ohne Kost mit 16 ß entlohnt.

In der Gesindeordnung war eine jährliche Loskündigung zu Ostern vorgesehen. Der Landwirtschaft
konnte dieser Termin nicht angenehm sein, da sie dann mitten im Sommer oft ohne Hilfe war. Über
spätere Vorschläge von vier jährlichen Kündigungsterminen hat man sich schließlich auf zwei
festgelegt, zu Ostern und Martini, bis dann 1810 feste Kalendertage, der 1.Mai und der 1.November,
bestimmt wurden.

Arbeitslose gab es im 18. Jahrhundert auf dem Lande noch nicht. Zwar war in der Gesindeordnung
schon eine gewisse Drückebergerei in Rechnung gestellt und bestimmt worden, daß Leute, _"die
diensttüchtig sind, aber nicht dienen wollen"_ bis zu einem gewissen Alter (männlich 20, weiblich 30
)Jeine Geldstrafe von 3 oder 2 Rthl. in die Königl. Kasse zahlen sollten. Es sollte ihnen _"das Sitzen auf
der sogenannten eigenen Hand"_ nicht gestattet sein (1770).

Dreißig Jahre später hatten sich die sozialen Zustände auf dem Lande wesentlich verschlechtert. Die
Armut ist groß. Im Winter, wenn _"die Bauern den Lohn drücken"_ , herrscht in manchen Familien bittere
Not. In der Hoyerharde wird schon _"die Saat des Aufruhrs vom unverantwortlichen Element
ausgestreut"_ . Die halbe Welt seufzt unter dem Kriege. Die Moral sinkt. Die Diebstähle nehmen zu.
Wenn man auch hoffen kann, daß bei eintretendem Frieden alles wieder abebbt, so gilt es doch,
inzwischen den Armen wenigsten das Brotkorn zu sichern. Zum erstenmal taucht in diesem
Zusammnhang der Gedanke auf, entweder landlose Familienstellen auf dem Lande anzulegen oder
Arbeitshäuser zu errichten. Und da die Hoffnung auf Besserung der Verhältnisse sich nicht erfüllten,
wird 1819 die Errichtung von Arbeits- und Armenhäusern angeordnet. (Siehe auch "Die Geschichte des
Armenwesens").

Wenn auch die Festeleute ohne Genehmigung ihre Stelle nicht verlassen durften, so hat es doch eine
Leibeigenschaft im eigentlichen Sinne bei uns nicht gegeben, weil die großen Güter fehlten, wo die
Bauern und Kätner durch Geburt Leibeigene waren.

Die Zeit der Leibeigenschaft ging in der 2. Hälfte des 18. Jahr- hunderts überhaupt zu Ende. Das
Desertieren war an der Tages- ordnung. Steckbriefe, Strafandrohung und Gegenmaßregeln wurden sehr
oft auch von der Kanzel unserer Kirche bekanntgegeben. Den Pastoren war untersagt, solche Personen
zum Abendmahl zuzulassen, und die Bauern durften sie nicht in Dienst nehmen. Am 2. Januar 1805
wurde die Leibeigenschaft in den Herzogtümern durch Königl. Verordnung abgeschafft.

*Der Fall Jes Hansen, Lügum.*

Wenn hier noch einiges über einen Freibauern berichtet wird, so nur deshalb, weil der Fall zeigt, daß
die Dorfschaft nicht nur in Angelegenheiten der Allmende, der Vertretung nach außen bezw. nach oben
und in Notzeiten als eine Einheit Sorgen und Leiden teilte und einträchtlich meisterte, sondern auch
darüber wachte, daß jeder seinen Teil der Lasten auf sich nahm, seinen Verpflichtungen nachkam und
seinen Hof zum Besten des Ganzen in Ordnung hielt und den Dorffrieden nicht durch willkürliches
Betragen störte.

Das war bei Jes Hansen der Fall. Daß er 1693 einen Prozeß gegen die acht Hegesmänner des Dorfes
hartnäckig durchführte - es handelte sich um Gräsungsgerechtigkeiten -, mag noch hingehen. Auffällig
ist aber, daß viele Seiten im Schuld- und Pfandprotokoll (seit 1698) ihn und seine Frau Karen
(Catharina) als Schuldner aufführen, sodaß ein großer Teil der Ländereien nach und nach verpfändet
werden mußte.

Er stammte aus Wimmersbüll. Nicht er, sondern sein Schwager Sönke Feddersen erhielt den elterlichen
Hof. Er selbst hat sich in eine Lügumer Bauernstelle eingeheiratet. Seiner Mutter, die ihren Mann um
viele Jahre überlebte, hat er in vielen Jahren das Leben mit Prozessen schwer gemacht. Die treibende
Kraft war immer die Frau, die ihm an Gewalttätigkeit nicht nachstand, an Mundwerk noch übertraf,
mußte sie doch einmal eine Brüche von 1 Rthl. bezahlen, weil sie die Frau von Hans Daniels, _"ohne
Ursach braun und blau geschlagen"_ hatte. Der Hof war durch ewige Prozesse, durch Trunkenheit und
Nachlässigkeit total verwirtschaftet und die Gebäude _"zum Umfallen"_ vernachlässigt. Oft war schon
der Konkurs bedrohlich nahe gewesen, hatte aber bis dahin noch immer durch irgend eine Erbschaft
abgewendet werden können. Auch daß er seinen Schwager von seinem Hof zu bringen versuchte, ist
zu werten als Versuch, einen letzten Rettungsanker in seiner trostlosen wirtschaftlichen Lage zu finden.
Da aber Sönke Feddersen ein guter Landwirt war, der seinen abgebrannten Hof wieder aufgebaut und
seinen steuerlichen Verpflichtungen pünktlich nachkam, kam Jes Hansen diesen Qualitäten gegenüber
ins Hintertreffen, und der zwölfjährige Streit (1695 - 1707) wurde zu seinen Ungunsten entschieden.
Seitdem wird seine Lage immer bedrohlicher. Die Schulden wachsen auf über 3.000 Taler an, nicht nur
bei Privat- personen, sondern auch beim Amtshause, dem Hardesvogten, den Kirchspielsvogten, den
Hegesmännern und dem Deichgrafen. Seit 17 Jahren ist er mit diesen oder jenen Abgaben in Rückstand.
Daß die wurdierten, d.h., verpfändeten und vom Staven abgekommenen Land- stücke, wieder
zurückkommen, kann wohl für die Zukunft die Stelle wertvoller machen, aber keine augenblickliche
Hilfe bringen. So tritt 1710 der Konkurs ein. Der Termin für den Verkauf wird fest- gesetzt. Da aber
keiner gerne mit der Frau zu tun haben will, weil Jes Hansen und seine Frau gegen den Übernehmer
Gewalttätigkeiten, Anzünden des Hauses usw. androht, erscheint keiner der Kreditoren zum Termin. Da
greift die ganze Dorfschaft unter Führung ihres Kirchspielsvogten Ingwer Janne durch die am Schluß
mitgeteilte Eingabe in den Gang der Geschehnisse ein. Die Gegennotdurft des Debitors, die ausführt,
daß er 35 Jahre diese besessen hat, wiegt die gewichtigen Gründe, die gegen sein Verbleiben sprechen,
nicht auf: vier Tage vor Weihnachten wurden er und seine Frau durch drei Fußknechte aus der
Wohnung gesetzt und der Hof nach einigem Hin- und Herschreiben erneut zum Verkauf gestellt.
Das interessante Schreiben der Dorfschaft, geschrieben und unterschrieben am Tage der fruchtlosen
Versteigerung, lautet:

[quote, I. Jonas und 31 Eingesessene]
"Nachdem mahlen daß Jes Hansen und Karen Jessen Gut zu Lügum der vielen darauf
hafftenden Schulden Insonderheit auch der Restirenden Herren und Anderer Plubliquen
gefällen So woll als der sehr üblen Haushaltung und administration Halber in Concours
gerahten und als bis dahin gediehen daß der Hoff mit dem zubehörigen Lande öffentlich an den
Meistbietenden solte Licitiret werden, Zu dem Ende auch solches alles Von verschiedenen
Cantzeln in hiesiger Harde und Anders wo Proclamiret, und dazu der Heutige Tag angesetzet
gewesen. Nun aber sich befunden, daß Niemandt sich dazu eingestellet, Weit weniger desfals
die auf Hochfürstl. Expressen Befehl ange- setzte Licitation zum Stande gebracht werden
konnte, So haben wir Endes Unterschriebene Kirchspielsvoigt und Eingesessenen des Dorfes
Lügum nach erbeisehender Nothurft und auf Special Begehren des Herrn Ambtschreibers
Nicolas Hansen absonderlich zu des Hochfürstl. Interesse und gemeinschaftlicher Dorfs Posten
beforderung uns nicht entlegen können, noch sollen, Kraft dieses Nach Unsern Pflichten und
Gewissen zu attest- ieren, daß so Viel zufanglich Cedenten Leben, Wesen und Handel angehet,
ist Leider, Dorf-, Stadt- und Landkündig, daß sie sehr viele Jahre her in stetiger Unruhe, Streit,
Handel und Prozessen Continuirlich gelebet, Wodurch an und durch das daraus erfolgende
Unwesen ihre Mittel verschleudert, mithin das Guth durch solche Entkräftigung und Wegen
Ermangelung der nöthigen Aufsicht; Betreiben und Bestreitung mehr und mehr herunter
gekommen und in sehr viele schulden gerathen, so daß nach ausweisung des Concurs
Protocolls über 3 bis 4.000 Taler übrig bleiben, dazu keine Bezahlung Vorhanden, und ob Woll
der Hof mit Zubehör sonsten Bekanter maßen Einer Von den Besten im gantzen Dorfe, und
Zumalhlen vorhin auch mit Frybunden Gerechtigkeiten Bonificiret gewesen, dahero auch aller
Wahrscheinlichkeit nach, sofern nur ein Guter Hauswirth darauf wieder gesezet würde, mit der
Zeit wieder in Gutem stand könnte gebracht werden, so daß es Woll die Herrschaft als hiesiges
Dorf damit Woll könnte versehen sein, so scheinet es doch aus Vielen sehr Bedenklichen und
Besorgl. umbständen noch Zur Zeit unmügl. Zu sein es dahin zu bringen, es sei denn daß die
Gnädige Herrschaft selbst die nachdrück- liche Hülfe hierin Verfügen und die Cedenten, welche
ab- sunderlich die Frau Karen Jesses für Bedrohliche jahr un- ruhige und Besorgliche Mute
Vermögen ihrer Worten und Werken selbst wollen angesehen sein, Einmahl Gäntzlich
Heraussetzen, Und dabei dem künftigen Licitanten oder Besitzer allen Hoch- obrigkeitl. schutz
Beystandt und andere Beyhülfe für besorg-lichen Brandtschaden, angedrohten Prozeß und
andere Vielen unfügnussen Gnädigst Werden Versichern lassen auf solchem Fall und Nicht Ehr
dieses Guth dürfte am Mann zu bringen sein, so lange aber dieses nicht geschiehet, wirt dies
Gantze Concurs ohne Frucht und das Guth Zum allgemeinen Großen Nachtheil und Verdruß
noch mehr Wüst liegen bleiben, welches alles und Ein Mehres war Zur steur der Wahrheit, Zum
Herr- schaft und der Wüsten Guths Besten und Aufnahm, Niemandt zu Lieb noch zu Leidt, auf
unser Gewissen und nach bestes Wissen und Verstande mit Eigenhandiger Unterschrift
Bezeugen sollen, So geschehen Lügum, d. 2. Nov. Ao 1771.
(Unterschrift: I. Jonas und 31 Eingesessene)"

=== 3.6.Adelige

Adelige hat es in unserm Kirchspiel und der weiteren Umgebung nicht gegeben, weshalb wir, wie
früher erwähnt, auch keine Leibeigenschaft kannten. Dennoch ist ein Fall bekannt, der von einem
Zusammenstoß zwischen Adel und Bürgertum berichtet, mitgeteilt in L. Andersen, Geschichte der Stadt
Tondern, und zwar in Lügum. Doch sei auch klar vorweg bemerkt, daß daraus kaum Schlüsse auf
Gewalttätigkeit und Hemmungslosigkeit des Adels zu ziehen sind. Aber als Spiegel der damaligen Zeit
und weil gerade Lügum der Schauplatz jener Untat war, sei sie hier am Schluß dieses Abschnittes
mitgeteilt.

Es war am Sonntag, den 8. Juli 1554, als der Ratsverwandte Andreas Momsen, von der Befrachtung
eines Schiffes zurückkehrend, auf dem Wege nach Tondern im *Krug zu Lügum* Rast machte. Hier
saß auch der ihm gänzlich unbekannte Junker Erich Emmicksen von Tyrstrupgaard, der bald anfıng,
über den _"von linnewandt gewirgkten underrogh"_ des Momsen zu spotten. Obgleich alle Anwesenden
auf Momsens Seite standen und die Hänseleien als unberechtigt zurückwiesen, zog dieser es doch vor,
das Lokal zu verlassen. Der Ritter ließ sofort anspannen, holte Momsen ein und setzte den Streit fort.
Momsen hat am 24. August das Zusammentreffen aus der Fremde beschrieben: _"Darauf bin ich ihm/
alß eine Bürger keyn einen vom adell billigh geziembt/ auß dem wege gefaren/ Er ist aber/ von seinen
wagen gesprungen und sein schwerdt außgezogen und mordtlich zu mir eingehauen/dha habe ich ihme/
eher ich mich zuer wehre gesteldt/ umh friede gebeten und umb gotteß willen angerufen/sich besser zu
bedenken/ich hatte jae nichts kegen ihne verwirkgt/ Eß ist aber mein flehentlich bitten und anrufen bey
ihme gantz unfruchtbar gewesen und offentlich außgeschrien/ ich scholde von seinen henden
sterben/und einen streich nach dem andern zu mir eingehauen und mich beide hende und in meine arme
beschwerlich verwundet und also fünf mal verwundet/ eher ich mich kegen ihme gewehrt/ Dieweil ich
aber mein eußerste nodt undt verdorben und nicht anders alß den leiblichen todt vor meinen augen
sehe/ stach ich wider nach ihme/ welcher stich seine todwunde gewesen/ leyder/Gott sey es geclaget."_ 

Auf Veranlassung der Sippschaft des Getöteten wurde Momsen sogleich von Herzog Johann für
friedlos erklärt, so daß niemand ihn "geleiden, noch hausen, noch hegen" durfte. Momsen war außer
Landes geflohen. Seine Bitte an den Herzog, Augenzeugen vernehmen zu lassen, einen Gerichtstag
anzusetzen und ihm freies Geleit zuzusichern, damit er wieder zu Weib und Kind und zu seinem Handel
kommen könne, wurde unter Einfluß der Emmichsenschen Sippschaft abgelehnt. Obgleich kein Zweifel
bestand, daß er in Notwehr gehandelt hatte, wurde sein Gut beschlagnahmt und ihm die Rückkehr
verweigert. Er ist in der Fremde gestorben. Erst fünf Jahre später hat der Herzog den Kindern das
väterliche Erbe zurückgegeben.
