== 4. Der alte Wald

=== 4.1. Der Wald

"Wann und warum ist der alte Wald unserer Gemarkung untergegangen?" So bin ich verschiedentlich
gefragt worden. Beide Fragen, die bei Baumfunden immer wieder auftauchten, sind nicht eindeutig zu
beantworten. Hier kann nur in Kürze darauf eingegangen werden.

Unser Land hat seine Vegetationsform verschiedentlich geändert. Nach dem Abschmelzen des Eises
hat hier noch lange ein arktisches Klima geherrscht, das sich erst ganz langsam milderte. Erst um
ca.5000 v.Chr. wurde es wesentlich milder, so daß Erle, Linde, Buche und Eiche den vorherrschenden
Bestand an Zwergbirke, Polarweide und ausgedehnten Nadelbäumen verdrängen konnten. Dieses neue
Kleid hat unserm Landstrich durch Jahrtausende bis ins Mittelalter der geschichtlichen Zeit hinein sein
Gepräge gegeben.

Wenn die Urkunden über den alten Waldbestand in der Karrharde auch recht dürftig sind, so genügen
sie im Zusammenhang mit andern Zeugen doch, um festzustellen, daß einstmals der Wald hier die
vorherrschende Vegetationsform gewesen sein muß. In der Danckwerthschen Landesbeschreibung von
1652 lesen wir: _"Insonderheit gehet sein Strich Sandes oder sandichten Bodens hindurch schier von
Humtorp auff Lugum, Ladelundt, Bramstede, Medelby biß an die Sandberge in Wyhesharde, Namens
Froßleesandt, werselbsten vorhinn ein Wald hindurchgegangen, ..."_ . Und in der Mejerschen
_"Renovirten Landesbeschreibung"_ , 1654, wird von einem großen _"Woldt Bramslundt benobenst andere
Höltzungen mehr"_ berichtet. Dieser Wald soll u.a. das ganze Kirchspiel Karlum bedeckt haben, und
_"noch heute findet sich in den ganzen Strich von Westen nach Osten in den Mooren oder in den mit
Heidekraut bewachsenen Sandgegenden eine Menge Stümpfe meist verkohlt traten sie bei Karlum in
der Richtung von NW nach SO auf, als wenn der Wald bei einem Sturm aus Nordwesten
verbrannt..."_ (Sach). Solche Zeugen haben wir auch in unserm Kirchspiel.

Den Einnahmebüchern des Amtes Tondern aus dem Jahre 1544 entnehmen wir: _"De uth Karrharde
gewen jarliches tho dem Toigelhowe(Ziegelhof) noch darbowen 424 foder holtes"_ , was, verglichen mit
den Naturalabgaben waldreicherer Harden zwar wenig war, aber doch für einen gewissen Waldbestand
spricht. Dasselbe tun ja auch unsere Ortsnamen Ellhöft (Erle) und Böglum (Buche) und
Struxbüll(Strauch = Busch). Auch in den Flurnamen Thüringbusch in Wimmersbüll schläft die
Erinnerung an frühere Zeiten.

Daß der Waldbestand gerade bei uns nicht so klein gewesen ist, mag man entnehmen aus einer Urkunde
aus dem Jahre 1497, in der Lügum und Böglum unter den wenigen Orten genannt werden, die noch zur
Schweinemast geeignet waren. Allerdings ist daraus auch zu schließen, daß der Wald stark im
Abnehmen begriffen war.

Wenn man in unsern Wiesen und Mooren nicht nur Birkenreste, sondern mächtige Eichenstubben
findet, so ist das ein Beweis dafür, daß der Wald einst auch Teile unserer Gemarkung bedeckt haben
muß. Die Eiche scheint danach auch bei uns der Hauptbaum gewesen zu sein. Die heutigen
Nadelwälder sind jüngeren Datums. (Siehe das Kapitel "Aufforstung').

Über die Gründe für den Untergang des alten Waldes sind die Gelehrten sich nicht ganz einig. Es ist
wohl so, daß die Natur selbst und der Mensch dafür verantwortlich zu machen sind. Es ist denkbar, daß
Veränderungen im Boden und des Klimas ein allmähliches Verkrüppeln des Waldes herbeiführten.
Auch mögen Katastrophen, Orkane, Sturmfluten, Brände oder Veränderungen in der Höhenlage des
Bodens das ihrige dazu getan haben. Sicher ist aber auch, daß die Menschen, der einzelne und die
Gemeinschaft, am Verschwinden des Waldes mitschuldig geworden sind.

Schon die komplizierten Besitzverhältnisse und Nutzungsrechte mußten sich verhängnisvoll auswirken.
Unkultiviertes, unbesiedeltes Land gehörte dem Landesherrn. _"Und wat sonsten nimandt tho gehöret,
dat gehöret dem Könige"_ (Jydske Lov). Die Bonden hatten das Recht des Fällens, der Schweinemast,
der Weide, des Pflügens und Rodens, wobei man zwischen Allmende = "gemeine Weide" und der
übrigen Feldmark unterscheiden muß. Letztere wurde unter den "Loseignern" verteilt. In der Allmende
war es so, daß die Erde dem König, den Bonden die Hölzung gehörte. Soweit der Wald Eigentum der
Dorfschaft war, erhielt jeder Nutzung, Holzschiften, zugeteilt. Nur Weide und Mast waren gemeinsam.
Der Wald war aber nicht räumlich geteilt, sondern nur die Nutzung, der Ertrag. So durfte stellenweise
und zeitweise nur der siebte Baum geschlagen werden.

In vielen herrschaftlichen Waldungen haben nachweislich recht umfangreiche Rodungen stattgefunden,
um Platz für Siedlungen zu schaffen. Diese wurden dann mit Lansten, Festebauern, besetzt, die dann
ihre Nutzungsrechte oft recht unterschiedlich und, vom Wald her gesehen, recht unsachgemäß und
raubbaumäßig ausübten. Schon die Waldweidewirtschaft, daß man also das Vieh im Sommer in den
Wald trieb, hatte schädliche Wirkungen für denselben, namentlich für jungen Nachwuchs. Besonders
Schafe und Ziegen mögen wenig Rücksicht auf Schonungen genommen haben. Ebenso mußte sich die
Schweinemast ungünstig auswirken. Im Herbst wurden die Borstentiere von den Dreschkoppeln und
buschigen Niederungen zur Eichelnmast in den Wald getrieben. Wenn man bedenkt, daß jeder Hufner
30 - 40, ja 50 - 60, oft auch 80 Schweine hielt, läßt sich der Schaden ermessen, den diese Wühler im
Waldboden an Wurzeln und an jungen Pflanzen anrichteten.

Dann war der Bedarf zu Bau- und Nutzholz damals sehr groß. Die häufigen Brände in Stadt und Land
zwangen die Menschen immer wieder, Neubauten aufzuführen. Möbel und Geräte erforderten viel
Nutzholz. Und da Holz und Torf die einzigen Brennmaterialien waren, mußte der Wald das größte
Kontingent an Feuerung stellen, wobei nicht nur an unsere dörflichen Feuerstellen zu denken ist,
sondern auch an die Stadt. So erhielt z.B. der Haderlebener Amtman jährlich 3.000 Fuder, während sich
der Propst mit 400 begnügte. Dazu kam, daß die Köhlerei im Mittelalter in Blüte stand. Bäcker und
Schmied gebrauchten Holzkohle. Auch die Glashütten mußten versorgt werden (Gläserkrug). Alles auf
Kosten des Waldes.

Ungezählte Fuder gingen alljährlich in die Stadt als Deputatholz, an den Amtmann, den Schloßherrn
und seine zahlreiche Bedienung, das Domkapitel usw. Der Bauer erhielt Pflug-, Rade- und Brennholz
zugewiesen, meistens so reichlich, daß er davon verkaufen konnte. So trieb nicht nur die Herrschaft
einen lebhaften Holzhandel, sondern auch die Mehrzahl der Bauern. Und dieser Handel beschränkte
sich nicht nur auf die Versorgung des Inlandmarktes, sondern ging über Hoyer, Ripen, Flensburg,
Husum, Friedrichstadt und Tönning in zahlreichen Schiffsladungen ins Ausland. Wenn man weiß, daß
in Tönning vier Holzhändler ein gutes Geschäft unterhielten und daß eine Firma in Friedrichsstadt noch
in den Jahren 1760 - 1763, als der Waldbestand schon zusammengeschrumpft war, noch 42
Schiffsladungen nach Holland verfrachtete, ermißt man, was der heimatliche Wald hergeben mußte.
Und wieviel Holz wurde nicht dem Schiffsbau zugeführt und welche Unmengen gingen für Schleusen
und Siele, für Deich- und Schanzarbeiten. Jeder Deichbau erforderte tausende von Pfählen und tausende
von Fudern an Busch. Und Busch brauchte auch jeder Bauer und Kätner für seine Zäune und Hecken,
beim Hause, in der Toft und um die Saatfelder. Schutzzäune gegen Sandflug und Wild waren nötig,
Einfriedigungen, die ihrer Natur nach jährlich ausgebessert oder erneuert werden mußten. So war es
kein Wunder, daß nicht nur der Niederwald und das Unterholz knapp werden mußten, auch der
Hochwald litt sehr, weil man die Bäume ihrer Kronen beraubte.

Zu allem erlaubten Holzeinschlag kam dann noch ein nicht minder großer unerlaubter. Die
Brücheregister weisen eine erschreckende Zahl von Wald- und Holzfrevel aus. In einem Orte worden
15 Diebereien aus Hölzungen verzeichnet. Die Hohen Strafen, 50 oder 60 Mk, der Kirchenpfahl, “in
der Karre gehen”, “auf dem Esel reiten”, Gefängnis für 8 Tage bei Wasser und Brot, ja, einmal sogar
die Todesstrafe, alles hat dieser Leidenschaft nicht Einhalt gebieten können.

Auch die langen mittelalterlichen Kriegszeiten mögen dem Walde oft übel mitgespielt haben. Die
fremden Söldnertruppen hatten keine Ursache, den Wald zu schonen, oft schalteten sie sich gut
verdienend in den Holzhandel ein.

Als Grundübel muß aber erwähnt werden, daß ein Forstschutz völlig fehlte. Jeder versorgte sich so gut
es ging auf Kosten des Waldes. Keiner dachte an Waldpflege und an Neuanpflanzungen. So ist es
erklärlich, daß infolge der waldfeindlichen Haltung der Bauern und des Jahrhunderte langen Raubbaus
der Waldbestand zusammenschmolz. Als man mit Verordnungen eingreifen wollte, war es bereits zu
spät. Holzvögte, Waldaufseher und Wegereiter wurden nicht selten Bundesgenossen der Frevler. Auch
sie lebten, schlecht besoldet, auf Kosten des Waldes.

Dazu kommt, daß auf einer bestimmten Stufe die Natur den Menschen in seinem Vernichtungswerk
wirksam und wesentlich unterstützte: waren erst die Rand- und Schutzbäume fort, so war der Restwald
jedem Sturm und Wetter ausgesetzt und sein Untergang beschleunigt. Heute stehen nur noch einige
kümmerliche Kratte als Zeugen einstiger mächtiger Eichenwälder. Und mit dem Verschwinden des
Waldes ändern sich wieder Klima und Boden. Da von Kultivierung des wüsten Landes noch keine Rede
sein konnte, kam eine andere Vegetation herauf, die Heide. - Von den Kampf unserer Vorfahren mit
ihr berichten die nächsten Blätter.

=== 4.2 Wildbestand und Jagd

Wildbestand und Jagd hängen mit dem Schicksal des Waldes eng zusammen. Viele Urkunden
bezeugen, daß unser Wald auch sehr wildreich gewesen ist. In Waldemars Erdbuch (1231) werden
Edelhirsche, Damhirsche, Wildschweine und Bären genannt. Bodenfunde in unserm Kirchspiel
bezeugen, daß auch wir Anteil daran gehabt haben. Es wurden von dem Bauern Nicolai Johannsen in
Ellhöft im Wiesengrund nördlich des Dorfes Teile eines Elchgeweihes gefunden. Der Arbeitsdienst
machte bei Entwässerungsarbeiten im Karrharder Alten Koog zwischen der Böglumer Zollstelle und
Ellhöft unmittelbar an der Bundesgrenze einen wertvollen Fund: Ein Elchgeweih eines kapitalen
Zwölfenders lag im Moor in einer Tiefe von 1,20 m und in der Nähe die Stange eines alten Rothirsches,
eines Achtzehnenders, deutliche Beweise dafür, daß auch unsere Gegend edles Hochwild beherbergt
hat. Um 1600 wird noch der Biber erwähnt. Um 1689 soll in der Frösharde der letzte Luchs geschossen
worden sein. Besonders stark verbreitet waren die Wildschweine. Sie haben nicht nur in den Wäldern,
sondern auch auf den angrenzenden Weideflächen und Saatfeldern der Bauern großen Schaden
angerichtet. Die Bauern beschwerten sich wiederholt in Eingaben darüber, hatten aber meist nur wenig
Erfolg; denn die Jagd war ein Vorrecht des Landesherrn. Bäuerliche Belange hatten hinter der
Erhaltung der Wildbahn zurückzutreten. Der Bauer selbst durfte nicht schießen. Das Verbot bezog sich
auf Schießen, Jagen, Hühnerfangen und Fischen.(1616) Es heißt dort, _"daß nicht allein nach
dieses Fürstenthumbs, sondern auch nach gantze Deutschlands übler Gewohnheit den Bauernstandes
Personen das Jagen Und schießen keines wegen beikommt"_ , würden doch sonst die Ausbeuten
landesherrlicher Treibjagden geschmälert wurden.

Treibjagden gab es auf Hochwild, Wildschweine, Füchse und Wölfe. Letztere waren das ganze
Mittelalter hindurch eine Landplage. Sie dezimierten den Viehbestand der Bauern, taten dem jagdbaren
Groß- und Kleinwild großen Abbruch und gefährdeten z.T. das Leben der Bevölkerung. An anderer
Stelle ist schon der Grenzdistrikt zwischen Schlux- und Karrharde als vorzügliches Jagdbebiet erwähnt
worden. Und wir haben noch eine Erinnerung an ferne Belästigungen in dem Flurnamen
Uhlekuhlacker(Wolfschlucht). Für solche Jagden mußten die Dorfschaften die Treiber stellen.
Außerdem mußte Proviant geliefert und Jagdgeld bezahlt werden. Lügum zahlte 28 Rthl 36 ß an
Jagdgeldern, jedenfalls dafür, daß durch das Wegschießen des Wildes der Feldschaden vermindert
wurde. Und jedes volle Bohl mußte jährlich zweimal 4 Pfd. Brot liefern.

Mit dem Schwinden des Unterholzes sowie des Waldes überhaupt und mit der zunehmenden
Besiedlung und Kultivierung wurden auch die Wölfe seltener. Wenn die Jagdordnung von 1784 noch
Bestimmungen über die Ausrottung der Wölfe enthielt, so war ihre Zeit mit dem Beginn des neuen
Jahrhunderts doch dahin.

Auch die Füchse fanden in den unterholzreichen Wäldern und in den Kratt- und Buschpartien der
Feldmark, die ja wegen der Jagd nicht gerodet werden durften, gute Behausungsstätten.Auch sie
wurden zeitweilig zur Plage und mußten durch Treibjagden, zu denen die Bauern wieder pflichtig
waren, bekämpft werden.

Der großen Zahl von Raubvögeln muß auch Erwähnung getan werden: Gänseadler, Uhu, Habicht,
Sperber, Raben, Krähen und Elstern. Da sie die Wildbahn schädigten, wurden Abschußverordnungen
erlassen und ansehnliche Schußgelder ausgesetzt (1690).

In allen Verordnungen spürt man das Bestreben, die Wildbahn zu schützen, den Wildbestand zu
erhalten und zu heben und eine reiche Jagdbeute für den Grundherrn sicherzustellen. Da nur wenig
Rücksicht auf die bäuerlichen Belange genommen wurden, ist es verständlich, daß der Bauer zur
Selbsthilfe greift. Er nimmt den Kampf gegen das ihm schädliche Wild selbst in die Hand, befreit sich
dadurch von lästigen Schädlingen und liefert seiner Küche manchen Braten. Dabei wächst der Appetit:
hat er sich zunächst mit Kleinwild und Hühnern begnügt, wagt er sich doch bald an die ergiebigere Jagd
auf Großwild. Heimlich schießt er alles weg, was ihm vor die Flinte kommt und kann so einen guten
Teil davon zum Verkauf stellen. Und die städtische Bevölkerung, besonders auch Offiziere von
_"unserer eigenen Soldatesque"_ (1695) beteiligt sich an dem unerlaubten Handwerk, nicht _"bedenken,
daß endlich die Wildbahn als ein kostbares Kleinod gar ruiniret und vernichtet werden Muß"_. Daß
Verordnungen gegen die Wilderer wiederholt und verschärft werden müssen und empfindliche Strafandrohungen enthalten, beweist, daß
sie keinen Erfolg haben. Es gibt unglaubliche Geschichten von Berufswilderern.

Erst die Verkoppelungsverordnung um 1770 leitet eine Zeit ein, die endlich die Förderung der
Feldkultur vor die Belange der Wildbahn und der Jagd stellt. Das Verbot, das auf den Feldern der
Untertanen stehende Strauchwerk wegzuräumen, wird aufgehoben. Die Bekämpfung des Raubzeugs
wird leichter. Neue Jagdgesetze berücksichtigen die Interessen des bäuerlichen Lebens. Seit 1848 darf
der Bauer auf eigenem Grund und Boden selbst die Jagd ausüben.

Da er sich aber, diese Freiheit mißbrauchend, oft zu schonungslosen Abschüssen verleiten läßt, die mit
Wildpflege und Schonung im Interesse des Bestandes, mit Gedanken, die heute in den Hegeringen
lebendig sind, unvereinbar sind, so ist es erklärlich, daß der Wildbestand zurückging. Erst die
Verwirklichung dieser Gedankengänge, neue Forst- und Jagdgesetze, Forstaufsicht und weidmännische
Schulung, besonders aber neue Aufforstungen haben eine begrüßungswerte Wandlung geschaffen.