== 5. Die Dorfwillkür
Jedes Dorf bildete im Mittelalter einen kleinen Staat im Staate, der sich um die Landesherrschaft wenig
kümmerte und deren Gesetze und Verordnungen nur mit Widerwillen respektierte. Das kleine
Gemeinwesen kam sich in seinen Machtbefugnissen fast souverän vor. Seit alter Zeit galt das aus
seelischer Haltung und wirtschaftlichen Bedürfnissen heraus geborene Recht, das einst in Urvätertagen
geworden war. Dieses hatte sich von Generation zu Generation mündlich überliefert. Bis zum Anfang
des 18.Jahrhunderts hat der Staat in die rein dörflichen Angelegenheiten kaum eingegriffen. Aber schon
ein paar Jahrhunderte früher lagen für das Dorf doch wichtige Gründe vor, die es angebracht erscheinen
ließen, allerlei feldpolizeiliche Vorschriften zu erlassen und diese Übereinkommen nun schriftlich in
einer sogenannten Beliebung oder Willkühr festzulegen.
Die erhaltenen Beliebungen geben uns allerdings kein vollständiges Bild von dem damaligen dörflichen
Zusammenleben. In ihnen ist vielmehr nur das aufgenommen und festgehalten worden, was in früheren
Zeiten Veranlassung zu Streitigkeiten gegeben hatte und auch voraussichtlich weiterhin Gegenstand
des Zankes werden konnte. Was den Leuten damals als unumstößliche Einrichtung und selbstver-
ständliches Brauchtum erschien, brauchte natürlich nicht besprochen und niedergeschrieben zu werden.
Für das Verständnis der alten Dorfverfassung ist es wichtig, daß wir uns an die bäuerlichen
Besitzverhältnisse in der Zeit vor der Feldaufteilung erinnern. (Siehe den betr. Abschnitt).
Das Original einer Lügumer Dorfwillkür ist mir bis heute nicht zu Gesicht gekommen, obgleich
bekannt ist, daß hier schon 1520 eine Beliebung aufgerichtet worden ist. Es heißt darin betr. Wisch-
und Medeland, daß sie _"zusammen liegen haben und ein Jeglicher sonst seinen Antheil begraben und
befriediget in meinung für demselben" und "daß einem Jeglichen, auf welche Zeidt sein Vieh, Pferde,
Ochsen, Schweine und Schafe , darauf zu treiben und hinwiederumb davon zu lassen, mandieret, und
bey hohester Strafe gebetten und verbotten"_ .
Da nun dieses für den Ertrag und die Erhaltung der Wiesen wichtige Dorfgesetz in den vier Dörfern
Lügum, Humterup, Braderup und Klixbüll im Laufe der Zeit in _"ungebürlicher Weise"_ immer mehr
mißachtet, einige gar _"zu nachtschlafender Zeidt ihre Pferde auf solche unser Wisch- und Medelandt
treiben, darauß dan schir groß Parlamendt und Unheil entsprungen, man dem uralten Gebrauche nicht
mehr gemeß leben will"_ , so bittet man 1611 die Landesherrschaft, einzuschreiten, die alte Willkür zu
bestätigen und sie bei ihren Rechten wirksam zu schützen, welches denn auch vom Herzog Johann
Adolph getan wird.
Obgleich 1693 von einer Lügumer Willkür, _"bestehend aus 7 Stücken"_ die Rede ist, ist bis jetzt, wie
gesagt, keine auffindbar gewesen. Dafür konnte ich aber eine fast 100 Jahre ältere Wimmersbüller
Beliebung als eines der wertvollsten Dokumente mittelalterlicher Dorfgeschichte ans Licht ziehen:

[quote]
____
* "Der Dorpschop Wimersbüll +
Einhellig Compromis oder Willkühr. *

Im Nahmen des Ewigen Gottes der Untrenbahren Hilligen Dreyfaltigkeit Amen.
Johann von Böhl Chronik des Kirchspiels Süderligum Seite 65
Kundt und tho wethende sy allen und Jedermennichligen, wes würden odder standes desülven
Jümmer syn mögen, dath wy sambtl. Inwahners tho Wimmersbüll an Bunden und Landtsten
ungeschieden, d. 9. Monathdag May Anno 1602....na Christy unsers verlösers gebort in des
Schriwers Jonas von Elwerfelden Huse tho Lügum byeinander sin gewesen, und hebben
darsülvest tho forderligsten Heil und nütze der gantzen gemeine des Dorpes Wimmersbüll ein
ordentlich Compromis oder Willköhr in etl. puncten angeordnet und upgerichtet welch wy
nachmals tho ewige Tiden vor uns und unsere Erwen oder Nahkömlingen by folgender poena
unverbracken belevet und geholden willen hebben, und sin de Nahmen der Bunden und
Landtsten, so in dyth willköhr gewilliget gewesen wi folger:

Andreas Ebsen, Carsten Feddersen, Bonnicke Hansen, Peter Ebsen, Jens Petersen, Iwer Nissen,
Lüdde Tortzen, Fedder Lützen, Fedder Petersen, Iwer Petersen, Andreas Bosen, Matz Bosen,
Tord Andersen, Iwer Tortzen, Carsten Petersen und Andreas Bosen der Jünger, alle Landsten
und Bunden tho Wimmersbüll.

1. Fürs Erste schölen alle Inwahners des Dorpes den gewontl. Schütte-Hägen Jährlich up unser
lewen Fruendag in der Vesten upbuwen und unstraflich ferdig maken, wofern sich auerß dessen
Jemandt verweigern und in solchen falle brökhaftig werde werden der oder die sülven schölen
ein ieder, so edder silkes geschütt an de verordnete twe Häges-Lüde einen halven Dahler
verbraken hebben.

2. Thom andern schall ein Jeder sin Lücken oder Dicke binnen und butten Dörpes, ydt sy woe
ydt wolle, tho Jeder Tidt von Maidag upsetten und ferdig holden, wo solckes als denne ock mit
den Hecken vor denne Dorpe gelicker mahten schall geholden warden. wofern auerß dor
urbauen Jennig mangel an den gemeinen Lücken und Hecken von dem Dörpe tho Jeder Tidt up
Maidag warden befunden, so schölen de verordnete twe Heges Lüde alles in ogen schin nehmen
und den bröckhaftigen tho jeder tidt ein pandt up twee schilling uthpanden.

3. Thom drüdden schölen alle inwahner des Dorpes Kraft dieses verpflichtet sein alle er quicke
und Mödere twee weeken vör Maidag von den Ackern tho holdende, beth und so lange de
sambtl. gemeine ehre wische vor de Besste uphegen, wi inglicken de Göße und Schwine von den
Acker up Maidag geheget schölen sin, De Göße auerß schölen gentzl. uth denne Dorpe
afgeschaffet warden, so lange dat dat Korn gantz und gahr uth denne felde ist weg geborgen
einem Jeden by verlust seiner Göße. Idt schall ock ein Jeder sin Schwine Beeste und Modere
also fohrt na verlopenen Maidage up sine egen ackern und Landt schlagen und holden, und
welcke ehre Modere oder Beeste darutbauen up eines andern Mans acker mothwillig werde
schlan, so schölen de obgemelte Heges Lüdde gemächtiget sin, den oder desülvigen, vör ein
Jeder Beeste oder Modere, so ofte dor up warden beslagen erstl. up einen schilling, thom
andern up twee, und thom drüdden up drey schillink und also warden höger, uth tho pandende,
beth und so lange so dyt gemeine willköhr in diesem puncte gehorsambtl. infolgen warden, ock
de verordnete Beiden Hegeslüde hirmit jennig ansehen der Persohn betrachten und gonst und
gaue dor vör nehmen, so schall ein Jeder von den Heges Lüden der gemeine dar vör geuen ein
Thonne dubbelt Behr, so ofte einen solckes auerwiset kan warden.

4. Thom verden hebben wy uns verwillköhret, dat von einem Jeden sine Schwine wanner ehme
solckes tho rechter Tidt von den Heges Lüden ward angekündiget, unstrafl. geplügget schölen
warden, damit se der gemeine Keinen schaden tho fögen, woll dar auer ungehorsahmbt
befunden warden von demsülvven schölen de Heges Lüden vör jedes schwin ein pandt up twee
schilling nehmen so ofte he ydt verbrickt.

5. Thom vöften ys einhellig von uns belevet dat ken Man von den Nabern frömbde Schape und
schwine up de gräßung tho denne Dorpe schall nehmen allß by verlust solcker upgenahmen
schape und Schwine stede und Feste tho holdende, woher ydt sick tho drogen dat einer oder
mehre in denne Dorpe sin scharr an schape und Schwine nicht warden ful hebben, wat in den
sülven von den gemeinen Dorpes Lüden up Jedes Boel bewilliget wahrt, so schall denes na
antall der Schwine und schape öuer dat gantze Dorpe gerecknet warden, und densülven so auer
Göße mehr allß schape und schwine hebben, erhelt allß bald wat ehme mit kan tho gerecknet
warden, dörch de verordnete 2 Heges Lüde ungehindert verschaffet oder ock dörch genöghafte
pandt uthgepandet warden, darinne schölen de gemeine Dorpes Lüde de gemeldten Heges
Lüden behülpl. sin, und wehr sich Kegen solcke uthpandung mothwillig warde varholden,
desülve schall der gemeine tho Jeder Tidt einen Rickes Daler thor Bröke geuen.

6. Thom Sösten hebben wy sinhellig beschlaten, dat dar Kein mandes, he sy wehr he wolle, sin
quick oder Mödderperde mottwilliger wise in de vange schall schlagen, ehe und bevohr dat
Korn und Höv rein daruth mag geborgen ys worden, den Auertredder schölen de Heges Lüde
vör Jedes mahl up veer schillinck uthpandigen.

7. Thom Sövenden schall sick Kein mandes gelüsten lahten, sine Beeste oder Möddern Twischen
eines andern Korn in den grauen in tho trecken und tho hödende, wehr auerß dar bauen
mothwillig ward befungen, desülve schall tho jeder Tidt von deme gerichteschriwer vor Einen
Rthl tho F.H. Register geschreuen warden.

8. Thom Achten ist von uns Compromittiret und bewilliget wofern Jemandes unßere gemeine
Schütte-Hege upbrecken und sine Beeste, quick und Möddern daruth ward nehmen, dat alß
denne de tho jeder tidt verordnete twe Heges Lüde den oder desülvigen mit Dings Dohm und
alles Touß mahlen up der gantzen gemeine uncosten gerichtl. schölen verfolgen.

9. Letzlich und thom Negenden willen und ordenen wy in dießer unßerer gemeinewillköhr, dat
de twe Heges Lide so jedes jahr van der gemeine verordnet, de dieke vör frömbt quick und
Beeste, wi desülve ock nahmen hebben möchten, wehren und hegen und na ehren gefallen
darvan nehmen schölen, wi ock Keinmandt von de Inwahners den Diek schölen begräßen, mit
ehre Beeste, Idt sy denne dat solches erstl. von den gemeinen Inwahnern bewilliget ist worden.
Ock ist hirby tho wehtende dat wy einhellig mit dießen unsern Compromis hebben ingefolget,
so Jemandts denne gewandtl. Dingwalle wanner desülve in denne Dorpe upholte, umbgedragen
oder von Nabern tho Nabern angekündiget ward, in de ungehorsahmbl. nach würde folgen, dat
dersülve den nabern eine Thonne dubbelt Behr schall thom Besten geuen, kunde auerst de
Hußwehrt bewisen, dat he nicht tho Huß währe, so schall he denne sin Volck darsülvest thor
Antwort lahten kamen und darmit genogsahms entschuldiget sin.

Dieße obgeschreuen Stück und articul sambtl. und eine Jeden besonderl. hebben wy vorernante
Inwahners tho Wimmersbül, an Bunden und Landtsten vor uns und unsere Eruen oder
Naköml.Bockstaffliches inhalts belevet, schollen ock von uns und den unsern tho keiner Tiden
Kindt noch Kinder vorgebohren und ungebohren in Beste- oder geringsten nicht auergetreden,
sondern viele mehr, by vorgeschreuener poen unverbracken geholdet warden, Ohrkundtlich mit
unser aller gewontl. Insegel versegelt getecknuß, vor uns und unsern Eruen bekrefftiget.
Ut supra +
Andreas Ebsen 

Peter Ebsen + 
min handt +
Fedder Petersen 

Karsten Petersen +
Von wegen dat Bunden +
Landt +
Min Handt 

Dat Bauen +
geschreuen +
Bekenne ick +
Carsten Petersen +
anstedt und von wegen +
Mines Moders gut +
Mit Egene Handt".

Zeichen und zehn Siegelabdrucke
____

Und nun einige Bemerkungen zu den Beliebungen im allgemeinen und zu der obigen im besonderen:
In jeden Abschnitt werden die _"Heges Lüde"_, die Hegemänner, erwähnt. Da sie ursprünglich nach der
Zahl der vorhandenen Bohlsstellen ernannt wurden, schwankt ihre Zahl. In Wimmersbüll waren es
zwei, in Lügum acht. Sie wurden jedes Jahr von den Dorfsleuten, d.h. von den Bunden und
Lansten(=Festebauern), gewählt und hatten dann als Aufsichtsmänner _"fleißig Achtung"_ zu geben, daß
die einzelnen Punkte der Willkür genau befolgt wurden.

Zuwiderhandlungen der Einwohner gegen die Satzungen wurden von den Hegemännern je nach
Schwere der Verfehlung mit einer in der Beliebung festgesetzten Brüche bestraft. Säumselige sollten
ausgepfändet werden. Vor allen Dingen durfte sich kein Dorfbewohner unterstehen, ungehorsam gegen
die verordneten Hegemänner zu sein. Kam das vor, so sollten die Dorfsleute ihnen behülflich sein.
Schwierigkeiten bei der Auspfändung wurden mit 1 Rthl belegt, einer nicht unbeträchtlichen Strafe,
wenn man bedenkt, daß damals ein fetter Ochse ca 16-18 Rthl kostete. Wer den Schütte-Hege
(Schüttkoben), in die herrenloses Vieh oder solches, das auf verbotenen Plätzen zur Unzeit aufgegriffen,
eingeschüttet war, aufbrach und sein Vieh befreite, wurde beim Dinggericht angezeigt.

Damit die Beliebung mit allen ihren Einzelheiten den Leuten lebendig in Erinnerung blieb, wurde sie
meisten jährlich _"umb Ostern in sämbtlicher Dorfleute Gegenwart"_ verlesen. Zu diesen
Zusammenkünften mußte der Hauswirt selbst erscheinen oder einen andern schicken. Die Bekanntgabe
in der Dorfschaft ging durch Schriftstück mittels Dingsrolle oder Thingstab von Nachbar zu Nachbar.
Wer seinen Nachbar nicht ansagte, hatte eine Tonne doppelt Bier an denselben zu liefern.
Aber auch mit der "hohen Dorfobrigkeit" hatte man wohl mitunter schlechte Erfahrungen gemacht, so
daß man es für richtig befunden hat, sie unter dasselbe harte Strafrecht zu stellen: Wer von den
Hegemännern säumig war, durch die Finger sah und sich durch Gunst und Gaben bestechen ließ,
mußte, so oft ihm solches nachgewiesen werden konnte, an die Dorfschaft eine Tonne Bier zahlen.
Es lag im Wesen der Feldgemeinschaft begründet, daß das gesamte Vieh der Dorfschaft
gemeinschaftlich auf den für die Gräsung ausgelegten _"gemeinen"_ Weiden gegräst wurde. Gewöhnlich
wurde jedes Jahr vor Maitag ein Überschlag gemacht, wobei genau festgesetzt wurde, wieviel Vieh jede
Stelle gräsen darf. Oft finden wir solche Zahlen in den Willküren verzeichnet. Über diese Zahlen hinaus
dürfen die Bohlsleute nicht gehen. Unter Schweinen, Schafen und Gänsen kann allerdings ein
Austausch stattfinden. Fremdes Vieh darf keiner ins Gras nehmen. Dieser Passus ist wohl
hineingebracht aus Angst vor Einschleppung der Viehseuchen, die, besonders im 18. Jahrhundert,
unsere Kirchspiele in verheerender Weise heimgesucht und die Viehbestände oft furchtbar gelichtet
haben.

In jedem Jahre zwei Wochen vor Maitag wurde die Weide neu befriedigt. Die Tiere mußten dann von
den Äckern und Wiesen entfernt werden. Die Gänse durften erst wieder erscheinen, wenn das Korn
geborgen war. Auch wurden die Wiesen erst wieder freigegeben, wenn das Heu eingebracht war.
Sicherlich hat man auch schon in Bezug auf das "Mein und Dein" trotz aller Gemeinschaftlichkeit
schlechte Erfahrungen gemacht. Darum wird ausdrücklich bestimmt, daß keiner sein Vieh auf anderer
Leute Land schlagen durfte. Wer mit seinem Vieh zwischen anderer Leute Korn ertappt wurde, mußte
sogar an die Obrigkeit 1 Rthl zahlen. (Punkt 7). In Westre wurde dieses Vergehen 1743 mit 2 Rthl und
1/2 Tonne Bier bestraft.

Eine wichtige Person war zu der Zeit der Feldhüter oder Dorfhirte. Mit ihm wollte es keiner gerne
verderben, weil ihm während des ganzen Sommers das gesamte Vieh der Nachbarschaft zu treuen
Händen übergeben war. In der abgedruckten Willkür fehlte eine Bestimmung über den Dorfhirten.
Bekannt ist aber, daß es einen gegeben hat und daß Haus Nr.11 das Haus des Dorfhirten war. In Westre
heißt es: _"Es soll die ganze Nachbarschaft ihr Vieh vor einen Hirten schlagen und niemandt erlaubet
seyn, seyn Vieh vor sich selbst zu weyden bei 8 Schilling Strafe"_ . Im Erdbuch von 1613 wird für Lügum
Jenß Peterßen als _"Koharde"_ genannt. Mit dem Dorfhirten wurde ein besonderer Traktat abgeschlossen.
Da das Amt oft wechselte, der Lohn auch sehr verschieden war, ist anzunehmen, daß jeweils der
Mindestbietende diesen Posten erhielt. Der Hirte hatte neben einer bestimmten Summe Geldes in bar
frei Wohnung im _"Harder-Haus"_ , bei dem der stets erwähnte Kohlgarten nicht fehlen durfte. Ferner
durfte er einige Kühe und Schafe frei gräsen. Stellenweise erhielt er auch an jedem Sonntagmorgen
die Hälfte der Milch des ganzen Dorfes von Ostern bis Martini und durfte zu Weihnachten von Haus
zu Haus gehen und um eine Gabe bitten, deren Größe in jedermanns freier Beliebung stehen sollte.
Gewöhnlich hatte er auch ein Stück Moor zugewiesen erhalten, wo er seinen Torf graben konnte. Seine
Ackerarbeiten und Fuhren sollten von den Bohlsleuten zur _"gewünschten Zeit"_ verrichtet werden. Da
bei der Feldaufteilung später seine Gräsungsgerechtigkeit fortfiel, erhielt er als Ablösungsobjekt die
_"Hirtenwiese"_. In Lügum trägt sie noch heute diesen Namen.

Da der Hirte nach diesem ein ganz angenehmes Auskommen hatte, war der Posten sicherlich sehr
begehrt. Sein Aufgabenbereich konnte recht verschieden sein. Der Haupthirte war der Kuhhirte, aber
auch das Jungvieh, die Kälber, die Schafe, selbst die Schweine, und wenn es gewünscht wurde, auch
die Gänse, mußten beaufsichtigt werden. Oft hatte ein Mann das Hirtenamt für das gesamte Vieh, wobei
dann sicher die Familienangehörigen haben helfen müssen.

Das ständige Verwenden der größeren Kinder zum Viehhüten war auch die Ursache für die ewigen
Klagen der Schulmeister über den schlechten Schulbesuch derselben im Sommer. Während die
Mädchen schon mit 5 oder 6 Jahren beim _"Spitzenmachen"_ beschäftigt wurden und bis zu ihrer
Konfirmation die Schule nur in den kurzen Wintermonaten besuchten, wurden die Knaben im Felde,
im Heu, in der Ernte, im Moor und als Hütejungen eingesetzt. Die große Armut der Kätner und Insten
zwang eben dazu, die Kinder zum _"Dienen"_ aus dem Haus zu geben und jede Verdienstmöglichkeit
auszunutzen. Als die allgemeine Weide in Fortfall kam und das Amt des Dorfhirten aufhörte, hielten
sich viele Besitzer einen Hütejungen für ihr eigenes Vieh, da ja die mangelhaften Einfriedigungen der
Privatweiden weitere Aufsicht über die Tiere erforderten. Noch vor 50 oder 60 J ahren, als die Haine,
das Pastoratsland westlich des Dorfes Lügum, an Kätner verpachtet war, ließen diese ihre Kühe durch
Jungen auf dem damals noch ganz uneingefriedigten Land gräsen. Dasselbe geschah in Ellhöft auf den
Allmerstücken.

Jeden Morgen wurden die Kühe dem Dorfhirten übergeben, jeden Abend lieferte er sie zur Melkzeit
wieder in die Toft beim Hause. Die anderen Tiere dagegen blieben oft draußen auf der Weide, wo sie
für die Nacht an einen besonderen Platz, die Fohl oder Fool, getrieben wurden. Der Name ist noch als
Flurname in Süderlügum und Ellhöft erhalten. Auch im Nordteil des jetzigen Waldes ist noch ein
umwallter Platz nachweisbar.

Auf die Weide getrieben, mußten alle Schweine mit Ringen in der Nase versehen sein, damit sie den
Boden nicht aufwühlten. Über die Gänse ist in der Wimmersbüller Willkür nur wenig gesagt, während
z.B. in Westre genau festgelegt war, daß _"eine alte Gans auf jeder Mannes Theil gehalten werden"_ , daß
dafür 1 Schilling Grasgeld zu bezahlen sei, daß, wenn es verlangt wird, sie _"einen Harder zu die Gänse
halten, und daß auf 3 alte Gänse ein Gander (Gänserich) kommen sollte"_. In Lügum erinnert der
Flurname _"Gooskilde"_ noch heute an die frühere Zeit.

Weiter enthält die Willkür neben diesen viehwirtschaftlichen Bestimmungen eine Reihe von
Vereinbarungen, die sich auf die Hegung der Felder, die Ackerwirtschaft, Wälle und Gräben, Wege und
Deiche beziehen. Die Instandhaltung dieser Einrichtungen bildete ja eine wesentliche Voraussetzung
für die gemeinschaftliche Wirtschafts-führung.

Für die Unterhaltung der Wege mußten die Bohlseingesessenen selbst Sorge tragen. Jedem war sein
Stück Weg zur Ausbesserung zugemessen. Das Ackerland war in Schläge für Sommer- und Wintersaat
eingeteilt, auf denen jeder Bohlsmann nach Maßgabe seines Anteils an der Feldmark seine Parzelle zu
bewirtschaften hatte. Gleichzeitig erfolgte Aussaat und Ernte. Genauso bei der Heuernte. Die
Hegemänner und die Ältesten im Dorfe sollten dann, _"eine gewisse Zeit anzusetzen, umb welche die
Wischen und der Rocken in 4 Tage gemähet und in 2 Tage zu Hause gefahren werden soll, und zwar
dergestalt wie es sämbtlichet Dorfsleute am nützlichesten seyn könnte"_ . - Nach der Ernte wurde das
Vieh auf die Stoppeln geschlagen, aber erst dann, wenn _"die letzte Garbe vom Feld eingeborgen war"_ .
Trotz dieser Feldgesetze, die zum Teil hohe Strafen festsetzten, werden immer wieder Übertretungen
gemeldet. Allein für das Jahr 1725 fand ich in den Verhörsprotokollen drei Fälle verzeichnet:

1. Auf die Klage einiger Einwohner wird dem _"größten Theil denen Eingesessenen des Dorfes Lügum"_
folgendes eröffnet: _"Auf der Supplicanten bescheidenes ansuchen wird mittelß dießem allen und jedem
des Dorfes Lügum Eingesessenen alles ernstes und bey 50 Rthl strafe angefohlen, daß sie sich nicht
unterstehen sollen, ihr jung Vieh vor d. 1.May auf des Dorfs gemeine Feld zu schlagen; im fall aber
sich jemandt finden möchte, der das seynige so lange mit futter nicht unterhalten könnte, soll demselben
dennoch keines weges erlaubt seyn, solches anders alß in zeyner abgegrabenen Fenne zu halten, bey
vorgedachter brüche"_ .

2. _"Denen sämbtl. Eingesessenen in Lügum wird hierdurch alles ernstes, und zwar bey 20 Rthl Königl.
Brüche anbefohlen, daß sich niemandt unterstehen soll, eingemeldetes Land, so sich an der
Uhlenbergerfeldtscheidung erstrecket, nemlich Gulum und Graßham genannt, mit Vieh, sonder allein
mit Pferden zu begräßen, wie auch sonst anderweitig nichts auf dem Felde Verwahrloß laufen zu
lassen, sondern entweder in ihren eingegrabenen Fennen, westen Tunderdamm, da auch würklich vor
dem Vieh hiert gehen lassen sollen, und falß jemands Vieh in Gulum oder Gräßham, oder sonst auf
gemeinem Feldt anderswo als vor dem Vieh hiert erfunden wird, soll derselbe nicht allein in gedachte
Brüche verfallen seyn, sonder Es soll auch sodann der Fußknecht befehliget werden, selbiges Vieh
sogleich auf der Stelle Todt zu schießen gestalt dann auch alles ernstes und bey 100 Rthl Strafe
inhibiret wird, daß niemandt mit gekauftem Vieh entweder Von Jahr Merkten, bekandten oder
unbekandte Örtern, zu Dorfe kommen soll, es sey denn daß sie mit Eydtlichen glaubhaften Attesten
Versehen seyn, daß das Vieh gesund und von gesunden Örtern hergekommen."_

3. Die Einwohner des Kirchspiels Ladelund und Westre klagen gegen die Dörfer Carlum, Lügum und
Rentz, besonders gegen den Müller Hans Friedrichsen in Ladelund. Letzteren wird nun _"bey schwerer
ahndung, und willkührlicher Brüche anbefohlen, daß sie sich nicht unterstehen sollen, denen
Supplicanten mit ihrem Vieh zu nahe zu treiben."_ Es wird ihnen, besonders den Karlumern, dringend
geraten, _"ihre Hunde so wol des tages, alß des nachts angebunden zu halten, wiedrigen falß der Ambts-
Fußknecht befehliget werden soll, auf der Supplicanten unkosten alle und jeden Hundt todt zu
schießen."_

In den beiden letzten Beispielen ist es wohl besonders die Angst vor Einschleppung der Viehseuche,
(siehe den besonderen Abschnitt), die Vorsichtsmaßnahmen und Höhe der Strafe diktiert.

Im ganzen hat man den Eindruck, daß die Beliebung für die Dorfschaft ein sehr wichtiges Dokument
gewesen sein muß. Satzungen regelten in alten Tagen das dörfliche Leben für manches Jahrzehnt und
richtete es in bestimmter Richtung aus. Den Originalen sieht man es an, daß man sie immer wieder in
die Hand genommen und studiert hat. Derbe Bauernfäuste haben ihre Spuren hinterlassen.

Die alten Willküren sind von Zeit zu Zeit erneuert und den veränderten Verhältnissen angepaßt worden,
so erneuerte Westre 1723 und 1743. Noch in diesen Dokumenten findet sich der Ausdruck _"vör ewige
Tiden"_ . Die letzten Verfasser konnten ja auch nicht ahnen, daß ihrer Arbeit nur eine verhältnismäßig
kurze Lebensdauer beschieden sein sollte. Schon 1766 kamen die ersten Verkoppelungsverordnungen
heraus. Die Durchführung der Bestimmungen über die Feldaufteilung hat überall große Aufregung und
viel Lärm und Streit in die friedliche Nachbarschaft gebracht. (Siehe den Abschnitt "Kampf gegen die
Heide"). Die Zeit der Dorfwillkür war vorbei.