== 8. Unsere Moore

=== 8.1. Die Entstehung der Moore
Ein Moor entsteht immer in einer abflußlosen Mulde. Es sind Seen, die durch Moorwachstum
allmählich verlanden. Auf undurchlässigem Grund solcher Mulden sammelt sich das Wasser
zu einem See, in dem dann durch unzählige kleine und kleinste Lebewesen pflanzlicher und
tierischer Art eine Unmenge von Sinkstoffen zu Boden gehen. Dieser sogenannte Faulschlamm
erhöht nach und nach den Boden. Am Ufer siedeln sich bald Pflanzen an, Uferschilf befestigt
den Boden und schiebt sich immer weiter in den See hinein. Das Ganze wird ein Schilfmoor.
Zweige, Laub, Rethreste, sterbende Pflanzenteile festigen den weichen schwimmenden
Seegrund. Am Rande bilden sich Soggen- und Binsengürtel, Erlen schlagen Wurzel, saure
Gräser, Süßgräser bilden dünne Humusschichten.

Über der untersten Schilf-, Soggen- und Bruchwaldtorfschicht findet man oft zahlreiche Reste
von Waldbäumen (Birken, Kiefern), die also auf dem Moor gestanden haben müssen. Das Moor
hat sich also einmal bewaldet. Da sich darüber aber wieder Torfschichten finden, ist die
Waldperiode nur von kurzer Dauer gewesen, was bei gleichbleibendem Klima und Wasserstand
kaum zu erklären wäre. Nur die große Landhebung vor 10.000 Jahren, die Anglushebung, und
die spätere Landsenkung mit gleichzeitigem feuchten Klima, die Literunasenkung, können diese
Erscheinung verständlich machen. In der Trockenperiode der Hebung konnte der Wald
aufwachsen, in der feuchten Senkungszeit ging er wieder unter. Da hatten die Torfmoose die
ihnen gemäßen Lebensbedingungen und überwucherten alles. Dieser Moostorf, entstanden in
der Zeit von ca. 7000 - 2000 v. Chr., ist wertvollster zersetzter Brennstoff. Da diese Schichten
nur 1-5 m stark sind, nach der Zeit ihres Wachstums aber viel stärker sein müßten - 1.000 Jahre
sollen 1 m ergeben - , so muß schon eine Unterbrechung der Torfbildung stattgefunden haben.
Und tatsächlich haben wir vom Ende der jüngeren Steinzeit (ca. 2000 v. Chr.) bis zum Ende der
Bronzezeit (ca. 700 v. Chr.) eine Trockenperiode durchgemacht, die die Schichten mit
Heidekraut überzogen, den Torf zersetzten und zusammenpreßten, um erst bei einsetzendem
feuchten Klima das Wachstum der Spaghnummoose wieder fortzusetzen und die letzte, obere
Torfschicht zu bilden. Die ist unzersetzt, rauhfaserig, hellbraun und von geringerem Brennwert.


So ergaben sich folgenden Schichten, die ihrem Alter
und ihrer Entstehung nach von unten nach oben zu lesen sind:

|===
| Jüngerer Moostorf, unzersetzt | gebildet seit der Eisenzeit +
700 v. Chr. bis heute
| Älterer Moostorf, zersetzt | aus der Zeit der Landsenkung +
7000 - 2000 v. Chr.
| Waldtorf, Kiefer, Birke | aus der Zeit der Landhebung
| Seggen- und Bruchwaldtorf +
Schilftorf +
Faulschlamm | aus der Zeit der Verlandung
| Tonmudde | aus der Zeit, da noch der See bestand
| Fester Untergrund, Sand oder Lehm | 
|===

=== 8.2. Das Schwansmoor
Das Schwansmoor liegt in einer großen von Westen nach Osten sich erstreckenden Mulde der
Osterberge. Es hat, soweit es zur Gemarkung Süderlügum gehört, eine Längenausdehnung von
reichlich 1.500 m und mißt an der breitesten Stelle reichlich 500 m. Es umschließt eine Fläche
von 74,2871 ha. Wie im ersten Abschnitt geschildert, ist es aus einem abgeschnürten See
entstanden und erwachsen. Auch hier haben die Torfmoose den größten Anteil an dem Aufbau
gehabt und eine Torfschicht bis zu 3 m entstehen lassen, wenigstens in der Mitte, wo infolge
der Wasserverhältnisse die Wachstumsbedingungen immer am günstigsten sind, so daß der
Volksmund es richtig als Hymose = Hochmoor bezeichnen konnte. Es war kein herrschaftliches
Moor; der Torf, der größtenteils der jüngsten Torfbildungsperiode angehörte, war wohl nicht
hart und fest genug und wurde deshalb nicht zur Gewinnung von Deputatstorf herangezogen.
(Siehe den Abschnitt: Süderlügum und Tondern). Es war ursprünglich ein Dorfschaftsmoor,
Süderlügum hatte den größeren, Westre den kleineren Anteil daran. Die übrigen Dörfer des
Kirchspiels hatten keine eigenen Moore und mußten in Eingaben immer wieder bitten, hier und
da in andern Dörfern ihren Torf graben zu dürfen und waren nirgends gern gesehene Gäste.
Die Besitzverhältnisse bei den Mooren waren ähnlich denen bei den Waldungen: Der Boden,
also auch das Moor, gehörte dem König oder dem Herzog, also der Herrschaft, aber dem
Bauern stand das Recht der Nutznießung als Weide und zur Torfgewinnung zu. Der Bohlsmann
erhielt 20 - 30 Fuder, der Kätner 6 - 10 Fuder (1711). Nach der Holz- und Jagdverordnung von
1737 durften auch die Festebauern ihren Torfbedarf hier decken. Auch ihnen wurde ein
bestimmtes zugewiesen. Für das, was sie mehr gruben, mußten sie 1/10 des Wertes an die
Amtskasse abliefern. Beispiel: Jens Matthiesen bekommt frei 2.200 Cubicfuß (110 Kubikfuß
\= ] Fuder), er hat mehr gegraben, 4.973 Cubicfuß, Wert desselben 5 Rthl 30 ß. 1/10 davon an
die Königl. Casse = 27 ß.
Meistens findet sich aber in den Akten die Bemerkung _"Haben bei weiten nicht soviel gegraben,
als ihnen nach der Holtz- und Jagdordnung erlaubet zu graben"_ , wenigstens war bei der
Schätzung nie mehr vorhanden.
Im Zuge der Feldaufteilung ist auch das Schwansmoor parzellenweise an die Bohlsbesitzer als
Eigentum übergegangen. Parzelle reihte sich nun an Parzelle, alle parallel von Süden nach
Norden verlaufend. Die Grenzen wurden durch Gräben und kleine Wälle kenntlich gemacht,
sind aber im Laufe der Zeit, besonders, als die größten Teile des Moores abgegraben waren, oft
gänzlich verwischt. Die ungenügende Kennzeichnung hat auch oft zu Streitigkeiten Anlaß
gegeben. So wissen wir z.B., daß Knud Tullesen (Süderlügum Nr. 43) 1884 _"in einer Reihe von
Jahren zu weit in Pastors Moor eingestrichen"_ . Sein Nachfolger mußte den Schaden wieder
gutmachen, indem er von seiner Moorschift bis an die Wasserlösung 6 Ellen an Pastors Moor
abtrat, nämlich 2 Ellen, die dem Pastor gehörten,und vier Ellen als Entschädigung für 50.000
Soden Torf, die widerrechtlich dort gegraben waren.
Als die Versorgung mit Brennmaterial im Amt Tondern schwieriger wurde, da die
herrschaftlichen Moore zusammenschrumpften, tauchte der Vorschlag auf, auch die
Privatmoore zur Deputattorflieferung mit heranzuziehen. Für Lügum wurde die Gefahr durch
den energischen Einspruch des Hardesvogten Lorentzen in Leck abgewendet. Er schrieb 1800:
_"Die Moore gehören den Bohlsstellen. Die Looseignen der Dorfschaft oder Commune,
innerhalb deren Feldscheide sie belegen sind, und die Besitzer derselben, zahlen vom selbigen
sowohl als von ihren sonstigen Ländereyen und Holtzschiften. Sie sind teile des Ganzen. Auch
die Festebauern haben durch Festebrief Nutznießung, er zahlt den Zehnte für mehr gegrabenen
Torf, ist also wohlerworbenes Eigenthum"_ .
Die Parzellen haben oft den Besitzer gewechselt. In der folgenden Übersicht werden aufgeführt:
Kartenblatt und Parzellennummer, Größe, ungefähre Breite der Streifen, Besitzer im Jahre 1879,
spätere Besitzer und jetziger Eigentümer (1946). Nicht immer hat man, der Kosten wegen, einen
Wechsel katasteramtlich erfassen und eintragen lassen, so daß wir hin und wieder zwischen
eingetragenem und wirklichem Besitzer unterscheiden müssen. In Zweifelsfällen konnte auch
die Nummer der Hauschronik benutzt werden.

[cols="1,^3,^3,^2,10",options="header"]
|===
|Nr. |	Karte/Nr. |	Größe in ha |	Breite m| Besitzverhältnisse 1879 und 1946	
|1 | XV/30 |2,0932 | 88 |1879: Anne Marie Peysen-1946: Peter Nielsen. 
|2 | XV/29 |0,6311 | 36 |1879: Chresten Petersen Holt - sp.: Peter Holt, seit 1905:Marie Matzen und Miteigentümer 
|3 | XV/26 |0,6352 | 36 |1879:Jacob P.Petersen-1946: Christian B. Petersen 
|4 | XV/25 |0,6083 | 30 |1879: Matthias Nicolaisen - 1946: Forst 
|5 | XV/22 |0,5841 | 28 |1879: Peter Wendt - sp. : Volkert Wollesen - 1946: Forst 
|6 | XV/21 |1,2040 | 62 |1879: Claus S. Tetens - 1883 geteilt unter Jörgen Christiansen, Braderup, und Hoekc, Westerhof - 1946: die westl. Parz.: J.Christiansen un. Gottlieb Christiansen (0.6084 ha). die öst.Parz. Bendix Volquardsen. Westerhof 0.5956 ha). 
|7 | XV/18 |0,3869 | 22 |1879: Hans P. Holdensen 1946: Hans Ferd. Hansen 
|8 | XV/17 |0,4675 | 28 |1879: Anton Nielsen - 1946: Julius Jensen 
|9 | XV/16 |0,5502 | 26 |1879: Nis Andreas Petersen (Nr.68) - 1946 Johannes Petersen Süderlügumfeld 
|10 | XV/13 |0,3319 | 6|1879: Silla Sönnichsen(Nr.83) sp.: Erich Hansen -1946: Forst 
|11 | XV/12 |0,4092 | 20 |1879: 1879: Jac. P. Iwersen - 1946: Chr. M. Petersen 
|12 | XV/9 |0,5077 | 26 |1879: Nicolay Hansen - 1946: Erich Hansen 
|13 | XV/8 |0,3334 | 20 |1879: Peter Wettering Iwersen - 1946: Heinrich Delfs 
|14 | XV/7 |0,8092 | 469 |Armenverband - 1946: Detlef Petersen 
|15 | XV/6 |0,5982 | 46 |1879: Christian Hansen - 1946: Ernst Burmeister 
|16 | XV/5 |0,8586 | 46 |1879 Ingeburg Andresen, geb. Hansen(Nr.54) -1946: Ingeburg Andresen und Kinder und Franz Hemming(Nr.31)
|17 | XV/31 |2,0574 | 80 |1879: Peter Carstensen Petersen sp.: Niels Hansen- 1946: Forst 
|18 | XV/28 |1,2078 | 18 |1879: Johannes Jacobsen - 1946: Anton Carstensen 
|19 | XV/27 |0,4027 | 8 |1879: Peter Hinrichsen - 1946: Cathrine Johannsen 
|20 | XV/24 |0,6444 | 28 |1879: Pastorat 1946: Pastorat 
|21 | XV/Z3 |0,6868 | 28 |1879: Peter W. Iwersen - 1946: Heinrich Delfs 
| 22 | XV/20 | 1,5239 | 62 | 1879: Claus Sax Tetens - 1882 geteilt:wsstl. Hälfte Jes Chr. Jepsen, östl. an Christian Sönnichsen - 1946: westl Teil: August L.Petersen 90,7529 ha), östl. Teil: Hans Ferd. Hansen (0,7710 ha)
| 23 | XV/19 | 1,3848 | 50 | 1879: Caroline Marie Willsen.geb.Kjerbüill - 1946: Johann Peter Bossen Petersen (Nr. 167)
| 24 | XV/15 | 0,5496 | 25 | 1879: Wilhelm Hansen Bünding (Nr. 130) - 1946: Forst
| 25 | XV/14 | 0,2130 | 6 | 1879: Silla Sönichsen.geb. Christiansen -sp. Erich Hansen - 1946: Forst
| 26 | XV/11 | 0,4823 | 20 | 1879: Jacob P. Iwersen - 1946: Christian M. Petersen
| 27 | XV/10 | 1,0714 | 40 | 1879:Caroline Marie Willsen.geb.Kjerbill - 1946: Johann Peter Bossen Petersen (Nr.167)
| 28 | XV/44 | 0,2624 | 10 | 1879: Peter Wendt - 1946: Cathrine Johannsen
| 29 | XII/55 | 0,8853 | 28 | 1879: Christian Hansen - 1946: Cathrine Johannsen
| 30 | XII/54 | 31,1472 | 45 | 1879:Detlef Dinnsen, Elhöft - 1946: Thomas Lorenzen, Ellhöft
| 31 | XII/53 | 1,1916 | 45 | 1879: Nicolay Hansen- 1946: Erich Hansen
| 32 | XII/52 | 1,0664 | 22 | 1879: Peter Wettering Iwersen - 1946: Erich Hansen.
| 33 | XII/51 | 0,5741 | 11 | 1879: Mathias Nissen Petersen - 1946: Sönnich Winter
| 34 | XI/50 | 0,5559 | 12 | 1879: Peter Wendt- 1946: Catharine Johannsen
| 35 | XII/49 | 1,1649 | 23 | 1879: Carsten Erichsen, Ellhöft - 1946: Jacob B.Christiansen, Ellhöft
| 36 | XII/48 | 1,139 | 23 | 1879: Peter Wendt - 1946: Cathrine Johannsen.
| 37 | XII/47 | 1,1785 | 23 | 1879: Nis A. Petersen (Nr.68) - 1946: Jacob Bossen
| 38 | XII/46 | 1,8731 | 23 | 1879: Christian P. Hermannsen(Nr. 13) - 1946: Joh. Chr. Block.
| 39 | XI1/45 | 0,9571 | 18 | 1879: Claus Sax Tetens - 1946: Enewald Knudsen, Seth (Nr.38)
| 40 | XII/44 | 0,9716 | 20 | 1879: P.Bachmann (Nr.79) - 1946: Wilhelm Eng(Nr. 108)
| 41 | XII/43 | 1,3038 | 22 | 1879: Claus Sax Tetens - nach ihm Nicolai Heinrich Hansen, Humptrup- 1883 wird die Parzelle in 2 Hälften verkauft an Caroline Carstensen, geb. Nielsen, und Peter Christ. P. Hoeck - 1946: Albert Oswald Petersen, Grelsbill(o.6486 ha) und Carsten Carstensen und Clara Nissen, Fischerhäuser (0,6452 ha)
| 42 | XII/42 | 1,8958 | 36 | 1879: Nis Joh. Paysen - 1946 Christian Burgwald.
| 43 | XII/41 | 1,8350 | 32 | 1879: Paulsen, Grellsbill, - 1946: Hans J. Thießen, Stellenhändler, Nordhastedt - jetziger Besitzer: Hans J. Thießen
| 44 | XII/40 | 0,6473 | 12 | 1879:Aug. Feddersen, Bremsbüll - bis heute.
| 45 | XII/39 | 1,1712 | 8 | Weg Forrst
| 46 | XII/38 | 1,2336 | 24 | 1879: Caroline Marie Willsen - 1946: JohannP. Bossen Petersen - Jestzt:Hema Schmidt,geb. Petersen(Nr. 167)
| 47 | XII/37 | 1,0104 | 18 | 1879:Hans Mollensen - 1946: Forst
| 48 | XII/36 | 1,3444 | 25 | 1879: Ingeborg Carstensen(Nr.82) - 1946: Carsten Jacob Angel, Bierremark.
| 49 | XII/35 | 1,5092 | 28 | 1879: Bohlsinteressentenschaft( Gemeinde)-1946: Jürgen Christensen, Braderupfeld.
| 50 | XII/34 | 0,9488 | 12 | 1879:: Nicolay Hansen - 1946: Erich Hansen
| 51 | XII/33 | 0,8723 | 16 | 1879: Claus Sax Tetens - 1946: Erich Hansen.
| 52 | XII/32 | 1,6052 | 30 | 1879: Peter W. Iwersen - 1946: Heinrich Delfs
| 53 | XII/31 | 1,6050 | 30 | 1879: Christ. Jacobsen - 1946: Thomas Volquardsen
| 54 | XII/30 | 1,5694 | 30 | 1879: Carl L. Heinsen, Humptrup - 1946: Forst
| 55 | XII/29 | 2,0983 | 40 | 1879: Nic.Hoh. Paysen - sp.: Anne Marie Paysen und Miterben - 1946: Christian Burgwald
| 56 | XII/28 | 1,9264 | 38 | 1879: Pastorat - 1946: Pastorat.
| 57 | XII/27 | 1,8791 | 38 | 1879: Jacob P. Iwersen - sp.:Joh.P.Bossen Petersen - 1946: Herma Schmidt.geb Petersen (Nr.167)
| 58 | XII/26 | 1,8490 | 40 | 1879: Chresten Petersen Holt sp.: Peter Holt - 1946: Marie Matzen und Miteigentiümer.
| 59 | XII/18 | 3,2590 | 75 | 1879: Hans Peter Holdensen 1946: Hans Peter Holdensen und Miteigentümer (Wilh.Eng 6/8, Nommensen Burgwald 1//8, Hans Holdensen 1/8)
| 60 | III/17 | 1,9364 | 40 | 1879: Cornelius Adolf Johannsen, Ellhöft - 1946: Joh. Nic.Johannsen, Ellhöft, und Peter Lorenz Lützen.
| 61 | III/16 | 2,3997 | 43 | 1879: Fedder Lorenzen(Nr.139) - 1949: Forst.
| 62 | III/9 | 1,8552 | 44 | 1879: Broder Hansen, Wimmersbill - 1946: Forst.
| 63 | I1I/2 | 3,0729 | 68 | 1879: Boh Brodersen Uhlenberg - 1946: Martin Schau, Uhlenberg. Die Parzelle XV/31 ist aufgeforstet; die Parzellen XV/13 und 14, II/39, 30 und 16 sind als Wege ausgelegt.
|===

Die Glanzzeit des Moores ist jetzt längst dahin. In der Zeit, da Holz und Torf und Heide die einzigen
Brennmaterialien waren, hatte es unschätzbaren Wert, der sich steigerte, je mehr der alte Wald
zusammenschrumpfte. Durch gesteigerte Ausgrabung sowie durch unsachgemäße Behandlung ist es
vorschnell "vergraben" worden. Die behördliche Anweisung, die Graben wieder zuzuwerfen, nicht bis
auf den Sand abzugraben und für Ableitung des Wassers sorgen (1757), wurde zu mangelhaft oder gar
nicht beachtet. 1767 berichtet der Hardesvogt Lorentzen, daß _"hier und da nur kuhlenweise Torf
gegraben werden"_ , daß man allen Torf, _"wo man nur beykommen kann"_ bis auf den Sand ausgräbt, so
daß an neuen Anwachs nicht zu denken sei und die Moore _"unbrauchbar"_ bleiben.

Und auch die Menge des gestrichenen Torfes hat zur schnellen Liquidierung wesentlich beigetragen,
wurde doch nicht nur für den eigenen Bedarf gegraben, sondern auch für den Verkauf. Und man konnte
das nicht gut verbieten. _"Das sey"_, wie es in dem erwähnten Lorentzenschen Bericht heißt, _"in Einsicht
der angrenzenden Marschen und der vielen auch in hiesiger Harde von Feuerung entblößten Dörfer und
der Schmiede halber wohl nicht thunlich"_. So ist es denn auch geblieben, auch nach der Feldaufteilung:
Jeder suchte ein gutes Geschäft zu machen und einen großen Kundenkreis zu gewinnen, den er Jahr für
Jahr beliefern konnte. Noch vor 50 Jahren war es nicht ungewöhnlich, wenn täglich während der
Abfahrtzeit 20, 30 und mehr Wagen die Sandwege zur Geest hinaufmahlten und die Winterfeurerung
in die Marsch holten.

Jetzt ist nicht viel mehr zu holen im Schwansmoor. Während des 1. und 2. Weltkrieges und in den
Nachkriegsjahren, als die Feuerung wieder knapp war, weil die Zufuhr an Kohle, Koks und Briketts fast
ganz unterbunden wurde, lebte die alte Geschäftigkeit im Moor und der alte Handel wieder etwas auf.
Hunderte von Fudern, oft nur leichten Flaggentorfs, sind wieder abgefahren und durch die Kamine
geschickt. Auch in normalen Zeiten versorgt sich noch dieser und jener mit einigen Fudern Flaggen. Im
übrigen ist es still auf der weiten Fläche, die jetzt fast überall bis auf den Sand abgegraben ist. Die Heide
überwuchert sie wieder und das Torfmoos, und nach Jahren mag hier und da wieder ein Flaggenstich
möglich sein.

Nachdem der Mensch hier seine Arbeit getan hat und nicht mehr störend eingreift, kommt die Natur
wieder zu ihrem Recht und formiert hier eine Pflanzengemeinschaft, die gerade auf diesem Boden unter
den naturgegebenen Bedingungen einen seltenen Formenreichtum erreicht: Heidekraut und
Glockenheide, Glockenblume und Habichtskraut, Jasiensz und Teufelsabbiß, Wohlverleih (Arnika) und
Enzian, Wollgras, Ährenlilie, Sonnentau und viele andere mehr. Und ebenso reich ist die Tierwelt dieses
Gebietes an Käfern, Schmetterlingen, Fliegen, Mücken, Kreuzottern und Ringelnattern. Der Hase hat
hier sein Lager und Rehe kann man rudelweise überraschen. Im Spätsommer, wenn das Heide-
Aschenbrödel ihr Hochzeitskleid angelegt hat, ist es am schönsten hier draußen. Dann fließen alle Farben
und Töne zu einer großen Symphonie zusammen.

Ob es immer so bleiben wird? Ob nicht der Mensch einmal dieses Stück Natur in Kultur nimmt und ein
Wald uns vergessen läßt, daß hier einst ein großes Moor war?

Dieses Schicksal hatte:
=== 8.3. Das Kätnermoor
Es ist längst kein Moor mehr; nur der Name lebt noch. Es liegt westlich vom Schwansmoor, bildete ein
großes Trapez mit einem Flächeninhalt von 15,2845 ha. (Siehe die Karte 1). Bei der Feldaufteilung war
es den Kätnern zum Flaggengraben und als Weide zugewiesen worden. Infolge der Höhenlage war die
Torfbildung hier nur mäßig. Es lagen hier 66 schmale Parzellen, alle vom Westen nach Osten, von denen
die meisten keinen halben Demat groß waren.
1895 wurde das Kätnermoor aufgeforstet.

Die letzten Besitzer waren:

```
1. Peter Hinrich Hinrichsen                               -  Par. 32 -0,1619 ha
2. Andreas Iwersen, Horsberg                              -   "   33 -0,1569 ha
3 Metta Boysen,geb.Christensen                            -   "   34 -0,1396 ha
4. Nic. Hans Feddersen,                                   -   "   35 -0.1943 ha
5. Andreas Chr. Christiansen                              -   "   36 -0,1725 ha
6. Carsten Christiansen, Lehrer und Häusler, Jardelund    -   "   37 =0,1973 ha
7. Carsten Carstensen                                     -   "   38 -0,1556 ha
8. Jürgen Christensen                                     -   "   39 -0.1719 ha
9 Christian Ulstrup                                       -   "   40 -0.1748 ha
10. Peter Wendt                                           -   "   41 -0,1780 ha
11. Joh. Jac. Eichhorn                                    -   "   42 -0,1690 ha
12. Ester Hansen,geb. Carstensen                          -   "   43 -0,1661 ha
13. Fedder Feddersen, Gastwirt                            -   "   44 -0,1656 ha
14. Andreas Christiansen, Kätner                          -   "   45 -0,1656 ha
15. Ingeborg Carstensen                                   -   "   46 -0,1695 ha
16. Sibbert Carlsen, Schmied                              -   "   47 -0,1764 ha
17. Carsten Christiansen, Lehrer u. Häusler, Jardelund    -   "   48 -0,1747 ha
18. Jacob Anton Nielsen, Bäcker                           -   "   49 -0,1717 ha
19. Andreas Lausten Riggelsen                             -   "   50 -0,1769 ha
20. Andreas Chr. Jensen, jun.                             -   "   51 -0,1738 ha
21. Maria Hansen, geb. Jacobsen                           -   "   52 -0,2210 ha
22. Joachim Heinr. Reimers, Chausseeaufseher              -   "   53 -0,2136 ha
23. Christine Feddersen, fr. verehel. Hartwigsen,Horsberg -   "   54 -0,2267 ha
24. Paul Hinrichsen, Kätner                               -   "   55 -0,2240 ha
25. Paul Hinrichsen, Kätner                               -   "   56 -0,2239 ha
26. Jürgen Gottfried Jürgensen                            -   "   57 -0,2122 ha
27. Chresten Petersen                                     -   "   58 -0,1800 ha
28. Caroline Marie Willsen,geb. Kjerbüll                  -   "   59 -0,2432 ha
29. Johann Jac. Eichhorn                                  -   "   60 -0,2608 ha
30. Janne Peter Andresen                                  -   "   61 -0,2284 ha
31. Nicolay Joh. Paysen                                   -   "   62 -0,2401 ha
32. Janne Peter Andresen                                  -   "   63 -0,2863 ha
33. Armenverband                                          -   "   64 -1,5240 ha
34. Carsten Hansen                                        -   "   65 -0,2155 ha
35. Nicoline Rieber,geb.Petersen                          -   "   66 -0,2204 ha
36. Jens Peter Julgaard                                   -   "   67 -0,2208 ha
37. Christine Feddersen, fr. verehelicht Hartwigsen       -   "   68 -0,2232 ha
38. Hans Wollesen                                         -   "   69 -0,2044 ha
39, Bendix Carstensen Block                               -   "   70 -0,2276 ha
40. Christian Petersen                                    -   "   71 -0,2198 ha
41. Hans Peter Hansen                                     -   "   72 -0,2198 ha
42. Lorenz Hansen Reimer,Schneider                        -   "   73. 0,2162 ha
43. Thue Jensen, Käthner                                  -   "   14 -0,2285 ha
44. Hans Peter Holdensen                                  -   "   75 -0,2018 ha
45. Hans Jensen, Käthner                                  -   "   76 -0,2103 ha
46. Peter Chr. Hinrichsen                                 -   "   77 -0,2087 ha
47. Jacob Peter Iwersen                                   -   "   78 -0.1953 ha
48. Andres Christiansen                                   -   "   79 -0,2162 ha
49. Chresten Andresen, sen.                               -   "   80 -0.2163 ha
50. Andreas Christiansen                                  -   "   81 -0,2149 ha
51. Jes Fr. Jensen, Häusler                               -   "   82 -0,2235 ha
52. Andreas Chr. Andresen                                 -   "   83 -0,2073 ha
53. Christian Peter Hartwigsen                            -   "   84 -0,2201 ha
54. Maria Rieber, geb.Lorenzen                            -   "   85 -0,2245 ha
55. Jürgen Christensen,Horsberg                           -   "   86 -0,2178 ha
56. Carsten Christiansen, Lehrer u. Häusler, Jardelund    -   "   87 -0,2065 ha
57. Mathias Andr. Mathiesen                               -   "   88 -0,2184 ha
58. Hans Peter Johannsen                                  -   "   89 -0,2173 ha
59. Carsten Carstensen, Horsberg                          -   "   90 -0.2289 ha
60. Jens Wilh. Hansen                                     -   "   91 -0,2231 ha
61. Andreas Peter Knudsen                                 -   "   92 -0,2199 ha
62. Jens Peter Andresen                                   -   "   93 -0,2138 ha
63. Marie Neve                                            -   "   94 -0,2410 ha
64. Carsten Bossen, Kätner                                -   "   95 -0,2199 ha
65. Hans Christ.Jürgensen                                 -   "   96 -0,3494 ha
66. Friedrich Wilhelm Emil Lerche                         -   "   97 -0,6562 ha
```
=== 8.4. Das Küstermoor (Galligmoor)
Auch westlich der Süderberge liegt ein weites Moor- und Heidegebiet. Wegen der Nähe des
Galgenberges führte es früher den Namen Galligmoor. Der Name wird nicht mehr benutzt. Ein Teil des
Moores ist in das Naturschutzgebiet "Mövensee" einbezogen worden. Die Eigentumsverhältnisse - es
liegt hart an der Braderuper Grenzscheide - scheinen hier sehr verwickelt gewesen zu sein. Es wird
berichtet über einen Streit der Bohlsbesitzer Jens Christensen und Konsorten in Lügum wider Jens
Feddersen und Konsorten in Humptrup aus dem Jahre 1804. In der ablehnenden Antwort des Amtshauses
heißt es nämlich! "_Es bestehen die Hufen in Lügum ungefähr zur Hälfte aus Eigenthums- und zur Hälfte
aus Feste-Ländereyen. Den Besitzern beiderley Ländereyen gehört auch das sogenannte Gallig-Mohr,
welches sie pro rata besitzen, ohne darüber einen besonderen Festebrief zu haben. Ob nun das ganze
Gallig-Mohr den Lügumers oder ob ein Theil davon nach Humptrup, Grellsbüll und Kahlebüll gehöret,
ist mit Nichten ausgemacht, so wie bey Mangel aller desfälligen Briefschaften auch nicht ausgemacht
ist, daß das ganze Mohr die Qualität der Festeländerreyen hat, oder ob diejenigen Stücke, die den
Besitzern der Bondengüter gehören, auch als Bondenländereyen zu betrachten sind. Da nun so wenig
diese als jene Frage beantwortet ist und ich keine desfällige befriedigende Nachricht habe erhalten
können, so vermag ich auch nicht genau anzugeben, inwiefern das Dominus directum bei dem
gegenwärtigen Streite in Betracht komme. Da der prätendierte Antheil an den sogenannten Gallig-Mohr
nicht von Erheblichkeit, müssen sie es selbst mit einander ausfahren"_ . - Wenn der Amtmann sich also
in den Besitzverhältnissen nicht auskannte, können wir die Sache auch auf sich beruhen lassen. Der
Zustand des Moores kann auch heute noch für die unerquicklichen Verhältnisse zeugen. Noch bis in die
letzten Jahre hat das Moor einen bescheidenen Teil an Torf und Flaggen geliefert. Die westlichste
Parzelle, 3,1531 ha, ist Süderligumer Gemeindebesitz. Aus ihr hat man den Torf für den Küster des
Dorfes gegraben. Sie führt deshalb noch heute den Namen Küstermoor.

=== 8.5. Die Wiesenmoore
Auch der Wiesenmoore muß in diesem Zusammenhang noch kurz gedacht werden. Ihre Entstehung ist
in dem Abschnitt über die Entstehung des Bodens beschrieben.

Es ist verständlich. daß der Landmann seine Wiesen nur ungern anzapft, wird die landwirtschaftliche
Ausnutzung doch wesentlich dadurch beeinträchtigt. Nur die Notzeiten der Kriegs- und Nachkriegsjahre
zwangen ihn zum Graben von Wiesentorf, das dann möglichst auf kleinste Ausmaße an der günstigsten
Stelle beschränkt wurde.

Der Wiesentorf brennt gut, da er gewöhnlich holzreich ist. Der hier und da vorkommende Salpetergehalt,
der beim Verbrennen einen stechenden Geruch abgibt, mußte mit in Kauf genommen werden.

Da man im Moor immer wieder auf Baumstämme stieß, konnte es nicht ausbleiben, daß die Frage ihrer
Herkunft ventiliert wurde und das Interesse für die Entstehung und Geschichte unserer Heimat auch an
dieser Stelle einige Förderung erhielt.