== 9. Der Karrharder Alten Koog
Der folgende Abschnitt ist ein Beitrag von Max Tobiesen, und ist hier voll wiedergegeben:

*Die Geschichte der Deich- und Wasserverhältnisse im Karrharder Alten Koog und ihre Auswertung im Unterricht.*

Arbeit des apl. Lehrers Max Tobiesen zur zweiten Prüfung für das Lehramt an Volksschulen

Eingereicht beim Schulamt des Kreises Südtondern in Niebüll am 15.8.1951

=== 9.1. Gliederung
A. Einleitung
B. Die Geschichte der Deiche:
    1.) Das Gebiet des Kooges vor der Eindeichung.
    2.) Der Bau des Grellsbüller Deiches.
    3.) Der Grellsbüller Deich als Außendeich(Sturmfluten).
    4.) Deichlasten des Karrharder Alten Kooges.
    5.) Die Mittel- und Sommerdeiche des Kooges.
C. Die Entwicklung der Wasserverhältnisse:
    1.) Wasserverhältnisse in alter Zeit.
    2.) Erste Entwässerungsversuche.
    3.) Ableitung des Wassers zum Meer.
    4.) Die Grenzlaufregulierung:
        a) Das Deutsch Dänische Regulativ für den Grenzstrom. |
        b) Das Entwässerungsproject der Tonderner Marsch.
    5.) Der neue Plan für die Binnenentwässerung.
D. Verwendung der erworbenen Sachkenntnisse im Heimatkundeunterricht.

=== 9.2. Einleitung

A. Während meiner bisherigen Tätigkeit galt mein größtes Interesse der Heimatkunde, als dem Kernfach
des gesamten Grundschulunterrichts. Sollten die Kinder des 3. und 4. Schuljahres, die ich zu betreuen
hatte, ihre engere und weitere Heimat kennenlernen, so mußte ich zunächst einmal selbst mit den
Gegebenheiten und Besonderheiten meines Wirkungsortes und seiner Umgebung vertraut sein. Die
günstige Lage Süderlügums an der Grenze zwischen Marsch und Geest ergab von selbst die Verteilung
des Stoffes auf einen Zweijahreskurs. Nach dem Prinzip "vom Nahen zum Fernen" ließ ich im ersten
Jahr von der engsten Heimat aus die Geestlandschaft und das östliche Hügelland "erobern". In der
gleichen Weise gestattete es die Lage, von der Dorfgemarkung aus die Marsch und die Westküste der
Klasse nahezubringen. Die gründliche Ausnützung der reichhaltigen Anschauungs- und
Beobachtungsmöglichkeiten im engeren Heimatraum setzte jedoch ein genaues Studium, der
heimatkundlichen Verhältnisse voraus. Ich nahm deshalb die Entwicklung eines begrenzten Gebietes
meines Wirkungsortes einmal genauer unter die Lupe. Als Studienobjektes wählte ich den sich nördlich
Süderlügum erstreckenden Karrharder Alten Koog. (In den folgenden Ausführungen als K. A. K.
bezeichnet). Dieser Raum sollte der Ausgangspunkt für die Betrachtung der Marsch in meinem
Heimatkunde-Unterricht sein. Die Beschäftigung mit den zur Verfügung stehenden Quellen ergab die
Möglichkeit, am Beispiel dieses Teiles der Dorfgemarkung der Klasse die besonderen Probleme der
Marschlandschaft zu zeigen und die Begriffe "Marsch" und "Koog" den Kindern deutlich zu machen.

=== 9.3. Die Geschichte der Deiche

==== 9.3.1. Das Gebiet des Kooges vor der Eindeichung

B.1. Bevor die Köge an der Wiedau eingedeicht wurden, konnte das Meerwasser ungehindert bis zum
Geestrand vordringen. Die damalige Festlandküste kann man heute noch genau verfolgen als Grenze
zwischen Marsch und Geest. Süderlügum, Wimmersbüll, Grellsbüll, Humptrup, Krakebüll, Kahlebüll,
usw. lagen also hart an der Nordseeküste. Im Norden Süderlügums dehnte sich die Niederung der
Süderau als tiefe Meeresbucht bis nördlich Ellhöft aus. Im Laufe der Jahrhunderte lagerte sich der
Schlick ab, so daß hier allmählich ein Wattenmeer entstand, in dem wohl einige kleine Inseln zerstreut
lagen. Wer nun glaubt, in dem hier später eingedeichten Koog fetten Marschboden vorzufinden, wird
eines Besseren belehrt, wenn er dieses Gebiet aufsucht. Wie ist das zu erklären? Durch den Abfluß der
Gewässer von den Höhen setzte langsam eine Versumpfung dieser entstandenen Niederung ein. Auch
auf der Geest muß eine ausgedehnte Versumpfung stattgefunden haben. Von dieser Beschaffenheit des
Bodens bekam schließlich die ganze Karrharde ihren Namen (dän. Kjer = Sumpf). Nun folgte eine
erneute Veränderung des "Marschbodens". Sumpf- und Moorpflanzen siedelten sich an. Die
Moorbildung setzte ein und ließ an der Oberfläche den Wiesentorf entstehen.

==== 9.3.2. Der Bau des Grellsbüller Deiches
B.2. Noch in der ersten Hälfte des 16. Jahrhunderts wirkten sich Ebbe und Flut durch das Einfallstor der
Wiedau bis in die Süderau-Niederung aus. Wrackstücke sollen weit ins Land hinein an den Ufern der
Auen angeschwemmt sein. Sturmfluten ließen auch die Süderau weit über die Ufer treten und richteten
großen Schaden an. Das angrenzende Land wurde zerwühlt, viel Vieh und nicht selten auch Menschen
fielen der Überflutung zum Opfer. Von diesen Verheerungen spricht auch die Verordnung vom
16.4.1554 zur Errichtung eines neuen Deiches von der Hoyerharde zur Karrharde. Es heißt dort:
_"Nachdem die groten flute storm, ungewetter und sverigen water jhe bothwylan unserm lande und armen
leutenn so twischen Hoyer, Wimmerßbul und Grelsbul in tondern ampte gesetenn und belegen sinn,
groten unoverwitnlichen schadenn thofugenn, und solche van jarenn tho jarenn jhe longer jhe
beschwerlicher inritet, also dat man sich undergang und verdorff daruth tho vermudende hefft."_
Schon wiederholt hatte man versucht, das Vorland der Wiedau und der Süderau zu sichern, doch waren
diese Bemühungen immer wieder an der Durchdämmung der Wiedau gescheitert. Zu Beginn der 50er
Jahre wurden die Eindeichungsarbeiten bei Tondern wieder aufgenommen. Der Amtmann von
Mösgeltondern, D. Ahlefeld, scheint die Errichtung eines Deiches von der Hoyer- zur Karrharde angeregt
zu haben. Dieser Vorschlag veranlaßte den Herzog Hans am 26.9.1553, ein Amtsthing in Tondern
abzuhalten, auf dem auch Deichsachen behandelt wurden. Daraufhin erließ er am 3.12.1553 eine
"Begnadigung" an die drei Harden, (Wieding-, Böking- und Karrharde), die Linienführung des neuen
Deiches von 12 Sachverständigen (Udkogs-folk) vornehmen zu lassen.
Dies geschah durch Lokalbesichtigung am 28.3.1554. Der Amtmann von Tondern, Otto von Thiemen,
nahm daran teil und berichtete dem Herzog von dem Ergebnis. Nach seiner Ansicht sei es sehr schwer,
einen so langen Deich aufzufahren, da so viele _"tieffen"_ zu überwinden seien, erklärte er. Auch die
Sachverständigen rieten von diesem Vorhaben ab, außer D. Ahlefeld und dem früheren Amtmann von
Tondern, die zuerst davon zum Herzog gesprochen hatten. Nach Ansicht der Sachverständigen mußte
zuerst das Tiefe zwischen der Horsbüllharde und Rutebüll durchdämmt werden. Das würde jedoch so
viel Holz erfordern, daß man den Leuten nicht zumuten könnte, dort zu deichen. Wenige Tage danach
erschien Herzog Hans wieder in Tondern, um sich an Ort und Stelle von den Möglichkeiten und
Schwierigkeiten des Deichbaues zu überzeugen

Das Ergebnis war die Verordnung vom 15. April:

_"Offen bevhel, verordennung unnd zulas eines newen teichs in Tunderen. Actum Tunderenn
den 15. aprilis anno Sden."_

Nun konnte mit den Arbeiten zur Aufschüttung des Deiches begonnen werden. Aus dem ausführlichen,
umständlich abgefaßten Schriftstück geht hervor, daß beim Bau des Grellsbüller Deiches Störten
eingesetzt wurden. Deichrichter und Deichvögte sollten berechnen, wieviele Störten benötigt wurden:

_"..offte up dertig (30) oder weniger deimst landes ein storten tho holden."_

(Die Störte war eine dreiräderige Karre mit Kippvorrichtung. Sie wurde von zwei Pferden oder Ochsen gezogen.)

Achtzig Stück Buchenholz stellte der Herzog als Hilfeleistung zur Verfügung. Bei der Überschlagung
der Wiedautiefen zog man auch die Untertanen mit heran, die weiter entfernt auf der Geest wohnten.
Im Weigerungsfalle wurde eine Geldstrafe bis zu 18 Schilling angedroht. Es heißt sogar in der
Verordnung, daß in besonderen Fällen solchen _"Ungehorsamen"_ das Land weggenommen werden soll:

_"So un ock darsulde ungehorsamlich avergan, schal sin land an die obrigkeit, worunter he
geseten, vorbrocken und verfallen sin."_

Im Jahre 1554 konnte das breite Wiedauwasser bei Legan überschlagen werden. Der holländische
Schleusenbaumeister Arend Cornelius baute hier die neue Schleuse, die 4000 Lübsche Mark kostete.
Damit war Tonderns Hafen weiter nach Westen verlegt worden, Schiffe, die Ladung für diese Stadt
hatte, mußten nun bei Legan anlegen.

Gegen entsprechende Deichpflichten nach dem "Spade-Landes-Recht") wurde das gewonnene
Koogsland denen zugesprochen, die die Lasten des Eindeichungswerkes getragen hatten. Die oben

angegebene Verordnung verkündet:
_"Gebenn und bevhelen derwegen allen und itzlichen so in solchen koge begroben und land
darinnen hebben hiermede ernstlichen: Gi willen eyn ider up guden vorrath also thom diken
varnothen  tracktenn und vorth ungesumet mit sammender gewaltiger handt den dik
eintrechtigh in mate und gestalt, wo bavengeschrevenn deimet demats glich in argen und
gudem in siell und sielgelde in pall und struck, in ungelt, uncost und alles, wat derup lopen
mag na oldem kogesrecht unnd na juwer egen vorplichtung unnd willkor angripenn. densulven
vor die hant demen unnd allen juwen bestern moglichenn vlit darinne vorwenden."_

Insgesamt wurden 6.000 ha Land durch den Grellsbüller Deich gewonnen, Davon erhielten die
Kirchspiele Süderlügum, Humptrup und Braderup das Gebiet südlich der Süderau, das als Karrharder
Alter Koog bezeichnet wird, mit rund 1.000 ha.

==== 9.3.3. Der Grellsbüller Deich als Außendeich (Sturmfluten)

B.3. Anfang Juli 1556 kam der Herzog anläßlich eines Gerichtstages nach Tondern, um bei dieser
Gelegenheit auch den fertiggestellten neuen Deich zu besichtigen. Einen sicheren Schutz kann dieser
Erdwall nicht gewährt haben. Im Vergleich zu den heutigen Außendeichen war diese Erdaufschüttung
ein unbedeutendes "Bollwerk" gegen den "Blanken Hans." Die dem Meer zugekehrte steile Wand war
mit Pfählen oder Rasenstücken gesichert. Im 16. Jahrhundert wußte man noch nicht, daß ein
flachabfallender Deich die geringste Angriffsfläche hat. Fast ausschließlich wurden die erwähnten
steilen Wäille errichtet, die man durch Pfähle abstützte. Auch unser Deich war ein solcher Stackdeich,
wie aus einem Gesuch der Koogsleute von 22.1.1835 hervorgeht: _"Unsere Deiche, welche mit Pfahlholz
geschützt waren...."_

Elf Jahre lang schützte der Grellsbüller Deich als Außendeich die hinter ihm liegenden Ländereien vor
Überflutungen. Der "Blanke Hans" verhielt sich in dieser Zeit verhältnismäßig ruhig. Einer größeren
Sturmflut hätte dieser lange Deich auch kaum standhalten können. Die Eindeichung des Gotteskooges
brachte eine wesentliche Entlastung für die lange Deichlinie. Im Jahre 1566 konnte die Verbindung der
Horsbüllharde mit Risum-Moor und zugleich der Anschluß der Insel an unseren Deich fertiggestellt
werden. Damit war der südliche Teil des Deiches von Ruttebüll bis Holm zum Binnendeich geworden.
Es sollte sich zeigen, daß die Ländereien des Karrharder Alten Kooges auch jetzt noch nicht
vollkommen vor einem Einbruch des Meerwassers gesichert waren. Bei der Weihnachtsflut 1593
brachen die Gotteskoogdeiche an mehreren Stellen. Die Flut durchbrach auch den Grellsbüller Deich
und setzte die ganze Gegend nach Tondern zu unter Wasser, wie Heimreich berichtet. Wahrscheinlich
wurde damals südlich des Buffelsieles eine große Wehle gerissen. Sie ist heute noch zu erkennen als
breite und tiefe Stelle im Dreiharder Gotteskoogstrom, Man muß nicht in der Lage gewesen sein, diese
Wehle zu stopfen; denn der Deich wurde außen herumgeführt. Später bekam das Wasserloch den
Namen "Hölle". Woher diese Bezeichnung stammt, ist unklar. Sie hängt jedenfalls mit der
ungewöhnlichen Tiefe dieser Stelle zusammen. Ältere Leute wissen von der "Hölle" folgende Sage zu
erzählen:

In der guten alten Zeit, als die Postkutsche das wichtigste Verkehrsmittel für Reisende war, ging die
Straße von Wimmersbüll bereits hart am Rande dieses tiefen Wasserloches vorbei. (Das ist auch heute
noch so). Eines Abends fuhr eine Postkutsche in der Dunkelheit zu nahe an den Rand und stürzte ins
Wasser hinein. Die ganze Postkutsche ging mit Mann und Maus unter. Alle Versuche, Menschen,
Pferde oder Kutsche zu bergen, waren vergeblich. Selbst mit den längsten Stangen konnte man nichts
von der Kutsche aufspüren. nach diesem Vorfall soll dieses Wasserloch wegen seiner "Grundlosigkeit"
den Namen "Hölle" bekommen haben.

==== 9.3.4. Die "Hölle"

Welchen Schaden die Weihnachtsflut von 1593 in unserem Gebiet angerichtet hat, ob Verluste an
Menschen, Tieren und Gebäuden zu beklagen waren, ist nicht festzustellen. Über die Auswirkungen
der späteren großen Fluten in unserem Koog ist ebenfalls nur wenig bekannt. Aus den vorliegenden
dürftigen Berichten über unsere Gegend kann man jedoch schließen, daß die unzähligen Angriffe des
Meeres auch hier zu spüren waren. So heißt es z.B. in einer Akte: _"Am 1.12.1615 stieg das Wasser im
Schloß zu Tondern bis an die Fenster. Bei Windtwedt spülte das Wasser eine Brücke fort."_

Die größte Flutkatastrophe, die Nordfriesland heimsuchte, die "Iandverderbliche Sündflut" vom 11.
Oktober 1634 forderte auch in der Karrharde ihre Opfer. Im ganzen Amt Tondern war kein Koog
trocken, neben großen Verlusten an Vieh waren auch Menschen zu beklagen, nach Heimreich" ') lautet
die Verlustliste für unser Gebiet so:

|===
|               |Menschen   | Pferde | Beeste   | Schafe | Schweine 
| Klixbüll      | 72        | 25     | 453      | 296   | 109
| Braderup      | 5 Fremde  | 21     | 112      | 73    | 41
| Huntorf +
 (Humptrup)     | 16        | 49     | 190      | 80    | 30
|Lügum +
(Süderlügum)    | 13        | 54     | 160      | 91    | 100
|===

==== 9.3.5. Deichlasten des Karrharder Alten Kooges
B.4. Im Laufe der Jahre hatte man im Deichbau immer mehr Erfahrung sammeln können. Die neuen
Seedeiche wurden höher und flachabfallend gebaut, so daß Deichbrüche seltener vorkamen. Damit
wurden die Lasten auch langsam erträglicher. Während heute das Land Schleswig-Holstein und der
Bund die Mittel für die Küstensicherung bereitstellen, mußte in ganz alter Zeit jeder Einzelne selbst für
die Unterhaltung und Instandsetzung seines Deichstückes aufkommen. Heimreich schreibt darüber: (
S. 3126)
_"In Deichsachen hat mans vor Alters also gehalten, daß ein jeder für sich selbst das Wasser
müsse abwehren, und er von andern keine Hülfe zu gewerten gehabt."_
Wer seinen Verpflichtungen am Deich nicht nachkommen konnte, mußte das Land verlassen gemäß
dem alten Wahlspruch: _" De nich will dieken, mutt wieken!"_ So heißt es in einer Verordnung der Fünf-
Harden-Räthe:
_"...daß ein jeder seinen Deich machen solle, da er sein Land hat, und so einer seinen Deich
nicht machen will oder kann, der soll den Spaten auf den Deich stecken, und wollen seine
Freunde den Spaten nicht ziehen, so soll die Herrschaft den Spaten ziehen."_

Die Geschichte der Köge und Deiche Nordfrieslands weiß von vielen Fällen zu berichten, da Menschen
bettelarm Haus und Hof verlassen mußten, weil sie ihren Deichabschnitt nicht in Ordnung halten
konnten. Der unerbittliche Kampf mit dem Meer machte zum Schutze aller solche harten Gesetze
erforderlich. Hart betroffen wurde das Hinterland des Hoyer Seedeiches. Zu Beginn des 17.Jahrhunderts
waren die Anstürme des "Blanken Hans" derart heftig und häufig, daß die Deich-Lasten unerträglich
wurden. Viele mußten den Spaten in den Deich stecken und Haus und Hof verlassen. Auch der K. A.
K. hatte an seinem Haffdeich jährlich große fortlaufenden Kosten. Die Hälfte des Sommers war der
Ausbesserung des Deiches gewidmet.
Mitte bis Ende des 17. Jahrhunderts bildeten sich überall in Nordfriesland Genossenschaften, denen die
Unterhaltung der Deiche übertragen wurde. Man vermaß die Marschländereien und klassifizierte sie.
Nach der Größe und Güte des Landes waren dann die Beiträge zu entrichten. Anfangs scheint der K.
A.K. nicht mit zu großen Lasten bedacht worden zu sein. Acht Wochen vor der zweiten "Mandränke",
am 29.7.1634 ordnete das Amt Tondern die Vermessung der Marsch-ländereien unseres Kooges an,
da diese noch nicht im _"ordinairen Teichbuch"_ verzeichnet waren. Eine Überprüfung ergab jedoch, daß
eine Vermessung des ganzen Kooges sich nicht lohnte, weil dieses Gebiet nicht als Marschland
anzusprechen war.

In späteren Jahren brachte man aber den Artikel 1 des Spade-Landes-Recht ') zur Anwendung und zog
auch den K.A.K. im gleichen Maße zu den Deichlasten heran. In diesem Artikel heißt es nämlich:

_"All das Land, unter einem Koge belegen, da die große Flut übergangen ist, das soll Demath Demaths
gleich in Deichen und Dämmen in argen und guten gemachet und gehalten werden."_

Nachdem der Hoyer Deich größere Beschädigungen erlitten hatte, sah sich der Herzog veranlaßt, die
Besitzer des Hinterlandes an ihre Pflichten zu ermahnen:

_"unsere underthansen, so under solchem Deich gehörig und der arbeit schuldig erkannth,
nemlich alle die jenigen, welcher landt vergangen jhars ennde jacobi (25. Juli) anno 61 ten
mit dem saltzwasser belaufen gewesen."_

Bei den häufigen Überflutungen der neueingedeichten Gebiete ist natürlich auch unser Koog mit
Salzwasser überlaufen worden. Unsere minderwertigen Ländereien mußten deshalb die gleichen Lasten
tragen, wie die übrigen Marschgebiete. Da die Deichbrüche sich wiederholten, die Lasten immer
drückender wurden, dachte man an eine Ausdehnung des Kooges. Man legte deshalb die Größe auf
2.250 Demath fest. Dabei wurden viele Geestländereien zur Marsch geworfen, weil sie vielleicht einmal
vom Meerwasser überschwemmt worden waren.
Als 1792 der Wiedingharder Seedeich brach, glückte es, die anderen Köge zur Mitarbeit heranzuziehen.
Das war 1758 schon einmal versucht worden, aber ohne Erfolg. Unser Koog erhielt nun mit 2250
Demat eine Ausschreibung nach der anderen.
Im Jahre 1803 wurde der Allgemeine Deichband für den ersten Schleswigschen Distrikt gebildet. Dazu
gehörten alle Köge von der damaligen Deutsch-Dänischen Grenze bis zur Grenze der Kreise Husum
und Tondern. Unser Koog rangierte in der Klassifikation als einer der allerschlechtesten. (Von 31
Kögen standen nur vier unter ihm). Trotzdem mußten unsere Ländereien ihre Beiträge nach der zweiten
Klasse leisten und immer _"Demat Demat gleich"_ mit den oktroyierten Kögen zahlen. Das Mißverhältnis
ist nur zu auffallend, wenn man bedenkt, daß ein Demat unseres Landes an Wert einem Viertel des
übrigen Koogslandes entspricht. Außerdem hatten jene Köge noch den Vorteil, ihr Stroh und sonstige
zum Deichbau benötigten Materialien teuer anzubringen. Als entfernt wohnende Interessenten
entgingen die Landbesitzer im K. A. K. jedoch dieser Vorteile. Sie mußten nur stetig zahlen, während
die andern einnahmen. Damit nicht genug wurde unser Koog gezwungen, eine Schuldensumme von
15.686 Rthl Silber zu übernehmen. Das entsprach nicht der Güte unserer Ländereien. Diese Lasten und
einige aufeinanderfolgende Mißernten brachten viele Eingesessenen von Lügum und Wimmersbüll in
Not. Sie sandten ein Bittgesuch an den König, in dem es zu Anfang heißt:

_"Die Eingesessenen der Dörfer Lügum und Wimmersbüll wagen es aus wahrer dringender Noth
gezwungen, Ew. Königl. Majestät ihre betrübte Lage allerunterthänigstvorzutragen
undallerfußfälligst Abgaben an Contribution und Pflicht, sowie die älteren Restanten aus
allerhöchster Gnade gänzlich erlassen werden mögen."_

Ob diesem Gesuch vom 22.1.1835 stattgegeben wurde, geht aus den Akten nicht hervor. Später ist der
K. A. K. jedenfalls in die niedrigste Klasse eingestuft worden. Nach dem Statut für den ersten Schles-
wigschen Deichband vom 1.5.1908 wurden die Deichbandbeiträge nach sechs Klassen entrichtet. Hier
war unser Koosg als 16. aufgeführt mit 1099,87 ha, im
Nachtrag 1 vom 21.6.1922 als 15. Koog mit 1121,39 ha
Nachtrag 3 vom 25.9.1931 als Nr.15a) K. A .K. 1111,88 ha
15 b) Ländereien am Haasberger See 18,15 ha
Über die Deichlasten sagt das Statut:
_"Als ertragsfähige Marschländereien gelten alle unter Deichschutz liegenden
Grundstücke, welche unter einer Höhenlinie von 3,50 m (seit 1848 unter 2,50 m) über
ordinairem Hochwasser bei Dagebüll (höchstbekannte Flut) das ist 4,50 m über N.N.
liegen.
Ausgenommen: Seedeich, unter Schau stehende Mitteldeiche, öffentl. Wege, Gewässer,
Sielzüge und Gräben, Ödland, sowie Wasserstücke 7. und 8. Klasse."_

==== 9.3.6. Die Mittel- und Sommerdeiche des Kooges

B.5. Mit der Eindeichung des Gotteskooges im Jahre 1566 war der Grellsbüller Deich südlich Ruttebüll
nicht mehr unmittelbar den Angriffen des Meeres ausgesetzt. Jedoch auch als Mitteldeich war er nicht
überflüssig. Er mußte genauso in Ordnung gehalten werden wie vorher als Seedeich, um die in seinem
Schutze liegenden Ländereien bei einem Bruch der Gotteskoogdeiches schützen zu können. Das Spade-
Landes-Recht sah für die Vernachlässigung oder gar Abtragung der Mitteldeiche härteste Strafen vor
in Artikel 20:
_"Wenn die Haff (See) Deiche nach aller Nothdurft auf das fleißigste gefertiget, sollen alle
Mitteldeiche erhöhet und verbessert werden, und Niemand selbige unter den Pflug legen oder
besäen. Diejenigen, die sich hier entgegen erdreistet sollen zum Halse gefället seyn"_ .
Auch die _"Hochfürstliche Deich -Ordnung im Amte Tunderen: Herzog Friedrichs zu
Schleswig-Holstein"_ nimmt auf diesen Artikel Bezug:
_"...daß bey Vermeidung Ihre Fürstl. Gnaden willkürlicher Strafe die Alte und Mitteldeich nicht
vergraben, gepflüget und besammet..."_ .

Die _"Tunderischen Koogs-Leuten"_ wurden darin aufgefordert, ihre alten Deiche von Grellsbüll nach
Ruttebüll zu erhöhen und zu verbessern. _"Stellen, die vom Saltzen Wasser weggerissen oder schamferet
zu ihrem Stande völlig gebracht und unstrafbar gebauet werden sollen."_ In der Verordnung wurde
weiter bestimmt, daß jeder sein Stück Deich erhalten sollte, nachdem Ausmaße der Ländereien, sowie
auch der Deiche festgestellt waren. Bei Landverkauf folgte die Deichlast mit. Deichgrafen, -vögte und
-richter wurden eingesetzt und mußten laufend über den Zustand der See- und Mitteldeiche berichten.
Es war nach dieser Deichordnung bei 10 Rthl _"Brüche"_ verboten, Erde von den Mitteldeichen
abzugraben. Der Deichrichter mußte jeden Sommer eine Deichschau abhalten. Festgestellte Mängel
wurden aufgezeichnet und sonntags auf dem Kirchhof verlesen. 14 Tage nach Schauung hielt der
Amtmann selbst die _"große Deichschau"_ ab. Arge Sünder konnten an _"Leib und Leben"_ gestraft und
nach Gottorf ins Gefängnis geschickt werden.
In unserem Koog war nicht nur der Grellsbüller Deich als Mitteldeich zu unterhalten, sondern auch der
Sommerdeich an der Süderau und am Kleinen Strom. Jedes Dorf, dasimK. A.K. Land hatte, war für
eine bestimmte Strecke verantwortlich, die man wiederum unter die Landbesitzer aufteilte. Wiederholt
wurde eine Neuverteilung vorgenommen. So erfolgte 1708 in Süderlügum eine _"Verlosung"_ der
entsprechenden Deichstücke nach der Bohlszahl. Eine genaue Aufstellung der Landanlieger und ihrer
Deichanteile berichtet über das Ergebnis einer erneuten Verteilung im Jahre 1742:
_"Anno 1742 im Monat November ist der Sommerteich, so daß Dorf Lügum zugehöret nach ihre
gethane Verlosung vertheilet und einem jeden nach seinem Lande zugemessen."_

Auch Wimmersbüll und Grellsbüll verlosten erneut ihren 143 Ruten langen Sommerdeich. Das alte
Register, das der Deichvogt Andreas Ebsen aus Wimmersbüll aufgestellt hatte, wurde 1708 durch neue
Namen verbessert.
Im Laufe der Jahrzehnte scheinen die harten Gesetze, wie sie im Spade-Landes-Recht aufgezeichnet
sind, immer mehr an Bedeutung verloren zu haben. Hätte man die Vernachlässigung der Sommerdeiche
zu Anfang des 19 ‚Jahrhunderts noch nach dem alten Deichrecht geahndet, wäre es den Eingesessenen
unseres Kirchspieles übel ergangen. 1817 wurde nämlich festgestellt, daß die Sommerdeiche ganz
verfallen waren. In der Kirche zu Lügum erfolgte die Bekanntmachung vom verheerenden Zustand der
Deiche. Es wurde angeordnet, sofort mit der Ausbesserung zu beginnen und in Zukunft die Deiche
jährlich zu überholen.
In späterer Zeit übernahm der Koog die Unterhaltung der Sommerdeiche. Laufend wurden sie
ausgebessert und überholt, besonders vor und nach dem Winterhochwasser. Noch 1924 stellte eine
Kommission des Deichgrafen fest: "Die Sommerdeiche sind in letzter Zeit vielfach verstärkt und erhöht
worden. Die zur Instandsetzung oder Wiederherstellung benötigte Erde wurde in den anliegenden
Ländereien abgegraben (Spätland). Die Besitzer erhielten für diese _"Späterde"_ eine bestimmte
Entschädigung, die von der Koogsversammlung festgesetzt wurde. Die Protokolle über die jährlichen
_"Koogsrechnungen"_ geben uns darüber Aufschluß. Ein Beschluß von 6.12.1922 lautet: _"Die
Entschädigung für Späterde wird von 10.000,- auf 500.000,- M pro Demat erhöht und für 1922
nachbezahlt."_ Vermutlich waren die Betroffenen wenig erfreut über diese gewaltigen Summen, da das
Geld in der wilden Inflationszeit schon wenige Stunden nach der Auszahlung beträchtlich an Wert
verloren haben konnte.
Während des Winterhochwassers kam es verschiedentlich zu Deichbrüchen. 1910 war der
Sommerdeich an zwei Stellen gebrochen. Einige Jahre später versuchten die Ellhöfter vergeblich ein
Loch in ihrem Sommerdeich mit Sandsäcken zu stopfen. Die Folge davon war eine anhaltende
Überflutung der östlichen Koogsländereien. Der Süderaudeich war besonders stark an den Biegungen
gefährdet. Hier konnte er leicht vom Wasser unterwühlt werden. Man baute deshalb im Laufe der Zeit
Schutzwände aus Holzpfählen, sogenannte Bollwerke.

Oft gaben einzelne Landanlieger durch nicht zu verstehende Gleichgültigkeit die Veranlassung zu
ernsten Beschädigungen und unter anderem zu einem Durchbruch des Sommerdeiches am Dreiharder-
Gotteskoog-Strom bei der Wimmersbüller Brücke. Hätte das Spade-Landes-Recht noch Gesetzeskraft
gehabt, wäre der Verantwortliche sicher nicht mit der Haftung für den Schaden weggekommen.

Der Graswuchs auf den Sommerdeichen des Koogs, der für Weidezwecke nicht ausgenutzt werden
konnte, wurde als _"Meedfrucht"_ verkauft. Die Käufer verpflichteten sich, das Gras bis zum 10. Juli zu
mähen und das Heu bis zum 31. Juli von den Deichen zu entfernen. Alles Unkraut mußte abgemäht
werden. Heute will der Landanlieger in den meisten Fällen selbst das Gras des zu seinem Land
gehörenden Sommerdeiches haben. Da die zur Meedfruchtgewinnung vermessenen Deichstücke aber
nicht mit der Längen- bezw. Breitenausdehnung der anliegenden Parzellen übereinstimmt, ist die
Verrechnung der Pachtbeträge sehr schwierig.

=== 9.4. Die Entwicklung der Wasserverhältnisse im K. A.K.

==== 9.4.1. Die Wasserverhältnisse in alter Zeit

C.1. Nach der Fertigstellung des Grellsbüller Deiches waren die Ländereien unseres Kooges
einigermaßen vor Überschwemmungen geschützt. Wenn der _"Blanke Hans"_ auch wiederholt bis in
unsern Koog vordringen konnte, so wuchs die Sicherheit vor dem Salzwasser im Laufe der Jahrzehnte
mit der allmählichen Verbesserung der Deiche und der Vorverlegung der Außendeichslinie nach
Westen. Überschwemmungen durch die Nordsee hatte man somit nicht mehr zu fürchten. Dafür trat
nun ein anderes Wasserproblem auf. Das Regenwasser von Marsch und Geest konnte nicht mehr
ungehindert abfließen. Es staute sich bei länger anhaltendem Regen im niedrigen Koogsgebiet.
Besonders waren naturgemäß die Überschwemmungen im Frühjahr und im Herbst. Je mehr Land der
Nordsee abgerungen wurde, je weiter die Außendeichslinie vorgeschoben werden konnte, desto länger
wurde der Abflußweg des Regenwassers zum Meer. Gleichzeitig vergrößte sich mit den neu
entstehenden Kögen das Niederschlagsgebiet. Der Mehranfall von Regenwasser in der Wiedau bewirkte
eine Rückstauung. Es gestaltete sich die Entwässerung unseres Kooges mit dem Vorrücken des
Außendeiches nach Westen immer schwieriger.

In der ersten Zeit nach der Eindeichung waren die Wasserverhältnisse völlig ungeregelt. Die Ländereien
des Kooges standen den ganzen Winter über unter Wasser. Das Land konnte wegen der Nässe nur als
Wiese und Weide nutzbar gemacht werden. Zur Verbesserung des Graswuchses versuchte man sogar
die Wiesen möglichst lange unter Wasser zu halten. Durch Stauvorrichtungen wurden auch die etwas
höher gelegenen Ländereien unter Wasser gesetzt. Diese "Berieselungswirtschaft" hat sich erhalten bis
Mitte des vorigen Jahrhunderts. Alte Leute aus Süderlügum wissen zu berichten, daß besonders die
Ellhöfter große Erfolge mit dieser Berieselungswirtschaft hatten. Sie sollen wahre Rekord-Heuernten
eingebracht haben.

Ähnlich wie jeder einzelne Landbesitzer für die Unterhaltung seines Deichstückes verantwortlich war,
so sorgte er auch selbst für Bewässerung und Entwässerung seines Landes. Übel dran waren die am
niedrigsten gelegenen Gebiete. Das losgelassene Stauwasser der höheren Ländereien verursachte hier
großen Schaden. Da die Landanlieger ihre Wiesen zu jener Zeit durch Dämme im Jündewatter
Mühlenstrom (Süderau) stauten, führte die Au viel Sand mit. Besonders starke Sandablagerungen waren
beim Peter-Prästes-Zug, dem letzten Teil der Süderau, zu beobachten. Der Sand verhinderte den Abfluß
des Wassers. Aufstauung und Überschwemmung waren die Folge.
Erst 1785 kam man zu einer einheitlichen Regelung. Die Kirchspielsvögte hatten dafür zu sorgen, daß
alle Ströme auf einmal geräumt wurden. Um eine erneute Versandung zu verhindern, durften nur noch
Holzschütten verwendet werden, die vom Deichvogt jährlich zu überprüfen waren. Es wurde nicht
gestattet, außer den bereits vorhandenen noch neue Stauschütten zu bauen. Mit Rücksicht auf die
niedrigeren Ländereien wurde nach dem 11.Mai nicht mehr erlaubt zu stauen. 1811 verlängerte man
diesen Termin auf den 24.Mai.

Schon im Laufe der nächsten Jahre wurde diese Berieselungswirtschaft planmäßiger durchgeführt.
Innerhalb des Kooges bildeten die Dörfer Kommunen, die für eine geregelte Stauung ihres Gebietes
sorgten. Nachdem Ellhöft schon seit längerer Zeit seine Wiesen unter Wasser setzte, reichten auch die
Lügumer eine Eingabe vom 9.4.1788 an den Deichgrafen in Tondern, um die Erlaubnis zum Bau eines
Stauwerkes in der Süderau zu erlangen:

_"Es ist ohnstreitig, daß unser Wiesenwucht sehr verbessert werden könnte, wenn wir die
Ländereien so wie es von benachbarten Dörfern geschieht, unter Wasser setzen könnten. Diese
Vorteile muß man uns notwendig erlauben, insofern solches ohne Nachtheil der Angrenzenden
geschehen kann. Hierbei ist aber gar kein Bedenken, insofern die Schütte nur mit der gehörigen
Vorsichtigkeit gesetzet und der Gebrauch desselben nach gewissen Grundregeln bestimmt
würde. In dieser Hinsicht haben wir in dem Jündewatter Strohm ohnweit Uhlenberg den Ort zu
der Erbauung bestimmt und damit wir dabey desto sicherer fahren und gegen künftige Chikanen
gesichert seyn mögen, wünschen wir schon, daß eine local Untersuchung durch Cammerassessor
und Hausvogt Lüders allenfalls in Beyseyn Ew. Hochwohlgebohren mit dem allerforder-
sonsten geschehen möge..."_ .

Bereits drei Tage später fand die Lokalbesichtigung statt. Das Ergebnis war die Bewilligung des
Antrages. Dabei wurde den Lügumern genau vorgeschrieben, wie das Stauwerk anzulegen sei. Die
Schüttenposten (Balken, die zur Absperrung der Au dienten) durften nur zur Zeit der Stauung stehen.
Auf keinen Fall konnte eine Stauung der Wiesen westlich vom Lügum Damm (Straße Süderlügum-
Tondern) genehmigt werden, _"....damit nichts von dem Wasser durch das berüchtigte Grellsbüller Siel
kommt,"_ heißt es in dem Besichtigungsbericht. Von diesem _"berüchtigten"_ Grellsbüller Sielwird später
noch die Rede sein.

Trotz des neu geschaffenen Stau-Regulativs konnten die Überschwemmungen im Sommer nicht
herabgemindert werden. 1803 beklagten sich Bremsbüll und Seth über das losgelassene Stauwasser von
Osten, das ihnen großen Schaden tat. Im Laufe der nächsten Jahrzehnte hielt man sich immer weniger
an die Regelungen. Vor allem wurde die Reinigung der Süderau und der anderen Nebenflüsse der
Wiedau sehr vernachlässigt, so daß diese ganz zu versanden drohten. Der _"Jündewatter Strohm"_ war
vom Haasberger See bis zur Mündung stark versandet. Eine besonders schmale Stelle befand sich
zwischen Bremsbüll und Flützholm. Der Deichvogt P. Dethlefsen, der in Bremsbüll wohnte, hatte hier
eine Furt durch den Strom. Wegen der dadurch hervorgerufenen Rückstauung in der Süderau mit ihren
Folgen machte er sich keine Sorgen. 1816 ordnete der Amtmann, der als Oberdeichgraf die
Oberaufsicht führte, die jährliche Reinigung der Ströme an. Die Süderau mußte bei Bremsbüll auf zwei
Ruten erweitert werden. Die Entfernung der Sandbänke wurde angeordnet und die Überfahrt verboten.
Besonderer Wert sollte auf gute Reinigung der Wasserläufe gelegt werden. Bis zum Beschautag am
5.Juni mußten alle Ströme sich in einem ordnungsgemäßen Zustand befinden.
Die Klagen über _"stagnierendes und abfließendes Wasser"_ wurden 1839 wieder laut, da ohne Rücksicht
auf die niedrigen Ländereien das Wasser in der Au gestaut bezw. abgelassen wurde. Das Amt Tondern
sah sich veranlaßt, die Anordnungen von 1785 über den Gebrauch der Stauwerke erneut zur Kenntnis
zu bringen. Nachteile für die tiefer liegenden Gebiete sollten beim Stauen vermieden werden.
Außerdem wollte man Sandablagerungsplätze auf Kosten der Stauer anlegen lassen, um der ständig
drohenden Versandung der Ströme wirksam begegnen zu können. Die Stauer waren jedoch nicht
gewillt, ihre Rechte schmälern zu lassen und behaupteten, ihnen stehe unbeschränktes Staurecht zu.

==== 9.4.2. Erste Entwässerungsversuche
C.2. Hatte man bis Mitte des 19. Jahrhunderts der Bewässerung mehr Beachtung geschenkt als der
Entwässerung, so zwangen die allmählich immer größer werdenden Überschwemmungen zu
entsprechenden Maßnahmen. Zwar sorgten Wasserläufe und Gräben auch schon damals für die
Weiterleitung des Wassers, doch nicht in genügendem Maße. Es war auch hier so, daß jeder
Landbesitzer im Koog so gut es ging für die Entwässerung seines Landes sorgte, manche bauten sogar
eigene Sommerdeiche zu Abwehr des Überschwemmungswassers. Allerdings konnten nicht ganz
willkürlich Maßnahmen getroffen werden. Einzelne überlieferte Regelungen, nach denen man sich
richten mußte, haben sich bis heute erhalten, wie z.B. betreffs der Reinigung der Gräben, man reinigte
nach dem _"Daumenrecht"_. Wenn der Eigentümer mit dem Gesicht nach außerhalb in seiner Wiese
stand, so hat er immer die linke Hälfte des Grabens in Ordnung zu halten.
Ein anderes altes Gewohnheitsrecht besagte, daß der Abfluß des Wassers nicht verändert werden durfte.
Auf dieses Recht berief sich 1777 Frantz Hansen auf Gulumhus, als man bei einer Überholung des
Weges Böglum-Ellhöft den Wasserlauf ableitete, daß das Wasser über seine mit _"Haber besäte Wiese
herabschoß"_. In seiner Beschwerde heißt es zu Anfang:

_"Es ist sowohl ausdrücklich als in der analogie der hiesigen Landrechten vollkommen gegründet,
daß das Wasser seinen alten Lauf behalten und darinnen nicht gehemmet oder gehindert werden
Soll..."_

Innerhalb einer Frist von acht Tagen mußte dieses Übel abgestellt werden durch Anlegung eines Sieles
und Aufräumung des alten Grabens.
Die Akten berichten über zahlreiche Fälle von solchen und ähnlichen Entwässerungsstreitigkeiten, die
oft verursacht wurden durch rücksichtslose Maßnahmen benachbarter Anlieger. Ein aufschlußreicher
Fall mag in diesem Zusammenhang hier noch erwähnt werden. Es handelt sich um die Klage der nach
Horsberg _"ausgeflütteten"_ Kätner über das Ausbleiben der vom Dorf versprochenen Hilfe zur
Entwässerung ihres Landes. (Die Ausgeflütteten waren die Leute, die nach der Feldaufteilung auf
Süderlügum-Feld ausgesiedelt wurden). 1804 richteten sie folgendes Schreiben an das Amt Tondern:

_"Nach dem letzten großen Brande in Lügum hatten auch wir das Unglück, daß unsere Häuser
ein Raub der Flammen wurden. Wir wurden nachher angehalten unsere Häuser osten des
Dorfes aufzubauen und uns versprochen, daß die gehörigen Anstalten zur Befreyung unserer
Ländereyen vom Wasser gemachet werden sollten. Dies ist bis jetzt noch nicht geschehen, und
wir leiden immerwährend den größten Schaden, da das über unser Land anhaltend stehende
Wasser alle unsere Arbeiten und Aussaaten vergeblich machte..."_

Bei der am 28. Juli 1804 stattfinden Lokalbesichtigung konnte diese _"streitige Sache beendet werden"_.
Es stellte sich heraus, daß die Dorfbewohner den _"Ausgeflütteten"_ nicht nur nicht geholfen hatten,
sondern im gegenteiligen Sinne tätig gewesen waren, da das Wasser früher seinen Lauf nach Westen
genommen hatte, mußte auch jetzt der freie Abfluß wieder hergestellt werden. Der Müller Nicolay
Lorenzen, der zwei Einfahrten zu seinen Fennen angelegt hatte, ohne für ausreichenden Abfluß der
Horsberger Wasserlösung zu sorgen, erklärte sich nach der Besichtigung bereit, vorgeschriebene Siele
zu legen. Auf Kosten der Dorfschaft sollte im Grausander Weg ein Siel gebaut werden. Bezeichnender
Weise konnte man sich nur wegen Berichtigung der Besichtigungskosten von 5 Rthl 42 ß nicht einig
werden. Sie wurden schließlich der Dorfschaft zur Last gelegt.

Immer schwieriger und dringender wurde das Entwässerungsproblem im Koog, als mit der Kultivierung
der Geest begonnen wurde. In alter Zeit versickerte ein großer Teil des Regenwassers in den
ausgedehnten Heide- und Moorgebieten. Der überschüssige Teil kam durch kleine gewundene
Wasserläufe zum Geestrand. Als man aber die Heideflächen in der Umgebung Süderlügums urbar
gemacht hatte, konnte das Wasser schnell durch ein im Laufe der Jahre immer besser reguliertes
Grabensystem in den Koog kommen. Das niedrige Koogsland konnte erst dann sein Regenwasser los
werden, wenn das Geestwasser vorbei war. Daran hat sich bis heute nichts geändert. Die großen
Wasserkatastrophen in der Marsch, wie sie in diesem Jahr besonders stark im Bongsieler Gebiet
auftraten, wurden und werden in der Hauptsache durch das Geestwasser und nur zum geringen Teil
durch das Regenwasser der Marsch angerichtet. Deshalb hat die Marsch immer wieder gefordert, die
Geest zu den Kosten der Regulierung mit heranzuziehen. Während dies in Ostfriesland geschehen soll,
liegt bei uns in Nordfriesland die Grenze des lastenpflichtigen Landes bei plus 2,50 m über N. N..
Das Problem der Ableitung des von der höheren Geest im Norden Lügums herunterfließenden Wassers
taucht in den Akten bereits 1815 auf. Durch Umleitung der Wasserlösung versuche man bei diesem Fall
die Ländereien zwischen Gohsham-Damm und Gulum-Weg vor Unterstauung zu schützen. Unter
anderem wurde empfohlen _"Jedes Jahr vor Maytag in dem Seitengraben eine Dämmung zu setzen, die,
wenn erforderlich nach Martini durchstochen werden durfte."_

1830 stand so viel Wasser im Koog, daß eine Lokalbesichtigung teilweise im Boot durchgeführt werden
mußte. Als Ursache dieser Überschwemmung wurden ungenügende "Wasserlösungen" festgestellt.
Ein langjähriger Streit entstand 1844 zwischen Süderlügum und Ellhöft wegen der Ableitung des
Geestwassers. Lügum klagte gegen das nördliche Nachbardorf, weil es durch eine bedeutende
Erdstauung dem Wasser einen veränderten Lauf gegeben hatte, so daß der Kirchensteig unter Wasser
gesetzt wurde. Die Angeklagten wiesen aber nach, daß hier der Kläger der schuldige Teil war. In den
letzten Jahren hatte man mehrere hundert Demat Heide nordöstlich des Dorfes urbar gemacht ohne für
eine gehörige Wasserlösung zu sorgen. Man ließ das Wasser einfach nach Norden fließen, wo es das
Ellhöfter Land regelmäßig mehrere Fuß hoch überschwemmte. Ellhöft schritt deshalb zur Selbsthilfe
und schützte sich durch eine Dämmung vor dem fremden Wasser. Da ein Teil des Regenwassers jedoch
von Westre-Feld kam, einigten sich die Dörfer in einem Vergleich auf die Teilung des Wassers. Ein
Teil sollte in gerade Richtung durch Ellhöft- und Gulumfeld nach Norden geleitet werden, während der
Rest von der Geestgrenze ab nach Westen am Kirchenweg entlang und dann an der Feldscheidung
zwischen Uhlenberg und Lügum seinen Abfluß in den Kleinen Strom finden sollte. Als dieser Plan
schon in Ausführung begriffen war, legte Jes Peter Brodersen von Uhlenberg Verwahrung dagegen ein.
Der Kleine Strom könnte unmöglich alles Wasser aufnehmen und würde seine Ländereien in Sumpf
verwandeln, so erklärte er. Nach der dritten Lokalbesichtigung durch Vertreter des Deichgrafen wurde
schließlich der Plan wieder aufgehoben. Ob man diese Frage bei der vierten Besichtigung am 12.7.1847
endlich zur Zufriedenheit aller Beteiligten lösen konnte, geht aus den Akten nicht mehr hervor.
Künstliche Entwässerungsanlagen, wie man sie überall dort benötigt, wo das Wasser eines besonders
niedrigen Landes nicht durch Gräben oder Kanäle allein abgeleitet werden kann, gab es auch im
K.A.K.. Thomas Dethlefsen auf Flützholm beantragte 1819 eine solche Anlage mit Erfolg. Zur
Entwässerung seines Landes ließ der Koog dort eine Entwässerungsmühle bauen. Bis vor wenigen
Jahren stand eine solche Entwässerungsmühle noch in Struxbüll. Mittels der Windkraft wurde das
Wasser aus einem Graben über den Sommerdeich befördert. Dabei übertrug man die Drehung der
Münhlenflügel auf eine Schnecke. Diese drehte sich in einer halbrunden Rinne und bewegte das Wasser
fortwährend nach oben.

==== 9.4.3. Ableitung des Wassers zum Meer
C.3. Einzelne Maßnahmen hinsichtlich der Entwässerung können nur dann einen Sinn haben, wenn sie
auf das größere System abgestimmt sind. In unserem Falle handelt es sich dabei um die Anlagen des
Hauptsielverbandes Ruttebüll-Südwesthörn, an die der K..A. K. angeschlossen ist. Es soll deshalb hier
zunächst die Frage erörtert werden: _"Wie wird das sich im Koog ansammelnde Wasser zum Meer
abgeleitet?"_

Durch ein ausgebautes Netz von Gräben und Wasserlösungen (Nebenvorflut) wird das Wasser aus dem
gesamten Niederschlagsgebiet der Süderau diesem Strom (Hauptvorfluter) zugeführt. Dieses System
hat vor allem in den letzten Jahren wesentliche Änderungen erfahren. Bis 1935 führte der Kleine Strom
das Wasser vom Ellhöfter Feld westlich von Groß-Struxbüll in die Süderau. Er war damals von Böglum
ab auf beiden Seiten bedeicht. Alles Koogswasser wurde also durch den Kleinen Strom oder
unmittelbar dem Hauptvorfluter, der Süderau, zugeleitet. Der besonders niedrige westliche Teil des
Kooges im Norden von Wimmersbüll durfte das eigene Regenwasser, auf keinen Fall aber
Überschwemmungswasser, durch das Buffelsiel in den Gotteskoog leiten. Heute wird der größte Teil
des Koogswassers auf diesem Wege abgeführt. In einem anderen Abschnitt wird auf diese Umleitung
noch näher eingegangen werden.

Eine besondere Stellung nimmt der Dreiharder Gotteskoogstrom ein. Ursprünglich floß die Karlumer-
Au, die nordöstlich von Karlum entspringt, nach Westen in das Wattenmeer. Nach der Eindeichun g.des
Gotteskooges mußte das abziehende Wasser dieser Au zur Entlastung dieses Kooges nach Norden
durch den Dreiharder Gotteskoogstrom der Süderau zugeführt werden. Da der Strom an beiden Seiten
bedeicht ist, wurde der K. A. K. durch dieses abfließende Geestwasser nicht behelligt. Um bei
besonders starkem Anfall von Regenwasser im Herbst und im Frühling den Koog nicht zu gefährden,
hat man auch das Gebiet des Haasberger Sees mit einem Deich versehen. Er wirkt als Staubecken für
die großen Wassermassen des oben erwähnten Stromes und der Süderau. Während der See im Sommer
dem Anblick einer grünen Wiese bietet, steigt das Wasser im Winter regelmäßig bis zur Deichkrone.
Im vorigen Jahr vermochte dieses Staubecken die sich ansammelnden Wassermassen kaum zu fassen.
Nur mit großer Mühe konnte ein Deichbruch und damit eine Überflutung des ganzen westlichen
Koogsgebietes von der Straße Süderlügum-Tondern verhindert werden. Eine übermäßige Stauung tritt
immer dann ein, wenn die Hoyer Schleusen bei anhaltendem Weststurm nicht geöffnet werden können.

Nach den technischen Berechnungen des Kulturbauamtes Schleswig vom 27.11.1929 hatte das
Niederschlagsgebiet der Süderau eine Größe von 490,6 qkm.
Es setzte sich aus folgenden Untergebieten zusammen:

|===
|1.) Von den Quellen zur Gehlau                                                                   | 114,8 qkm
|2.) Gehlau                                                                                       | 101,6 "
|3.) Von der Gehlau bis zur Alten Au                                                              |  93,4 "
|4.) Alte Au und Scheidebeck                                                                      |  70,3 "
|5.) Das Gebiet nördlich der Süderau von der Alten Au bis zur Mündung                             |  20,7 "
|6.) Kleiner Strom                                                                                |  36,5 "
|7.) Karlumerau, bezw. Dreiharder Großer Strom                                                    |  42,5 "
|8.) Der westl. Teil des Kooges, der zeitweilig durch das Buffelsiel in den Gotteskoog entwässert |  10,0 "
|9.) Haasberger See                                                                               |   0,8 "
|                                                                                                 | 490,6 qkm
|===

Das Wasser dieses gesamten Niederschlagsgebietes kann auf zwei verschiedenen Wegen ins Meer
gelangen:

1.) Durch die Süderau in die Wiedau und durch die Hoyer Schleusen in die Nordsee.

2.) Durch das Buffelsiel in den Aventofter See, von dort durch das Schöpfwerk von Verlath in den
Ruttebüller See und von da schließlich durch die Wiedau und dann durch die Hoyer
Schleusen in die Nordsee.
Es kann jedoch auch durch den Gotteskoog-Sielzug bei Südwesthörn in die Nordsee geleitet
werden.

==== 9.4.4. Die Grenzlaufregulierung

===== 9.4.4.1. Das Deutsch-Dänische Regulativ für den Grenzlauf

C.4a Die Abstimmung im Jahre 1920 brachte für den Hauptsielverband Ruttebüll-Südwesthörn und
somit auch für unseren Koog entscheidende Veränderungen. Alle Marschländereien nördlich der
Süderau und der Wiedau, sowie die beiden Friedrichen Köge schieden laut Deutsch-Dänischem
Staatsvertrag vom 10.4.1922 aus dem Hauptsielverband aus. Die Süderau wurde zum Grenzstrom und
die Wiedau lag von nun an gar nördlich der Reichsgrenze. Die Hauptentwässerung ging also durch das
Gebiet eines fremden Staates.

In verschiedenen Abkommen wurden die Wasser- und Deichverhältnisse an der Deutsch-Dänischen
Grenze geregelt. Im dritten Abkommen vom 10.4.1922 stellte man Regulative auf für die einzelnen
Grenzabschnitte. Das für den K. A. K. in Frage kommende Regulativ gilt für den Abschnitt der Süderau
vom Grenzstein 191 (Zufluß der Alten Au) bis zum Grenzstein 336 (Einmündung in die Wiedau). Es
enthält genaue Angaben über geographische Lage, Profil, Gefälle und Sohlenlage des Wasserlaufes.
Auch die erlaubten Übergänge und Stauwerke in der Au sind dort aufgenommen worden, außer der
Chausseebrücke sind noch drei Holzbrücken zugelassen. Für die Besitzer von Bremsbüll und Flützholm
ist beim Grenzstein 216 eine Furt durch die Au gestattet. Zugelassen sind die beiden bereits in der Au
bestehenden Stauwerke bei Uhlenberg und Haasbereg.

Außerhalb des Koogsgebietes obliegt die Unterhaltungspflicht des Wasserlaufes den anliegenden
Landbesitzern. Für die restliche Strecke sind die beiderseitigen Köge verantwortlich.Wegen
Devisenschwierigkeiten beschloß man am 19.1.1938, die gemeinsam zu unterhaltende Strecke von
Grenzstein 208 bis 226 (den sogenannten Peter Pr&stes Zug) aufzuteilen. Dem K. A. K. wurden 1,4 km
zugeteilt und den Dänischen Kögen die letzten 760 m. Zweimal jährlich bis zum 15. Juni und bis zum
1.September mußte der Strom gereinigt werden. Die beiderseitigen Wasseraufsichtsbehörden hatten
gemeinsam die Schau vorzunehmen. Dieses Regulativ wurde am 17.11.1927 in einer gemeinsamen
Sitzung in der oben angegebenen Form festgelegt. Zur Regelung aller Unstimmigkeiten und
Unklarheiten in Deich- und Wassersachen bildete man eine Deutsch-Dänische Grenzwasser-
Kommission, in der alle Grenzköge durch ihre Deichvögte vertreten sind.

===== 9.4.4.2. Das Entwässerungsprojekt der Tonderner Marsch

C.4b Sechs Jahre nach der neuen Grenzziehung nahmen die Dänen ein groß angelegtes Projekt zur
Entwässerung der Tonderner Marsch in Angriff. Vom jeher hatten diese Marschländereien bei hohem
Wasserstand in der Nordsee und gleichzeitigem anhaltendem Geestwasserzufluß unter starken
Überschwemmungen zu leiden. Um diesem Übel abzuhelfen, wurden die Geestwasserläufe und die
Grünau mit Deichen versehen. Den Oberlauf der Süderau leitete man bei Windwedt ab und führte das
Wasser durch einen 2,5 km langen Kanal (Windwedt-Kanal) der Grünau zu. Durch vier Pumpstationen
plante man dieses Marschgebiet künstlich zu entwässern. Damit die anfallenden Wassermassen nicht
in die Süderau gedrängt wurden, baute man bei Mühlenhaus eine Sperrschleuse.

Nach Meinung der Dänen würde dieses Projekt für unseren Koog wesentliche Vorteile bringen. Man
versprach sich von diesen Maßnahmen vor allem einen früheren Abfluß aus dem Gotteskoogsee und
dem Haasberger See. Die Bewässerung im K.A.K. würde durch die Stauwehren bei Windwedt
sichergestellt.

Während der Süderaudeich auch nach Fertigstellung des Planes den Ansprüchen genügen würde, müßte
der Deich an der Wiedau zwischen Aventoft und dem Ruttebüller See erhöht werden. Die erforderliche
Erde sollte dem Bett der Wiedau entnommen werden. Gleichzeitig dachte man dadurch eine größere
Wasseraufnahmefähigkeit der Au zu erreichen. Bei Sturmflut würde die Wiedau mit dem Ruttebüller
See und der Grünau wie ein Behälter mit 350 ha Areal wirken. Für den äußersten Notfall war der
Friedrichen Koog östlich der Wiedau als Notbehälter vorgesehen.
Dies war in großen Zügen der Plan, wie er zur Ausführung kam. Er brachte Veränderungen für den
gesamten Hauptsielverband insbesondere für unseren Koog. Das Kulturbauamt Schleswig bestätigte
die Richtigkeit der dänischen Berechnungen und versprach sich eine Verbesserung der
Wasserverhältnisse für den K.A.K. An bautechnischen Veränderungen erfordert dieses Projekt nach
Meinung des Bauamtes lediglich die Anlage eines Rückdeiches von Windwedt bis Beierskrug. Außer
dieser Maßnahme sollte die Abdämmung des Grabenzuges am Weg nach Beierskrug den Koog vor den
ableitenden Wassern schützen.

Gegenüber einem früheren Gebiet von 490,6 qkm würde die Süderau in Zukunft nur noch ein
Niederschlagsgebiet von 80,3 qkm zu entwässern haben. Man rechnete damit, daß die Au durch die
herabgesetzte Wasserführung von Windwedt bis zum Stauwerk nördlich Uhlenberg zeitweilig nur als
Zuleiter für die Bewässerungsgenossenschaft Süderligum benutzt werden würde. Eine
Verschlechterung der bisherigen Deichschutz- und Entwässerungsverhältnisse war also keinesfalls zu
befürchten.

In bestimmten Teilen des Kooges hielt man künftig Überschwemmungen sogar für ausgeschlossen, so
z. B. In dem Bereich des kleinen Stromes und in den noch durch einen Rückdeich zu schützenden
Ländereien an der oberen Süderau.

Während jedoch auf dänischer Seite die geplanten Arbeiten durchgeführt wurden, blieb der Ausbau des
Sommerdeiches von Windwedt nach Beierskrug in den Anfängen stecken. Wie zu erwarten, strömte
das Wasser an dieser Stelle in den Koog hinein und überflutete die Ländereien von Böglum. 1931 nahm
die Überschwemmung solche Ausmaße an, daß der entstandene Schaden von den einzelnen Besitzern
nicht getragen werden konnte. Böglum, damals noch selbständige Gemeinde, legte energischen Protest
ein und verlangte vom Staat, als dem Träger der Arbeit, Schadenersatz und forderte den beschleunigten
Ausbau des erwähnten Deiches. Der Deichvogt wurde ermächtigt, falls nötig, einen Rechtsanwalt zu
nehmen und gegen den Preußischen Staat Klage zu führen.

Die Erfahrung lehrte, daß die Auswirkungen der Entwässerungsarbeiten in der Tonderner Marsch für
unseren Koog doch anderer Art waren, als vorher berechnet. Statt der erhofften Vorteile stellten sich
erhebliche Nachteile ein. Durch die Anlage der Sperrschleuse an der Süderau-Mündung konnte das
Wasser nicht wie bisher jederzeit abgeführt werden, sondern immer erst, wenn die Dänischen Köge
entwässert waren. Der K. A. K. hatte wegen des zu geringen Fassungsvermögens der Süderau unter
häufigen Überschwemmungen zu leiden. Die Koogsvertreter forderten deshalb eine grundlegende
Änderung der Grenzlaufregulierung, die es ermöglichte, gleichzeitig mit den Dänischen Kögen zu
entwässern. Daraufhin entschloß sich die Grenzwasserkommission zum Ausbau der Süderau. Der K.
A. K. übernahm die Ausgrabung der Au von Windwedt bis Mühlenhaus. Die beteiligten Dänischen
Köge zahlten 4.000 Kronen und verpflichteten sich, eine Vertiefung der letzten Strecke von
Mühlenhaus bis zur Mündung vorzunehmen.

Auf einer Koogsvertretersitzung am 17.2.1933 beschloß man darüber hinaus, nicht nur die Süderau,
sondern auch den Dreiharder Gotteskoogstrom ausgraben zu lassen. Als weitere Maßnahme sollten die
Sommerdeiche an beiden Strömen erhöht werden. Alle Arbeiten waren am 11.8.1939 fertiggestellt.
Nach den bisherigen schlechten Erfahrungen versprachen sich die Vertreter des Kooges von diesen
Bauvorhaben noch nicht die restlose Sicherheit vor Überflutungen. Sie waren einstimmig der Ansicht,
daß die Deicherhöhung den Koog nicht genügend vor den sich im Haasberger See anstauenden
Wassermengen schützte. Das Schöpfwerk bei Verlath würde den Wasserstand so hoch halten, daß die
Sperrschleuse bei Mühlenhaus praktisch immer geschlossen bleiben müßte. Es wurde deshalb
vorgeschlagen, an dieser Stelle ein Schöpfwerk zu errichten, das unabhängig vom Wasserspiegel in der
Wiedau, einen Abfluß der Süderau sicherstellte. Man beauftragte den Deichvogten am 21.7.1933 in
dieser Angelegenheit mit dem Regierungsrat Hoek zu verhandeln. Die Regierungsstellen entschieden
sich aber für einen anderen Plan, so daß dieses Projekt nicht zur Ausführung kam.

===== 9.4.5. Der neue Plan für die Binnenentwässerung

C.5. Maßnahmen verschiedenster Art wurden getroffen, um die Entwässerungsschwierigkeiten zu
beheben. Auch die Ableitung des Kleinen Stromes von der Böglumer Brücke westlich Uhlenberg zur
Süderau, die 1933 durchgeführt wurde, bedeutete keine wesentliche Verbesserung der
Wasserverhältnisse. Sollte den nachteiligen Folgen des dänischen Projektes wirksam begegnet werden,
so mußte die gesamte Binnenentwässerung eine grundlegende Änderung erfahren. Immer mehr kam
man zu der Überzeugung, daß nur eine Verlegung der Entwässerung entscheidende Verbesserungen
herbeiführen könnte. Am 17.2.1933 berieten die Koogsvertreter zum ersten Mal einen neuen Plan, der
ihnen vom Landrat unterbreitet wurde. Neben den bereits erwähnten Maßnahmen: Erhöhung der
Sommerdeiche, Ausgrabung der Süderau usw., sollte der Kleine Strom durch einen Hauptgraben mit
dem Buffelsiel verbunden werden. Der Plan sah also vor, den größten Teil des Koogswassers durch das
Buffelsiel an den Gotteskoog abzuleiten. Während die Ableitung des Wassers durch dieses Siel früher
sehr vorsichtig gehandhabt wurde, brauchte der Gotteskoog nach dem Bau des Schöpfwerks bei Verlath
nicht mehr so ängstlich zu sein. Das Werk ist in der Lage, alles anfallende Wasser in die Wiedau zu
schaffen.

Nach langer Beratung nahmen die Koogsvertreter den Plan an und übertrugen dem Arbeitsdienst die
Ausführung sämtlicher Arbeiten. Um den Struxbüller Ländereien eine bessere Entwässerung zu geben,
sollte im Zuge dieser Maßnahmen hier ein kleines Schöpfwerk errichtet werden. Dieses Bauwerk kam
jedoch nicht zur Ausführung, da es sich später als überflüssig erwies.

Zwei Jahre später konnte der Beschluß gefaßt werden über die Inangriffnahme des neuen Planes zur
Binnenentwässerung. Die Staugenossenschaft Süderlügum verzichtete in einer Erklärung auf die
Bewässerung ihrer Ländereien mit der Maßgabe, lediglich zur Einnahme von Trinkwasser für das Vieh
von ihrem Staurecht Gebrauch zu machen. Damit waren nun die Voraussetzungen gegeben, an eine
Sicherstellung der Entwässerung zu denken, unter Berücksichtigung einer gleichzeitigen Bewässerung.
Neben den Hauptgraben, der den Kleinen Strom zum Buffelsiel umleitete, hob der Arbeitsdienst sechs
größere Gräben aus, sogenannte Rottgräben. Diese sollten durch abgezweigte Laufgräben das sich in
den Parzellengräben sammelnde Wasser dem Kleinen Strom zuführen. Man plante darüber hinaus, das
Geestwasser nicht wie bisher dem Grabensystem des Kooges zuzuleiten. Alle Wasserlösungen, die das
Geestwasser aufnehmen, sollten in besonderen Ableitungsgräben aufgefangen werden. Dieses Wasser
wollte man direkt der Süderau zuführen. Als der Krieg 1939 ausbrach, mußte der Arbeitsdienst seine
Arbeiten einstellen. Dadurch kam der letzte Teil des Planes, der eine gesonderte Geestentwässerung
vorsah, nicht mehr zur Ausführung.

Nach dem Kriege setzte man die Ausführung des Planes fort, der z.Zt. noch nicht ganz abgeschlossen
ist. Die in der erwähnten Form vorgesehene Geestentwässerung wurde jedoch nur für den östlichen Teil
des Kooges durchgeführt. Der Ableitungsgraben I, der jetzt ausgebaut wurde, fängt alles Geestwasser
östlich der Straße Süderligum-Tondern auf. Ein Dücker leitet das Wasser unter dem Kleinen Strom
hindurch. Ohne mit dem Koogswasser in Berührung zu kommen, fließt es in die Süderau.

Die Besitzer der Ländereien südlich des Ableitungsgraben I zogen es vor, auf den Anschluß an die
Entwässerung des Kooges zu verzichten. Sie verpflichteten sich, einen Dücker unter dem Kanal zu
bauen und am Südufer Schutzdeiche aufzuwerfen. Diese Arbeiten schienen ihnen wohl immer noch
billiger zu sein, als die ständige Entrichtung von Koogsgeldern. Für den westlichen Teil des Kooges
verzichteten die Koogsvertreter auf eine gesonderte Geestentwässerung. Hier blieb es bei der alten
Regelung: Die Wasserlösungen führen das Regenwasser der Geest den entsprechenden Rottgräben zu,
die es mit dem Koogswasser zusammen dem Buffelsiel zuleiten.

Doch auch dieser neue Plan für die Binnenentwässerung brachte nicht die endgültige Lösung der in
unserem K.oog besonders gelagerten Wasserverhältnisse. Hier das richtige Verhältnis zwischen Ent-
wässerung und Bewässerung zu finden, bleibt zukünftigen Plänen vorbehalten.

Die Umleitung der Binnenentwässerung brachte eine Vervollkommnung der Entwässerung mit sich,
teilweise natürlich auf Kosten der Bewässerung. Ländereien, die noch bis 1935 für den Ackerbau nur
in geringem Umfang nutzbar gemacht werden konnten, wie Gulum, Uhlenberg, Struxbüll u.a., werden
seitdem gepflügt und besät. Der Entwässerungsplan hat also eine Umstellung der Bewirtschaftung des
Koogslandes bewirkt.

Auch die negativen Auswirkungen sollen hier erwähnt werden. So fordern zwei Bauern von Böglum
die Befreiung ihrer Parzellen von den Koogslasten, da diese durch die Entwässerung im Ertrag
wenigstens um 50% zurückgegangen seien. Einer behauptet, sein Land sei seit der Fertigstellung des
neuen Entwässerungsplanes so minderwertig geworden, daß es gar nicht besser sei als Heideland. Ein
Bauer von Struxbüll weigert sich dagegen, Koogsgeld zu zahlen, weil durch die mangelhafte
Entwässerung jährlich viele Demat unter Wasser stehen. Der Ertrag dieses Landes "sei gleich Null!"
behauptet er. Zweifellos ist eine entsprechende Entwässerung Struxbülls allerdings nicht genügend
berücksichtigt worden. Die Protokolle der Koogsververtretersitzungen von 1939 bis heute sprechen
immer wieder von Einlaßsielen und Stauvorrichtungen in der Süderau und im Kleinen Strom zur
Verbesserung der Bewässerung, vor allem zur Sicherstellung der Trinkwasserversorgung für das Vieh.

=== 9.5. Verwertung der erworbenen Sachkenntnisse im Heimatkunde-Unterricht
+++D.+++ Nach der Sichtung und Ausarbeitung des gesammelten vorliegenden Materials ergaben sich folgende Fragen:

1.) Was kann ich davon für den Unterricht verwerten ?
2.) Wie kann ich das tun ?
